### ISSUE TITLE
The daemon could honor the configuration file

### ISSUE THREAD

**Issue by es20490446e** [FluidSynth/fluidsynth#1000]
fluidsynth could honor the defaults set at "/etc/conf.d/fluidsynth", except if any setting is explicitly passed as argument as different.

**Comment by derselbst** [comment]
Why is it /etc/conf.d/fluidsynth, and not some other directory or filename? How should fluidsynth know about this? To me, this also seems more like a systemd issue. Where to read the defaults should be ideally handled in the systemd world, rather than in fluidsynth.

**Comment by es20490446e** [comment]
That's true.
