### ISSUE TITLE
UnsatisfiedLinkError, cannot locate symbol "__register_atfork" 

### ISSUE THREAD

**Issue by hxy493045049** [FluidSynth/fluidsynth#1002]
fluidSynth for 2.2.3
I'm using prebuild android binaries. And it's crash on some device.
vivo Y53L     os: 6.0.1
vivo Xplay5A  os:5.1.1
OPPO R9s  os:6.0.1
...  below 6.0

crash log 
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libogg.so"...
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__fwrite_chk" referenced by "...lib/arm64/libFLAC.so"...

I notise in 2.2.0 release note, it's required android >=30. Does it still required in 2.2.3?
But it's works fine above android 6.0

My gradle
compileVersion 29 
min 21  target 29
cmake  cmake_minimum_required(VERSION 3.10.2) 

i'm not good at ndk. any suggestions would be greatly appreciated

**Comment by derselbst** [comment]
You need Android API 24. I'll adjust the name of the ZIP file for the upcoming release to make this clear.

**Comment by hxy493045049** [comment]
> You need Android API 24. I'll adjust the name of the ZIP file for the upcoming release to make this clear.

Well, I can't just update my App. It's belongs to company. Can you please tell which release could support for API 21?

**Comment by derselbst** [comment]
> Can you please tell which release could support for API 21?

This is not a question of which release could support it. It's a question of against which android API you compile. We build against API 24 for reasons. If you have different needs, you have to compile fluidsynth yourself, see [the documentation in the wiki](https://github.com/FluidSynth/fluidsynth/wiki/BuildingForAndroid) and [the build pipeline](https://github.com/FluidSynth/fluidsynth/blob/master/.azure/azure-pipelines-android.yml).

**Comment by hxy493045049** [comment]
> > Can you please tell which release could support for API 21?
> 
> This is not a question of which release could support it. It's a question of against which android API you compile. We build against API 24 for reasons. If you have different needs, you have to compile fluidsynth yourself, see [the documentation in the wiki](https://github.com/FluidSynth/fluidsynth/wiki/BuildingForAndroid) and [the build pipeline](https://github.com/FluidSynth/fluidsynth/blob/master/.azure/azure-pipelines-android.yml).

got it, thanks
