### ISSUE TITLE
more playing examples.

### ISSUE THREAD

**Issue by netpipe** [FluidSynth/fluidsynth#1012]
https://github.com/divideconcept/FluidLite/issues/22

put these into examples folder for playing with different API's they work for both.

**Comment by derselbst** [comment]
You must be kidding. Fluidsynth has audio drivers that take care of playing back with ALSA, SDL2 and many more. FluidLight has stripped away those parts, which is pointed out [here](https://github.com/divideconcept/FluidLite/issues/22#issuecomment-674494410) and [here](https://github.com/divideconcept/FluidLite/blob/master/README.md). There is no point in using FluidLight, while needing functionality which has been stripped and then coming up with code to reinvent the wheel. Seriously.
