### ISSUE TITLE
Downstream project needs to detect if DLS or SF3 soundfonts are supported by the library at build time

### ISSUE THREAD

**Issue by pedrolcl** [FluidSynth/fluidsynth#1022]
Summary: a project using libfluidsynth may need to enable/disable some code if DLS or SF3 soundfont formats are supported. This is not possible to know right now, at build time.

### Related discussion

This comes from this Qsynth issue:  rncbc/qsynth#56

### Describe the solution you'd like

The capabilities of libfluidsynth are exposed to the downstream buildsystems. 

### Describe alternatives you've considered

* The typical way to detect features from libfluidsynth in downstream projects is to test the availability of some public function with cmake's `check_function_exists()`, but there is none right now. [CheckSymbolExists](https://cmake.org/cmake/help/v3.13/module/CheckSymbolExists.html) would be better in this case, if `fluidsynth.h` had some #define macros providing this information.
* For pkg-config build systems, an alternative would be adding some CFLAGS.
* For the cmake imported target, defining some boolean variables would work.
* The alternative of a new function exposing at run time the built-in capabilities is also acceptable.

### Additional context

Here is a screenshot of the Open File dialog from Qsynth. It has a single filter allowing SF2 and SF3 soundfont formats, but not the DLS one. 

![Screenshot_20220110_212101](https://user-images.githubusercontent.com/15184708/148833853-503fbebc-e2b1-4f97-95db-deb2f67785ab.png)

Knowing at build time the supported formats would allow to include/exclude the correct file filters on this dialog.

**Comment by derselbst** [comment]
This confuses me. I would understand, if you were asking for a runtime check. But a compile-time check doesn't make any sense, IMO. It's very common to compile fluidsynth as shared library. If you exchange the library, you get different capabilities of that library. May not be a common use-case on Windows, but it surely is on Linux.

Now, thinking of the idea of exposing capabilities in general: Where to start and where to end? Fluidsynth has so many compile-time-options. I don't see a benefit in exposing them.

Regarding your particular use-case: I believe your feature request is an overkill given the minor problem you're facing. It's just a filename. Since fluidsynth might be capable of loading DLS files, the *.dls wildcard should be simply included in the file-filter by default.

If you really wanted to list only those files which are supported by fluidsynth, you should call `fluid_is_soundfont()` on every single file and display only the ones for which it succeeds.

**Comment by pedrolcl** [comment]
> If you really wanted to list only those files which are supported by fluidsynth, you should call fluid_is_soundfont() on every single file and display only the ones for which it succeeds.

This doesn't work with Qt's (or any other) Open File dialog, where the user can navigate to any arbitrary directory from inside the same dialog window. You can't test the entire filesystem with `fluid_is_soundfont()`. It would be possible to test only two or three files of each type, but this would require to distribute those test files with the applications, and install the files at a known location.

In terms of simplicity, two simple lines in fluidsynth.h.in with...
~~~
#cmakedefine FLUIDSYNTH_SUPPORTS_SF3 @LIBSNDFILE_SUPPORT@
#cmakedefine FLUIDSYNTH_SUPPORTS_DLS @LIBINSTPATCH_SUPPORT@
~~~
Is the easiest, and cheapest solution, and It would be acceptable. A few other capabilities that may be worthy also are the builtin drivers, for audio and MIDI. But if you give me a choice, then I'll take the most expensive: a new boolean function to query those capabilities at runtime.

**Comment by derselbst** [comment]
> This doesn't work with Qt's (or any other) Open File dialog, where the user can navigate to any arbitrary directory from inside the same dialog window. You can't test the entire filesystem with fluid_is_soundfont().

The core problem of what you're asking for is a job for `fluid_is_soundfont()`. I am aware, that this means you would have to implement your own custom FileDialog (or perhaps derive the existing one). I am aware, that this is some effort. But it would work exactly for what you're asking for.

> In terms of simplicity, two simple lines in fluidsynth.h.in with

This is no question of simplicity. As I explained, those two lines don't do what you want. It gives you the same reliability as simply hardcoding the *.dls file-filter.

So, if we're seriously considering to add this kind of functionality, the only answer can be adding a new capability function. I'm afraid that this function will bloat up in the future and report all kinds of capabilities, options, etc. And justifying the need for  such a function solely for the purpose of setting a file-filter in a dialog is a way too small argument, I'm sorry. In the end, filenames can be anything. If they have the wrong extension, things will break. This wouldn't happen so easily when using `fluid_is_soundfont()`.

**Comment by pedrolcl** [comment]
> this function will bloat up in the future and report all kinds of capabilities, options, etc.

Then you will swear, considering this MIDI 2.0 pending feature... :rofl: 
https://www.midi.org/midi-articles/midi-capabilties-inquiry-presentation-at-adc
