### ISSUE TITLE
WAV export is distorted with short drum samples

### ISSUE THREAD

**Issue by corentingurtner** [FluidSynth/fluidsynth#1026]
Hey there,
I'm having an issue with Fluidsynth 2.2.3 (that's the last one available with brew for me). 

### FluidSynth version 
2.2.3 on MacOS 11.6 (Big Sur)

### Current behavior
When sending the output of a MIDI file (conga.mid, attached) playing one drum note to a WAV file, the audio file is distorted (see conga.wav attached). 
Here is the command I used to generate this WAV file :

`fluidsynth -L 2 -g 1 -r 44100 -R 1 -O s16 -F conga.wav ./FluidR3_GM.sf2 conga.mid`

Please not that I tried to remove the reverb (-R 1) and tried to lower the gain (-g 1) but the issue still happened. 
I exported the same audio samples in the past (few years ago) and they didn't get distorted this way, I wouldn't be able to tell you which version of fluidsynth I was using at that time though.

### Expected behavior

I attached an audio sample of what it was sounding like before, you can find in the archive ("expected conga.mp3").
It's also possible to get a quick idea of the expected output by loading FluidR3 in the fluidsynth interpreter and playing the same MIDI note than the file : 
noteOn channel 9 pitch 62 velocity 127

### Other information
Attached files
[congas.zip](https://github.com/FluidSynth/fluidsynth/files/7872379/congas.zip)

**Comment by derselbst** [comment]
> Please not that I tried to remove the reverb (-R 1)

You enabled reverb.

> tried to lower the gain (-g 1)

You increased the gain.

> -L 2

You specified two stereo channel pairs. But the fast file renderer currently only writes out the first channel pair. The wet reverb sound plays on the first channel pair. The dry sound plays on the second channel pair which is not written. Remove -L2 and it will work.

**Comment by corentingurtner** [comment]
Thanks so much for your fast answer!
Regarding -R and -g, I meant that I tried to remove this arguments in another command.

Anyway, I tried without -L 2 and it's working, I didn't realized those were stereo pairs, I was thinking about single channels instead. 

Thanks a lot, and sorry, this ticket was support in the end.

**Comment by derselbst** [comment]
I've just added a warning: #1028
