### ISSUE TITLE
Actually, "GS DT1" sysex only supports Channel 11......

### ISSUE THREAD

**Issue by LoveBodhi** [FluidSynth/fluidsynth#1035]
Other channels are not supported yet...

**Comment by derselbst** [comment]
What am I supposed to do with this issue pls? What are you asking for? I can't work like that.

Looking at the code it supports all channels:
https://github.com/FluidSynth/fluidsynth/blob/de478947bf740228c32ad57221bfd8a92b90e4ed/src/synth/fluid_synth.c#L2432

If you have a problem, provide some more information, e.g. a MIDI with which the issue can be reproduced. Or make a pull request to propose a change. But in any case, explain yourself.

**Comment by LoveBodhi** [comment]
Testing file: http://vgmusic.com/music/console/nintendo/gamecube/SH_Bingo_Highway-KM-GS.mid

I set device ID, it still not work for other channels (e.g. This uses Channel 1 for percussion)...

**Comment by derselbst** [comment]
The checksum of the SysEx message of your midi file is incorrect, causing fluidsynth to ignore the entire SysEx message.

**Comment by LoveBodhi** [comment]
Thanks for the help.

**Comment by LoveBodhi** [comment]
They're just balance problem......
