### ISSUE TITLE
synth.dynamic-sample-loading leads to frequent startup crashes now

### ISSUE THREAD

**Issue by kode54** [FluidSynth/fluidsynth#1043]
### FluidSynth version
libfluidsynth version 2.2.4, as compiled for x86 with vcpkg, with the vcpkg recipe modified to enable libsndfile support.

### Describe the bug
When linked into foo_midi, and seeking around MIDI files randomly, which invokes a full FluidSynth teardown and restart when seeking backwards, the player can sometimes crash. This crash only occurs if dynamic loading of samples is enabled.

### Expected behavior
Player should not crash when restarting FluidSynth repeatedly.

### Steps to reproduce
1. Install foo_midi under foobar2000.
2. Configure the plugin to use FluidSynth and any SoundFont file in .sf2 or .sf3 format.
3. Play Onestop.mid from Windows, or any MIDI file really.
4. Seek around the file randomly.

### Additional context
The source code lives at https://gitlab.com/kode54/foo_midi

**Comment by derselbst** [comment]
Two questions after a brief look at the source code:

1. Why are you creating 3 `fluid_synth` instances?
2. Can `SFPlayer::render` be called concurrently to `SFPlayer::shutdown`?

**Comment by kode54** [comment]
1. I need GM mapping, for three ports. 48 channel single instance never worked well for this.
2. None of the methods in the class will be called concurrently from other threads. The entire instance lives, operates, and dies within a single thread. Multiple instances may be created, but none of them are interacted with on threads other than where they were created.

**Comment by derselbst** [comment]
Ok, I'll look into it towards the end of the week.

PS: sparse41 and sparse43 of CBFD fail to play back correctly in layzusf2 when HLE is enabled. Not sure if that's already known... probably not important either as LLE works fine.

**Comment by kode54** [comment]
Cripes, it's not your bug. My code was doing a subtraction backwards:

```
if (how many to do > (done - todo)) how many to do = done - todo;
```

instead of

```
if (how many to do > (todo - done)) how many to do = todo - done;
```

With unsigned type variables, so the condition was never getting checked, and a heap corruption was occurring as a render duration greater than the requested buffer size was processed. This happened more frequently when the player was configured to render to high sample rates, such as 192 kHz.

There was another bug where that while loop would also fail to escape if it had rendered as many samples as were requested, but didn't completely render the leftover samples, because that condition wasn't checked as well. That would just lead to a lock up, not heap corruption.

Thank goodness for gflags.exe and Windows' memory heap overrun detection method.

**Comment by kode54** [comment]
> Ok, I'll look into it towards the end of the week.
> 
> PS: sparse41 and sparse43 of CBFD fail to play back correctly in layzusf2 when HLE is enabled. Not sure if that's already known... probably not important either as LLE works fine.

PS: Please repost this lazyusf2 issue on my Gitlab.com tracker for foo_input_usf, or check it out later and subscribe to the issue I'll post there. I'll check it out, nonetheless.
