### ISSUE TITLE
"All notes off" CC message erroneously turns off voices currently held in sustain

### ISSUE THREAD

**Issue by rianhunter** [FluidSynth/fluidsynth#1051]
### FluidSynth version
```
FluidSynth runtime version 2.1.7
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

FluidSynth executable version 2.1.7
Sample type=double
```

### Describe the bug
The MIDI spec says that "all notes off" message should not cut off voices that are in sustain, it should just mark them in "release mode". Verbatim:

>  THE RELATIONSHIP BETWEEN THE HOLD PEDAL AND "ALL NOTES OFF"

> If Note Off messages are received while the hold pedal (controller 64 (40H)) is 'on' they must be
> recognized but not acted upon until the release of the hold pedal. The same is true for the All Notes Off
> message. A Hold or Sustain pedal 'On' message takes priority over Note Off and All Notes Off until it is
> released.

> All Notes Off should force voices to go to the release stage of the envelope, and not terminate the sound
> of the notes abruptly. 

### Expected behavior
"All notes off" should ignore voices held in sustain or in sostenuto. For voices held in sustain, it should mark them as "off" and they should be turned off when sustain is released.

### Steps to reproduce

1. Turn on a note
2. Turn on sustain (CC#64)
3. Send "all notes off" (CC#123)
4. Note should still be playing but it is turned off.

**Comment by derselbst** [comment]
Sry, I cannot reproduce this one:

```bash
$ fluidsynth -a alsa /usr/share/sounds/sf2/FluidR3_GM.sf2
prog 0 42
noteon 0 60 127
cc 0 64 127
cc 0 123 127
# note keeps playing
noteoff 0 60
# still playing
cc 0 64 0
# note off
```

**Comment by rianhunter** [comment]
Sorry you're correct. The predicate was wrong but `fluid_voice_noteoff()` did the right thing despite that.
