### ISSUE TITLE
LSB values are not cleared when MSB CCs are received.

### ISSUE THREAD

**Issue by rianhunter** [FluidSynth/fluidsynth#1052]
### FluidSynth version
```
$ fluidsynth --version
FluidSynth runtime version 2.1.7
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

FluidSynth executable version 2.1.7
Sample type=double
```

### Describe the bug
The first 32 CCs are MSB CCs. The MIDI spec says that the LSBs that correspond to these MSBs should be set to 0 upon reception of the MSB. Verbatim:

> When an MSB is received, the receiver should set its concept of the LSB to zero. 

### Expected behavior
When I send any value to e.g. Volume MSB (CC#7) the LSB should be set to `0`.

### Steps to reproduce

1. Send any value to an MSB CC (CC#<32)
2. Its LSB will be non-zero.

**Comment by derselbst** [comment]
After having thought about this, I do have concerns here: If MSB and LSB are sent at the same tick, the order in which they arrive the synth may be undefined. E.g. the events could be received in the following order:

CC#39 = 60
CC#7 = 45

Even though both events were sent at the same tick, the MSB event will be received after the LSB event, causing the previous LSB=60 to be reset accidentally.

Also, whether or not a synth actually uses MSB and LSB, or only one of it, is not obvious to the client either. In fact, I don't even know whether all CCs in fluidsynth are 14 bits wide (i.e. use MSB and LSB). I know that we do handle portamento time as 14 bits, but we did have MIDIs which assumed it to be only 7 bits wide.

I'm afraid that such a change would cause more trouble than use. So, I would prefer to keep the current implementation, even though it's not strictly compliant.

**Comment by rianhunter** [comment]
I'm not sure what you mean about the current tick, I conceive of MIDI messages as having a definite order. Is this a thing for MIDI events that are sourced from a MIDI file? If there are MIDI software interfaces which re-arrange MIDI events that come from a file that occur at the same tick, then yes I agree it's probably better to not do this change. I just wanted to bring it up to you in case you weren't aware. At the minimum it might be good to place a comment to signify to future people that not clearing the LSB CCs is intentional.

**Comment by derselbst** [comment]
> If there are MIDI software interfaces which re-arrange MIDI events that come from a file that occur at the same tick, then yes I agree it's probably better to not do this change.

Yes. Fluidsynth's sequencer does.

But I agree it should be documented. Maybe `fluid_synth_cc` would be a good place. I'll keep this open until I do so.

**Comment by derselbst** [comment]
I just documented this behavior in the commit linked above. If you think there's another suitable place, let me know.

**Comment by rianhunter** [comment]
That seems fine enough to me! I'll let you close

**Comment by derselbst** [comment]
Thanks!
