### ISSUE TITLE
Setting `audio.periods` gives an error

### ISSUE THREAD

**Issue by jeffkaufman** [FluidSynth/fluidsynth#1058]
### FluidSynth version
```
$ fluidsynth --version
FluidSynth runtime version 2.1.7
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

FluidSynth executable version 2.1.7
Sample type=double
```
### Describe the bug

Recommended settings for low latency output give an error.

### Expected behavior

Following https://github.com/FluidSynth/fluidsynth/wiki/LowLatency should not give startup errors.

### Steps to reproduce

Run:

```
$ fluidsynth -c=2
fluidsynth: error: requested set value for setting 'audio.periods' out of range
```

This should instead configure `audio.periods` to be 2.

```
$ fluidsynth
> info audio.periods
audio.periods:
Type:          integer
Value:         16
Minimum value: 2
Maximum value: 64
Default value: 16
Real-time:     no
> set audio.periods 2
Warning: 'audio.periods' is not a realtime setting, changes won't take effect.
```

Providing a settings file also doesn't work:

```
$ fluidsynth -f <(echo "set audio.periods 2")
...
Warning: 'audio.periods' is not a realtime setting, changes won't take effect.
```

**Comment by jeffkaufman** [comment]
Workaround: build from source and change:

```
- fluid_settings_register_int(settings, "audio.periods", 16, 2, 64, 0);
- fluid_settings_register_int(settings, "audio.periods", 2, 2, 64, 0);
```

**Comment by jeffkaufman** [comment]
Thanks!  I'm not sure where I got `-c=2`; the latency docs have `-c 2` which does work.

(`-c=2` does work on 1.x, but it sounds like it's now parsing as `=2` which is invalid?)

**Comment by mawe42** [comment]
I corrected the latency docs after you opened this issue, they were indeed misleading and suggested the wrong argument style. Not sure what changed between 1.x and 2.x...

**Comment by jeffkaufman** [comment]
Thanks for letting me know you had fixed the docs! I was really confused why I had expected `-c=2` to work ;)
