### ISSUE TITLE
Add a function to create a sequencer event from a midi event

### ISSUE THREAD

**Issue by jimhen3ry** [FluidSynth/fluidsynth#1078]
### Related discussion
This idea was suggested by Tom M. at the end of Discussion #1072 .

### Is your feature request related to a problem?
MIDI input can be in the form of a FluidSynth MIDI Event ([fluid_midi_event_t](https://www.fluidsynth.org/api/group__Types.html#ga61c72b76e3ee344637994c3071f74d94)), e.g. input from the MIDI Player. An application that receives FluidSynth MIDI Events can send them to the synthesizer with [fluid_synth_handle_midi_event()](https://www.fluidsynth.org/api/group__midi__input.html#ga2327ed7bf1ff702b0ec4095b59d7d660). Alternatively, MIDI Events can be sent to the FluidSynth Sequencer with [fluid_sequencer_add_midi_event_to_buffer()](https://www.fluidsynth.org/api/group__sequencer.html#gaac5a0b2178a6d638d9c3d23b3735f4f2).

[fluid_sequencer_add_midi_event_to_buffer()](https://www.fluidsynth.org/api/group__sequencer.html#gaac5a0b2178a6d638d9c3d23b3735f4f2) "[t]ransforms an incoming MIDI event (from a MIDI driver or MIDI router) to a sequencer event and adds it to the sequencer queue for sending as soon as possible." There is no straightforward way of sending a MIDI Event to the Sequencer for sending at a later time. 

### Describe the solution you'd like
Add a function to transform an incoming MIDI event to a sequencer event _without_ adding the event to a sequencer queue. This would allow an application to use [fluid_sequencer_send_at()](https://www.fluidsynth.org/api/group__sequencer.html#ga83314f4ad773979841afe50cc2efd83f) to send a MIDI Event to the Sequencer for sending at a later time. 

fluid_event_from_midi_event(fluid_event_t*, const fluid_midi_event_t*) is the proposed function to be added.

### Additional context
It is proposed that the added function would only add the provided MIDI Event to the provided Sequencer Event. The application would need to add additional items to the Sequencer Event, e.g. a destination sequencer with [fluid_event_set_dest()](https://www.fluidsynth.org/api/group__sequencer__events.html#ga554261a62cfa890262ec26366b35ce8a), before adding the Sequencer Event to a sequencer queue. 

The current [fluid_sequencer_add_midi_event_to_buffer()](https://www.fluidsynth.org/api/group__sequencer.html#gaac5a0b2178a6d638d9c3d23b3735f4f2) would be rewritten to place its current code for transforming an incoming MIDI event to a sequencer event in the new function and use that new function.

**Comment by jimhen3ry** [comment]
I have added fluid_event_from_midi_event(fluid_event_t*, const fluid_midi_event_t*) to midi/fluid_seqbind.c and added a FLUIDSYNTH_API line to include/seqbind.h. I have rewritten fluid_sequencer_add_midi_event_to_buffer() to use fluid_event_from_midi_event(). I did a commit of these changes against my local 2.2.X branch. I did what I could think of to test these changes on a 64 bit Windows machine. 

I have not contributed to an open source project before. I need some hand holding on how you would like me to proceed from here.

**Comment by jimhen3ry** [comment]
Attached is a patch file for my proposed changes
[patch1078.txt](https://github.com/FluidSynth/fluidsynth/files/8461189/patch1078.txt)
.

**Comment by derselbst** [comment]
Looks good, thanks. Ofc, it doesn't compile because the `const` qualifier is being discarded. I will fix this by next week.

> I have not contributed to an open source project before. I need some hand holding on how you would like me to proceed from here.

You could have also forked this repo, commit and push your changes to your fork, and then create a PullRequest to propose the changes. But this way is fine either, now I opened the PullRequest: #1080

**Comment by derselbst** [comment]
Merged and will part of 2.2.7, thanks!
