### ISSUE TITLE
Many ocurrences of an error related with glib library in Android devices

### ISSUE THREAD

**Issue by pcomposer** [FluidSynth/fluidsynth#1089]
This is an example of the crash report in some android devices

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.own.pcomposer <<<

backtrace:
  #00  pc 000000000009a9e4  /apex/com.android.runtime/lib/bionic/libc.so (tgkill+12)
  #00  pc 0000000000160c8c  /data/app/~~urFH-eH3PDVKuOTzgQ_BGA==/com.own.pcomposer-U1i-B7DJjj0xxy5d3z0hOw==/split_config.armeabi_v7a.apk!lib/armeabi-v7a/libglib-2.0.so (offset 0x10a000) (__aeabi_ldiv0)
  #00  pc 00000000000099fd  /data/app/~~urFH-eH3PDVKuOTzgQ_BGA==/com.own.pcomposer-U1i-B7DJjj0xxy5d3z0hOw==/split_config.armeabi_v7a.apk!lib/armeabi-v7a/libpcomposer.so (offset 0x50c000) (generateKeysSeq)
  #00  pc 00000000000053ff  /data/app/~~urFH-eH3PDVKuOTzgQ_BGA==/com.own.pcomposer-U1i-B7DJjj0xxy5d3z0hOw==/split_config.armeabi_v7a.apk!lib/armeabi-v7a/libpcomposer.so (offset 0x50c000) (Java_com_own_pocketcomposer_audio_AudioEngine_nPlaySequence)
  #00  pc 0000000000026c09  /data/app/~~urFH-eH3PDVKuOTzgQ_BGA==/com.own.pcomposer-U1i-B7DJjj0xxy5d3z0hOw==/oat/arm/base.odex (art_jni_trampoline+176)
  #00  pc 00000000000d47d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68)
  #00  pc 00000000004f2559  /apex/com.android.art/lib/libart.so (art_quick_invoke_static_stub+276)
  #00  pc 000000000012cb3f  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+166)
  #00  pc 0000000000245c97  /apex/com.android.art/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+254)
  #00  pc 000000000023e611  /apex/com.android.art/lib/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+564)
  #00  pc 00000000004e910f  /apex/com.android.art/lib/libart.so (MterpInvokeStaticRange+370)
  #00  pc 00000000000cf694  /apex/com.android.art/lib/libart.so (mterp_op_invoke_static_range+20)
  #00  pc 000000000012f3ac  /data/app/~~urFH-eH3PDVKuOTzgQ_BGA==/com.own.pcomposer-U1i-B7DJjj0xxy5d3z0hOw==/oat/arm/base.vdex (com.own.pocketcomposer.audio.AudioEngine.access$100)
  #00  pc 00000000004e9279  /apex/com.android.art/lib/libart.so (MterpInvokeStaticRange+732)
  #00  pc 00000000000cf694  /apex/com.android.art/lib/libart.so (mterp_op_invoke_static_range+20)
  #00  pc 000000000012eea8  /data/app/~~urFH-eH3PDVKuOTzgQ_BGA==/com.own.pcomposer-U1i-B7DJjj0xxy5d3z0hOw==/oat/arm/base.vdex (com.own.pocketcomposer.audio.AudioEngine$a.a+100)
  #00  pc 0000000000236951  /apex/com.android.art/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.16941288902046113640)+248)
  #00  pc 000000000023d0c1  /apex/com.android.art/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+120)
  #00  pc 00000000004d5233  /apex/com.android.art/lib/libart.so (artQuickToInterpreterBridge+698)
  #00  pc 00000000000d9361  /apex/com.android.art/lib/libart.so (art_quick_to_interpreter_bridge+32)
  #00  pc 000000000004da43  /data/app/~~urFH-eH3PDVKuOTzgQ_BGA==/com.own.pcomposer-U1i-B7DJjj0xxy5d3z0hOw==/oat/arm/base.odex (n4.b$b.run+354)
  #00  pc 00000000000d47d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68)
  #00  pc 00000000004f2427  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+282)
  #00  pc 000000000012cb2d  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+148)
  #00  pc 00000000003ff4df  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+374)
  #00  pc 00000000003ff5ef  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+42)
  #00  pc 0000000000440b35  /apex/com.android.art/lib/libart.so (art::Thread::CreateCallback(void*)+1056)
  #00  pc 00000000000aad13  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40)
  #00  pc 0000000000064193  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)

**Comment by derselbst** [comment]
Crashes usually occur due to programmers fault. This "backtrace" is meaningless. Closing.
