### ISSUE TITLE
Create a public method for the synth so we can use fluid_sample_timer_t to create sequences

### ISSUE THREAD

**Issue by pcomposer** [FluidSynth/fluidsynth#1090]
I would like you to give public access to create fluid_sample_timer_t * and add it to the synth so we can create our custom sequencer
and avoid using the default MIDI event sequencer, that in my case is not efficient enough for android devices, i need to create a custom sequencer so if there could be a public access to fluid_sequencer_process(). so the custom sequencer can be created

**Comment by derselbst** [comment]
Your "Make-it-public-so-I-can-reinvent-my-own-custom-stuff" is not a valid argument. Start a discussion and provide more information. Closing.
