### ISSUE TITLE
Option to Treat Warnings as Error

### ISSUE THREAD

**Issue by Meerkov** [FluidSynth/fluidsynth#1091]
Hi, currently my use of fluid synth produces this message:

```
fluidsynth: warning: No preset found on channel 0 [bank=0 prog=2]
fluidsynth: warning: No preset found on channel 1 [bank=0 prog=1]
fluidsynth: warning: No preset found on channel 2 [bank=0 prog=3]
fluidsynth: warning: No preset found on channel 3 [bank=0 prog=4]
fluidsynth: warning: No preset found on channel 4 [bank=0 prog=5]
fluidsynth: warning: No preset found on channel 5 [bank=0 prog=0]
```

I'd like to treat this as an error, rather than a warning. Is there an option to do so? If not, can one be added? Otherwise I need to have a script do some asynchronous processing of this log message in order to kill the command, which is inconvenient.

**Comment by derselbst** [comment]
To treat warnings as errors, just use the same error logging function for both, errors and warnings:

```
void my_error_log_function(int level, const char *message, void *data)
{
    // ...
}

fluid_set_log_function(FLUID_ERR, &my_error_log_function, NULL);
fluid_set_log_function(FLUID_WARN, &my_error_log_function, NULL);
```

**Comment by Meerkov** [comment]
@derselbst this doesn't fix the problem, because if you download the compiled .exe you can't change these values.
