### ISSUE TITLE
Handle disabling of Velocity to Filter Cutoff modulator in a better manner

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#11]
Issue posted to fluid-dev by S. Christian Collins  

<http://lists.gnu.org/archive/html/fluid-dev/2008-01/msg00040.html>  

Seems this default modulator has changed between [SoundFont](/apps/trac/fluidsynth/wiki/SoundFont) specifications. In particular, [SoundFont](/apps/trac/fluidsynth/wiki/SoundFont) version 2.04 drops the amount source switch behavior (which seemed moronic to begin with). FluidSynth should be modified to be smarter about encountering modulators meant to disable this "feature" (turn off this modulator if any velocity to filter cutoff is seen with an amount of 0 and either the amount source is not specified or is a switch velocity source) and also perhaps remove the switch component from the default.  

Reported by: elementgreen

Original Ticket: [fluidsynth/tickets/11](https://sourceforge.net/p/fluidsynth/tickets/11)

**Comment by derselbst** [comment]
@mawe42 I would like to get rid of this hack: 
https://github.com/FluidSynth/fluidsynth/blob/master/src/synth/fluid_mod.c#L327-L342

What is your opinion of handling velocity 2 attenuation modulator? Should it be default according to 2.04 spec? Should we have a setting to let the user decide whether it should be default? Or should we completely remove it from the code and the user would still have the option to manually add such a modulator to any instrument?

**Comment by mawe42** [comment]
And for the 2.01 disabling detection, allow both types: the one according to 2.01 spec with negative polarity for source2, and the one mentioned in the code and used in the "Kingston Piano" with positive polarity. So don't check source2 polarity at all.

Then we've got another hack, but I think this one can't be avoided. And it is still much nicer than the current way of doing things...

**Comment by derselbst** [comment]
Oh yes vel2fc (copy'n paste :) ).

> Well, musically I think it makes no sense to have this as a default modulator.

Same opinion. We have been pretty successful although ignoring it. And if there is an instrument where it would really make sense, the user could still manually add a modulator for it.

> and detect if a soundfont tries to disable either the 2.01 or 2.04 version and react accordingly... Then we've got another hack

I was actually not intending to fight a hack with yet another hack. I could imagine that there might be cases causing unwanted behaviour.

**Comment by mawe42** [comment]
So you would rather have no vel2fc modulator by default and add a setting to enable 2.04 behaviour on request? That sounds fine by me. Then FS doesn't behave according to spec, but with the current hack it hasn't for a long time anyway. And nobody seems to have noticed or cared :-)

**Comment by derselbst** [comment]
Not quite sure regarding the setting yet. The advantage of having _no_ such setting would be that any vel2fc modulator hack in any soundfont could be safely removed. It would be absolutely clear to the user that if any filtercutoff is needed, one would have to manually add a custom modulator (and I dont think there would be many instruments requiring that). Introducing a setting however would mean that the user must be aware of whether this must be turned on or off and this again could vary from file to file... not the clean solution I was looking for.

**Comment by derselbst** [comment]
In fact the amount of this modulator really matters and heavily depends among different instruments. E.g. listening to a standard piano with the default 2.04 vel2fc mod I cannot tell the difference whether the mod is on or off. I have to at least triple the amount to hear any effect.

So I really think this should be manually specified on a per instrument basis by the user. Having this as def mod seems to be pointless to me. But I'm a programmer, no musician, so...

**Comment by mawe42** [comment]
> The advantage of having no such setting would be that any vel2fc modulator hack in any soundfont could be safely removed.

But only if those soundfonts are only used by FluidSynth. There are many other engines out there, some of which probably implement the default vel2fc modulator. So if I would create a new SoundFount, I would always add the vel2fc override (unless I want this effect, of course).

**Comment by derselbst** [comment]
Main engines like SynthFont, VirtualMidiSynth and TiMidity dont support it either, see a [test done by Christian Collins](https://docs.google.com/spreadsheets/d/1QzqA9IetT7MVDhG-oSFAWrciyg6O-oaQ_hGsl8fKeSo/edit#gid=2011028303). And some further info [here](https://docs.google.com/document/d/1CwLMch1hgcp18H2VjLZ9Zi2hvgM8nxEHx03zVrXWT2I/edit).

**Comment by mawe42** [comment]
Ah, very interesting! Well, that seems to settle it, doesn't it? Remove vel2fc default modulator completely but allow for custom modulators to be added. But what Christian Collins says about FluidSynth in the compatibility chart is not quite correct:

> FluidSynth is right, in my opinion, to leave a default curve out of their implementation, while allowing custom modulators to function normally.

Only the not-quite-to-spec default modulator with a positive unipolar switch on the secondary source is ignored. The negative unipolar switch as specified in 2.01 is still applied. And "allowing custom modulators to function normally" is only true if the custom modulator doesn't use the same setup as the default one but with a different amount. 

And that's the thing that is still bugging me: if they decided a few year ago that ignoring the 2.01 vel2fc is the way to go, why didn't they just remove the default modulator but decided on this hacky (and incomplete, it seems) override in fluid_mod_get_value?

**Comment by mawe42** [comment]
> Only the not-quite-to-spec default modulator with a positive unipolar switch on the secondary source is ignored. The negative unipolar switch as specified in 2.01 is still applied. 

Ignore this please, I was confused. There is no vel2fc with negative unipolar switch as secondary source set up as default modulator in FluidSynth. So there's no need to ignore that as well.
