### ISSUE TITLE
Unsynchronized and unbalanced playback

### ISSUE THREAD

**Issue by Magnus26** [FluidSynth/fluidsynth#1102]
### FluidSynth version
_Execute `fluidsynth --version` and provide the output._

2.1.7 and 2.2.7

### Describe the bug
_Provide a clear and concise description of the current situation, e.g. how the bug manifests._

Playback is unsynchronized and unbalanced between instrument and vocal parts in Igor Engraver 1.7 via Wine in Q4OS.

### Expected behavior
_Provide a clear and concise description of what you expected to happen._

A synchronized and balanced playback like with Fluidsynth 1.1.

### Steps to reproduce
_Please explain the steps required to duplicate the issue, esp. if you are able to provide a sample application. E.g. how to start fluidsynth, what shell commands to enter, what midi events to send, etc._

Launch QSynth 0.9.1 and Igor Engraver 1.7. Open a score in Igor Engraver and start playback.

### Additional context
_If you are able to illustrate the bug with an example, please provide simple
source code below or as attached file. List any other information that is relevant to your issue, e.g. stack traces, related issues, build logs, suggestions on how to fix, links to related discussions at fluid-dev, etc._

```
insert code snippets, soundfonts or anything relevant here, or attach it as extra file(s) if it's too much
```

**Comment by derselbst** [comment]
Please provide a download link for Igor Engraver

**Comment by Magnus26** [comment]
I believe I have solved the problem by making the following settings in QSynth's Setup dialog window: MIDI tab: MIDI Client Name ID (ALSA/CoreMidi): qsynth; Audio tab: Audio Channels and Audio Groups: 1.

**Comment by derselbst** [comment]
I just had a listen and it sounds ok to me. As you seem to have found a solution, I'll close this issue.
