### ISSUE TITLE
Conversion from 'size_t' to 'int', possible loss of data

### ISSUE THREAD

**Issue by jimhen3ry** [FluidSynth/fluidsynth#1104]
### FluidSynth version
2.2.7 commit 308cf73

### Describe the bug
The Windows Visual Studio 2022 compiler gives a warning for line 143 of fluid_midi.c:
`mf->buf_len = length;`
because mf->buf_len is an int and length is a size_t.

### Additional context
Should the typedef for fluid_midi_file in fluid_midi.h be changed to make buf_len a size_t?

**Comment by jimhen3ry** [comment]
My proposed change pushes the issue down to fluid_midi.c, fluid_midi_file_read() on line 252 where mf->buf_len is used in calculations of bytes read. Perhaps it would be better to cast in the assignment on line 143:
`mf->buf_len = (length < INT_MAX) ? (int)length : -1;`
I haven't worked through the implications of the extremely unlikely possibility of mf->buf_len = -1.

**Comment by derselbst** [comment]
Fixed by f013e82d58d00e8feb7e82e22051632c61893306 . If you ever find a MIDI file bigger 2GB, pls. give me a copy.
