### ISSUE TITLE
fluid_wasapi.c: conversion from 'size_t' to 'int', possible loss of data

### ISSUE THREAD

**Issue by jimhen3ry** [FluidSynth/fluidsynth#1105]
### FluidSynth version
2.2.7 commit 308cf73

### Describe the bug
In fluid_wasapi.c, fluid_wasapi_finddev_callback(), on line 844 string_t wcslen(id) is assigned to int nsz, which potentially causes a loss of data.

### Additional context
nsz needs to be an int when passed as an arg to WideCharToMultiByte() on line 832. Should the assignment on line 844 be changed to
`nsz = (wcslen(id) < INT_MAX) ? (int)wcslen(id) : -1;`
The lines following use nsz as follows:
`    d->id = FLUID_ARRAY(wchar_t, nsz + 1);
    FLUID_MEMCPY(d->id, id, sizeof(wchar_t) * (nsz + 1));
`
As best I can figure, neither FLUID_ARRAY nor FLUID_MEMCPY will throw an error for nsz = -1. But I think the call with nsz = -1 will at least be safe, and extremely unlikely. Of course, the whole scenario of wcslen(id) > INT_MAX is extremely unlikely. This issue is really about making paranoid compilers happy.

**Comment by derselbst** [comment]
Fixed in d554067fc553465177e68982f0bd6f6aab4c2cfb .
