### ISSUE TITLE
/etc/fluidsynth.conf not loaded

### ISSUE THREAD

**Issue by FredFoo** [FluidSynth/fluidsynth#1118]
### FluidSynth version
FluidSynth executable version 2.2.7
Alpine Linux 3.16.0 on a Raspberry Pi 3

### Describe the bug
If you provide $home/.fluidsynth and for instance set a default soundfont the soundfont is loaded. If you move the file to /etc/fluidsynth.conf (copied both filenames from the defaults in the source code in this repo) nothing happens. Have no idea where it fails in the code and cannot see an error message other than the default sf2 does not exist. 

### Expected behavior
Load and process both files just the same.

### Steps to reproduce
- create $home/.fluidsynth and add setting
- start fluidsynth and check if setting has been applied
- stop fluidsynth, move $home/.fluidsynth to /etc/fluidsynth.conf
- start fluidsynth again and check for the same setting to be applied

### Additional context
I assumed that in the file settings are given as if entering them on the cli, i.e. a line contains for example
```
set synth.default-soundfont /some/path/to/some/valid/file.sf2

```
In my case the purpose of the installation is only running fluidsynth. I run everything as root.

**Comment by derselbst** [comment]
Thanks for the report. Fluidsynth didn't check whether the user config file actually existed. This has been fixed by the linked PR.
