### ISSUE TITLE
2.2.9 Hardening options for systemd service are problematic for user service

### ISSUE THREAD

**Issue by dvzrv** [FluidSynth/fluidsynth#1147]
### FluidSynth version
2.2.9

### Describe the bug
After upgrading the Arch Linux package to 2.2.9 in testing, I received the bug report [#75821](https://bugs.archlinux.org/task/75821).
In it it becomes clear that hardening options only possible for systemd **system services** have been applied to the fluidsynth systemd **user service** (in https://github.com/FluidSynth/fluidsynth/commit/3d1fcea29a19472d6c18ff5755b14cc719718220) and prevent the service from starting:

* ProtectHostname
* ProtectHome
* ProtectKernelTunables
* ProtectKernelModules
* ProtectKernelLogs
* ProtectControlGroups

The commit references that the above are allegedly automatically added to systemd services on openSUSE (https://en.opensuse.org/openSUSE:Security_Features#Systemd_hardening_effort). If this is indeed the case *also* for systemd **user services**, then that is wrong. Either way, the above sandboxing options do not work for systemd **user services** and need to be removed!

### Expected behavior
Only hardening options available to **user services** are used.

### Steps to reproduce

```
systemctl --user start fluidsynth
```

### Additional context
Most of the documentation of available hardening options can be found in `man systemd.exec` (see subsections in https://man.archlinux.org/man/systemd.exec.5#SANDBOXING). Great care has to be taken not to use those only available in **system services** (e.g. running as a privileged user or as root).

**Comment by derselbst** [comment]
Ok. Admittedly, I don't really know how people are using this service downstream. The patch already exists  for almost a year in the opensuse repository. And since nobody complained I assumed it's fine to be applied upstream. I wasn't aware of user services. Thanks for the report.

**Comment by bluca** [comment]
@dvzrv @derselbst these option can work for user units, but right now `PrivateUsers=yes` has to be set too, as that enables a user namespace which allows the user manager to do mounts. I'll send a PR to do so. The alternative is to also remove ProtectSystem= which also does not work without PrivateUser=.

**Comment by dvzrv** [comment]
Hmm, how does this work on kernels that have user namespaces disabled?

**Comment by bluca** [comment]
> Hmm, how does this work on kernels that have user namespaces disabled?

It does not, and gracefully falls back. But all distributions nowadays enable user namespaces, as it's needed for sandboxing Chrome, Firefox, Flatpak and such.

**Comment by dvzrv** [comment]
> But all major distributions nowadays enable user namespaces, as it's needed for sandboxing Chrome, Firefox, Flatpak and such.

That is only partly true. I'm currently running linux-hardened which disables it by default ;)
But yeah, if it indeed falls back gracefully if it is not enabled, then that is alright. :)

**Comment by bluca** [comment]
Sure, there are some stragglers, but fewer and fewer, because these days the browser is the main attack vector on any user machine, and the sandboxing implemented by user namespaces gives effective and significant improvements on that front.

**Comment by dvzrv** [comment]
> It does not, and gracefully falls back.

@bluca it unfortunately does not fall back gracefully.

@derselbst I have received yet another report (https://gitlab.archlinux.org/archlinux/packaging/packages/fluidsynth/-/issues/2) of this not working on kernels where user namespaces are disabled by default.

What is the course of action here?

**Comment by derselbst** [comment]
My knowledge about systemd and all those hardening options is limited. I can hardly provide an advice here. I'm open for suggestions. However, reverting the hardening options again seems counterproductive, as the Arch user is using a hardened flavor of linux, and reverting the sandboxing would open it up again, at least from my understanding. Ofc. packagers are free to (partly) revert or change the systemd service files for their distros.

**Comment by dvzrv** [comment]
I understand.

I guess generally it is a sane default when assuming that most kernels offer namespace support by default.

The hardened kernel being somewhat special in that it requires users to actively opt in to the use of namespaces probably means that we should clarify this in our [distribution wiki](https://wiki.archlinux.org/title/Security#Kernel_hardening).

In the mentioned ticket I have pointed at two ways of working around the issue arising with the use of namespaces in systemd user services.

Generally, I guess it would be good to figure out whether a fallback was in place and then removed, whether it never worked or whether there never was one. Again, I guess that is probably not something for you to figure out though (would be great to hear @bluca's thoughts on it though).

**Comment by LukasThyWalls** [comment]
> It's because the options below can't be used in user service.
> 
> ```
> ProtectKernelTunables=true
> ProtectKernelModules=true
> ProtectKernelLogs=true
> ProtectControlGroups=true
> ```

Yeah, I read all the topic, what I'm saying is this is how It comes actually by default in my system (It works as a user service, It has those options in the systemd service file) and by default It doesn't work until you edit that.

So, or the distribution needs to take care of that, or there is other configuration they didn't make to made it work?
