### ISSUE TITLE
audio.jack.autoconnect erroneously connects to MIDI ports

### ISSUE THREAD

**Issue by ReinholdH** [FluidSynth/fluidsynth#1149]
When using audio.jack.multi=1 not all ports and fx are connected, and as a consequence - after the bug happens - ports are connected alternating to the wrong output side. The bug is in fluid_jack.c line 637, 658

If jack_connect fails with err because jack_ports[o] won't exist "i" needs to be decremented. See "i--" added in order to connect port "i" to jack_ports[0] again. Otherwise port "i" does not get connected, and the following port gets connected to the wrong output side.
 
Here is the snapshot of fluid_jack.c starting with line 613
` if(autoconnect)
    {
        jack_ports = jack_get_ports(client, NULL, NULL, JackPortIsInput | JackPortIsPhysical);

        if(jack_ports && jack_ports[0])
        {
            int err, o = 0;
            int connected = 0;

            for(i = 0; i < 2 * dev->num_output_ports; ++i)
            {
                err = jack_connect(client, jack_port_name(dev->output_ports[i]), jack_ports[o++]);

                if(err)
                {
                    FLUID_LOG(FLUID_ERR, "Error connecting jack port");
                }
                else
                {
                    connected++;
                }

               if (!jack_ports[o])
               {
                    o = 0;
                    i--;    //  i needs to be decremented
                }
            }

            o = 0;
            for(i = 0; i < 2 * dev->num_fx_ports; ++i)
            {
                err = jack_connect(client, jack_port_name(dev->fx_ports[i]), jack_ports[o++]);

                if(err)
                {
                    FLUID_LOG(FLUID_ERR, "Error connecting jack port");
                }
                else
                {
                    connected++;
                }

                if (!jack_ports[o])
                {
                    o = 0;
                    i--; //  i needs to be decremented
                }
            }

            jack_free(jack_ports);   /* free jack ports array (not the port values!) */
        }
        else
        {
            FLUID_LOG(FLUID_WARN, "Could not connect to any physical jack ports; fluidsynth is unconnected");
        }
    }`
I hope this is the final solution. Works fine in my setup. Can somebody double-check. Thx.

**Comment by ReinholdH** [comment]
I want to add that the used settings are

audio.jack.multi=1
synth.audio-channels=16
synth.audio-groups=16

**Comment by derselbst** [comment]
The purpose of that line

https://github.com/FluidSynth/fluidsynth/blob/97eefe959be59ff1f93a8921e18bfbe0e044ed53/src/drivers/fluid_jack.c#L635

is to check whether we have reached the end of the NULL terminated array of Jack's physical ports. Note that `o` has been incremented during  the `jack_connect` call, so this now points to the next port. This is not related to any potential connection error during `jack_connect`.

With your change, some of fluidsynth's ports are being connected twice (e.g. l05, l10, l15, r02, r07, r12):
![grafik](https://user-images.githubusercontent.com/8152480/189535283-f9932891-2501-4303-8265-ac9f47fd3adb.png)

You probably meant to decrement `i` in that if-clause:
https://github.com/FluidSynth/fluidsynth/blob/97eefe959be59ff1f93a8921e18bfbe0e044ed53/src/drivers/fluid_jack.c#L626-L629

However, doing so is potentially dangerous as it might cause the loop to never terminate.

I think it would be better to figure out why jack is failing to connect to these ports. Any details that caused the error?

**Comment by ReinholdH** [comment]
Thanks for the immediate response. Yes, I agree. My proposal from above is wrong but the solution is much more simple.

"audio autoconnect" needs to be restricted to audio ports only :-).

In line 615 of fluid_jack.cpp
`jack_ports = jack_get_ports(client, NULL, NULL, JackPortIsInput | JackPortIsPhysical);`
all ports are taken into account including MIDI ports. If MIDI ports are present and activated in addition to audio ports the "audio autoconnect" fails. Line 615 needs to be
`jack_ports = jack_get_ports(client, NULL, JACK_DEFAULT_AUDIO_TYPE, JackPortIsInput | JackPortIsPhysical); `                             
This change works fine in my setup. Is this proposal OK?

**Comment by derselbst** [comment]
Oh, ofc. Thanks Reinhold! Just opened the PR.
