### ISSUE TITLE
Please add a 'fluid_player_get_total_time' and 'fluid_player_get_current_time' functions in milliseconds and pause/resume functions too.

### ISSUE THREAD

**Issue by SlackerNReckless** [FluidSynth/fluidsynth#1151]
Hi! :-)

Well, we can get the total ticks using the 'fluid_player_get_total_ticks' function and the current tick with the 'fluid_player_get_current_tick' functions. But not in milliseconds. 

And a pause/resume function named 'fluid_player_pause' and another one called 'fluid_player_resume' like the functions: 'fluid_player_play', 'fluid_player_seek', 'fluid_player_stop' enabling us to pause/resume the player.

Well, I'd like to write a Delphi MIDI player using the awesome fluidsynth library. Yeah... using the 'libfluidsynth-3.dll'. I know about Audacious but I'd like to write an own.

Note: it's non-commercial, for private use. 

Anyway, thanks for reading this message and my best regards! ;-)

**Comment by derselbst** [comment]
To make `fluid_player_get_total_ticks` return msecs one would need to keep track of all past and future tempo change events, by building up a tempo change map. This is a huge amount of implementation and testing effort and surely won't happen unless somebody (you) makes a contribution. Also, the return value of this function would change whenever someone overrides the player's tempo via `fluid_player_set_tempo`.

Fluidsynth's MIDI player shall provide very basic functionality. For anything beyound that, I usually recommend to use a proper MIDI parsing library.

On the other hand, exposing `fluid_player_get_current_tick` with msec should be trivial to do.

**Comment by SlackerNReckless** [comment]
Ok! Looks like I'll have to rely on a MIDI library.  :-|

Well, actually I already wrote not only a MIDI player as a fully featured Audio Player based on [BASS library](http://www.un4seen.com/bass.html) by Un4seen Developments but I really liked the way FluidSynth plays MIDI files, very "fluid"! :-D 

So I imagined I could write a nice MIDI player using it but it seems I can't only with this FluidSynth, as you even said above, its player API is very basic.

And by the way, I know I can simulate a pause/resume by getting the current tick, stopping the player and then seeking the player to that position and playing it from.

Anyway... Thanks for replying me. Cheers! ;-)

**Comment by SlackerNReckless** [comment]
Hey! It's me again...

Well, I could write my FluidSynth Player. In Delphi with help of this [pasfluidsynth - Pascal translation of FluidSynth headers](https://gitlab.com/bunnylin/pasfluidsynth/). I just converted that unit to Delphi as that unit is for Freepascal / Lazarus. I just converted the functions I needed. Not all.  Please, don't ask me for a "port" of it.

I had to use a MIDI parsing library, actually a simple Delphi component (unit) to get the duration of the file in milliseconds. It's the only thing I really wanted in this 'libfluidsynth'. Like I said above I could simulate a successful pause/resume button by using stop, getting the current tick and then resuming the playback in that position.

I also implemented a seek bar, just a TScrollBar (Delphi's VCL), actually a standard ScrollBar by just sending a stop, seeking the position and then resuming playback. 

Actually this "FluidSynth Player" I developed is a fork of my "BASS Player" without equalizer and effects provided by the BASS library. Just a MIDI Player with support for "customized" SoundFonts. Something like, if it finds a SoundFont with the same filename of the MID file it will load that SoundFont instead of using the configured one. Something Audacious lacks. 

Well, in the BASS library this featured is supported even with a SoundFont already configured. 

FluidSynth is great, but really limited. :-(

And I think you could create a Virtual MidiOutput driver like some soft synthesizers like BASSMIDIDrv. VirtualMidiSynth (based on BASSMIDI) and other soft synthesizers out there like OmniMIDI and SynthFont. Google for! 

Well, creating a SoundFont synthesizer with the only intent of provide a MIDIinput driver to be used with a Keyboard or passing raw MIDI events to it is completely useless.  It would be nice to have a MidiOutput driver like these soft synthesizers have. 

By the way, I'm not new in soundfonts technology, I still have an old Sound Blaster AWE32 ISA card in an old PC I have here with 8MB of Wavetable RAM, not counting my SoundBlaster Live!'s cards, I have 3! and an Audigy one. You know the EMU8000, EMU10k1 and EMU10k2 processors!!! 

I need to say I'm a Pascal/Delphi and Freepascal/Lazarus programmer. Although I know C/C++ and other languages like JAVA my language is Pascal and often I translate "header" files of C/C++ libraries to Pascal. 

I just dislike C/C++. Pascal is more classy! :-P

Anyway... everything is working fine now. They are working 'fluidly'. YEAH! :-D  

And thanks for your time reading this. 

P.S. You can close this "issue" if you want. ;-)
