### ISSUE TITLE
Starting with commit 1e740e8, the synth output sounds different

### ISSUE THREAD

**Issue by vladkosi** [FluidSynth/fluidsynth#1182]
### FluidSynth version
Commit 1e740e89d22c3655e4295b4933dc7c71d705ebbd

### Describe the bug
Using this soundfont https://github.com/trevor0402/SC55Soundfont/releases the "strings" in Doom 2 title music sound different.

### Steps to reproduce
```
fluidsynth -R 0 -C 0 -r 44100 -F output.wav SC-55.SoundFont.v1.2b.sf2 DM2TTL.MID
```

### Expected behavior
I am not sure if the output should sound the same. Maybe the new one is correct.

### Additional context
Output from build https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=8495&view=results
[output-c27bd35.zip](https://github.com/FluidSynth/fluidsynth/files/9946100/output-c27bd35.zip)

Output from build https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=8511&view=results
[output-fa27689.zip](https://github.com/FluidSynth/fluidsynth/files/9946101/output-fa27689.zip)

[DM2TTL.zip](https://github.com/FluidSynth/fluidsynth/files/9946104/DM2TTL.zip)

**Comment by derselbst** [comment]
Wow, you seem to be very familiar with that tune to spot such a decent difference. But you're absolutely correct. In the commit you've linked I completely overlooked that `fluid_ct2hz_real()` and `fluid_act2hz()` behave differently for negative values. I've fixed that. I'm pretty confident it's backward compatible. The original sound should be restored. Pls have a test, here are the fixed binaries:
https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=8537&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by vladkosi** [comment]
I was testing old versions of GZDoom and this is the Doom 2 start-up music.

The sound is fixed in the linked binaries.

**Comment by derselbst** [comment]
Great, thanks for reporting!
