### ISSUE TITLE
Tuning does not work for MIDI files.

### ISSUE THREAD

**Issue by ROBROSY** [FluidSynth/fluidsynth#1200]
`double pitch[12]={100,400,200,700,500,800,700,900,800,300,600,1000};

fluid_settings=new_fluid_settings();
fluid_settings_setnum(fluid_settings,"synth.sample-rate",SOUNDFREQUENCY);
fluid_synth=new_fluid_synth(fluid_settings);
fluid_synth_sfload(fluid_synth,"/usr/share/sounds/sf2/default-GM.sf2",1);
fluid_synth_activate_octave_tuning(fluid_synth, 0, 0,"256", pitch, 1);
for(a=0;a<16;a++) fluid_synth_activate_tuning(fluid_synth,a,0,0,1);
fluid_player=new_fluid_player(fluid_synth);
fluid_player_add(fluid_player,"for_elise_by_beethoven.mid");`

I'm downloading music via fluid_synth_write_s16 and I can't hear the pitch changes.

If instead of player I use fluid_settings_setstr(fluid_settings, "audio.driver", "alsa");fluid_audio = new_fluid_audio_driver(fluid_settings, fluid_synth); and fluid_synth_noteon - tuning change is heard.

Description is weak, vague, misleading, few examples.

It is not explained what **bank, prog, apply** is, what **name** is used for.

It is not stated that after fluid_synth_activate_octave_tuning you should use fluid_synth_activate_tuning and assign tuning to a specific channel. The **apply** description suggests that you don't have to, it should work immediately, for all notes, i.e. all channels.

**Comment by ROBROSY** [comment]
Another example:

`#include <stdlib.h>
#include <string.h>
#include <fluidsynth.h>
 
/* An example midi file */
const char MIDIFILE[] = {
    0x4d, 0x54, 0x68, 0x64, 0x00, 0x00, 0x00, 0x06,
    0x00, 0x01, 0x00, 0x01, 0x01, 0xe0, 0x4d, 0x54,
    0x72, 0x6b, 0x00, 0x00, 0x00, 0x20, 0x00, 0x90,
    0x3c, 0x64, 0x87, 0x40, 0x80, 0x3c, 0x7f, 0x00,
    0x90, 0x43, 0x64, 0x87, 0x40, 0x80, 0x43, 0x7f,
    0x00, 0x90, 0x48, 0x64, 0x87, 0x40, 0x80, 0x48,
    0x7f, 0x83, 0x60, 0xff, 0x2f, 0x00
};
 
int main(int argc, char** argv)
{
    int i;
    void* buffer;
    size_t buffer_len;
    fluid_settings_t* settings;
    fluid_synth_t* synth;
    fluid_player_t* player;
    fluid_audio_driver_t* adriver;
    settings = new_fluid_settings();
    synth = new_fluid_synth(settings);
    player = new_fluid_player(synth);
    fluid_settings_setstr(settings, "audio.driver", "alsa");
    adriver = new_fluid_audio_driver(settings, synth);
    fluid_synth_sfload(synth, "/usr/share/sounds/sf2/default-GM.sf2", 1);
    double pitch[12]={100,400,200,700,500,800,700,900,800,300,600,1000};
    fluid_synth_activate_octave_tuning(synth, 0, 0,"256", pitch, 1);
    for(int a=0;a<16;a++) fluid_synth_activate_tuning(synth,a,0,0,1);
    /* queue up the in-memory midi file */
    fluid_player_add_mem(player, MIDIFILE, sizeof(MIDIFILE));
    /* play the midi file */
    fluid_player_play(player);
    /* wait for playback termination */
    fluid_player_join(player);
    fluid_player_seek(player,0);
    fluid_player_play(player);
    fluid_player_join(player);
    /* cleanup */
    delete_fluid_audio_driver(adriver);
    delete_fluid_player(player);
    delete_fluid_synth(synth);
    delete_fluid_settings(settings);
    return 0;
}
`

**Comment by derselbst** [comment]
I hear 3 notes being played with the tuning you've specified. The second call to play() repeats the MIDI, but this time, there is no tuning. That's because the setting [player.reset-synth](https://www.fluidsynth.org/api/fluidsettings.xml#player.reset-synth) defaults to true. Add a 
`fluid_settings_setint(settings, "player.reset-synth", 0);` into the code to prevent resetting of the synth.

I haven't tested whether it makes a difference when using fluid_synth_write_s16 - but I cannot imagine why it should.

I'm unable to provide additional information about the tuning API, as I'm not familiar with it.

**Comment by ROBROSY** [comment]
OK, after installing the new version, it actually works like this...
Although you might wonder if the tuning should reset after the song ends...

**Comment by derselbst** [comment]
> OK, after installing the new version, it actually works like this...

Thanks for confirming.

> Although you might wonder if the tuning should reset after the song ends...

This is the idea behind the setting. If you don't like, disable it as I suggested.

**Comment by ROBROSY** [comment]
But I can't just turn it off because I understand other settings are also reset.
