### ISSUE TITLE
3 errors pop up anytime i run fluidsynth

### ISSUE THREAD

**Issue by jamo2011** [FluidSynth/fluidsynth#1204]
### FluidSynth version 
2.3.1

### Current behavior
fluidsynth: error: not enough MIDI in devices found. Expected:1 found:0
fluidsynth: error: Device "default" does not exists
Failed to create the MIDI thread; no MIDI input
will be available. You can access the synthesizer
through the console.

### Expected behavior
Not giving me 3 errors

### Other information

![Screenshot_20230116_084846](https://user-images.githubusercontent.com/107405252/212693503-012fbdaa-e78f-4b04-99fc-2fefd31b7a80.png)

**Comment by derselbst** [comment]
Do you have a MIDI device plugged in?
Yes: Start fluidsynth with `--verbose` to see additional information to figure out what's going on.
No: Start fluidsynth with the `-n` flag.
