### ISSUE TITLE
Starting fails on IPv4-only systems

### ISSUE THREAD

**Issue by 3hhh** [FluidSynth/fluidsynth#1205]
### FluidSynth version 
2.1.7

### Current behavior

On a debian-11 with `5.10.0-20-amd64` kernel and `GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX ipv6.disable=1"`  in `/etc/default/grub`:

```
> fluidsynth -a pulseaudio -m alsa_seq -i -l -s -p FluidSynth /usr/share/sounds/sf3/default-GM.sf3
FluidSynth runtime version 2.1.7
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

fluidsynth: error: Failed to create server socket: 97
Failed to create the server.
Continuing without it.
fluidsynth: warning: Failed to set thread to high priority
fluidsynth: Using PulseAudio driver
fluidsynth: warning: Failed to set thread to high priority
```
--> Doesn't start.

### Expected behavior

Starts.

### Other information

IIRC it worked until recently with a different kernel version. Maybe the Linux kernel changed its behaviour?

`strace`:
```
[...]
openat(AT_FDCWD, "/home/user/.fluidsynth", O_RDONLY) = -1 ENOENT (No such file or directory)
socket(AF_INET6, SOCK_STREAM, IPPROTO_IP) = -1 EAFNOSUPPORT (Address family not supported by protocol)
write(2, "fluidsynth: error: Failed to cre"..., 54fluidsynth: error: Failed to create server socket: 97
) = 54 
write(2, "Failed to create the server.\nCon"..., 52Failed to create the server.
[...]
lstat("/run", {st_mode=S_IFDIR|0755, st_size=800, ...}) = 0
lstat("/run/user", {st_mode=S_IFDIR|0755, st_size=60, ...}) = 0
lstat("/run/user/1000", {st_mode=S_IFDIR|0700, st_size=200, ...}) = 0
lstat("/run/user/1000/pulse", {st_mode=S_IFDIR|0700, st_size=80, ...}) = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 12
fcntl(12, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
setsockopt(12, SOL_SOCKET, SO_PRIORITY, [6], 4) = 0
fcntl(12, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(12, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
connect(12, {sa_family=AF_UNIX, sun_path="/run/user/1000/pulse/native"}, 110) = 0
sendto(10, "W", 1, MSG_NOSIGNAL, NULL, 0) = -1 ENOTSOCK (Socket operation on non-socket)
write(10, "W", 1)                       = 1
clock_gettime(CLOCK_MONOTONIC, {tv_sec=5989, tv_nsec=431246028}) = 0
write(10, "W", 1)                       = 1
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f6518ab6000
mprotect(0x7f6518ab7000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7f65192b5ef0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[2767], tls=0x7f65192b6700, child_tidptr=0x7f65192b69d0) = 2767
futex(0x5586a257dfa8, FUTEX_WAIT_PRIVATE, 0, NULLfluidsynth: warning: Failed to set thread to high priority
) = 0
futex(0x5586a257e2b0, FUTEX_LOCK_PI_PRIVATE, NULL) = 0
getpid()                                = 2763
getpid()                                = 2763
getpid()                                = 2763
getpid()                                = 2763
getpid()                                = 2763
getpid()                                = 2763
clock_gettime(CLOCK_MONOTONIC, {tv_sec=5989, tv_nsec=434464802}) = 0
write(10, "W", 1)                       = 1
clock_gettime(CLOCK_MONOTONIC, {tv_sec=5989, tv_nsec=434519215}) = 0
write(10, "W", 1)                       = 1
futex(0x5586a257e2b0, FUTEX_UNLOCK_PI_PRIVATE) = 0
futex(0x5586a257dfac, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x5586a257e2b0, FUTEX_LOCK_PI_PRIVATE, NULL) = 0
futex(0x5586a257e2b0, FUTEX_UNLOCK_PI_PRIVATE) = 0
write(2, "fluidsynth: Using PulseAudio dri"..., 36fluidsynth: Using PulseAudio driver
) = 36
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f65182b5000
mprotect(0x7f65182b6000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7f6518ab4ef0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[2768], tls=0x7f6518ab5700, child_tidptr=0x7f6518ab59d0) = 2768
futex(0x7f6518ab59d0, FUTEX_WAIT, 2768, NULLfluidsynth: warning: Failed to set thread to high priority
[...]
```

**Comment by derselbst** [comment]
> Expected behavior
Starts.

Why? Compiling fluidsynth with IPv6 support and then disabling IPv6 via Grub is surely not considered to be a use-case. If you don't want IPv6, compile fluidsynth from source by passing `-Denable-ipv6=0` to cmake.

> IIRC it worked until recently with a different kernel version. Maybe the Linux kernel changed its behaviour?

I will certainly not start debugging the Linux kernel for you because of this.

**Comment by 3hhh** [comment]
> > Expected behavior
> > Starts.
> 
> Why?

Because most servers do it that way:
If one socket (be it IPv4 or IPv6) is not available for some reason, still provide the service on the other socket. Probably spit out some warning. If no socket can be opened, fail to start.
Check the Apache, lighttpd, nginx, ... whatever code.

> Compiling fluidsynth with IPv6 support and then disabling IPv6 via Grub is surely not considered to be a use-case. If you don't want IPv6, compile fluidsynth from source by passing `-Denable-ipv6=0` to cmake.

A compile-time feature flag is meant to enable an _additional_ feature, not break a previously existing IMHO.
E.g. enabling `jack` shouldn't break `pulseaudio`.

**Comment by derselbst** [comment]
> Because most servers do it that way:
If one socket (be it IPv4 or IPv6) is not available for some reason, still provide the service on the other socket. Probably spit out some warning. If no socket can be opened, fail to start.

I get your point. However, it has been that way for 9 years and you're the first one to complain. So pls. excuse, but I believe this is a very low-priority issue.
 If this fallback behavior really is so important to you, I welcome your PR to implement this.

**Comment by 3hhh** [comment]
Hm if I read the code correctly, `fluidsynth` always only starts exactly one IP stack. That's also unexpected as most servers start their service on both stacks, if IPv6 support is enabled. There's usually a configuration option to explicitly select the IP stack to use for users with other needs.

That unfortunately makes implementing this feature way beyond my C skills.

Also, I now guess that the debian maintainers recently switched from IPv4 to IPv6, possibly thinking the same way I did.

Documenting that `-Denable-ipv6=1` enables IPv6 _at the cost of_ disabling IPv4 might help.

**Comment by derselbst** [comment]
> Documenting that -Denable-ipv6=1 enables IPv6 at the cost of disabling IPv4 might help.

Done. I opened #1208, flagged with "Help wanted". Let's see if someone is willing to do it.
