### ISSUE TITLE
Fails to build without OpenMP

### ISSUE THREAD

**Issue by pkubaj** [FluidSynth/fluidsynth#1216]
### FluidSynth version
2.3.1

### Describe the bug
When OpenMP support is not present, Fluidsynth doesn't build (even with enable-openmp disabled).

### Expected behavior
enable-openmp should make it possible to build fluidsynth without OpenMP.

### Steps to reproduce
make -C /usr/ports/audio/fluidsynth (on FreeBSD/powerpc or FreeBSD/armv7)

### Additional context
The problem is probably because CMakeLists.txt first looks for OpenMP support and checks for enable-openmp later.

**Comment by derselbst** [comment]
Pls. provide the full CMake console output as well as `CMakeOutput.log` and `CMakeError.log`.
