### ISSUE TITLE
Missing dependency "libomp.so" on the Android release.

### ISSUE THREAD

**Issue by Roboron3042** [FluidSynth/fluidsynth#1222]
### FluidSynth version
2.3.1

### Describe the bug
Missing dependency on the Android release:
```
Error: dlopen failed: library "libomp.so" not found: needed by.../libfluidsynth.so
```

### Expected behavior
All FluidSynth Android dependencies are included in the release.

### Steps to reproduce
I downloaded fluidsynth-2.3.1-android24.zip for use on an Android project. Added every library as target on my CMake project and linked to it. At runtime, it complained that "libomp.so" is mising.

**Comment by Roboron3042** [comment]
Thank you very much - I didn't know OpenMP was in the Android NDK already. After linking to it everything works as expected.

May I suggest to document this somewhere? The [BuildingForAndroid)](https://github.com/FluidSynth/fluidsynth/wiki/BuildingForAndroid) page persuades users to use the build artifacts (rightfully so) and points them to the readme - but there is no information about how to do that there.

Later it is also mentioned the "using prebuilt libraries on Android" document, but either this document does not exist or I was not able to find it...

Personally a small README in the artifacts' archive pointing out that linking to the OpenMP present in Android NDK is necessary would have suffixed for me.

**Comment by derselbst** [comment]
> May I suggest to document this somewhere?

Yeah, sure. You're welcome to edit the wiki or wherever you think it fits best.

**Comment by Roboron3042** [comment]
Thank you. Added the missing page "Using prebuilt libraries on Android". Hopefully this will be helpful to the next dev in need.

**Comment by derselbst** [comment]
Nice, thanks!
