### ISSUE TITLE
pause/silence added between tracks in playback queue

### ISSUE THREAD

**Issue by liPillON** [FluidSynth/fluidsynth#1227]
### FluidSynth version
FluidSynth runtime version 2.3.1
FluidSynth executable version 2.3.1
Sample type=float
I used the [official](https://github.com/FluidSynth/fluidsynth/releases/tag/v2.3.1) Win64 binaries to reproduce the bug.

### Describe the bug
Countinuous playback of midi files designed to be played on repetition is broken, due to pause/silence being added between each "loop".

### Expected behavior
The attached midi file is 1m56s long and designed to give users the impression of looping on itself, when played on "repeat track" mode. There should not be any pause/silence between each repetition of the track.

### Steps to reproduce
Launch `fluidsynth.exe TimGM6mb.sf2 D_E5M1.mid D_E5M1.mid` to have the track being played 2 times in a row.
Using the 2.3.0 binaries the playback will be seamless.
Using the 2.3.1 binaries there will be a few seconds of silence between the 1st and 2nd repetition.

### Additional context
This is not limited to fluidsynth.exe - applications relying on libfluidsynth are also affected:
https://github.com/fabiangreffrath/woof/issues/962 

### Test Files & Logs
I'm attaching the midi file and the soundfont used.
The logs captured using `fluidsynth.exe --verbose` show what's happening during the switch between the 1st and 2nd repetition of the track.

[D_E5M1.mid.zip](https://github.com/FluidSynth/fluidsynth/files/11088204/D_E5M1.mid.zip)
[TIMGM6MB.SF2.zip](https://github.com/FluidSynth/fluidsynth/files/11088205/TIMGM6MB.SF2.zip)
[230verbose.txt](https://github.com/FluidSynth/fluidsynth/files/11088525/230verbose.txt)
[231verbose.txt](https://github.com/FluidSynth/fluidsynth/files/11088526/231verbose.txt)

**Comment by fabiangreffrath** [comment]
Possibly connected to this change:
https://github.com/FluidSynth/fluidsynth/commit/752bf65e39731301c2300cf92e3ccc10a22079e8

**Comment by liPillON** [comment]
adding a few pingbacks to other (probably) related issues/prs

https://github.com/FluidSynth/fluidsynth/issues/24
https://github.com/FluidSynth/fluidsynth/pull/1159
https://github.com/FluidSynth/fluidsynth/discussions/1165
https://github.com/FluidSynth/fluidsynth/pull/1167


apologies if this is considered spamming..

**Comment by fabiangreffrath** [comment]
The following patch fixes the issue for me:
```patch
--- a/src/midi/fluid_midi.c
+++ b/src/midi/fluid_midi.c
@@ -2179,6 +2179,8 @@ fluid_player_callback(void *data, unsigned int msec)
             fluid_atomic_int_set(&player->seek_ticks, -1); /* clear seek_ticks */
         }
 
+        if(player->currentfile->next == NULL && player->loop == NULL)
+        {
         /* Once we've run out of MIDI events, keep playing until no voices are active */
         if(status == FLUID_PLAYER_DONE && fluid_synth_get_active_voice_count(player->synth) > 0)
         {
@@ -2207,6 +2209,7 @@ fluid_player_callback(void *data, unsigned int msec)
         {
           status = FLUID_PLAYER_PLAYING;
         }
+        }
 
         /* Once there's no reason to keep playing, we're actually done */
         if(status == FLUID_PLAYER_DONE)
```

**Comment by derselbst** [comment]
@topaz Fabian suggests to only apply your "MIDI-Player-fadeout"-change (#1159), when the player has reached the last file in the queue. Would you agree with this or would it break your use-case?

**Comment by topaz** [comment]
I agree with the intent of this change; it does not break my use-case.

The way the proposed change is implemented makes me wonder if there exists a better solution where instead of making https://github.com/FluidSynth/fluidsynth/blob/e141c2edb188a97f081354b816103fc1f1af41bc/src/midi/fluid_midi.c#L2182-L2209 conditional, that code is moved somewhere so that it just naturally triggers after the whole playlist completes. However, I'm not sure where that _somewhere_ is, and it seems like it would need to prevent the final call to https://github.com/FluidSynth/fluidsynth/blob/e141c2edb188a97f081354b816103fc1f1af41bc/src/midi/fluid_midi.c#L2217-L2220 in that situation. If such a location doesn't exist, the change as proposed seems acceptable.

**Comment by derselbst** [comment]
Thanks for the feedback @topaz - I had a look, but couldn't find a better place to put it.
@liPillON Thanks for the report and @fabiangreffrath for the fix!
