### ISSUE TITLE
Allow the user to select the channel in the banks

### ISSUE THREAD

**Issue by batata004** [FluidSynth/fluidsynth#1235]
Hi, when I open Fluidsynth on android I can assign to each line a soundfont which will only be played on a specific channel.

However frequently I need to play more than one instrument together when I press a key on my midi controller. However my midi controller only sends the key presses to a specific channel that I configured in it. So, if I configure it to send the notes to channel 3 then Fluidsynth will only play the instrument loaded in the third line. But what if I need to play 2 different instruments? If I place them on different lines, each one will be assigned to a different channel...

Is this possible with the current implementation or do you know any android app that allows me to do that?

Thank you and congratulations for this amazing work.!

**Comment by derselbst** [comment]
> But what if I need to play 2 different instruments?

There are several options. Obviously, modify your controller to send events on multiple channels. Or add some MIDI routing app in between which performs this job. Or you probably achieve that with different MIDI modes. For the latter, pls. learn [about MIDI modes 1 - 4 and basic channels](http://www.philrees.co.uk/articles/midimode.htm#base). We've also got plenty of [documentation](https://github.com/FluidSynth/fluidsynth/raw/master/doc/polymono/FluidPolyMono-0004.pdf) how this is implemented in fluidsynth. If you need further support, pls. ask at the mailing list, you'll reach way more people.

**Comment by batata004** [comment]
@derselbst You are awesome, thank you for clarification! Unfortunatelly my MIDI CONTROLLER only sends data in a single channel. What I am doing today is using different instruments for different keys on my midi controller. For example: for key notes from 20 to 30 I use PAD sounds... for key notes from 40 to 80 I use piano sound, from 80 to 127 I use drum... I just need an app that allows me to do that, unfortunatelly the only way I am finding this possible is using apps named DAW... but they are bloated with lots of features I dont need and most of them are paid.

What is the easiest way you would recommend me to accomplish this? I just use a midi controller with my android tablet to play live in restaurants/bars and I would like a simple app that allows me to play different instruments for different keys..
