### ISSUE TITLE
It looks like the midi CC for cutoff (74) is not implemented, right?

### ISSUE THREAD

**Issue by batata004** [FluidSynth/fluidsynth#1238]
I tried using effects like Reverb and Chorus and they work as expected, I mean, FluidSynth seems to be reading their CC values. However for some reason the Cutoff on CC 74 is not having any effect in the app. Is that true? Or FluidSynth is using another differet CC?

**Comment by derselbst** [comment]
The SoundFont 2 specification doesn't specify a default implementation for CC74. Pls. refer to the wiki for details:
https://github.com/FluidSynth/fluidsynth/wiki/FluidFeatures
