### ISSUE TITLE
libfluidsynth: negative sample refcount when a soundfont is shared by multiple synth instances

### ISSUE THREAD

**Issue by PhysSong** [FluidSynth/fluidsynth#1256]
### FluidSynth version
FluidSynth version 2.3.3(`libfluidsynth.so.3.2.0`) on Arch Linux

### Describe the bug
`delete_fluid_synth()` may hang due to `sample->refcount` being negative, which makes `fluid_sfont_delete_internal` fail.
https://github.com/FluidSynth/fluidsynth/blob/a85aa9811ca511809964fd55f692120baa362640/src/sfloader/fluid_defsfont.c#L250-L253
This only happens when multiple `fluid_synth_t` instances share a `fluid_sfont_t` instance, and they are manipulated by multiple different threads.

### Expected behavior
`sample->refcount` is always non-negative, and `delete_fluid_synth()` doesn't fail

### Steps to reproduce
You can refer to https://github.com/LMMS/lmms/issues/6437 for real-world examples.

### Additional context
This was found while investigating a bug in LMMS(https://github.com/LMMS/lmms/issues/6437). See [here](https://github.com/LMMS/lmms/issues/6437#issuecomment-1605900145) for the original comment.
The relevant code in LMMS can be found in https://github.com/LMMS/lmms/blob/master/plugins/Sf2Player/Sf2Player.cpp.

**Comment by derselbst** [comment]
Interesting, thanks for the report. Just had a quick look into LMMS' code: so it does essentially create a new `fluid_synth_t` for every SF2 track, does it? And when you create a new project or quit it deletes all the synths and the issue occurs, right?

**Comment by PhysSong** [comment]
> Interesting, thanks for the report. Just had a quick look into LMMS' code: so it does essentially create a new `fluid_synth_t` for every SF2 track, does it? And when you create a new project or quit it deletes all the synths and the issue occurs, right?

Basically, it's true. Things like note on and note off are handled in multiple worker threads, so I suspect something goes wrong when multiple threads access multiple synths sharing one soundfont, such as note events at the same time across multiple tracks.

**Comment by derselbst** [comment]
I had a look into that.

From my understanding, you keep adding the same `fluid_sfont_t` to multiple synths through `fluid_synth_add_sfont`. But this is illegal. Cf. the API docs of that function:

> ownership is transferred to synth.

`fluid_sfont_t` is the administrative structure for maintaining a soundfont, containing all the presets, instruments and samples. By doing so, you make multiple synths believe that they have exclusive access to those structures. When each synth is then driven by a different thread, this must go wrong.

Do not try to share soundfonts between synths. Instead, call `fluid_synth_sfload` everytime when loading a new font. Fluidsynth shares the samples between all synths via its internal sample cache. Hence the memory consumption should stay (almost) the same, even when loading the same big soundfont over and over again.

---

IMO, you should also address the logic behind `sf2Instrument::updateSampleRate()`: Whenever you clone a track, this slot is called and destroys all synths, then recreates them, even though the sample rate has obviously not changed. Also, the constructor of `sf2Instrument` calls this slot after having set up itself, basically resulting in complete reconstruction again.

**Comment by PhysSong** [comment]
> Fluidsynth shares the samples between all synths via its internal sample cache.

Thanks. Is that also true for FluidSynth 1? I'm asking this because LMMS still supports v1.

**Comment by derselbst** [comment]
It was introduced in 1.1.7: https://github.com/FluidSynth/fluidsynth/wiki/ChangeLog#fluidsynth-117

**Comment by PhysSong** [comment]
Thanks. I'll update the downstream issues accordingly.
