### ISSUE TITLE
Some notes being duplicated when rendering a wav audio file

### ISSUE THREAD

**Issue by ErickPicheli** [FluidSynth/fluidsynth#1262]
### FluidSynth version
FluidSynth version 2.3.2

### Describe the bug
Some notes are being played twice when rendering a midi input to a wav audio, I tweaked some of the available settings trying to figure out what could be causing this behavior without success.

### Expected behavior
An audio output without some notes being duplicated.

### Steps to reproduce
This only happens with a few MIDI inputs, I am not quite sure what aspect of these particular MIDI files is causing the issue, unfortunately I can't really attach a MIDI file.

Edit: It seems this is caused by notes happening in a quick enough succession, if this is quick enough, the first note is played twice, instead of the expected sequence(I'm not quite sure this is exactly what's causing the issue).

**Comment by derselbst** [comment]
You need to provide a MIDI file. Otherwise, I can't reproduce this.

**Comment by ErickPicheli** [comment]
I figure I could just link a google drive with an example: https://drive.google.com/file/d/1t2Es-iUR5TtkBtmqh1cPQWtQTbeapgkg/view?usp=sharing

This is one of the MIDI files unexpectedly repeating notes

**Comment by derselbst** [comment]
[Mirror: Gwyn, Lord of Cinder.zip](https://github.com/FluidSynth/fluidsynth/files/12138424/Gwyn.Lord.of.Cinder.zip)

I don't hear any "duplicate notes". Pls. be more specific where / when you hear them.

**Comment by ErickPicheli** [comment]
[Gwyn.Lord.of.Cinder.zip](https://github.com/FluidSynth/fluidsynth/files/12139235/Gwyn.Lord.of.Cinder.zip)
Here's an example of a rendered wav file from the same MIDI, there are repeating notes right in the beginning, could this be because of some octave restraint? I notice the note is played in the same octave twice, but really in the MIDI it's the same note but one octave lower and then one octave higher.

**Comment by ErickPicheli** [comment]
https://drive.google.com/file/d/1blmz4rxraIDPoJOnL14ddGLmhEtj_blF/view?usp=sharing
Here's an example of a rendered wav file from the same MIDI, there are repeating notes right in the beginning, could this be because of some octave restraint? I notice the note is played in the same octave twice, but really in the MIDI it's the same note but one octave lower and then one octave higher.

**Comment by derselbst** [comment]
Here is what I hear when running:

```bash
fluidsynth -F gwyn.ogg -T oga -ni /usr/share/sounds/sf2/FluidR3_GM.sf2  Gwyn\,\ Lord\ of\ Cinder.mid
```

[gwyn.zip](https://github.com/FluidSynth/fluidsynth/files/12139700/gwyn.zip)

Which Soundfont are you using and what's the exact command you're using?

**Comment by ErickPicheli** [comment]
I just discovered that the problem was in other manipulations I was doing previously in the MIDI file, before rendering the audio, the problem was not at all related with FluidSynth! I really appreciate the help, and sorry for the confusion.
