### ISSUE TITLE
Make settings more pleasing, natural and subtler

### ISSUE THREAD

**Issue by es20490446e** [FluidSynth/fluidsynth#1282]
The chorus effect makes the sound more realistic while increasing its stage.

But as seen in:
- https://github.com/coelckers/prboom-plus/issues/65
- https://code.videolan.org/videolan/vlc/-/issues/25483

When the effect is too strong it makes the audio sound weirdly widened, with plenty of songs uncomfortable to listen.

So I'm suggesting making the chorus effect default settings more subtle, in particular using the defaults of chocolate-doom:
- level: from 2.0 to 0.35.
- depth: from 8.0 to 5.0

These new values will slightly colorize the audio, making it sound more natural. But without making it sound like New Age music.

I have tested them with a bunch of games, with the [GeneralUser](https://schristiancollins.com/generaluser.php) soundfont, and I found no longer any problem with it.

If you agree with these, I can make a pull request.

**Comment by es20490446e** [comment]
@derselbst @jjceresa @mawe42 Let me know if you want this.

**Comment by mawe42** [comment]
> @derselbst @jjceresa @mawe42 Let me know if you want this.

I don't really have a preference here. But subtler chrous generally sounds good to me.

**Comment by kitchen-ace** [comment]
Hi, I was asked to comment on this through https://github.com/chocolate-doom/chocolate-doom/issues/1261 

One of the issues with the fluidsynth chorus algorithm is that it seems to significantly increase the volume of whatever it's applied to, relative to other instruments. Furthermore the amount of chorus an instrument gets is determined by the soundfont instrument defaults, and not any midi CCs. So if the software calling fluidsynth doesn't provide a way to adjust the chorus settings, it renders some soundfonts effectively unusable.

I found using the suggested settings above (level: from 2.0 to 0.35, depth: from 8.0 to 5.0) brings the chorus back down to a balanced level, even for those with a lot of chorus on them, without completely muting the effect.

**Comment by es20490446e** [comment]
I'm working on a fix right now.

[S. Christian Collins](https://schristiancollins.com), the author of the GeneralUser GS sound-font, shared with me his refined settings. Which he had tested with plenty of midi files and other sound-fonts.

Personally, after a huge amount of tries, I was unable to improve them. I will post some demos along with a pull request when it is ready.

**Comment by derselbst** [comment]
In general I'm open to change the default settings. I would not apply such a change for a 2.3.x release, though. But for a future fluidsynth 2.4.0 this should be ok.

I have seen the DarkBasic zip file in the linked issue seems to originate from one author only. If possible, having a few more demo songs from other authors would be helpful as well.

**Comment by es20490446e** [comment]
I will be making some tests for a while, to see how well the settings play with different sound-fonts and songs, and I will come back to you.

**Comment by jjceresa** [comment]
Of course changing the fx unit default settings values shouldn't be a problem. But as this will change the sound, this should be documented at future release time.

@kitchen-ace

>..Furthermore the amount of chorus an instrument gets is determined by the soundfont instrument defaults, and not any midi CCs..

No, sorry, CC 93 allows level chorus send independently on each instrument. See SF2 specs chapter 8.4.9.

@es20490446e. As your changes affect also Reverb unit, I suggest to change this issue title

**Comment by jjceresa** [comment]
>Shall I take any further action?

Just changing the title as appropriate. Thanks.

**Comment by derselbst** [comment]
Thanks for your PR. Your changes look good, but I didn't had a chance to test this yet. Pls. keep this issue open until the change is merged.
