### ISSUE TITLE
Bad dependency requires on fluidsynth 2.3.2+

### ISSUE THREAD

**Issue by AngryPenguinPL** [FluidSynth/fluidsynth#1295]
### FluidSynth version
 2.3.2/2.3.4

### Describe the bug
After compilation, the package does not pass rpm tests. There is a wrong dependency request to install packages that do not exist. Which prevents the installation of the fluidsynth package.

The last good version of fluidsynth was 2.3.1, the problem started from version 2.3.2 and continues until now in 2.3.4.

Here is what it looks:
```
cooker_main_updates                             6.0 kB/s | 2.3 kB     00:00    
DEBUG util.py:446:  Error: 
DEBUG util.py:446:   Problem: conflicting requests
DEBUG util.py:446:    - nothing provides cmake(oboe) needed by lib64fluidsynth-devel-2.3.4-1.x86_64 from @commandline
DEBUG util.py:446:    - nothing provides (cmake(instpatch) or cmake(InstPatch)) needed by lib64fluidsynth-devel-2.3.4-1.x86_64 from @commandline
DEBUG util.py:446:    - nothing provides (cmake(jack) or cmake(Jack)) needed by lib64fluidsynth-devel-2.3.4-1.x86_64 from @commandline
DEBUG util.py:446:    - nothing provides (cmake(lash) or cmake(LASH)) needed by lib64fluidsynth-devel-2.3.4-1.x86_64 from @commandline
DEBUG util.py:446:    - nothing provides (cmake(midishare) or cmake(MidiShare)) needed by lib64fluidsynth-devel-2.3.4-1.x86_64 from @commandline
DEBUG util.py:446:    - nothing provides (cmake(opensles) or cmake(OpenSLES)) needed by lib64fluidsynth-devel-2.3.4-1.x86_64 from @commandline
DEBUG util.py:446:    - nothing provides (cmake(pipewire) or cmake(PipeWire)) needed by lib64fluidsynth-devel-2.3.4-1.x86_64 from @commandline
DEBUG util.py:446:    - nothing provides (cmake(portaudio) or cmake(PortAudio)) needed by lib64fluidsynth-devel-2.3.4-1.x86_64 from @commandline
DEBUG util.py:446:    - nothing provides (cmake(readline) or cmake(Readline)) needed by lib64fluidsynth-devel-2.3.4-1.x86_64 from @commandline
DEBUG util.py:446:    - nothing provides (cmake(sndfile) or cmake(SndFile)) needed by lib64fluidsynth-devel-2.3.4-1.x86_64 from @commandline
DEBUG util.py:446:    - nothing provides (cmake(systemd) or cmake(Systemd)) needed by lib64fluidsynth-devel-2.3.4-1.x86_64 from @commandline
DEBUG util.py:448:  (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Worth to add there is no such cmake package like "(cmake(jack)"  and other. This requires is bogus.

I was able to reproduce this problem on OpenMandriva Cooker, ROME and 5.0 releases. Also looks like ROSA Linux is also affected. They trying workaround problem by this requires exlude: https://abf.io/import/fluidsynth/commit/ca846f5e6f21b58a15f11076c70e150811945c48#diff-F1R5

### Expected behavior
Package install fine.

### Steps to reproduce
1.Compile fluidsynth 2.3.2+
2. Try pass rpm testes or just install it on rpm based distro from Mandriva family like OpenMandriva or ROSA Linux.

**Comment by derselbst** [comment]
Fluidsynth is neither responsible for maintaining RPM packages, nor does it generate or manage dependencies for these packages. If your distribution adds cmake-based `Requires` clauses (through some kind of intransparent rpmbuild-macro-magic), it should also make sure to generate corresponding `Provides` clauses for packages like Oboe, Jack, Lash, Pipewire and all the other packages being complained about. Since this doesn't seem to be the case, you should report this bug to the package maintainer of your distribution.
