### ISSUE TITLE
Unable to load DLS files in fluidsynth 2.3.4 Windows builds.

### ISSUE THREAD

**Issue by RoqueDeicide** [FluidSynth/fluidsynth#1298]
### FluidSynth version
2.3.4

### Describe the bug
DLS files don't load. "error: Not a Soundfont file" is printed out when attempting to load one from the shell. "Parameter 'RLNDGM.DLS' not a SoundFont or MIDI file or error occurred identifying it." message is printed out when attempting to load one from the command line.

### Expected behavior
DLS files should be able to load.

### Steps to reproduce
Attempt to load any DLS file from any Windows build from 2.3.4 release page.

### Additional context
Tried to load gm.dls and RLNDGM.DLS with the same result. libinstpatch-2.dll is present in all 2.3.4 Windows builds, but it doesn't appear to be loaded by fluidsynth.exe. Logs for fluidsynth compilation for Release 34 in Azure indicate "Support for DLS files:   no (libinstpatch not found)".

**Comment by derselbst** [comment]
Thanks for the report. Support for DLS and SF3 in the precompiled binaries seems to have gone lost in 2.3.2. The PR linked above should fix the issue. Feel free to grab the `fluidsynth-x64` artifact from here and let me know whether it works for you:
https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=9829&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by RoqueDeicide** [comment]
Thank you. I downloaded fluidsynth-x64, and it appears to load DLS files successfully, but, oddly enough, it now prints "error: Not a Soundfont file" regardless of how I load the DLS file. Whatever, it works, as far as I am concerned.

**Comment by derselbst** [comment]
Thanks for confirming. That error is fine - it just tries the SF2 loader before it attempts the DLS loader.
