### ISSUE TITLE
fluidsynth: error: Internal error: Trying to replace an existing rvoice in fluid_rvoice_mixer_add_voice?!

### ISSUE THREAD

**Issue by Wayho** [FluidSynth/fluidsynth#1300]
### FluidSynth version
_Execute `fluidsynth --version` and provide the output._

### Describe the bug
_Provide a clear and concise description of the current situation, e.g. how the bug manifests._

### Expected behavior
_Provide a clear and concise description of what you expected to happen._

### Steps to reproduce
_Please explain the steps required to duplicate the issue, esp. if you are able to provide a sample application. E.g. how to start fluidsynth, what shell commands to enter, what midi events to send, etc._

### Additional context
_If you are able to illustrate the bug with an example, please provide simple
source code below or as attached file. List any other information that is relevant to your issue, e.g. stack traces, related issues, build logs, suggestions on how to fix, links to related discussions at fluid-dev, etc._

```
insert code snippets, soundfonts or anything relevant here, or attach it as extra file(s) if it's too much
```

**Comment by derselbst** [comment]
No ticket description, no information to understand and reproduce this issue. Closing.
