### ISSUE TITLE
Fluidsynth not playing GS midi properly. 

### ISSUE THREAD

**Issue by visionblue20** [FluidSynth/fluidsynth#1304]
Fluidsynth 2.3.4

Channel 11 drums, sound balancing

When playing a GS midi from my karaoke machine to fluidsynth it does not sound right
USB MIDI interface > Fluidsynth

It should sound as good as the MIDI-OX + Virtualmidisynth as demo'd in this youtube video https://youtu.be/4iQ1ZLxeTds

**Comment by visionblue20** [comment]
Fluidsynth 2.3.4

Channel 11 drums, sound balancing

When playing a GS midi from my karaoke machine to fluidsynth it does not sound right
USB MIDI interface > Fluidsynth

It should sound as good as the MIDI-OX + Virtualmidisynth as demo'd in this youtube video https://youtu.be/4iQ1ZLxeTds

**Comment by derselbst** [comment]
> It should sound as good as the MIDI-OX + Virtualmidisynth

What is "good"? "Good" is your personal opinion. Its nothing that I could possibly implement. And it's not a bug if you don't like it.

I can hear, that the percussions are louder in Virtualmidisynth. I don't know why, as this is proprietary software and you have neither provided the MIDI nor the soundfont file.

Fluidsynth however strictly follows the attenuation and volume envelopes defined by the SoundFont2 spec. Fluidsynth on the other hand doesn't claim to be an accurate GS MIDI synth. If you want your soundfont to sound different from the default given by the SF2 spec, and more closer to GS, you need to define modulators in your soundfont, see
https://github.com/FluidSynth/fluidsynth/wiki/FluidFeatures
