### ISSUE TITLE
XG bank drum-channel auto-switch not sufficient

### ISSUE THREAD

**Issue by ReinholdH** [FluidSynth/fluidsynth#1307]
We recently activated SysEx support in our apps. This is an excellent enhancement of fluidsynth. 

However, many (hundreds...!!) of MIDI files horribly sound as drums.
A detailed research shows that these statements in fluid_chan.c cause the problem. 

    if(style == FLUID_BANK_STYLE_XG)
    {
        /* XG bank, do drum-channel auto-switch */
        /* The number "120" was based on several keyboards having drums at 120 - 127,
           reference: https://lists.nongnu.org/archive/html/fluid-dev/2011-02/msg00003.html */
        chan->channel_type = (120 <= bankmsb) ? CHANNEL_TYPE_DRUM : CHANNEL_TYPE_MELODIC;
        return;
    }

Those MIDI files which sound horribly use MSB = 120 for drums and MSB = 121 for the instruments. 
My conclusion, taking into account reference link in the code, that the correct MSBs for drums are 120, 126, 127 but not the complete range from 120 to 127.

**Comment by derselbst** [comment]
Thanks Reinhold. Indeed, even the linked discussion on the mailing list only mentions banks 120, 126 and 127. I am tempted to change this behavior as you suggested for the next 2.3.5 release, even though the referenced code already exists for 14 years.

**Comment by derselbst** [comment]
Oh right, thanks: 91b86d8bbdf922eda764c41c6325d8150485a368

Will become publicly available soon.

**Comment by hikari-no-yume** [comment]
Hi, I just happened to stumble upon this.

Are you aware that copies of the Yamaha XG specifications are available online? The [Yamaha XG spec version 2.0](http://www.jososoft.dk/yamaha//pdf/XGspec2-00e.pdf) on page 236 has this handy table:

![image](https://github.com/user-attachments/assets/e810a0e6-33a9-4be4-8c88-077af1334c6d)

As you can see the bank MSB is split into nibbles, and the table puts the high nibbles in the columns and the low nibbles in the rows. For the bank MSB numbers you have mentioned:

- 120 = 78h. In the table it's "GM2 Sound".
- 121 = 79h. In the table it's "GM2 Percussion".
- 122 through 125 (= 7Ah through 7Dh) are left blank.
- 126 = 7Eh. In the table it's "XG SFX Kit".
- 127 = 7Fh. In the table it's "XG Drum Kit".

After the table, the spec has these comments on those numbers:

![image](https://github.com/user-attachments/assets/5e751acc-5190-4229-80d4-ccfe93734fa6)
![image](https://github.com/user-attachments/assets/5edec299-4453-43f6-9c4c-d1fcb96a1681)

It also comments on a number of other MSBs and LSBs.

Based on this, it does seem correct that 121, 126 and 127 should be drumkits. But notice they do have different fallback behaviours.

**Comment by hikari-no-yume** [comment]
In case you're reading the email notification: sorry, I confused 120 with 121 when I wrote my comment, I fixed this now.
