### ISSUE TITLE
"fluidsynth" fails to load a soundfont in "Godot"

### ISSUE THREAD

**Issue by jlx-286** [FluidSynth/fluidsynth#1308]
### FluidSynth version
```
FluidSynth runtime version 2.3.4
Copyright (C) 2000-2023 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.4
Sample type=float
```

### Describe the bug
- "fluidsynth" fails to load a soundfont in "[Godot](https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_mono_win64.zip)"
(but the "Unity Editor" works normally)
- part of the output in "[cmd.exe](file:///C:/Windows/System32/cmd.exe)"
```
fluidsynth: error: Invalid chunk id in level 0 parse
fluidsynth: error: Failed to load SoundFont "TimGM6mb.sf2"
```

### Expected behavior
load (for a while) and play [the song](file:///C:/Windows/Media/onestop.mid)

### Steps to reproduce
- enable "fluidsynth command" if not enabled
    + [download FluidSynth](https://github.com/FluidSynth/fluidsynth/releases/download/v2.3.4/fluidsynth-2.3.4-win10-x64.zip) and "unzip"
    + add the directory of "libfluidsynth-3.dll" to "`%path%`"
    + reboot
- "run libfluidsynth"
    + "`private const string PluginName = "libfluidsynth-3";`" instead in the "166th" row of the script "<https://github.com/jlx-286/lunatic-rave-3/blob/master/LR3_default(480p)/Scripts/FluidManager.cs> or <https://github.com/jlx-286/lunatic-rave-3/blob/master/LR3_WMIX(720p)/Assets/Scripts/FluidManager.cs>"
    + run "Godot_v3.5.3-stable_mono_win64.exe" in "cmd.exe" or open "Godot_v3.5.3-stable_mono_win64_console.cmd"
    + play the (Godot) project
    + part of the output in "cmd.exe" (`fluid_synth_sfload` returns -1)
    ```
    fluidsynth: error: Invalid chunk id in level 0 parse
    fluidsynth: error: Failed to load SoundFont "TimGM6mb.sf2"
    ```

### Additional context
- the (Godot) project: <https://github.com/jlx-286/lunatic-rave-3/tree/master/LR3_default(480p)>
- ~~<https://assetstore.unity.com/packages/tools/audio/fluid-midi-player-173680>~~
- ~~<https://github.com/godotengine/godot/issues/89213>~~

**Comment by derselbst** [comment]
Given the error message, it's very likely that the soundfont file is broken. Please provide the soundfont file.

**Comment by jlx-286** [comment]
<https://github.com/jlx-286/lunatic-rave-3/blob/master/LR3_default(480p)/TimGM6mb.sf2>

**Comment by derselbst** [comment]
Ok, the provided soundfont is valid. To be absolutely sure, pls. check the hashes of the file you're using:

```
$ md5sum Tim.sf2 
1f1ad87ae6f87033d9a591eca567d919  Tim.sf2
$ sha256sum Tim.sf2 
c5378b62028c920cb11e4803327983fee2f2cdff5dc89c708e39da417e51c854  Tim.sf2
```

If they are the same, one would need to investigate deeper, for which I'm currently lacking time though.

**Comment by jlx-286** [comment]
But "[audioplugin-fluidsynth-3.dll](https://assetstore.unity.com/packages/tools/audio/fluid-midi-player-173680)" works in "Godot"

**Comment by derselbst** [comment]
Aha, so you have exchanged the dll and then it loads the soundfont correctly? I have no knowledge about Godot. And as we have confirmed that the soundfont is structurally valid and loaded correctly by the standalone version of fluidsynth (with the officially built binaries you've linked), I would pass this issue back to the Godot maintainers. @AThousandShips FYI.
