### ISSUE TITLE
Can't modulate `Vib LFO freq` slowly

### ISSUE THREAD

**Issue by yukulele** [FluidSynth/fluidsynth#1310]
### FluidSynth version

FluidSynth runtime version 2.2.5
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.5
Sample type=double

### Describe the bug

I have a sf2 file with a modulator `CC-01 Modulation wheel` to `Vib LFO freq`.

When I slowly modulate `CC-01` from `0` to `127` LFO seem to be stopped

### Expected behavior

The LFO should gradually become faster and faster. (as Polyphone does)

### Steps to reproduce

* open [sample-LFO-freq.sf2](https://github.com/FluidSynth/fluidsynth/files/14774802/sample-LFO-freq.zip) with fluidsynth
* start playing a note
* slowly vary the modulation wheel from 0 to 127
*

**Comment by derselbst** [comment]
Works fine in fluidsynth 2.3.5

```
> noteon 0 60 126
> cc 0 1 0
> cc 0 1 10
> cc 0 1 20
> cc 0 1 30
> cc 0 1 40
> cc 0 1 50
```

**Comment by yukulele** [comment]
@derselbst, for comparison, here is how the same instrument reacts with Polyphone:

https://github.com/user-attachments/assets/1f15fb7d-900f-46b8-804b-e1296a52d3bd
