### ISSUE TITLE
Patch for compiling fluidsynth (d519d9) with mingw32

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#132]
Consider this change so that mingw32/gcc4.6 will compile most recent fluidsynth version (d519d9):

--- fluid_sys-ORIG.c	2014-10-16 22:40:05 -0400
+++ fluid_sys.c	2014-10-16 22:47:14 -0400
@@ -1008,13 +1008,13 @@ fluid_server_socket_run (void *data)
       server_socket->cont = 0;
       return;
     } else {
-#ifdef IPV6
+/* #ifdef IPV6
       inet_ntop(AF_INET6, &addr.sin6_addr, straddr, sizeof(straddr));
 #else
       inet_ntop(AF_INET, &addr.sin_addr, straddr, sizeof(straddr));
-#endif
+#endif */
       retval = server_socket->func (server_socket->data, client_socket,
-                                    straddr);
+                                    inet_ntoa (addr.sin_addr));
 
       if (retval != 0)
 	fluid_socket_close(client_socket);
@@ -1165,13 +1165,13 @@ static void fluid_server_socket_run (voi
     }
     else
     {
-#ifdef IPV6
+/* #ifdef IPV6
       inet_ntop(AF_INET6, &addr.sin6_addr, straddr, sizeof(straddr));
 #else
       inet_ntop(AF_INET, &addr.sin_addr, straddr, sizeof(straddr));
-#endif
+#endif */
       r = server_socket->func (server_socket->data, client_socket,
-                               straddr);
+                               inet_ntoa (addr.sin_addr));
       if (r != 0)
 	fluid_socket_close (client_socket);
     }

Reported by: nobody

Original Ticket: [fluidsynth/tickets/134](https://sourceforge.net/p/fluidsynth/tickets/134)

**Comment by derselbst** [comment]
basic2004 wrote:
> And I want compile current development version with MinGW,
> but I failed with "the procedure entry point g_cond_broadcast could not be located in the dynamic link library libfluidsynth.dll" without IPV6 and disabled inet_ntop like this patch.
> https://sourceforge.net/p/fluidsynth/tickets/134/
> I saw a linker error about inet_ntop before patch.

@basic2004 There are three patches listed there, as I understand you applied the `fluid_sys.diff`? Could you please test it with the `check_inetntop.diff`? Also could you provide the full log of those two builds?

**Comment by basic2004** [comment]
Well done! I compiled 3 patches successfully.
Here is an archive of log files. [fluidsynth_logfile.zip](https://github.com/FluidSynth/fluidsynth/files/1120256/fluidsynth_logfile.zip)

And "the procedure entry point g_cond_broadcast could not be located in the dynamic link library libfluidsynth.dll" error was solved to overwrite correct dll files.
Here is compiled binary with DLLs. [fluidsynth-f0a83e1-check_inetntop-binary-mingw.zip](https://github.com/FluidSynth/fluidsynth/files/1120261/fluidsynth-f0a83e1-check_inetntop-binary-mingw.zip)

**Comment by derselbst** [comment]
Ok, sounds and looks good. I think we'll go with the `check_inetntop.diff` then. Thanks for testing!
