### ISSUE TITLE
Status byte that should not change the running status results in an error

### ISSUE THREAD

**Issue by tatsuki-makino** [FluidSynth/fluidsynth#1329]
### FluidSynth version
FluidSynth runtime version 2.3.4
Copyright (C) 2000-2023 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.4
Sample type=double

This version has been ported to FreeBSD.
### Describe the bug
SMF files containing system exclusive messages in the middle of messages dependent on running status cannot be played with an "Unrecognized MIDI event" error.

### Expected behavior
Even if a message such as system exclusive is received in the middle of a message that depends on the running status, it should not affect the running status.

### Steps to reproduce
Just play it on the command line.
fluidsynth -i -n -r 44100 default.sf2 some.mid
I don't know how to make an SMF file with a system exclusive sandwiched between messages that depend on running status, since I only listen :)

### Additional context
I think we should filter out status bytes that shouldn't be put in running status.
[patch.txt](https://github.com/user-attachments/files/15523337/patch.txt)
This patch allows normal playback, but I'm not sure if it's the right thing to do for all status bytes.

**Comment by pedrolcl** [comment]
> Even if a message such as system exclusive is received in the middle of a message that depends on the running status, it should not affect the running status.

This is against the [Standard MIDI Files specification](https://midi.org/standard-midi-files-specification), page 7:

>  Sysex events and meta-events cancel any running status which was in effect. Running status does not apply to and may not be used for these messages.

This bug report is invalid. Your MIDI files are broken.

**Comment by derselbst** [comment]
Thanks for digging in the MIDI spec Pedro! And I agree, we cannot change this, the spec is very clear about this behavior, sry. If needed, I'd be open to introduce a more precise error message in this case. PR welcome, I'll leave this ticket open for a while.

**Comment by pedrolcl** [comment]
Hi Tom! The error message "Unrecognized MIDI event" is fine for me. The same bug report was added to Drumstick today: https://github.com/pedrolcl/drumstick/issues/23

I must admit that my error messages are much worse!

**Comment by tatsuki-makino** [comment]
Hello, since the parties involved are here, I will consolidate the reply here.

> Standard MIDI Files specification, page 7:
The Japanese version of the standard that I own also contained a translation of that sentence :)

The Japanese version of the standard book is not divided into separate volumes, so I don't know which receiver standard book it will be.
However, it is written that the receiver should fully consider the running status when receiving channel messages.

The broken SMF files I have were treated as fine by some SMF players considering that they are corrupted.
However, the attached commands of Fluidsynth and drumstick require SMF files to be strict.
When playing an incorrect SMF file, it is recommended to use pre-processing software.

As an appendix, a hexadump near the damaged location is attached.
![hexdump.png](https://github.com/FluidSynth/fluidsynth/assets/59942452/ef870873-dfe9-4aff-a6f1-dbed8e7cd15e)
