### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Jotalea** [FluidSynth/fluidsynth#1343]
### FluidSynth version
FluidSynth runtime version 2.3.1
Copyright (C) 2000-2022 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.1
Sample type=double

### Describe the bug
Fluidsynth started filling my whole RAM and slowed down my computer by a lot.

### Expected behavior
No crispy audio. No slowed down computer.

### Steps to reproduce
Boot up computer. Audio sounds crispy, restart pipewire. Process by the name "fluidsynth" allocates all the available RAM.

### Additional context
Computer:
- OS: Debian 12.5 (Linux 6.1.0-21-amd64)
- DE: GNOME
- RAM: 4GB (+8GB swap)

**Comment by derselbst** [comment]
fluidsynth 2.3.1 is out of support. Pls. try again with 2.3.5. Also, try a different version of pipewire. Given your vague description, I cannot reproduce this.
