### ISSUE TITLE
MIDI File timing parsed incorrectly 

### ISSUE THREAD

**Issue by spessasus** [FluidSynth/fluidsynth#1351]
### FluidSynth version
_Execute `fluidsynth --version` and provide the output._
```cmd
fluidsynth --version
FluidSynth runtime version 2.3.5
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.5
Sample type=float
```

### Describe the bug
_Provide a clear and concise description of the current situation, e.g. how the bug manifests._
The provided [midi file](https://github.com/user-attachments/files/16180043/issue.zip) (soundfont doesn't matter) plays drums totally out of sync. Note that the stock channel 10 drums play fine, only GS drum parts are out of sync.

### Expected behavior
_Provide a clear and concise description of what you expected to happen._
The midi should play correctly. Two programs that play it fine are [SpessaSynth](https://spessasus.github.io/SpessaSynth) and [MidiPlayer6](https://falcosoft.hu/softwares.html).

### Steps to reproduce
_Please explain the steps required to duplicate the issue, esp. if you are able to provide a sample application. E.g. how to start fluidsynth, what shell commands to enter, what midi events to send, etc._
```
fluidsynth soundfont.sf2 -o synth.device-id=16 -o synth.gain=1 issue.mid
```
Is the command i used to play the file.

### Additional context
I have encountered a similar problem when developing my own midi player and the issue was related to running byte. I was caching the running byte for every message before, but it's only applicable to the voice messages (note on, off, cc change, etc.). After changing it to only cache voice messages, it fixed the issue. Maybe that will help.

**Comment by derselbst** [comment]
Sounds fine to me. What do you mean by "GS drum parts"? Which channel, which track, at which timestamp?

Note that this MIDI file also uses meta event 0x21, which I and fluidsynth have never heard of before.

**Comment by spessasus** [comment]
Hi, sorry for not responding earlier as I only saw the comment on #1352.

[Comparison of rendered audio. (the same soundfont) The SpessaSynth is how it should sound like. For example check second 34 on fluid.](https://github.com/user-attachments/files/16216672/comparison.zip)

The 0x21 is not relevant here, the channel 17 is acoustic bass that just gets changed into a piano due to #1352. The timing is fine.

The drum channels are (counting from 1): 10 (default MIDI drums, plays fine), 11, 12, 13, 14, 15. The tracknums for the channels are (counting from 0): 12, 13, 14, 15, 16. So yes, 5 drum channels. But I don't see drum channel limit in the code. Also I've noticed that fluidsynth uses Standard Drum Kit when it should use drum kit 17 (based on the sound).
 Let me know if i should provide the soundfont too.

**Comment by spessasus** [comment]
I've found another MIDI file that also seems to be broken (it also makes use of running bytes). [apple_running_byte.zip](https://github.com/user-attachments/files/16229234/apple_running_byte.zip)
It works in:
- Windows Media Player
- Falcosoft MIDI Player
- Signal MIDI Editor
- SpessaSynth

fluidsynth reports "error: Invalid length for EndOfTrack event", but when I checked with the Falcosoft's event explorer, the length was perfectly fine. This further indicates that the running status seems to be incorrectly parsed in fluidsynth.

**Comment by derselbst** [comment]
You're right. I've just committed a fix for this. apple_running_byte plays without issues and  also the original MIDI now play in sync. (I've missed the `synth.device-id=16` option previously...)

Looks like this bug existed since 039e880a9437fde543bb4d1da7f91c8bf2f3c175 - so thanks for the report!

**Comment by spessasus** [comment]
Hi derselbst,

While the timing is correct now, the `apple_running_byte` MIDI still sounds incorrect:
1. The RPN Coarse Tuning is not applied, some instruments are wrong
2. The bass & lead has turned into saw wave (00:15)
3. A lot of the Note off messages are not processed, which leads to a ton of voice killing and a warning
4. No pitch tuning for toms at the start.

I've built fluidsynth with debug and here's the output:
[Full log.txt](https://github.com/user-attachments/files/16325101/log.txt)

[Audio comparison. Note the incorrect pitch and notes that don't finish when they should. (I've also included the soundfont to reproduce)](https://github.com/user-attachments/files/16325150/comparison.zip)

The logs also show that something's wrong:
The below trimmed to logs that I think are important.
```
./fluidsynth ~/htdocs/SpessaSynth/soundfonts/soundfont.sf2 ~/Downloads/issue.mid -o synth.device-id=16 -F out.wav
fluidsynth: debug: SDL2 driver testing audio device: Renoir Radeon High Definition Audio Controller Digital Stereo (HDMI)
fluidsynth: debug: SDL2 driver testing audio device: Family 17h/19h HD Audio Controller Analog Stereo
FluidSynth runtime version 2.3.5
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

fluidsynth: warning: Preset 'Tremolo Strings': Some invalid generators were discarded
Rendering audio to file 'out.wav'..
fluidsynth: debug: /home/spessasus/Desktop/clutter/Fluidsynth/src/midi/fluid_midi.c: 1985: Loading midifile /home/spessasus/Downloads/issue.mid
fluidsynth: debug: File load: Allocating 396926 bytes
fluidsynth: debug: Division=480
fluidsynth: debug: tempo=500000, tick time=1.041667 msec, cur time=0 msec, cur tick=0
fluidsynth: debug: signature=4/4, metronome=24, 32nd-notes=8
fluidsynth: Ignoring unrecognized meta event type 0x21
fluidsynth: debug: /home/spessasus/Desktop/clutter/Fluidsynth/src/midi/fluid_midi.c: 691: alloc metadata, len = 10
(this line repeats with different len)

fluidsynth: debug: Killing voice 1218, index 218, chan 7, key 39 
fluidsynth: debug: Polyphony exceeded, trying to kill a voice
(A LOT more of these...)

fluidsynth: debug: Voice is on! channel 3, key 27
(a lot of these too...)

fluidsynth: debug: Voice is on! channel 6, key 77
fluidsynth: warning: End of the MIDI file reached, but not all notes have received a note off event! OFFing them now! Run with --verbose to spot pending voices.
fluidsynth: debug: /home/spessasus/Desktop/clutter/Fluidsynth/src/midi/fluid_midi.c: 2266: Duration=228.262 sec
```

**Comment by derselbst** [comment]
Oh yeah, of course. My previous fix was inaccurate. I've corrected it, and now sounds better to me. Feel free to test the release/2.3 branch again.

**Comment by spessasus** [comment]
There we go, it works now. Good job!
Closing this.

**Comment by PolyMeilex** [comment]
Hi @derselbst I'm working on the same issue in my project, and I'm wondering how did you come to the conclusion that SYSEX and Meta don't cancel the running status:
https://github.com/FluidSynth/fluidsynth/blob/94d195a564a08e89c396656b116734ea115476ae/src/midi/fluid_midi.c#L956

As far as I can tell by reading the spec, implementations and random websites on the topic, the SYSEX should cancel the running status. Am I missing something, or was this fixed just to appease this one potentially broken file?

**Comment by derselbst** [comment]
The Midi specs wording is vague in this case. It could be interpreted that
any Running Status would be reset by a sysex Event. When i tried that a
bunch of midi files broke. Hence i figured that cancel actually means
interrupting Running Status. And thats how it is implemented now.
