### ISSUE TITLE
Random SEGFAULT on delete_fluid_player

### ISSUE THREAD

**Issue by be1** [FluidSynth/fluidsynth#1354]
### FluidSynth version
_Execute `fluidsynth --version` and provide the output._
fluidsynth: debug: SDL2 driver testing audio device: Family 17h/19h HD Audio Controller Speaker + Headphones
FluidSynth runtime version 2.3.5
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.5
Sample type=double

Bug also happen on previous versions of libfluidsynth.

### Describe the bug
_Provide a clear and concise description of the current situation, e.g. how the bug manifests._
libfluidsynth crashes randomly on `new_fluid_player` followed by `delete_fluid_player`;
### Expected behavior
_Provide a clear and concise description of what you expected to happen._
Looping over `new_fluid_player(fluid_synth);` `delete_fluid_player(fluid_player);` should never segfault.

### Steps to reproduce
_Please explain the steps required to duplicate the issue, esp. if you are able to provide a sample application. E.g. how to start fluidsynth, what shell commands to enter, what midi events to send, etc._
I think the following snippet is self-explanatory:
```
int main () {
    fluid_settings_t* fluid_settings;
    fluid_synth_t* fluid_synth;
    fluid_audio_driver_t* fluid_adriver;
    fluid_player_t* fluid_player;

    fluid_settings = new_fluid_settings();
    fluid_settings_setstr(fluid_settings, "audio.driver", "alsa"); // fails with pulseaudio too

    fluid_synth = new_fluid_synth(fluid_settings);
    fluid_synth_set_gain(fluid_synth, 1.);

    fluid_adriver = new_fluid_audio_driver(fluid_settings, fluid_synth);


    while (1) {
        fluid_player = new_fluid_player(fluid_synth);
        delete_fluid_player(fluid_player);
    }
}
```
I get :
malloc(): unsorted double linked list corrupted
Erreur de segmentation (core dumped)

I could not get a readable backtrace for now, sorry.

This happen also after reading a small amount of MIDI file with a preloaded soundfont and interrupted with `fluid_player_stop();` followed by `fluid_player_join();`

### Additional context
_If you are able to illustrate the bug with an example, please provide simple
source code below or as attached file. List any other information that is relevant to your issue, e.g. stack traces, related issues, build logs, suggestions on how to fix, links to related discussions at fluid-dev, etc._

This is the smallest snippet I could find to reproduce those random crash.

My real application, https://github.com/be1/redrose is crashing randomly on `delete_fluid_player`
see also: https://github.com/be1/redrose/blob/main/app/abcsynth.cpp
```
insert code snippets, soundfonts or anything relevant here, or attach it as extra file(s) if it's too much
```

**Comment by derselbst** [comment]
This is expected. Please read the documentation of `delete_fluid_player()`, there is a big red warning there: https://www.fluidsynth.org/api/group__midi__player.html#ga9e655b26be62b17c59319a287ef382f3

**Comment by derselbst** [comment]
I also recommend reading https://www.fluidsynth.org/api/MIDIPlayer.html to learn about the correct order of object creation.

**Comment by be1** [comment]
This is now clear :) thank you for your explanation.
So, for jack or pipewire audio driver, there is no easy way to retain connections between libfluidsynth and other apps across replays. Now I know it.
