### ISSUE TITLE
FluidSynth ignores LSB in Pitch Bend Range

### ISSUE THREAD

**Issue by spessasus** [FluidSynth/fluidsynth#1357]
### FluidSynth version
_Execute `fluidsynth --version` and provide the output._

```
FluidSynth runtime version 2.3.5
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.5
Sample type=double
```

### Describe the bug
_Provide a clear and concise description of the current situation, e.g. how the bug manifests._

Fluidsynth only allows to specify the pitch bend range in semitones, ignoring the cent tuning via data entry.
[Test MIDI file](https://github.com/user-attachments/files/16366815/test-rpn-00-00-pitch-bend-range.zip) The second note in this file doesn't change its pitch as the bend range is set to 50 cents.

### Expected behavior
_Provide a clear and concise description of what you expected to happen._

The second note should have a noticeable pitch change when the range is set to 50 cents.

### Steps to reproduce
_Please explain the steps required to duplicate the issue, esp. if you are able to provide a sample application. E.g. how to start fluidsynth, what shell commands to enter, what midi events to send, etc._

1. Get the file
2. `fluidsynth microsoft_gm.sf2 test-rpn-00-00-pitch-bend-range.mid `
3. No audible pitch change on the second note

### Additional context
Soundfont spec doesn't say anything about the way pitch bend range should be stored so simply doing
```c
float pitchBendRange = semitones + (cents / 100);
```
should easily fix the problem without further modifications.

**Comment by derselbst** [comment]
You're welcome to file a PR: https://github.com/FluidSynth/fluidsynth/blob/ad24c8bebb62edae507d563684255aef47464377/src/synth/fluid_synth.c#L1848

**Comment by spessasus** [comment]
Alright, I created a pull request, I hope it looks good!
