### ISSUE TITLE
MIDI Format 2 files do not play sequentially

### ISSUE THREAD

**Issue by spessasus** [FluidSynth/fluidsynth#1366]
### FluidSynth version
_Execute `fluidsynth --version` and provide the output._
```
$ fluidsynth --version
ALSA lib pcm_dsnoop.c:567:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2722:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2722:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2722:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_oss.c:404:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:404:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_a52.c:1036:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:481:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:481:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
FluidSynth runtime version 2.3.6
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.6
Sample type=double
```

### Describe the bug
_Provide a clear and concise description of the current situation, e.g. how the bug manifests._
[test-2-tracks-type-2.zip](https://github.com/user-attachments/files/16553196/test-2-tracks-type-2.zip)

The provided MIDI file plays notes simultaneously when it shouldn't.

### Expected behavior
_Provide a clear and concise description of what you expected to happen._
This MIDI file should play sequentially (like indicated in the text events)

### Steps to reproduce
_Please explain the steps required to duplicate the issue, esp. if you are able to provide a sample application. E.g. how to start fluidsynth, what shell commands to enter, what midi events to send, etc._
```
fluidsynth test-2-tracks-type-2.mid
```
Hear the 2 scales simultaneously

### Additional context

- TiMidity++ works fine
- Falcosoft MidiPlayer works fine
- spessasynth works fine

**Comment by derselbst** [comment]
I looked through the code. Format 2 is currently not supported, and the code doesn't check for it.

**Comment by hikari-no-yume** [comment]
Standard MIDI File format 2 is a pretty obscure feature that I don't think is commonly used. In a format 2 file, I believe that the different tracks are intended as different "arrangements" of a piece, rather than being intended to play simultaneously (like in format 1). It's not obvious to me what the correct way to play those back is for a MIDI player: playing them back sequentially makes sense, but letting the user pick which to play also makes sense.

Simply choosing not to support format 2 would be a reasonable option.

**Comment by derselbst** [comment]
Ok, thanks for the feedback. I have implemented a check.
