### ISSUE TITLE
library 'glib-2.0' not found

### ISSUE THREAD

**Issue by zaun** [FluidSynth/fluidsynth#1368]
### FluidSynth version
2.3.6

### Describe the bug
using cmake, when linking my app getting complaints about glib-2.0.
`ld: library 'glib-2.0' not found`

### Expected behavior
Configure should have realized I don't have glib-2.0 and not tried to use it.

### Steps to reproduce
try to build an app on MacOS without glib.

**Comment by derselbst** [comment]
I hardly understand what you're trying to do. Without any logs or any further details it's impossible to help.

**Comment by pedrolcl** [comment]
> Expected behavior:  Configure should have realized I don't have glib-2.0 and not tried to use it.

The glib dependency is mandatory in FluidSynth. You cannot build FluidSynth without it, neither in MacOS or elsewhere.

There are [forks](https://github.com/chirs241097/fluidsynth-sans-glib) of FluidSynth trying to remove this dependency, but have not been merged yet into this official repository.

**Comment by ebraminio** [comment]
Just am putting useful links here:
* https://github.com/FluidSynth/fluidsynth/discussions/847
* https://github.com/Ghabry/fluidsynth/tree/no-glib
