### ISSUE TITLE
fluidsynth[1761]: Failed to create secure directory

### ISSUE THREAD

**Issue by Fluke667** [FluidSynth/fluidsynth#1369]
`
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
fluidsynth[1761]: Failed to create secure directory (/run/user/0/pulse): Read-only file system
`

Running fluidsynth on Linux Debian 12

My chmod is set correct for user 0 and for user 1000 and subfolders

ls -l /run/user
drwxr-xr-x  7 root     root     220 16. Aug 00:53 0
drwxr-xr-x 18 fluke667 fluke667 620 16. Aug 10:32 1000

echo $XDG_RUNTIME_DIR
/run/user/1000

This happens since some days, fluidsynth is installed from the repo

fluisynth version 2.3.1
fluisynth runtime version 2.3.1

ps aux|grep fluidsynth
root        1836  1.0  0.5 1517584 179048 ?      SLsl 11:05   0:00 /usr/bin/fluidsynth -is /usr/share/sounds/sf3/default-GM.sf3

Thats the Command used and the Audio driver i think.
Its not in the systemd services list.
Its installed by Lutris for Gaming i think

**Comment by Fluke667** [comment]
its spaming my syslog

**Comment by derselbst** [comment]
Would you _please_ provide a few more information on how you're running fluidsynth?

**Comment by Fluke667** [comment]
Updated first comment

**Comment by derselbst** [comment]
This is not helpful. What version of fluidsynth? What's the commandline you're using? Which audio driver? Is it running as systemd service?

**Comment by Fluke667** [comment]
Updated first

**Comment by derselbst** [comment]
> Thats the Command used and the Audio driver i think.

So are you even executing fluidsynth yourself?

> Its not in the systemd services list.

Are you sure? What about: 

`sudo systemctl status fluidsynth`

`systemctl --user status fluidsynth`

**Comment by Fluke667** [comment]
Im not Executing it myself

sudo systemctl status fluidsynth
Unit fluidsynth.service could not be found.


systemctl --user status fluidsynth
○ fluidsynth.service - FluidSynth Daemon
     Loaded: loaded (/usr/lib/systemd/user/fluidsynth.service; enabled; preset: enabled)
     Active: inactive (dead) since Fri 2024-08-16 11:51:55 CEST; 11min ago
       Docs: man:fluidsynth(1)
   Main PID: 2463 (code=exited, status=255/EXCEPTION)
        CPU: 271ms

Aug 16 11:51:55 fluidsynth[2463]: fluidsynth: error: Failed to open the "default" audio device
Aug 16 11:51:55 fluidsynth[2463]: Failed to create the audio driver. Giving up.
Aug 16 11:51:55 fluidsynth[2463]: fluidsynth: warning: Failed to set thread to high priority
Aug 16 11:51:55 fluidsynth[2463]: FluidSynth runtime version 2.3.1
Aug 16 11:51:55 fluidsynth[2463]: Copyright (C) 2000-2022 Peter Hanappe and others.
Aug 16 11:51:55 fluidsynth[2463]: Distributed under the LGPL license.
Aug 16 11:51:55 fluidsynth[2463]: SoundFont(R) is a registered trademark of Creative Technology Ltd.
Aug 16 11:51:55 systemd[2444]: fluidsynth.service: Main process exited, code=exited, status=255/EXCEPTION
Aug 16 11:51:55 systemd[2444]: fluidsynth.service: Failed with result 'exit-code'.
Aug 16 11:51:55 systemd[2444]: Failed to start fluidsynth.service - FluidSynth Daemon.

**Comment by derselbst** [comment]
These error you see do not originate from fluidsynth. They most likely originate from pulseaudio, because fluidsynth tries to uses that as audio driver. The fact, that pulseaudio complains about a read-only filesystem can be explained when fluidsynth runs as systemd daemon. Since 2.3.1 fluidsynth's daemon uses hardening options:

https://github.com/FluidSynth/fluidsynth/blob/2e60f94a2d27acf39768011dda64a8762a05f9ee/fluidsynth.service.in#L10-L16

The assumption that fluidsynth is running as systemd daemon in your case is supported by the fact, that the commandline you see contains the flags `-is`, which is the default commandline for the daemon.

Since fluidsynth is not writing these log files I don't see anything that can be done on our side. If you google the errors you'll find ways to mitigate this within pulseaudio. You may ask the pulseaudio guys. You may disable or delete the fluidsynth user daemon. Or you may uninstall fluidsynth.

Therefore I'm closing this.
