### ISSUE TITLE
Adding FluidSynth as dependency to Qt Project with CMake failing

### ISSUE THREAD

**Issue by BrickSigma** [FluidSynth/fluidsynth#1375]
### FluidSynth version
```
FluidSynth runtime version 2.3.6
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.6
Sample type=float
```

### Describe the bug
I am trying to add fluidsynth as a library dependency for my Qt project using CMake, but when Qt Creator attempts to configure the cmake project it fails, saying that GLib2 could not be found.

My main goal is to utilize it's API for recording MIDI input and rendering it into a wav file with a Qt frontend.

Some more details:

- OS: Windows 11
- Qt Creator version 14.0.1
- Compiling with MinGW (provided by the Qt online installer, as well as CMake)
- I have followed the instructions on the wiki for adding in the glib dependencies as described [here](https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake#building-with-mingw-on-windows)

### Expected behavior
Upon saving the CMakeLists.txt file in Qt creator it should successfully configure the cmake project with no errors

### Steps to reproduce
1. Create a new Qt Widgets project with CMake as the build system
2. Add the fluidsynth source code folder to the root of the Qt project folder (downloaded from the releases page on github and renamed to `fluidsynth`)
3.  Add the following lines to the CMakeLists.txt file:
```
target_include_directories(Fluidsynth-test PRIVATE ./fluidsynth/include)
add_subdirectory(./fluidsynth)

target_link_libraries(Fluidsynth-test PRIVATE Qt${QT_VERSION_MAJOR}::Widgets Fluidsynth)
```
4. Save the file and let cmake configure the project

### Additional context
Here is part of the output from CMake in Qt Creator's general messages section when saving the CMakeLists.txt file:

```
[cmake] -- Found GLIB2: C:/freesw/lib/libglib-2.0.dll.a
[cmake] -- Could NOT find InstPatch (missing: InstPatch_LIBRARY InstPatch_INCLUDE_DIR) (Required is at least version "1.1.0")
[cmake] -- Could NOT find SDL2 (Set SDL2_DIR to the directory containing its CMake config)
[cmake] -- Could NOT find Readline (missing: Readline_LIBRARY Readline_INCLUDE_DIR)

...

[cmake] CMake Error at fluidsynth/src/CMakeLists.txt:365 (target_link_libraries):
[cmake]   Target "libfluidsynth-OBJ" links to:
[cmake] 
[cmake]     GLib2::glib-2
[cmake] 
[cmake]   but the target was not found.  Possible reasons include:
[cmake] 
[cmake]     * There is a typo in the target name.
[cmake]     * A find_package call is missing for an IMPORTED target.
[cmake]     * An ALIAS target is missing.
```

**Comment by BrickSigma** [comment]
So after a few hours I've settled on using MSYS2 and MinGW packages for FluidSynth to avoid building from source completely, but I'm still interested in knowing how to resolve these errors.

**Comment by derselbst** [comment]
You should either discover fluidsynth via pkg-config:

```cmake
find_package(PkgConfig QUIET)
PKG_CHECK_MODULES(FLUIDSYNTH fluidsynth>=2.2.0 IMPORTED_TARGET)
 
if(FLUIDSYNTH_FOUND)
     target_link_libraries(Fluidsynth-test PRIVATE PkgConfig::FLUIDSYNTH)
endif()
```

Or via CMake's logic:

```cmake
list(APPEND CMAKE_MODULE_PATH "/path-to-unzipped-win-binaries/lib/cmake/fluidsynth/")
find_package(FluidSynth)
target_link_libraries(Fluidsynth-test PRIVATE FluidSynth::libfluidsynth)
```


You have chosen to find fluidsynth and all of its dependencies manually, which makes you run into errors like you're observing. In this case, you would also need to fix them manually.

**Comment by BrickSigma** [comment]
Thanks for the reply, the second option worked for me and I'm now able to use it in my project, for some reason though using MSVC to compile the Qt project results in some include error's such as `uintptr_t` being undeclared from vcruntime.h, so I'm using MinGW instead to compile it.

**Comment by pedrolcl** [comment]
> 2\. Add the fluidsynth source code folder to the root of the Qt project folder (downloaded from the releases page on github and renamed to `fluidsynth`)

This is the source of all your troubles. 

It would be equivalent to using Fluidsynth as a git submodule. In both cases, you would need to add in your `CMakeLists.txt` something like this:

    add_subdirectory(fluidsynth)

> I have followed the instructions on the wiki for adding in the glib dependencies as described [here](https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake#building-with-mingw-on-windows)

This wiki page is very old, has been edited by many hands, and it is utterly obsolete now. ftp.gnome.org pre-built versions of glib for Windows are 15 years old. Please, avoid them. And the wiki page in particular doesn't cover the scenario of using fluidsynth as a submodule or subdirectory.

> I've settled on using MSYS2 and MinGW packages for FluidSynth

Wise decision. But be aware of some pitfalls of MSYS2/MinGW: https://github.com/pedrolcl/sonivox/discussions/19

```
list(APPEND CMAKE_MODULE_PATH "/path-to-unzipped-win-binaries/lib/cmake/fluidsynth/")
find_package(FluidSynth)
target_link_libraries(Fluidsynth-test PRIVATE FluidSynth::libfluidsynth)
```

I prefer to use [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html) for external dependencies of my projects, assigned from outside the `CMakeLists.txt` script. Here is how I build Drumstick in QtCreator:

![image](https://github.com/user-attachments/assets/86df5c85-ef25-4997-84e6-f5e4db0fbc5c)

**Comment by BrickSigma** [comment]
Thanks for the input. When using MSYS/MinGW and trying to link with fluidsynth statically I would get undefined reference errors to `__imp__*` functions, and I have seen the fluidsynth has an archive .a file so I'm unsure how to statically link it...

One more problem I'm facing (probably not related to FluidSynth) is trying to bundle all the DLL's together and the exe into an installer using Inno Setup, and Qt seems to rely on libgcc_s_seh while FluidSynth uses libgcc_s_sjlj and when both of them are used the app won't start, is there any way to make FluidSynth use the "seh" version?

**Comment by pedrolcl** [comment]
> Thanks for the input. When using MSYS/MinGW and trying to link with fluidsynth statically I would get undefined reference errors to `__imp__*` functions, and I have seen the fluidsynth has an archive .a file so I'm unsure how to statically link it...

You should use the MSYS2 Fluidsynth packages. The repository is fully up to date, and includes the static and dynamic libraries:

https://packages.msys2.org/package/mingw-w64-x86_64-fluidsynth?repo=mingw64

Once installed, you will find two different `.a` library files in `/mingw64`:

```
/mingw64/lib/libfluidsynth.a
/mingw64/lib/libfluidsynth.dll.a
```

The first one `libfluidsynth.a` is the static library, and the second `libfluidsynth.dll.a` is the import library for linking the dynamic DLL. Unfortunately, Fluidsynth build system allows only one of them at once, so MinGW provides only the dynamic linking exported target, and you will need to write the CMake commands yourself for the static linking. Yes, I find this issue annoying myself.

> One more problem I'm facing (probably not related to FluidSynth) is trying to bundle all the DLL's together and the exe into an installer using Inno Setup, and Qt seems to rely on libgcc_s_seh while FluidSynth uses libgcc_s_sjlj and when both of them are used the app won't start, is there any way to make FluidSynth use the "seh" version?

The pre-built FluidSynth .ZIP files distributed in the Release area, here at GitHub, are built with the SJLJ exception model. This cannot be changed once compiled; you would need to rebuild FluidSynth from its sources. The libraries compiled with SJLJ are not compatible with the Qt pre-built official releases, which are built with the SEH exception model. The MinGW package is built with the SEH exception model, so it is fully compatible with the Qt official libraries.

About the other part of the question, here is a bash script that I use in the MinGW shell for bundling the DLLs with a program. Use it as:

```
$ cd yourbuilddir
$ ~/copydlls.sh yourprogram.exe
```

Here is the script, which I call `copydlls.sh`:

```
#!/usr/bin/bash

BINDIR=$(dirname $1)

paths=( "/mingw64/bin"
		"/usr/local/bin"
		"/usr/bin"
		"/bin"
		${BINDIR} )

function findAndCopyDLL() {
    for i in "${paths[@]}"
    do
        FILE="$i/$1"
        if [[ -f $FILE ]]; then
			#if [[ ! -f $BINDIR/$1 ]]; then
				cp -n $FILE $BINDIR
			#fi
            echo "Found $1 in $i"
            copyForOBJ $FILE
            return 0
        fi
    done
    return 1
}

function copyForOBJ() {
    dlls=`objdump -p $1 | grep 'DLL Name:' | sed -e "s/\t*DLL Name: //g"`
    while read -r filename; do
        findAndCopyDLL $filename || echo "Unable to find $filename"
    done <<< "$dlls"
}

copyForOBJ $1

```

**Comment by BrickSigma** [comment]
Wow, thanks! I'll try out the bash script and also see how to statically link FluidSynth. I think I can mark this as closed for now, once again thank you for the support.
