### ISSUE TITLE
SF3 decoder produces crackling sound for loud samples

### ISSUE THREAD

**Issue by spessasus** [FluidSynth/fluidsynth#1380]
### FluidSynth version
_Execute `fluidsynth --version` and provide the output._
It is seen in the video: 2.3.6

Full command:
```
FluidSynth runtime version 2.3.6
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.6
Sample type=double
```

### Describe the bug
_Provide a clear and concise description of the current situation, e.g. how the bug manifests._

https://github.com/user-attachments/assets/411938c1-a55f-43e7-a0ef-64a6726bf4ab

1. playing the "Orchestra Hit" patch with fluidsynth via the Virtual MIDI Piano Keyboard. You can hear the crackling
2. Playing the patch via Polyphone. You don't hear the crackling
3. Playing the patch via SpessaSynth. You don't hear the crackling

### Expected behavior
_Provide a clear and concise description of what you expected to happen._
No crackling like Polyphone or spessasynth. If that matters, polyphone uses 7th order (I believe) while spessa uses linear.

#### Soundfont
[GeneralUserGS.zip](https://github.com/user-attachments/files/16998495/GeneralUserGS.zip)

It is just GUGS sf2 converted to sf3 via musescore/sftools.

_Please explain the steps required to duplicate the issue, esp. if you are able to provide a sample application. E.g. how to start fluidsynth, what shell commands to enter, what midi events to send, etc._
1. fluidsynth GeneralUserGS.sf3 -o synth.gain=0.5 -o audio.driver=pulseaudio`
2. Switch to the patch 56 "Orchestra Hit"
3. Play some notes like in the video
4. Hear the crackling sound

### NOTE: This is not a driver issue. Running the same command with the sf2 version works fine!

PS: About the driver errors: I always had those and ignored them as it seems to work fine with `audio.driver=pulseaudio` instead of the default pipewire. I don't think they are related.

**Comment by derselbst** [comment]
I successfully reproduced this with any audio driver. The sample is quite loud and the audio is clipping. It took me a while to realize that this is the same bug that I have reported to libsndfile more than 7 years ago: libsndfile/libsndfile#194

A simple additional - but improperly documented - preprocessing step is needed, see my commit above.

Thanks for the report!
