### ISSUE TITLE
Support SF2.04 absolute value modulators

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#1391]
### Related discussion
--

### Is your feature request related to a problem?
Fluidsynth doesn't support absolute value modulator transforms. In fact, it actively disables them during loading:
https://github.com/FluidSynth/fluidsynth/blob/ce97c6d43715d550d6a3f1cc8d952f68b57e3e68/src/sfloader/fluid_defsfont.c#L1651-L1658

### Describe the solution you'd like
SF2.04 8.3:
> The output value of the multiplier is to be the absolute value of the input value, as
defined by the relationship:

### Describe alternatives you've considered
--

### Additional context
--

Please upvote this issue if you're lacking this functionality.

**Comment by spessasus** [comment]
Hi,

I'm sorry if I misunderstood something, but reading the SF spec isn't this just Math.abs of the value?
> The output value of the multiplier is to be the absolute value of the input value, as
defined by the relationship:
> output = square root ((input value)^2)

Square root of squared value is just abs of that value.

So making:
```c
/* it's as simple as that: */
return (fluid_real_t) mod->amount * v1 * v2;
```
this:
```c
if(mod-> trans == 2) return fabs((fluid_real_t) mod->amount * v1 * v2);
return (fluid_real_t) mod->amount * v1 * v2;
```
would implement it? Or am I reading the SFspec incorrectly?

**Comment by derselbst** [comment]
> Square root of squared value is just abs of that value.

Yes, that's also my understanding. I'm just wondering what would be the purpose / use-case behind this.

**Comment by derselbst** [comment]
Implementing this would require to introduce a new field in the fluid_mod struct, which should also be modifiable via the API. Such an API change to the modulator API should be considered together with feature #1355.

**Comment by spessasus** [comment]
Here's a test soundfont:
[absolute value test.zip](https://github.com/user-attachments/files/17422590/absolute.value.test.zip)

NOTE: Rename .zip to .sf2, zip is so github will accept this

**Comment by spessasus** [comment]
It works exactly like the I described above (tested on polyphone and spessasynth)
