### ISSUE TITLE
Fluidsynth's pan modulator amount is not correct

### ISSUE THREAD

**Issue by spessasus** [FluidSynth/fluidsynth#1395]
### FluidSynth version
_Execute `fluidsynth --version` and provide the output._
2.3.6

### Describe the bug
_Provide a clear and concise description of the current situation, e.g. how the bug manifests._
`Sfspec24.pdf` section 8.4.6:
> 8.4.6 MIDI Continuous Controller 10 to Pan Position
Source Enumeration = 0x028A (type=0, P=1, D=0, CC=1, index = 10)
Destination Enumeration = Initial Attenuation
Amount = 1000 tenths of a percent
Amount Source Enumeration = 0x0 (No controller)
Transform Enumeration = 0 (Linear)

Yet
https://github.com/FluidSynth/fluidsynth/blob/66adce6ad9772dd7285370d3f78b6824b907c0e8/src/synth/fluid_synth.c#L396-L409

Spec says 1000, so why is it set to 500? 

Amount of 1000 does not mean that the full range of the modulator is 1000, with 0 being -500, 64=0 and 127=500. 
The range is twice that because of bipolar transform: 0=-1000 64=0 127=1000, like with the pitch modulator.

With the current behavior, you can clearly notice this:
- [stereo_square.zip](https://github.com/user-attachments/files/17267418/stereo_square.zip)
- In polyphone, panning both stereo and mono squares hard left results in right channel being silent.
- In fluidsynth, that's not the case. `Stereo Square` sounds like it's a bit on the left but not fully. `Mono Square` fully goes to the left.

This is because, amount of 1000 always forces the sample to be on the desired channel. That is:
- hard left for the right sample is: `500 + (-1000) = -500` which is left.
- hard right for the left sample is `-500 + 1000 = 500` which is right.

Where with amount being 500 like fluid sets:
- hard left for the right sample is: `500 + (-500) = 0` which is the middle. That is not what we want.
- hard right for the left sample is `-500 + 500 = 0` which is the middle. That is not what we want.

I think this is why creative chose 1000 and not 500.

### Expected behavior
_Provide a clear and concise description of what you expected to happen._
It should be 1000 and both of the attached soundfont's presets should pan in the same way.

### Steps to reproduce
_Please explain the steps required to duplicate the issue, esp. if you are able to provide a sample application. E.g. how to start fluidsynth, what shell commands to enter, what midi events to send, etc._
1. boot up fluid
2. run it with the attached soundfont
3. select stereo square
4. set CC10 to 0 or 127
5. play a few notes
6. repeat 3-5 with mono square
7. hear the difference

### Additional context
_If you are able to illustrate the bug with an example, please provide simple
source code below or as attached file. List any other information that is relevant to your issue, e.g. stack traces, related issues, build logs, suggestions on how to fix, links to related discussions at fluid-dev, etc._
None

**Comment by derselbst** [comment]
@mawe42 I think this is the problem you observed 6 years ago which led to the creation of the custom balance modulator: https://lists.nongnu.org/archive/html/fluid-dev/2018-01/msg00006.html

Opinions?

**Comment by mawe42** [comment]
> @mawe42 I think this is the problem you observed 6 years ago which led to the creation of the custom balance modulator: https://lists.nongnu.org/archive/html/fluid-dev/2018-01/msg00006.html
> 
> Opinions?

Hm... interesting. I will have time to look at this in more detail over the weekend.

**Comment by spessasus** [comment]
Nevermind, the pan amount is correct. That is, using 1000 leads to the pan being too extreme (i received a bug report on my synth which did use 1000 as the amount). Closing this!
