### ISSUE TITLE
Support of vorbis-compressed sf3 sound fonts 

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#140]
Musescore 2.0 introduced a new soundfont format sf3
See: https://musescore.org/en/node/20818

I took the liberty to post this request from Fabian Greffrath <fabian@greffrath.com> from
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=740710 into the ticket system of fluidsynth.

Musescore is widely used and created this new format as part of their version 2.0 delivery.
Would be great if this feature would be officially distributed by fluidsynth.

Reinhold

Reported by: z34rgfj35

Original Ticket: [fluidsynth/tickets/142](https://sourceforge.net/p/fluidsynth/tickets/142)

**Comment by fabiangreffrath** [comment]
See:
https://github.com/fabiangreffrath/fluidsynth-code-git/commit/6a9e05ee3e486ac1c91fda3d0df535422934a578

**Comment by derselbst** [comment]
@fabiangreffrath Looks good. Feel free to create a pull request so this can be discussed. However, I currently dont think that this will make it into the upcoming 1.1.7 maintenance release.
