### ISSUE TITLE
When the macro GETOPT_SUPPORT is disabled, the built binary cannot interpret the output file name "-" as a pipe.

### ISSUE THREAD

**Issue by stardusteyes** [FluidSynth/fluidsynth#1403]
### FluidSynth version
fluidsynth -version
FluidSynth runtime version 2.3.6
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

### Describe the bug
On the command line, an output filename "-" following "-F" is misinterpreted as the start of another option.
In this case, an error will occur indicating an incorrect option specification.

This problem occurs when building with the macro GETOPT_SUPPORT disabled.
For example, when building Fluidsynth binaries for Windows with Microsoft Visual Studio.

### Expected behavior
The command line option "-F -" is expected to be interpreted as outputting audio to a pipe.
The release binaries distributed on fluidsynth's github work as expected and do not have this issue.

### Steps to reproduce
```
>fluidsynth.exe -F -
Expected argument to option -F found switch instead
Usage: fluidsynth [options] [soundfonts]
Try -h for help.
```

### Additional context
This issue can be fixed by updating the code in fluidsynth.c as follows:
https://github.com/FluidSynth/fluidsynth/blob/66adce6ad9772dd7285370d3f78b6824b907c0e8/src/fluidsynth.c#L511

```diff
- if(optarg[0] == '-') 
+ if ((optarg[0] == '-') && ((optarg[1] != '\0') || (c != 'F')))
```

**Comment by derselbst** [comment]
Thanks! Will be implemented as suggested.
