### ISSUE TITLE
ChangeLog: remove, or update URLs

### ISSUE THREAD

**Issue by 0-wiz-0** [FluidSynth/fluidsynth#1413]
It's a minor thing, but when updating packages for pkgsrc, I look at NEWS and ChangeLog files. The one coming with fluidsynth is heavily outdated (and says so at the top) and not updated any longer. It also mentions two URLs to look at for changes, but those are at Sourceforge. I think it's time for removing this file, or at least updating the URLs to github. Thanks!

**Comment by derselbst** [comment]
Done, thanks!
