### ISSUE TITLE
iOS framework

### ISSUE THREAD

**Issue by Irving-Xu** [FluidSynth/fluidsynth#1436]
Can FluidSynth be compiled into a library for iOS? Does the official site provide a precompiled library for iOS?

**Comment by derselbst** [comment]
> Can FluidSynth be compiled into a library for iOS?

Sure.

> Can FluidSynth be compiled into a library for iOS? Does the official site provide a precompiled library for iOS?

No, since nobody has made a contribution yet. You're welcome to do so. But this is not the right place to discuss about that. You might have more luck when you contact our [mailing list](https://lists.nongnu.org/mailman/listinfo/fluid-dev).

**Comment by Irving-Xu** [comment]
I have subscribed to the mailing list and sent a help request to fluid-dev-owner@nongnu.org, but I haven’t found any information about iOS-related compilation issues or precompiled libraries.
Please help!

My email is xhj634850447@gmail.com.

**Comment by derselbst** [comment]
> I have subscribed to the mailing list and sent a help request to [fluid-dev-owner@nongnu.org](mailto:fluid-dev-owner@nongnu.org)

The instructions clearly say: "To post a message to all the list members, send email to [fluid-dev@nongnu.org](mailto:fluid-dev@nongnu.org)."
