### ISSUE TITLE
Cloning the repo causes errors

### ISSUE THREAD

**Issue by spessasus** [FluidSynth/fluidsynth#1440]
### FluidSynth version
Not related

### Describe the bug
It seems that adding the filter test files broke git clone:
```zsh
git clone "https://github.com/fluidsynth/fluidsynth"
Cloning into 'fluidsynth'...
remote: Enumerating objects: 21711, done.
remote: Counting objects: 100% (1245/1245), done.
remote: Compressing objects: 100% (598/598), done.
remote: Total 21711 (delta 818), reused 1009 (delta 641), pack-reused 20466 (from 1)
Receiving objects: 100% (21711/21711), 10.58 MiB | 9.15 MiB/s, done.
Resolving deltas: 100% (16294/16294), done.
Downloading test/manual/awe32_nrpn/Altitude/Altitude-SB Audigy2 ZS.ogg (7.4 MB)
Error downloading object: test/manual/awe32_nrpn/Altitude/Altitude-SB Audigy2 ZS.ogg (9c4ded7): Smudge error: Error downloading test/manual/awe32_nrpn/Altitude/Altitude-SB Audigy2 ZS.ogg (9c4ded7fc02982d2239a830ad08b41ddeea6f5d6a081568cd073290695e322ce): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to '/home/spessasus/Desktop/clutter/fluidsynth/.git/lfs/logs/20241125T151415.673716381.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: test/manual/awe32_nrpn/Altitude/Altitude-SB Audigy2 ZS.ogg: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

### Expected behavior
No errors when cloning, like previously.

### Steps to reproduce
```git clone "https://github.com/fluidsynth/fluidsynth"```

### Additional context
If this is not important, feel free to close it

**Comment by derselbst** [comment]
Which git versions are you using?
```
git-lfs --version
git --version
```

**Comment by spessasus** [comment]
```
git-lfs --version
git-lfs/3.5.1 (GitHub; linux amd64; go 1.22.1)
git --version
git version 2.47.0
```

**Comment by derselbst** [comment]
I don't see any CI build that has LFS checkout enabled. The bandwidth quota will reset in 15 days, I'd suggest we keep observing this to see if the bandwidth quota somehow correlates with the number of CI builds. If it doesn't, I'd simply outsource the test files into a dedicated repository without using LFS.

**Comment by derselbst** [comment]
I'm starting to realize that using LFS for storing those binaries was a big mistake. When the Quota is exceeded, push access is also greatly impacted. Our quota will be reset in 9 days. Until then, I'll have set up a dedicated repo for the test files and will reference it via git submodule. I need to think about whether it will become necessary to rewrite the commit history to permanently remove the LFS files, or whether they can be kept there.

**Comment by spessasus** [comment]
Wouldn't rewriting the commit history break a ton of stuff like issues and pull requests? It changes the commit hashes, right?

**Comment by derselbst** [comment]
Yes, I also hope to get around it. Simply removing all LFS references should be sufficient to fix the quota issue... I hope.

**Comment by derselbst** [comment]
I have moved the testfiles from LFS to git submodule. I do no longer receive an error when cloning the repository, pls. confirm. I suppose one might still run into an error when attempting to checkout any of the commits that use LFS.

**Comment by spessasus** [comment]
Can confirm, cloning doesn't cause any errors now.
