### ISSUE TITLE
Some instruments are played 1 octave too low.

### ISSUE THREAD

**Issue by bjascob** [FluidSynth/fluidsynth#1443]
### FluidSynth version
FluidSynth runtime version 2.2.5  (although I saw the same issue in version 2.4.1)

### Describe the bug
The pitch of notes for instruments (aka programs) 16, 17 and 18 (Drawbar, Percussive and Rock Organs) is low by 1 octave. I'm using the default soundfont of FluidR3_GM.sf2 on linux. I see this bug I my software, but I also see it when using VMPK with the FluidSynth MIDI driver. VMPK plays the notes correctly when using their default MIDI driver named SonivoxEAS.

### Steps to reproduce
Here is a simple python program to play the notes so you can hear them audibly using the pyfluidsyth bindings.
```
import time
import fluidsynth
fs = fluidsynth.Synth()
fs.start()
sfid = fs.sfload('/usr/share/sounds/sf2/FluidR3_GM.sf2')
# program_select(channel, soundfont_id, bank_num, program_num))
fs.program_select(0, sfid, 0, 0)    # Acoustic Grand Piano
fs.program_select(1, sfid, 0, 17)   # Test instrument
veloctiy = 100
midinum  = 60
if 1:
    print('Playing Acoustic Grand Piano C4')    # correct C4
    fs.noteon(0, midinum, veloctiy)
    time.sleep(1.0)
    fs.noteoff(0, midinum)
if 1:
    print('Playing Test Instrument C4')         # Pitch is too low
    fs.noteon(1, midinum, veloctiy)
    time.sleep(1.0)
    fs.noteoff(1, midinum)
if 1:
    print('Playing Test Instrument C5')
    fs.noteon(1, midinum+12, veloctiy)
    time.sleep(1.0)
    fs.noteoff(1, midinum+12)
if 1:
    print('Playing Test Instrument C6')
    fs.noteon(1, midinum+24, veloctiy)
    time.sleep(1.0)
    fs.noteoff(1, midinum+24)
fs.delete()
```
It can be difficult to hear to difference so here is an STFT plot to compare program 0 and program 17, both at note 60 (middle-C)

![Note60_Prog0_vs_Prog17](https://github.com/user-attachments/assets/fb9b617b-6eda-4756-88da-190d0d0f00cd)

At this sampling rate the note should have a fundamental frequency at bin 33, with harmonics every 33*N. You can see that is true for the blue line (program 0) but for the red line (program 17) the harmonics are every 16 * N, indicating the note is half the frequency, or 1 octave too low.

**Comment by derselbst** [comment]
Instruments 16,17,18 are all overriding their base note, for which fluidsynth accounts correctly as far as I can see. This is a common choice up to the soundfont designer, not a bug.

@pedrolcl Does VMPK / SonivoxEAS account for base note overrides at instrument level?

**Comment by pedrolcl** [comment]
> Does VMPK / SonivoxEAS account for base note overrides at instrument level?

No. Neither the Sonivox nor the Fluidsynth VMPK backends have access to those details of the soundfonts. But virtual instruments designers may have reasons to change the base octave of their instruments, for instance:

https://github.com/mrbumpy409/GeneralUser-GS/blob/main/documentation/CHANGELOG.md
```
000:019 Pipe Organ: Transposed down an octave to match the tonality of the Sound Canvas.
```

I don't think that neither the synthesizers or upstream applications should take any action regarding this issue.

And _"the default soundfont of FluidR3_GM.sf2"_ may be a default on some c**p Linux distribution, like Debian or Ubuntu, but that does not mean a default for Fluidsynth. This report should be addressed to the Debian and Ubuntu bug trackers, or the the FluidR3_GM.sf2 authors (good luck with that!).

CC: @mrbumpy409

**Comment by bjascob** [comment]
Thanks for the info. It sounds like this is a design choice of the soundfont and not something that's actually wrong so I'll close out this issue.
