### ISSUE TITLE
Rename "sndfile.dll" into "libsndfile-XXX.dll" for Windows Distribution

### ISSUE THREAD

**Issue by prof-spock** [FluidSynth/fluidsynth#1450]
Dear all,

sorry, this is ultrapicky and a real minor issue, but it has bitten me for the FluidSynthPlugin distribution based on FluidSynth.

In the new 2.4.1 release for Windows the included library `libsndfile` is now provided as `sndfile.dll` instead of `libsndfile-XXX.dll`. This goes somewhat against the convention: all dynamic libraries of FluidSynth (except for the Windows system libraries) are named with prefix `lib`, the library name stem and an optional version suffix.

Is there a reason for the name change?

Best regards,
Prof. Spock

**Comment by derselbst** [comment]
We are just consuming the prebuilt libsndfile Windows binary from their GH repo - that's all I know.
https://github.com/libsndfile/libsndfile/releases

**Comment by prof-spock** [comment]
Hello derselbst,

thanks for personally chiming in! Long time no hear ...

By your redirection I have found some explanation on the [libsndfile site](https://github.com/libsndfile/libsndfile). There is a CMAKE configuration variable called `ENABLE_COMPATIBLE_LIBSNDFILE_NAME` as follows:
> `ENABLE_COMPATIBLE_LIBSNDFILE_NAME` - set DLL name to libsndfile-1.dll (canonical name) on Windows platform, sndfile.dll otherwise, OFF by default. Library name can be different depending on platform. The well known DLL name on Windows platform is libsndfile-1.dll, because the only way to build Windows library before was MinGW toolchain with Autotools. This name is native for MinGW ecosystem, Autotools constructs it using MinGW platform rules from sndfile target. But when you build with CMake using native Windows compiler, the name is sndfile.dll. This is name for native Windows platform, because Windows has no library naming rules. It is preferred because you can search library using package manager or CMake's find_library command on any platform using the same sndfile name.

Okay, it seems that the `sndfile.dll` name is now the preferred name. I find this decision unfortunate, since all the Unix-based software distributions typically use the libXXX naming convention and also previous versions of libsndfile and FluidSynth had obeyed it by using `libsndfile-1.dll`.

Anyway, it definitely is not a FluidSynth topic (unless you decide to rename that library for your own binary distribution to have a consistent library naming scheme in Windows 😉)

Best regards,
Prof. Spock
