### ISSUE TITLE
ADD input driver for simple RS232

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#162]
Hello,

at the time of writing, it seems to me that fluidsynth accepts MIDI events from several input drivers:
- Jack
- OSS
- ALSA
- Windows MidiIn
- Midishare
- Coremidi

But it seems it is not able to use a simple RS232 serial port.
I'm wondering if you would accept in your code an additional driver that it opens a serial port and it receives the MIDI event in this traditional way. For me, it is easy to implement a code that it reads/writes the serial ports (on Windows), a bit more difficult is to integrate that code into fluidsynth.
My suggestion would be to write a common callback that it receives a buffer and its length and it processes it and few other sources for handling the serial port, something like this:
fluid_rs232.c (for common parts)
fluid_rs232_win.c (for handling rs232 on Windows)
fluid_rs232_posix.c (for handling rs232 on Linux, Mac, BeOS, etc)

What do you think?

Sincerely.

Reported by: carlo_bramini

Original Ticket: [fluidsynth/tickets/164](https://sourceforge.net/p/fluidsynth/tickets/164)

**Comment by derselbst** [comment]
@carlo-bramini You could use fluid_jack.c as template. Whenever you receive an input via rs232 perhaps trigger an interrupt or callback that queues the data to a local buffer and then either schedule a call to `fluid_jack_driver_process()` or run this function periodically in order to process this buffer that hopefully holds useful midi data.

**Comment by mawe42** [comment]
Linux already has a fully working RS232 to MIDI driver, and I guess the same applies to other UNIX OS. So there's no need to replicate this functionality in FluidSynth. And for Windows, you might be able to use something like http://projectgus.github.io/hairless-midiserial/

**Comment by derselbst** [comment]
> Linux already has a fully working RS232 to MIDI driver,

Would have wondered if they didnt. I guess it can be routed to Midi-Through port? In this case I agree that it's somewhat too low level and unsuited for fluidsynth.

**Comment by mawe42** [comment]
> I guess it can be routed to Midi-Through port? In this case I agree that it's somewhat too low level and unsuited for fluidsynth.

I had another look at the snd-serial midi driver that I had in mind and noticed that I got it wrong. The existing driver only works with the ISA UART 16550 chip, so not very usable nowadays... :-/ But there's ttymidi for Linux, which is supposed to work well. Haven't used it myself, though.

**Comment by derselbst** [comment]
Closed due to inactivity.
