### ISSUE TITLE
Calculation of lower boundary for attenuation should also consider channel pressure, key pressure and pitch wheel

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#163]
While testing the patch for ticket #50, I noticed that modulators which affect initial attenuation and use the general controllers channel pressure, key pressure and pitch wheel prevent note on events from happening when the modulator is set so that the initial volume is 0.

The reason is that the function fluid_voice_get_lower_boundary_for_attenuation only considers continuous controllers but ignores the three controllers mentioned above. With this patch, key pressure, channel pressure and pitch wheel can be used in initial attenuation modulators and behave just like other continuous controllers, like the expression controller for example.

Reported by: mawe242

Original Ticket: [fluidsynth/tickets/165](https://sourceforge.net/p/fluidsynth/tickets/165)

**Comment by mawe42** [comment]
I noticed that the patch I sent to the old sourceforge tracker contains a bug, it should therefore not be merged as is. Will fix it and create a proper pull request in the next few days.

**Comment by derselbst** [comment]
@mawe42 Thx for joining. Could you take care of this issue whenever you're free?

**Comment by mawe42** [comment]
Sure, will look at it today.
