### ISSUE TITLE
Remove autotools buildsystem

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#166]
autotools should be removed upon a 1.2 release.

**Comment by derselbst** [comment]
also watch out for and remove duplicate files, one used by cmake another by autotools (e.g. config_win32.[in|cmake])

**Comment by kmatheussen** [comment]
Is there a reason for doing this? It's usually much less trouble compiling a project using autotools than cmake, especially if you are cross compiling.

**Comment by derselbst** [comment]
The autotools build system was deprecated almost 7 years ago. It is just such a pain to maintain two different buildsystems and I'm not willing to do that, sry. Ofc we could just leave it untouched so it gets completely orphaned, but people would still attempt to build with it, causing confusions and wasted time. Thus I consider removing it the better way to go.

As for cross compiling, I'm having too little experience, so I cant tell. However CMake has the better cross platform support, which makes cmake preferable IMO. I'm open to any suggestions that make cross compilation easier with cmake.

**Comment by kmatheussen** [comment]
Sure, if it creates extra work, that's a valid reason to remove it. I didn't know it was deprecated. I wish you would deprecate cmake instead though.

Regarding cross compilation, it's usually enough for the build system to prefix a string to all the normal commands such as gcc, ar, ld, and so forth. In autotools, all of this is handled by the "--host" argument, while on cmake it's a complete mess and it's also seemingly impossible to find valid and clear documentation about it. In my experience, cmake has non-existant cross platform support. The only solution that works in practice is to override CC, CFLAGS, etc. manually.

**Comment by derselbst** [comment]
cmake uses variables like `CMAKE_SYSTEM_NAME`, `CMAKE_SYSTEM_PROCESSOR` and `CMAKE_FIND_ROOT_PATH` as described here: https://cmake.org/Wiki/CMake_Cross_Compiling

Might not be as comfortable as autotools, but looks like a good approach to me.

**Comment by kmatheussen** [comment]
My experience is that these don't work, and it's not a good approach either. You also need to install (and probably edit) some global cross-compilation configuration files, and it's very frustrating trying to find out how to make them work. I've never gotten them to work. And there is no understandable documentation, and googling it turns up nothing useful. Problem is that they make things too complicated. The only thing we need is to set a prefix variable for the compilation commands, and/or an easy way to override CC/CCC. The latter is possible, you need to sweat a lot to achieve it.

**Comment by derselbst** [comment]
done in 3939941c5f3fdaef6bf9258fabd5725e7666554a
