### ISSUE TITLE
Bank of midi channel 10 hardcoded

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#172]
midi channel 10 is currently hardcoded to the drum bank (i.e. 128) and cannot be changed by explicit events, because of [fluid_chan.c:267](https://github.com/FluidSynth/fluidsynth/blob/cf1975e35ffbca96cb47da38157ffead7f4897d5/fluidsynth/src/synth/fluid_chan.c#L267) and [fluid_synth.c:1948](https://github.com/FluidSynth/fluidsynth/blob/cf1975e35ffbca96cb47da38157ffead7f4897d5/fluidsynth/src/synth/fluid_synth.c#L1948).

@elementgreen @diwic Do you know why it was implemented like this? I can understand this behaviour for `FLUID_BANK_STYLE_GM`. But at least for `FLUID_BANK_STYLE_MMA` wouldnt it be a better solution to initialize channel 10 with `DRUM_INST_BANK` and allow bank changes?

**Comment by derselbst** [comment]
Changes from #176 tested. Seems to work as expected.

**Comment by diwic** [comment]
@derselbst I don't remember much more than semi-wild discussions on the mailinglists. IIRC, the MMA mode was something we invented ourselves, so can't really say if this will break some usage scenario or not.
