### ISSUE TITLE
Readme file should be styled as Markdown

### ISSUE THREAD

**Issue by markh-de** [FluidSynth/fluidsynth#181]
Suggesting to (manually) convert the top-level project information `README` file to **Markdown** for proper styled display on Github (and other tools).
Would you accept such a PR?

**Comment by derselbst** [comment]
Explicitly converting to markdown may be redundant, because github recognizes the current style. We only need to rename it to README.md and it'll work fine, see my former custom fork: https://github.com/derselbst/fluidsynth/blob/master/README.md

**Comment by markh-de** [comment]
Yes, it's nice of MD to interpret the current file content quite usefully.
However, if we rename it to `md`, then we should really apply MD styling consequently to all parts/elements of the file, such as sub-sections, headers, etc.

If you agree, I'll prepare a PR.

**Comment by derselbst** [comment]
Alright, if it satisfies your OCD ;)

**Comment by derselbst** [comment]
But note that I already moved and renamed it: 1e825a5d54e4ecbd0e60f855eb45c1e5235d7a03
