### ISSUE TITLE
Top-level "fluidsynth" directory node

### ISSUE THREAD

**Issue by markh-de** [FluidSynth/fluidsynth#182]
Most projects on Github directly use the repository top-level for `README` file and source directories. In this (fluidsynth) repository, the top-level consists of a single (imo redundant) sub-directory node, and no project/repo `README`. Was that extra level added on purpose or by mistake during the initial commit?

I know that Git is not really move-aware, so removing that directory level just for sanity will cause a lot of trouble (at least if there are branches to be merged). But should you ever plan to change the project's internal source directory structure, I suggest using that opportunity and also remove the "fluidsynth" top-level directory node.

For the time being, should we at least add a `README.md` file to the repo top-level, as a "landing page" for project visitors?

**Comment by derselbst** [comment]
> the top-level consists of a single (imo redundant) sub-directory node

Absolutely agreed.

> Was that extra level added on purpose or by mistake during the initial commit?

Dont know. I think this had been common practice on sourceforge (or even before that time).

> I know that Git is not really move-aware, so removing that directory level just for sanity will cause a lot of trouble (at least if there are branches to be merged)

Yep, I plan to do this but not before having merged most custom forks floating around here.

> For the time being, should we at least add a README.md file to the repo top-level, as a "landing page" for project visitors?

Ok, I'll do that.

**Comment by derselbst** [comment]
top level fluidsynth dir removed
