### ISSUE TITLE
Windows VisualStudio 2017, snprintf

### ISSUE THREAD

**Issue by harborsiem** [FluidSynth/fluidsynth#189]
I get a compile error in Visual Studio 2017 with function "snprintf" which was defined in file "config_win32.h.in" (#define snprintf _snprintf).
Error 	C1189	#error:  Macro definition of snprintf conflicts with Standard Library function declaration

**Comment by derselbst** [comment]
Just added a commit which should fix that. Please checkout from recent git and try again.

**Comment by harborsiem** [comment]
Works fine.
Very fast work !!!

Regards
Hartmut

**Comment by derselbst** [comment]
Great.

> Very fast work !!! 

Just dont expect this to become default ;)
