### ISSUE TITLE
refactor rvoice_mixer

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#197]
`rvoice_mixer` needs a bit refactoring after the workaround to fix #192. Think about:

- [x] remove `fluid_rvoice_eventhandler_t::is_threadsafe`
- [x] remove "synth.parallel-render"
- [x] remove fluid_voice_t::debug
- [x] refactor chrous and reverb types
  - fluid_revmodel_set takes floats.
  - fluid_revmodel_presets_t uses fluid_real_t
  - fluid_revmodel_t uses fluid_real_t
  - fluid_rvoice_mixer_set_chorus_params takes doubles
  - fluid_rvoice_mixer_set_reverb_params take doubles
  - fluid_rvoice_event_t::realparams is fluid_real_t.
  - public synth API takes doubles
  - etc.
- [x] ~each `rvoice` gets its own mono resampled `buffer[FLUID_MIXER_MAX_BUFFERS_DEFAULT*FLUID_BUFSIZE]`?~
- [x] ~openMP parallelization?~
- [x] get rid of that hug macro magic switch case in rvoice_event_handler
- [x] variable naming not very intuitive (buf_blocks, buf_count, current_blockcount ???)
- [x] loop that initializes rvoice buffer in `fluid_rvoice_buffers_check_bufnum()` is superfluous
- [x] efficiently render "silence"
- [x] rethink fluid_synth_check_finished_voices()
- [x] ~fluid_rvoice_set_output_rate() is called twice (by fluid_voice_set_output_rate() and fluid_rvoice_mixer_set_samplerate())~
- [x] process effects units in parallel

**Comment by jjceresa** [comment]
About the mixer.
> variable naming not very intuitive (buf_blocks, buf_count, current_blockcount ???)

Some infos follows:
![mixer-fluid_rvoice_mixer_t](https://user-images.githubusercontent.com/32781294/36636041-9e2f6704-19be-11e8-934d-7a47346772da.JPG)

- `buf_count`: is the number of buffers .
This number  depends of the number of `audio output`. This number is specified by `mixer->buffers.buf_count`. (Probably a better naming should be related to the audio output number).

- Internally each buffer have the same maximum size (`buf_blocks`). (not a good name too).
- The size of a buffer (buf_blocks) is specified in blocks. Each block have `FLUID_BUFSIZE `samples

- `current_blockcount`: is the current  index (0 to buf_blocks) of the block been mixed.
***
Some images shows the internals links from 'detail to top':
![mixer-fluid_mixer_buffers_prepare](https://user-images.githubusercontent.com/32781294/36636043-9e7aa35e-19be-11e8-96e0-cd9987973b87.JPG)
![mixer-fluid_mixe_one](https://user-images.githubusercontent.com/32781294/36636042-9e51edba-19be-11e8-80a2-8f9e451d706e.JPG)

The `buffs `table pointers keeps the mixer independent of the real buffers structure.
***
![mixer-fluid_rvoice_mixer_render](https://user-images.githubusercontent.com/32781294/36636044-9e9812c2-19be-11e8-9e20-42a4680183cd.JPG)
The caller request `blockcount  `block (each block is FLUID_BUFSIZE sample size ).
The function returns the `real blocks number` processed.

**Comment by derselbst** [comment]
Thanks for this illustration!
