### ISSUE TITLE
libfluidsynth 1.1.7 - compiler issues

### ISSUE THREAD

**Issue by ReinholdH** [FluidSynth/fluidsynth#202]
First of all, thanks for publishing fluidsynth 1.1.7

I ran into compiler issues when creating the libfluidsynth library:

(1) fluid_rvoice_event.c line 187
  int old_queue_stored = fluid_atomic_int_add(&handler->queue_stored, 1);
"fluid_atomic_int_add" is refering "g_atomic_int_add" which is a void function and not an int function

(2) fluid_synth.c line 189
 fluid_settings_register_str(settings, "synth.default-soundfont",
			      DEFAULT_SOUNDFONT, 0, NULL, NULL);
DEFAULT_SOUNDFONT is undefined  and parameters are missing compared to the definition of fluid_settings_register_str

It would be great if somebody could fixed these issue that a fresh and clean start with is possible.

Thank

Reinhold

**Comment by derselbst** [comment]
> "fluid_atomic_int_add" is refering "g_atomic_int_add" which is a void function and not an int function

Before glib 2.30 it did not return an int, so the glib you build against seems to be older than that. I pushed a commit that should fix this issue: 39ccd5f77d7f0c5ccbb1f28e21fa1f252aafa116
You could either apply these changes or update glib to at least `2.30`.

> DEFAULT_SOUNDFONT is undefined

I guess you've built fluidsynth using the deprecated and unmaintained autotools buildsystem? If so you'll have to fix it your own by replacing `DEFAULT_SOUNDFONT` with an empty string for instance.

**Comment by ReinholdH** [comment]
Thanks. That was very helpful.
