### ISSUE TITLE
"select" commands in a config file are ignored in fast_render mode

### ISSUE THREAD

**Issue by mqnc** [FluidSynth/fluidsynth#203]
this is how my config file looks:

```
load /home/me/soundfonts/FluidR3_GM.sf2 1 0
load "/home/me/soundfonts/GeneralUser GS v1.471.sf2" 1 200
fonts
select 0 1 0 81
select 9 2 328 16
channels
```

then I run fluidsynth using
`fluidsynth -f "fluidsynth.cfg" -F out.wav in.mid`

The console output is:

```
FluidSynth version 1.1.6
Copyright (C) 2000-2012 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

loaded SoundFont has ID 1
loaded SoundFont has ID 2

ID  Name
 2  /home/mirko/soundfonts/GeneralUser GS v1.471.sf2
 1  /home/mirko/soundfonts/FluidR3_GM.sf2

chan 0, Saw Wave
[I cut the other channels out]
chan 9, Power
[I cut the other channels out]

Rendering audio to file 'out.wav'..
```
so one might think the correct instruments are chosen before rendering. But the sound stays piano and doesn't become saw wave. However, if I include program change messages in the beginning of the midi file, everything works fine. But I don't want to do that manually for every midi file...

**Comment by derselbst** [comment]
You have to call `fluidsynth` with
```
-o player.reset-synth=0
```
otherwise the synth is being reset before every midi song.

**Comment by mqnc** [comment]
Thank you! Should have known that fluidsynth is flawless :)
Is loading multiple midi files only useful for chaining them into a single wav file? Can one render multiple midi files into multiple wav files in a single session?

**Comment by derselbst** [comment]
Only into a single wav file, AFAIK. Multiple midis to multiple wavs can be done via bash scripting though.

**Comment by mqnc** [comment]
Yes, that's what I'm doing. It means that the soundfonts have to be reloaded for every file. But that's just a minor inconvenience.

**Comment by derselbst** [comment]
ok
