### ISSUE TITLE
Feature request: Accept MIDI data from a pipe

### ISSUE THREAD

**Issue by mk-pmb** [FluidSynth/fluidsynth#209]
Now that I have a work-around for the original (output) issue from #208, let's investigate the input issue. To reproduce in bash:

1. Setup

```bash
$ export LANG=C
$ dpkg -S TimGM6mb.sf2 | grep . || sudo apt-get install timgm6mb-soundfont
timgm6mb-soundfont: /usr/share/sounds/sf2/TimGM6mb.sf2
$ alias timgm='strace -o trace.log fluidsynth --disable-lash '$(
  )'--fast-render=/proc/self/fd/42 42>&1 1>&2 '$(
  )'--audio-file-type=flac /usr/share/sounds/sf2/TimGM6mb.sf2'
$ alias playflac='play --no-show-progress --type flac'
$ <<<'TVRoZAAAAAYAAQABAeBNVHJrAAAAFAD/BAAAwE8AkEV/gRaARX8A/y8A
' base64 --decode >oca.mid
```

2. Verify rendering MIDI data from file (this should work perfectly)

```bash
$ timgm oca.mid | tee >(sha1sum -b >&2) | playflac -
FluidSynth version 1.1.6
Copyright (C) 2000-2012 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
Rendering audio to file '/proc/self/fd/42'..
269e078f93e3b7ffc69774bfee91f21754d8977c *-
$ <oca.mid timgm /dev/stdin | false
FluidSynth version 1.1.6
Copyright (C) 2000-2012 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
Rendering audio to file '/proc/self/fd/42'..
```

3. Test rendering MIDI data from pipe. Same command as previous, just with `cat` and pipe instead of input redirection:

```bash
$ cat oca.mid | timgm /dev/stdin | false
FluidSynth version 1.1.6
Copyright (C) 2000-2012 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
Parameter '/dev/stdin' not a SoundFont or MIDI file or error occurred identifying it.
No midi file specified!
```

The strace log part with the double read:

```diff
+ open("/dev/stdin", O_RDONLY)            = 3
  fstat64(3, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
  mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb7711000
+ read(3, "MThd\0\0\0\6\0\1\0\1\1\340MTrk\0\0\0\24\0\377\4\0\0\300O\0\220E"..., 4096) = 42
  close(3)                                = 0
  munmap(0xb7711000, 4096)                = 0
- open("/dev/stdin", O_RDONLY)            = 3
  fstat64(3, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
  mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb7711000
- read(3, "", 4096)                       = 0
  close(3)                                = 0
  munmap(0xb7711000, 4096)                = 0
- write(2, "Parameter '/dev/stdin' not a Sou"..., 86) = 86
```

Copied from other thread:
> The first read seems to be from `fluid_is_soundfont()` @ `src/utils/fluid_sys.c:349`. Would be nice if future versions of fluidsynth would support CLI flags to allow announcing which sort of data to expect in the next filename, so it has to read them only once.

Example:

```bash
$ cat oca.mid | timgm --nextarg=midi /dev/stdin | false
```

**Comment by derselbst** [comment]
So I see it as follows: The first open indeed comes from `fluid_is_soundfont()`. When this happens on a pipe it reads the MThd chunk from it. fluidsynth recognizes that this is no soundfont and closes. Just afterwards fluidsynth checks for `fluid_is_midifile()`. But oops, the MThd chunk is already gone from the pipe as it was read before. No data is left, so this is obviously not a midi file. close(). And this is not the only time the fluidsynth executable tests for a midifile.
In short: the fluidsynth executable is simply not designed to read midifiles from a pipe.

Of course one could think about rewriting that... honestly speaking, I have no interest in doing so.

However what you want to achieve should be easily doable writing your own small program: Read data from the pipe and store that in a buffer until you receive the end of the midi file. Continue reading the data from the pipe to a different buffer again until end of midi. Provide these buffers to fluidsynth's player, see [Playing a MIDI file from memory](http://www.fluidsynth.org/api/index.html#MIDIPlayerMem). Instead of playing them back you'll have to use the fast file renderer. Currently there is no example code of how to use the file renderer. You could look into fluidsynth.c how it is done or just ask if you need support.

**Comment by mk-pmb** [comment]
Thanks for the hints!
For my current project I can't include compiled binaries or code that has to be compiled, but if I need fluidsynth in another project again, I might try. I'd still prefer the command line switch though. :-)

**Comment by derselbst** [comment]
Still convinced that a custom command line app is the best way to implement this feature.

For reference: here's the doc about the fast file renderer: http://www.fluidsynth.org/api/index.html#FileRenderer

**Comment by mk-pmb** [comment]
In case anyone else wants to help get it to work with the original FluidSynth binaries: I just got the idea to send the MIDI data as often as FluidSynth tries to read it:

```bash
$ cat oca.mid /dev/zero | head --bytes=4k >oca.4k0
$ cat oca.4k0 oca.4k0 oca.4k0 | timgm /dev/stdin | false
```

This successfully circumvents the problem previously described:

```diff
-open("/dev/stdin", O_RDONLY)            = 3
 fstat64(3, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
 mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb7723000
+read(3, "MThd\0\0\0\6\0\1\0\1\1\340MTrk\0\0\0\24\0\377\4\0\0\300O\0\220E"..., 4096) = 4096
 close(3)                                = 0
 …
-open("/dev/stdin", O_RDONLY)            = 3
 fstat64(3, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
 mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb7723000
+read(3, "MThd\0\0\0\6\0\1\0\1\1\340MTrk\0\0\0\24\0\377\4\0\0\300O\0\220E"..., 4096) = 4096
 close(3)                                = 0
```

However, the 3rd time it tries to read, it also seeks:

```diff
-open("/dev/stdin", O_RDONLY)            = 4
 fstat64(4, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
 mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb7723000
 fstat64(4, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
-_llseek(4, 0, 0xbff963f0, SEEK_END)     = -1 ESPIPE (Illegal seek)
```

… so there's probably no hope to easily make it work with pipes.
