### ISSUE TITLE
Version 1.1.7, Windows 32 Bit Visual Studio compiler error in fluid_rvoice_event.c

### ISSUE THREAD

**Issue by harborsiem** [FluidSynth/fluidsynth#210]
In file "fluid_rvoice_event.c", line 186 I get error C2120 ("void" with types not allowed).
I think it is a problem in file gatomic.h , line 43 in the declaration of function "g_atomic_int_add".
function should return a gint instead of void.

**Comment by derselbst** [comment]
Yep, sry for that. Here's the solution: https://github.com/FluidSynth/fluidsynth/issues/202#issuecomment-327404015

**Comment by harborsiem** [comment]
I have tried the commit that should fix this issue:   39ccd5f .
My version of glib and gthread is 2.28.8, intl.dll is 0.18.1. These are the latest published versions for Windows I have found.
Visual Studio 2017 build the libfluidsynth.dll successfull.

But I have to build the release a second time because the first build failed with a link error to Release\fluidsynth.lib (LNK1181)

Then I try to use the libfluidsynth.dll in my C# application. But I have no sound anymore when I play a midi sequence via a SF2-file.
The libfluidsynth Version 1.1.6 works ok.

**Comment by derselbst** [comment]
> But I have to build the release a second time because the first build failed with a link error to Release\fluidsynth.lib (LNK1181)

Did you clean up the solution before rebuilding? In case yes, I need the the full build log.

> I have no sound anymore when I play a midi sequence via a SF2-file.

Please open a new issue and describe how excatly you are playing the midi (using fluidsynths midi player, only the synth or an audio driver? which audio driver?). If possible provide short example code. Also try playing the midi with the `fluidsynth` executable directly.

**Comment by harborsiem** [comment]
>> But I have to build the release a second time because the first build failed with a link error to Release\fluidsynth.lib (LNK1181)
>
> Did you clean up the solution before rebuilding? In case yes, I need the the full build log.

After clean up the solution it's ok.
