### ISSUE TITLE
Windows 7: No sound when playing midi notes

### ISSUE THREAD

**Issue by harborsiem** [FluidSynth/fluidsynth#215]
Then I try to use the libfluidsynth.dll in my C# application. But I have no sound anymore when I play a midi sequence via a SF2-file.
 The libfluidsynth Version 1.1.6 works ok.
I play the midi via the synth (fluid_synth_noteon,  fluid_synth_noteoff and so on)

I try to call fluidsynth.exe directly. I got this message:
C:\Users\harbor\Projects\VS20xy\Fluidsynth117\build\src\Debug>fluidsynth
FluidSynth version 1.1.7
Copyright (C) 2000-2012 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

fluidsynth: error: FluidSynth hinstance not set, which is needed for DirectSound

Failed to create the audio driver

**Comment by derselbst** [comment]
Ok, so you've built fluidsynth using VS. Did you use autotools or cmake prior to that? Could you provide the VS build log (make sure compiler flags are displayed, i.e. build log set to verbose mode).

> I play the midi via the synth (fluid_synth_noteon, fluid_synth_noteoff and so on)

Are you pulling the sample buffer via directly (via fluid_synth_process(), fluid_synth_nwrite() or fluid_synth_write())?

And please try:
```
fluidsynth -F test.wav SomeSF.sf2 Some.MIDI
```

**Comment by harborsiem** [comment]
> Did you use autotools or cmake prior to that?

I use cmake-gui.exe prior to VS. 

> Could you provide the VS build log (make sure compiler flags are displayed, i.e. build log set to verbose mode).

Where I can find the VS build log ? Where can I set the verbose mode ?
I am not familiar with C - development

> Are you pulling the sample buffer via directly (via fluid_synth_process(), fluid_synth_nwrite() or fluid_synth_write())?

I don't use these functions. I use fluidsynth as a MIDI-Port.

I had tried to generate the test.wav. I got this file. But it's not a valid wav file (No Header).

**Comment by derselbst** [comment]
> Where I can find the VS build log ? Where can I set the verbose mode ?

And I’m not familiar with VS. No offense, but seriously: http://www.letmegooglethat.com/?q=visual+studio+verbose+build

> I don't use these functions. I use fluidsynth as a MIDI-Port.

So you must be using an audio driver. dsound I guess. Which brings the error above, where I need the build logs.

> But it's not a valid wav file

Ah, you’ve build without libsndfile. Didn’t know that. Thus you get a raw pcm file. Just load it into audacity or so to verify whether fluidsynth works or not.

**Comment by harborsiem** [comment]
In the zip there is the debug log from building the release.

[ReleaseBuildLog.zip](https://github.com/FluidSynth/fluidsynth/files/1343691/ReleaseBuildLog.zip)

> Thus you get a raw pcm file. Just load it into audacity or so to verify whether fluidsynth works or not.

I import "test.wav" in audacity as a raw file. I get a sound when I set encoding to signed 16 bit pcm and stereo.

**Comment by derselbst** [comment]
Ok, after a first look at the build log it seems the problem is that the `FLUIDSYNTH_NOT_A_DLL` macro is defined. Will further investigate in the next days.

**Comment by derselbst** [comment]
Pushed a commit that should fix the dsound driver. Feel free to check out the [1.1.x](https://github.com/FluidSynth/fluidsynth/tree/1.1.x) branch and let me know if it works.

**Comment by harborsiem** [comment]
Fix works for me.
Thanks.
