### ISSUE TITLE
Windows: libfluidsynth.dll should show version info in explorer file detail view

### ISSUE THREAD

**Issue by harborsiem** [FluidSynth/fluidsynth#216]
This is an example german detail view from libfluidsynth.dll:

![properties](https://user-images.githubusercontent.com/28147549/30904161-7151f17a-a371-11e7-8a93-0170a16a5f19.jpg)

You can do this with the following resource file inside the zip:

[libfluidsynth_dll.zip](https://github.com/FluidSynth/fluidsynth/files/1336385/libfluidsynth_dll.zip)

In the cmake generated libfluidsynth.vcxproj file you have to add at the end of file:

<Project ...
...

  <ItemGroup>
    <ResourceCompile Include="libfluidsynth_dll.rc" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
  </ImportGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties RESOURCE_FILE="libfluidsynth_dll.rc" />
    </VisualStudio>
  </ProjectExtensions>
</Project>

**Comment by harborsiem** [comment]
ups, the last lines are lost
 
 `<ItemGroup>
    <ResourceCompile Include="libfluidsynth_dll.rc" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
  </ImportGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties RESOURCE_FILE="libfluidsynth_dll.rc" />
    </VisualStudio>
  </ProjectExtensions>
</Project>`

**Comment by derselbst** [comment]
The screenshot shows the way it should be?

Anyway, I dont quite know what you want me to do. Could you please elaborate?

**Comment by harborsiem** [comment]
It would be a nice feature to see the version of a *.dll or *.exe with the file explorer. One can also look with an other program to these informations via winapi functions.

> The screenshot shows the way it should be?

Yes, Sir.

> Could you please elaborate?

I give it a try.
First of all take a look to the file "libfluidsynth_dll.rc" (inside the above .zip file) with a text editor.
In this file at line 7, 8, 26, 31 there are version infos they are shown in the screenshot. The values of version infos have to substitute in every new version. The version info consist @FLUIDSYNTH_VERSION_MAJOR@, @FLUIDSYNTH_VERSION_MINOR@, @FLUIDSYNTH_VERSION_MICRO@, 0.
So I think it is a good idea to define a basic resource file similar to fluidsynth/include/fluidsynth/version.h.in. In the cmake tools you have to generate this basic resource file to a correct resource file.

Next step is to add the lines in the "libfluidsynth.vcxproj" file as I had written formerly.

After build the solution, you get the version info in the dll.

**Comment by derselbst** [comment]
Thanks. So the "libfluidsynth_dll.rc" is a resource file specifically for VS and nothing else?

> Next step is to add the lines in the "libfluidsynth.vcxproj" file as I had written formerly.

Dont know how you imagine that. cmake is doing all that project file generation stuff, we dont have any control over that. And manually messing around in such a project file is the totally wrong way to go IMO as there is no guarantee that it's still a valid file afterwards.

**Comment by harborsiem** [comment]
> So the "libfluidsynth_dll.rc" is a resource file specifically for VS and nothing else?

The resource file is a Windows specific file. You can find more in the MSDN pages.
Here you can find more about cmake and resource files (Google search: "cmake resource compiler").

[stackoverflow](https://stackoverflow.com/questions/3526794/how-do-i-build-a-win32-app-with-a-resource-file-using-cmake-and-mingw)

The extra lines in the vcxproj file should be done by the cmake stuff when you insert a command for the rc file in "CMakeLists.txt".

**Comment by derselbst** [comment]
> The resource file is a Windows specific file. You can find more in the MSDN pages.

Thx. That's the information I was missing. Then one could think about shipping the `.rc` file, call that resource compiler via cmake and hope cmake will take care of that when generating the VS proj file.

But I also have to say that I dont consider this to have priority.

**Comment by derselbst** [comment]
Frankly, I don't think I'll ever get to this. I neither have the means nor the time to test this. I would probably accept a pull request for this. Otherwise I'll close this as wont fix... some day.

**Comment by harborsiem** [comment]
I have done a google search: cmake windows dll version

I found this page:
[generate-windows-dll-version-info-resource-with-cmake](https://www.codeofclimber.ru/2015/generate-windows-dll-version-info-resource-with-cmake/)

new files in src directory:
generate_product_version.cmake
VersionInfo.in
VersionResource.rc

with some small modifications to the original files

modified src/CMakeLists.txt in src directory of fluidsynth

This works for Windows with Visual Studio 2017.
But I don't know if the changes in CMakeLists.txt are Ok for other builds.
@derselbst : Please check it

Here are the files:
[WindowsVersion.zip](https://github.com/FluidSynth/fluidsynth/files/1670483/WindowsVersion.zip)

**Comment by harborsiem** [comment]
I pushed the wrong button

**Comment by derselbst** [comment]
Sure looks good. Some annotations:

* Please modify the `src/CMakeLists.txt` of the master branch and try again
* `generate_product_version.cmake`, `VersionInfo.in`, `VersionResource.rc` should be placed into the `cmake_admin/` dir (this will spare you the extra `include()` and adjustment of `CMAKE_MODULE_PATH`)
* Unless you're sure this also works for MinGW, it should be

```cmake
if ( WIN32 AND NOT MINGW )
generate_product_version(
#...etc...
```

If you create a pull request with these changes it'll be likely to be accepted.
