### ISSUE TITLE
Use Library on Android

### ISSUE THREAD

**Issue by vmudimupersonal** [FluidSynth/fluidsynth#221]
I am trying to use the library in an Android app. I can not seem to get an so file built on a mac os. Is there a process of doing this? If so where can I get the information?

**Comment by derselbst** [comment]
Which version of fluidsynth are you using?
Which build system are you using (cmake or autotools)?

> I can not seem to get an so file built on a mac os.

What is the error you are experiencing?

**Comment by vmudimupersonal** [comment]
Thank you for the quick response. 
I am on fluidsynth : v1.1.7 using CMake

I do not get an error per say but when I run make in my build directory I get the executable but I can not locate the .so file as my intention is to write a JNI mapping for use in an android app. I Can see the .framework file but that is as far as shared resources go when I run make (without any targets i.e running the default target) in my build folder.

**Comment by derselbst** [comment]
> I get the executable but I can not locate the .so file

The .so file should be located in build/src/ directory.

**Comment by vmudimupersonal** [comment]
I might be missing a trick but when go into my build folder and run the make command on it's own I have attached the screenshot of my build src folder and there is no .so file. I am doing the build on a mac. The only thing though is I have not installed Doxygen. I am not sure if this has any consequences for the build as I thought that was for the documentation generation. On My configure page in CMake I have BUILD_SHARED_LIBS checked (enabled). Are there any other config parameters I need to check to get the .so file?

<img width="1010" alt="fludi-synth-build-folder" src="https://user-images.githubusercontent.com/22462693/31174406-0b404c6e-a8d1-11e7-8859-53040bd23b56.png">

**Comment by derselbst** [comment]
> I Can see the .framework file

Apparently it's a folder. Have you looked there?

**Comment by derselbst** [comment]
> The only thing though is I have not installed Doxygen.

Doesnt matter btw.

**Comment by vmudimupersonal** [comment]
When I expand the .framework folder there is no .so file under it. Is there a binary distribution that I can use to bootstrap my android application as I really love the library and need to get traction on my application development.

<img width="1341" alt="fluid-synth-lib-folder-expanded" src="https://user-images.githubusercontent.com/22462693/31177896-f4aab7da-a8dc-11e7-931b-83d6155f5018.png">

**Comment by derselbst** [comment]
It must be there. Please change to the root dir of the fluidsynth source dir and search for `*.so`

**Comment by vmudimupersonal** [comment]
Thank you. I still can not locate the .so file. For my use case I think I will have to cross compile for android. I will get started on looking up ways to cross compile the library for use on android. Is there any documentation that you know of that can assist me in this regard?

**Comment by derselbst** [comment]
Strange. Can you try it via commandline?

```
cd fluidsynth-1.1.7/
rm -r build
mkdir build && cd build
cmake ..
make VERBOSE=1
```

And please post the complete log.

> I will get started on looking up ways to cross compile the library for use on android. Is there any documentation that you know of that can assist me in this regard?

Not yet, sry.

**Comment by vmudimupersonal** [comment]
Attached is my log file after running the commands above.
[fluid_build.log](https://github.com/FluidSynth/fluidsynth/files/1356111/fluid_build.log)

**Comment by derselbst** [comment]
Ok, your "library" seems to be `build/src/FluidSynth.framework/Versions/1/FluidSynth` while your exec is `build/src/fluidsynth`.

As I just learned cmake doesnt add the `.so` extension to it because `FRAMEWORK` is set to true: https://cmake.org/cmake/help/v3.0/prop_tgt/FRAMEWORK.html

Not familiar with MacOS, dont know what that means.

**Comment by vmudimupersonal** [comment]
Thank you. I will spin up a linux VM and rebuild. If I get an .so file on a linux environment for android do you know what are the steps I would take to make use of it? So far I am leaning towards building the .so and then using JNI to link in the so. Seems to me that is the way to go from what I can see. Thank you again for your help.

**Comment by derselbst** [comment]
> If I get an .so file on a linux environment for android do you know what are the steps I would take to make use of it?

No sry. All I know is that you have to build the .so file via cross compilation. I so far havent done this myself and cant support you beyond this step.

**Comment by vmudimupersonal** [comment]
Thank you for the support. I will look to into the cross compilation process. Closing the issue.

**Comment by mawe42** [comment]
Maybe this will help you: https://github.com/taka-no-me/android-cmake
