### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by petmakris** [FluidSynth/fluidsynth#223]
Why there are no binary releases for windows as for Linux?

Thanks

**Comment by derselbst** [comment]
For which OSs should we provide binaries, for which not? And for which architectures, for which not? Who decides that? With what support should fluidsynth be built? (ALSA?, JACK?, PulseAudio?, Portaudio?, dbus?, libsndfile?, lash?) Should we also provide binaries for all those 3rd party libs? Or should we just statically link them all in? Or should we provide both options? And even if we had published binaries anyway, who should build and maintain them? I dont have time for that, but I also wont be arbitrarily accepting binaries from various contributors, as I cannot be sure that fluidsynth hasnt been modified or hacked in some way.

So... you see all those question marks: that's the reason.

If building from source can be made easier on Windows in some way, we can discuss that. No problem. But just arbitrarily releasing binaries is the wrong way IMO.
