### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by mawe42** [FluidSynth/fluidsynth#250]
Somewhat related to #179, but a little larger: I would love it if we could decide on a coding style that we expect in new contributions. The FluidSynth codebase has grown over many years and with many different coding styles. The differences are not just in the white-space, but also with things like naming of functions and variables, naming of macros, whether to use braces for single line statements after if, etc...

I think it would help a lot towards a more readable and maintainable codebase to set something, anything, as soon as possible, publish it and apply those rules to new code.

Even just a few rules would go a long way. I don't have a strong preference, but personally I like:

- Macros always UPPER_CASE_AND_SEPARATED_BY_UNDERSCORES
- Function names always lower case, words separated by underscores
- Variable names always lower case, words separated by underscores
- Every block after an if, else, while or for should be enclosed in braces (but single `continue` or `break` statements are allowed)
- Every function, even static ones, should have a short comment explaining it's purpose
- Every non-static function should be documented with purpose, params and return value
- (From the discussion about unsigned int) Use plain `int` for numbers, even if that number should only ever be positive.

What do you think?

**Comment by derselbst** [comment]
Good idea. For the whitespace part `clang-format` should take care of.

Let me add:

* **Allman Style** Braces everywhere (`clang-format`)

> Every block after an if, else, while or for should be enclosed in braces (but single continue or break statements are allowed)

Agreed. `clang-tidy` can do this job. The last part (continue and break statement) however might be tricky for `clang-tidy`, so I wouldnt mind also placing them in a scope. 

> Every function, even static ones, should have a short comment explaining it's purpose

With an emphasis on **should** (not must). Else this might result in comments with only little to non informative content.

> Every non-static function should be documented with purpose, params and return value

Would not go that far: Every public API function must be doced with purpose, params and return value.
> Use plain int for numbers, even if that number should only ever be positive.

Prefer `int` to `unsigned int`. Use a narrowed type for a struct member declaration if adequate. (e.g. iterating over an array using `FLUID_N_ELEMENTS` better use an `unsigned int`)
