### ISSUE TITLE
How to modify envelope values(such as attack,release..)?

### ISSUE THREAD

**Issue by LynnShyu** [FluidSynth/fluidsynth#270]
How to modify envelope values(such as attack,release..) of each instrument?

Thanks!

**Comment by derselbst** [comment]
This is no support forum. Learn about Soundfonts and about how to use Soundfont Editors.

**Comment by LynnShyu** [comment]
It's not about soundfont editor, I want to control those envelope values in my code. Just like , fluid_set_volenv_attack(fluid_synth_handle, double attack_value)

**Comment by mawe42** [comment]
Please use the fluid-dev mailing list for these kinds of questions. You will reach many more people that way as well.
