### ISSUE TITLE
Remove src/unused directory

### ISSUE THREAD

**Issue by mawe42** [FluidSynth/fluidsynth#272]
Is there any reason why we should keep the contents of the "unused" directory? As far as I can see, it really is unused, as the name suggests.

It does trip me up sometimes, when I'm looking where a particular variable or function is used and I stumble across weird code, only to later notice that I'm in "unused" again...

**Comment by derselbst** [comment]
I'm absolutely with you. Fixed in f2c4cfb6b62bccfe6f98ac362c1d30658b173aee and 4571d996b3071030325efc37670c9646acfc1ac4.

**Comment by mawe42** [comment]
Great, thanks!
