### ISSUE TITLE
How can I modify voice parameter values (envelope attack..., filter cutoff...) in my code?(Not in SoundFont editor)

### ISSUE THREAD

**Issue by LynnShyu** [FluidSynth/fluidsynth#273]
How can I modify voice parameter values, such as envelope attack、release、filter cutoff、lfo......IN MY CODE?(Not in SoundFont editor)

**Comment by derselbst** [comment]
This is still no support forum. Have you even read the issue template?

> Please do not submit support requests or "How to" questions here. Instead, please use FluidSynth's
mailing list: https://lists.nongnu.org/mailman/listinfo/fluid-dev
