### ISSUE TITLE
CI for Windows using Appveyor

### ISSUE THREAD

**Issue by mawe42** [FluidSynth/fluidsynth#276]
[appveyor.yml.txt](https://github.com/FluidSynth/fluidsynth/files/1465206/appveyor.yml.txt)
As Travis doesn't support Windows builds at the moment, I've created a config file for Appveyor, which is basically Travis for Windows. The attached file builds FluidSynth for x64 and x86, bundles the created files into a zip file and stores them it a build artifact. 

I've tested this on the av-test branch in my repo. Seems to work fine, and the "artifacts" from the build (i.e. the zip file) can even be pushed as a GitHub release automatically (could configure this to only do this when it's building a tag). Overall it seems like a very nice system to use, I think.

To use this, put the attached file as .appveyor.yml in the repo root (and remove the branches: only: av-test config), create an account on Appveyor for FluidSynth and create a GitHub project.

Theres also a badge that we can add to the project homepage, just like with Travis.

**Comment by derselbst** [comment]
Oh, nice work. I still dont like publishing binaries, but perhaps I will
just do it now that we could cover Windows, Linux and MacOSx in a fully
automated way.

**Comment by mawe42** [comment]
Publishing binaries is just a side-effect that might be nice, especially for Windows users. But what I think is really important is to have CI for Windows. Especially as most developers that are currently actively contributing seem to be Linux/Unix only.

**Comment by derselbst** [comment]
Automated build setup and works fine. Will keep this open until I looked into that deployment mechanism. But why should I create a github project?

**Comment by mawe42** [comment]
Great! And sorry about the confusion: with github project I meant "adding the fluidsynth repo" to your appveyor account.

**Comment by jjceresa** [comment]
> As Travis doesn't support Windows builds at the moment, I've created a config file for Appveyor, which is basically Travis for Windows.

Nice work ! . Does it mean that perhaps it should be possible  to have an automatic build with report (as is it actually the case for Linux and MacOs) when a new commit is freshly pushed on fluidsynth repository ?.

**Comment by derselbst** [comment]
@jjceresa Seems like you didnt hat a recent look at our [README](https://github.com/FluidSynth/fluidsynth/blob/master/README.md) ;)

**Comment by jjceresa** [comment]
@derselbst 
> Seems like you didnt had a recent look at our README ;)> Seems like you didnt had a recent look at our README ;)

Oh thanks. So the answer to my question is:` "Yes, but for master branch only "`.
Did you know if a github notification way exist ? (when for example a documentation page (i.e readme) has been updated) ?

**Comment by derselbst** [comment]
Actually it works for every branch, but it seems it just displays the build for the most recent commit, which is master currently. To view it for other branches you will have to go the way via the commit history.

> Did you know if a github notification way exist ? (when for example a documentation page (i.e readme) has been updated) ?

I dont think it's possible to watch specific files, but we have a dashboard: https://github.com/orgs/FluidSynth/dashboard

**Comment by mawe42** [comment]
> Did you know if a github notification way exist ? (when for example a documentation page (i.e readme) has been updated) ?

You could subscribe to the RSS feed of a particular branch. For the master branch the feed URL is:
https://github.com/FluidSynth/fluidsynth/commits/master.atom

Although that doesn't give you notifications for specific files, just for the whole branch.

**Comment by jjceresa** [comment]
Oh thanks, this will be useful.

**Comment by derselbst** [comment]
Regarding binary publishing we currently have:

* appveyor for windows x86 and x64 builds
* travis for linux x64
* travis for macosx x64

Is that enough? One could think about expanding the linux build to even more architectures and distributions by using [openBuildService](http://openbuildservice.org/) which would look like this: https://software.opensuse.org/download.html?project=home%3Aderselbst%3Aanmp&package=fluidsynth

I dont think it would be too useful for linux users as they would use their own distro packages anyway.

**Comment by mawe42** [comment]
I think it would be best to keep the binary publishing to the absolute minimum and only solve the problem that comes up the most: building FluidSynth on Windows. Linux distributions integrate FluidSynth (granted, not always the latest version...), and for OSX there seems to be a homebrew package. So it should be as simple as "brew install fluidsynth".

But I guess if using the OBS is easy and painless, why not. What's your experience with using OBS for anmp?

**Comment by derselbst** [comment]
OBS is actually quite nice. As usual you can setup a webhook that triggers a build on every push. Building for openSUSE is easy, for RPM-based distros in general you'll need to use pkg-config due to different package naming conventions across distros. Building for DEB or PKGBUILD based distros however requires additional build files, which means increased maintenance effort for me, not sure how long I could bear this up :/

So for promoting such an unknown piece of software like ANMP it is quite nice to just being able to download prebuilt packages for your distro. But for an established software like fluidsynth it might be just an overkill.

**Comment by mawe42** [comment]
> Building for DEB or PKGBUILD based distros however requires additional build files, which means increased maintenance effort for me, not sure how long I could bear this up :/

And as a lot of people are using Ubuntu these days, I guess building for RPM-based distros only will mean daily "Please provide Ubuntu packages" issues here on GitHub. So my feeling is: better leave it to the distros.

**Comment by derselbst** [comment]
I've added a separate appveyor script that uses vcpkg (based on ff411b9f99a562a2decd83323ef51bc784d512b2) so we have a CI build against old glib (<2.30) and new glib (>= 2.30) on windows. I'd close this ticket then. If we ever switch appveyor to msys2, this can be done separately.

**Comment by mawe42** [comment]
Sounds good!
