### ISSUE TITLE
Microtuning support

### ISSUE THREAD

**Issue by suhr** [FluidSynth/fluidsynth#278]
Like in [One-SF2](http://xen-arts.net/one-sf2-stereo-soundfont-vsti/).

See [AnaMark tuning file format](http://www.mark-henning.de/files/am/Tuning_File_V2_Doc.pdf).

**Comment by derselbst** [comment]
You have used too few words, I can only guess what you want: Fluidsynth
supports the Midi Tuning Standard, see all those tuning functions in the
synth API:
http://www.fluidsynth.org/api/synth_8h.html#a82eea41553b546ec063c2dc840ca711d

**Comment by suhr** [comment]
So frontends use fluidsynth as a library, not as a server? I see.

> Fluidsynth supports the Midi Tuning Standard

Does that mean I can send MTS messages over MIDI to tune the synth?

**Comment by derselbst** [comment]
> Does that mean I can send MTS messages over MIDI to tune the synth?

Looks pretty much like you can:
https://github.com/FluidSynth/fluidsynth/blob/987aa33486f654b3f36dd4c195a78f602864a3a4/src/synth/fluid_synth.c#L1292-L1300

**Comment by suhr** [comment]
Amazing. I believe this should be documented somewhere.

**Comment by derselbst** [comment]
It's on the todo list: https://github.com/FluidSynth/fluidsynth/blob/08ba48712de107beaa8b32ddf2286e3b6bb62f97/TODO#L41

The [API doc](https://github.com/FluidSynth/fluidsynth/blob/master/doc/fluidsynth-v11-devdoc.txt) would be a suitable place. However I have neither experience with MTS nor a use-case for it.

**Comment by suhr** [comment]
I definitely have a use case for MTS, but I don't have a tool to send MTS messages. I'll write one and try to tune fluidsynth into 31edo.

**Comment by derselbst** [comment]
Ok, good luck. Closing this for now.

**Comment by suhr** [comment]
It doesn't seem do to anything. Following http://www.hermode.com/downloads/Apple_Logic_Tuning_Data.pdf and http://www.microtonal-synthesis.com/MIDItuning.html, I send SINGLE NOTE TUNING CHANGE and then TUNING PROGRAM CHANGE

```
fn run()  {
    let midi_out = MidiOutput::new("MTS Output").unwrap();

    let mut conn_out = midi_out.connect(0, "mts-out").unwrap();

    let mut bytes = vec![0xf0, 0x7f, 0x7f, 0, 127];
    for (i, v) in (0..128u8).map(|i| 36.77 + (12.0 / 31.0) * i as f32).enumerate() {
        let int = v.round();
        let msb = (int * 128.0).round();
        let lsb = (msb * 128.0).round();

        bytes.push(i as u8);
        bytes.push(int as u8);
        bytes.push(msb as u8);
        bytes.push(lsb as u8);
    };

    bytes.push(0xf7);

    drop(conn_out.send(&bytes));

    drop(conn_out.send(&[0xb0, 0x64, 0, 0x65, 0x03, 0x06, 0]));

    conn_out.close();
}
```

QSynth (a fluidsynth frontend) receives the message, but the tuning doesn't change.

**Comment by derselbst** [comment]
Please discuss that "HowTo" on the mailing list, I cant give useful support. An make sure you use 1.1.8, 1.1.6 is outdated and unsupported.
