### ISSUE TITLE
Using Portaudio and audio.portaudio.device setting

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#284]
It could be interesting for the user of an application to select the `audio card` to be use by a instance of FluidSynth `audio driver`. 

- a)For example when the application run on a machine with `multiple i/o audio cards`, the application can run multiple `synth instance` each connected to `separate i/o cards` when needed.

- b)Another example is to be able to benefit of the available `latency `on a specific `OS host audio driver`.
For example, with audio driver `alsa` (for linux OS), a FluidSynth application can benefit of the low latency of pretty any audio cards.
On Windows OS actually `dsound `is the only FluidSynth audio driver available (not low latency). Anyway on Windows, there are host audio native driver (`WDMKS`) allowing low latency, and `ASIO `too.

Actually `FluidSynth PortAudio driver` seems to be the only candidate to do jobs` (a) and (b) `regardless of the OS. So, i wonder if it could be possible to rely on `audio.portaudio.device` to select one device other than the `default device` ?.

**Comment by derselbst** [comment]
> So, i wonder if it could be possible to rely on audio.portaudio.device to select one device other than the default device ?

Dont quite know what you mean. On every call to `new_fluid_settings()` portaudio looks through available soundcard devices and appends them to the option list for that setting:
https://github.com/FluidSynth/fluidsynth/blob/c0cd1887db17b5d31aa07fe27814480850ae89ac/src/drivers/fluid_portaudio.c#L92-L98

So what you're describing should already be possible.

**Comment by jjceresa** [comment]
Interesting. Effectively, in FluidSynth the user  should be able to choose the device via its name.
The user needs only to know the names and capabilities of the devices presents on the machine. This could done by the application using portaudio API.
Sometimes i forget all these good things FluidSynth is capable !. Many thanks for the information.

**Comment by derselbst** [comment]
The user can iterate over all available options of that setting using `fluid_settings_foreach_option()`. That way he would get the available devices.

**Comment by jjceresa** [comment]
> So no need to use portaudio API directly.

Many thanks. Good thing, this could make the application more simpler using only FluidSynth API.

However, i have noticed that distinct `portaudio device` have the same `name` (if i am not wrong). In portaudio each `device` is uniquely identified by its `index`. Each unique `index `represent a couple `(host api,host device)`.I think that the `name `forwarded by portaudio (using `Pa_GetDeviceInfo()` ) comes from the native `host device driver`. So at the end, the using `fluid_settings_foreach_option()` could make the user unable to choose the device.
Anyway, i need time to verify if distinct `device index` have really the same `name`.

**Comment by jjceresa** [comment]
Effectivelly, actually in `portaudio driver` different `device index` have the same `name`. This is verifiable using the command `>info audio.portaudio.device`.
1)
```
> info audio.portaudio.device
audio.portaudio.device:
Type:          string
Value:         Speakers 1 (SB Live! Audio [CE00])
Default value: PortAudio Default
Options:       Mappeur de sons Microsoft - Output, PortAudio Default, PÚriphÚrique audio
 principal, SB Live! Audio [CE00], SB Live! Audio [CE00], SB PCI, SB PCI, Speakers 1 (SB Live! Audio [CE00]), Speakers 1 (SB PCI), Speakers 2 (SB Live! Audio [CE00]), Speakers 2 (SB PCI)
Real-time:     no
```
We can see `SB Live! Audio [CE00] `and `SB PCI` boths 2 times. This isn't not a bug, each device is really accessed via a different `host API`. Simply the actual naming is not sufficient.

So using only of the `host device name `to identify the device to work with is not sufficient. And the driver is actually unable to selected the intended driver chosen by the user.

I can propose a PR with a `naming format` so that the portaudio device name (designed by `audio.portaudio.device` setting) will be unique for all available devices. This is not difficult to do and involve simple modifications in `new_fluid_portaudio_driver()` and `new_fluid_portaudio_driver()`.

Here, this works fine now like this:
2)
```
> info audio.portaudio.device
audio.portaudio.device:
Type:          string
Value:         17:Windows WDM-KS:Speakers 1 (SB Live! Audio [CE00])
Default value: PortAudio Default
Options:       10:Windows DirectSound:SB Live! Audio [CE00], 11:Windows DirectSound:SB P
CI, 17:Windows WDM-KS:Speakers 1 (SB Live! Audio [CE00]), 18:Windows WDM-KS:Speakers 2 (
SB Live! Audio [CE00]), 23:Windows WDM-KS:Speakers 1 (SB PCI), 24:Windows WDM-KS:Speaker
s 2 (SB PCI), 3:MME:Mappeur de sons Microsoft - Output, 4:MME:SB Live! Audio [CE00], 5:M
ME:SB PCI, 9:Windows DirectSound:PÚriphÚrique audio principal, PortAudio Default
Real-time:     no
```
As an example, the 2 previous old name `SB PCI` and `SB PCI` (displayed by command (1)) are now respectively `5:MME:SB PCI`   and `11:Windows DirectSound:SB PCI` (displayed by command (2)).

`5`: is the `portaudio device index`.
`MME`: is the `host API name`.
`SB PCI`: is the `host device name`.

**Comment by derselbst** [comment]
Ok sure, sounds viable.
