### ISSUE TITLE
Pulseaudio defaults to high latency, and option to change it is somewhat misleading

### ISSUE THREAD

**Issue by jarmar** [FluidSynth/fluidsynth#303]
### FluidSynth version 
1.1.6

### Current behavior

The default behaviour when using the Pulseaudio driver is high latency (on my system 100 ms), and it can only be adjusted by turning the `audio.pulseaudio.adjust-latency` setting off. As long as this setting is on, PulseAudio ignores the configured buffer length and selects its own maximum buffer size available.

### Expected behavior

Since the other drivers default to low-latency playback, the PulseAudio driver should do so as well.

### Other information

The description in the FluidSynth documentation of the `audio.pulseaudio.adjust-latency` is:

> If TRUE increases the latency dynamically if PulseAudio suggests so. Else uses a buffer with length of "audio.period-size". 

However, what the option actually does is set `bufattr.maxlength = -1`. According to the [PulseAudio documentation](https://freedesktop.org/software/pulseaudio/doxygen/structpa__buffer__attr.html):

> Setting this to (uint32_t) -1 will initialize this to the maximum value supported by server, which is recommended.

While this might be a good default if it is desirable to use low CPU by default, it should be more clearly documented and referenced. However, with the default buffer size being 64, it seems to me that this setting should be off by default.

**Comment by derselbst** [comment]
I dont think it's a good idea to have every audio driver default to low latency. As you already said, not everyone has a "powerful" CPU. And if you can achieve the desired behaviour just by switching off `audio.pulseaudio.adjust-latency` I dont see a necessity to change the default latency setting for pulseaudio and possibly break playback for some other users.

However I agree that the documentation is not clear. It was probably meant to set the `PA_STREAM_ADJUST_LATENCY` flag. I will look into that.

**Comment by derselbst** [comment]
`pa_simple_new()` always specifies the `PA_STREAM_ADJUST_LATENCY` flag when creating the playback stream. Also note that `pa_buffer_attr::maxlength` only specifies the maximum length of the audio buffer. `pa_buffer_attr::tlength` sets the target length of the buffer and this is always initialized to the value of "audio.period-size". Why your pulseaudio server still defaults to high latency I cant tell. Anyway I've updated the docs, it should now be clearer.
