### ISSUE TITLE
compile error on 

### ISSUE THREAD

**Issue by FlyingFishBird** [FluidSynth/fluidsynth#305]
### FluidSynth version 
2.0.0

### Current behavior
Compile failed on osx

### Steps to reproduce
```bash
mkdir build
cmake ..
make
```
And build failed.

### Other information
```bash
src/drivers/fluid_coremidi.c:177:3: error: void function 'delete_fluid_coremidi_driver' should not return a value
```
```delete_fluid_coremidi_driver()``` return 0 at the last line of this function.
It should return none.

**Comment by derselbst** [comment]
Ok, thanks!
