### ISSUE TITLE
Explicit cast to avoid warning

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#310]
This suggest an explicit cast to avoid warnings:
https://github.com/FluidSynth/fluidsynth/blob/bf5dbc60cf1e2f0fbd566fdd9fb0c22a3cd7fea8/src/midi/fluid_seqbind.c#L283
		fluid_event_noteoff(&evt, chan, `(short)`fluid_midi_event_get_key(event));
***
https://github.com/FluidSynth/fluidsynth/blob/bf5dbc60cf1e2f0fbd566fdd9fb0c22a3cd7fea8/src/midi/fluid_seqbind.c#L287
                  ` (short)` fluid_midi_event_get_key(event), `(short)`fluid_midi_event_get_velocity(event));	
***
https://github.com/FluidSynth/fluidsynth/blob/bf5dbc60cf1e2f0fbd566fdd9fb0c22a3cd7fea8/src/midi/fluid_seqbind.c#L290-L291
		fluid_event_control_change(&evt, chan, `(short)` fluid_midi_event_get_control(event),
								`(short)`  fluid_midi_event_get_value(event));
***
https://github.com/FluidSynth/fluidsynth/blob/bf5dbc60cf1e2f0fbd566fdd9fb0c22a3cd7fea8/src/midi/fluid_seqbind.c#L294
		fluid_event_program_change(&evt, chan, `(short)` fluid_midi_event_get_program(event));
***
https://github.com/FluidSynth/fluidsynth/blob/bf5dbc60cf1e2f0fbd566fdd9fb0c22a3cd7fea8/src/midi/fluid_seqbind.c#L300
		fluid_event_channel_pressure(&evt, chan, `(short)`fluid_midi_event_get_program(event));
***
https://github.com/FluidSynth/fluidsynth/blob/bf5dbc60cf1e2f0fbd566fdd9fb0c22a3cd7fea8/src/midi/fluid_seqbind.c#L303-L305
		fluid_event_key_pressure(&evt, chan,
					 `(short)`fluid_midi_event_get_key(event),
					 `(short)`fluid_midi_event_get_value(event));

**Comment by jjceresa** [comment]
Sorry there is a missing cast.
https://github.com/FluidSynth/fluidsynth/blob/bf5dbc60cf1e2f0fbd566fdd9fb0c22a3cd7fea8/src/midi/fluid_seqbind.c#L303-L305
		fluid_event_key_pressure(&evt, chan,
					 `(short)`fluid_midi_event_get_key(event),
					 `(short)`fluid_midi_event_get_value(event));

**Comment by derselbst** [comment]
It's there, you were refering to the outdated revision, here's the new one:

https://github.com/FluidSynth/fluidsynth/blob/4203e102207a789565c6b3ed46acb8be104878cd/src/midi/fluid_seqbind.c#L303-L305
