### ISSUE TITLE
Source Code Vs Build Directory

### ISSUE THREAD

**Issue by jaddytucson** [FluidSynth/fluidsynth#313]
Hello, 

I am having trouble with the instructions for the CMake installation. I like that they are descriptive and somewhat informative but am not sure if the procedure in the wiki is correct, as the cmake options do not seem to point the compiler in direction of the source code, when calling cmake from the build directory. 

 Would it be better to move to the source tree and set an installation target? I am doing the opposite (as instructed) but am unable to move about thoroughly. See code ( inside building_directory$):

`cmake` -DCMAKE_INSTALL_PREFIX=/usr/local/src/fluidsynth-1.1.6/fluidsynth -Denable-ladspa=1

	CMake Error: The source directory "/usr/local/src/fluidsynth-1.1.6/build" does not appear to contain CMakeLists.txt.
	Specify --help for usage, or press the help button on the CMake GUI.

`cmake` .. -DCMAKE_SOURCE_DIR=/usr/local/src/fluidsynth-1.1.6/fluidsynth -Denable-ladspa=1

	CMake Error: The source directory "/usr/local/src/fluidsynth-1.1.6" does not appear to contain CMakeLists.txt.
	Specify --help for usage, or press the help button on the CMake GUI.

`cmake` .. -DCMAKE_SOURCE_DIR=[/usr/local/src/fluidsynth-1.1.6/fluidsynth] -Denable-ladspa=1

	CMake Error: The source directory "/usr/local/src/fluidsynth-1.1.6" does not appear to contain CMakeLists.txt.
	Specify --help for usage, or press the help button on the CMake GUI.

`cmake` .. -DPROJECT_SOURCE_DIR= [/usr/local/src/fluidsynth-1.1.6/fluidsynth] -Denable-ladspa=1

	CMake Error: The source directory "/usr/local/src/fluidsynth-1.1.6/build/[/usr/local/src/fluidsynth-1.1.6/fluidsynth]" does not exist.
	Specify --help for usage, or press the help button on the CMake GUI.

`cmake` -DCMAKE_INSTALL_PREFIX=[/usr/local/src/fluidsynth-1.1.6/fluidsynth] -Denable-ladspa=1

	CMake Error: The source directory "/usr/local/src/fluidsynth-1.1.6/build" does not appear to contain CMakeLists.txt.
	Specify --help for usage, or press the help button on the CMake GUI.

Note that "/fluidsynth," is the source tree where I extracted the download. Please let me know if I'm posting this in the wrong place, as well. I can be opportunistic but try to stay informed. Thanks again. Happy holidays...

**Comment by derselbst** [comment]
Usually it's better to post support requests to our mailing list. Anyway,
the correct usage of cmake is:

cmake [options] <path-to-source>

In your case:

cmake -Denable-ladspa=1 /usr/local/src/fluidsynth-1.1.6/fluidsynth

should work.

**Comment by jaddytucson** [comment]
you gave some good pointers and i found an interesting article on the issue, which may lead to an answer. it describes my scenario perfectly. 
http://cprieto.com/posts/2016/10/cmake-out-of-source-build.html

**Comment by derselbst** [comment]
Ok, I actually think I gave you the correct answer for out-of-source builds. It allows you to build whatever cmake project from whatever directory you are currently in and also to install it from there. To me it makes no sense to perform oos builds from the CMakeLists.txt. It's up to the user to decide from where to build a project.

Therefore I'm closing this.
