### ISSUE TITLE
True zero gain for maximum attenuation

### ISSUE THREAD

**Issue by mawe42** [FluidSynth/fluidsynth#319]
During the discussion on #317 about which range to use for the new balance control, we also discussed the fact that FluidSynth currently doesn't make channels completely silent when attenuation is at maximum. Looking through the Sound Font 2.04 specs, we found the following paragraph:

>  The volume envelope operates in dB, with the attack peak providing a full scale output, appropriately scaled by the initial volume. The zero value, however, is actually zero gain. The implementation in the EMU8000 provides for 96 dB of amplitude control. When 96 dB of attenuation is reached in the final gain amplifier, an abrupt jump to zero gain (infinite dB of attenuation) occurs. In a 16-bit system, this jump is inaudible.

So, to be true to the EMU8k hardware, we should probably do something like the following in our "final gain amplifier" (which I think is effectively fluid_rvoice_buffers_mix):
```diff
 fluid_rvoice_buffers_mix(fluid_rvoice_buffers_t* buffers, 
                          fluid_real_t* dsp_buf, int samplecount, 
                          fluid_real_t** dest_bufs, int dest_bufcount)
 {
+  const fluid_real_t MIN_GAIN = pow(10.0, (double) 960.0 / -200.0);
   int bufcount = buffers->count;
   int i, dsp_i;
   if (!samplecount || !bufcount || !dest_bufcount) 
     return;
 
   for (i=0; i < bufcount; i++) {
     fluid_real_t* buf = get_dest_buf(buffers, i, dest_bufs, dest_bufcount);
     fluid_real_t* next_buf;
     fluid_real_t amp = buffers->bufs[i].amp;
-    if (buf == NULL || amp == 0.0f)
+    if (buf == NULL || amp <= MIN_GAIN)
       continue;
 
     /* Optimization for centered stereo samples - we can save one 
        multiplication per sample */
     next_buf = (i+1 >= bufcount ? NULL : get_dest_buf(buffers, i+1, dest_bufs, dest_bufcount));
     if (next_buf && buffers->bufs[i+1].amp == amp) {
       for (dsp_i = 0; dsp_i < samplecount; dsp_i++) {
         fluid_real_t samp = amp * dsp_buf[dsp_i]; 
         buf[dsp_i] += samp;
         next_buf[dsp_i] += samp;
       }
       i++;
     }
     else {
       for (dsp_i = 0; dsp_i < samplecount; dsp_i++)
         buf[dsp_i] += amp * dsp_buf[dsp_i];
     }
   }
 }
```

But like the paragraph explains, that is only an inaudible jump on 16-bit systems. We have support for 24-bit samples and also provide >= 24-bit outputs. So I'm a little unsure on how to resolve this. I would really like to be able to switch off channels completely. It will benefit performance, but also make channel separation more exact. But the hardcoded 96 dB threshold seems to be wrong for > 16 bit.

Should fluid_rvoice_buffers_mix maybe use a different threshold for 16 bits (96 dB) and >= 24 bits (144 dB) output? It would be really great if somebody with access to emu8k and emu10k hardware could experiment with this. Is the 10k1 or 10k2 even capable of rendering 24-bit samples? And where does it make the jump to infinite attenuation? 

@mrbumpy409 Sorry to bother you again, but you seem to have a great wealth of knowledge about the EMU hardware. Could you maybe give us your opinion on this subject?

**Comment by mrbumpy409** [comment]
On 01/06/2018 07:22 AM, Marcus Weseloh wrote:

Should fluid_rvoice_buffers_mix maybe use a different threshold for 16 bits (96 dB) and >= 24 bits (144 dB) output? It would be really great if somebody with access to emu8k and emu10k hardware could experiment with this. Is the 10k1 or 10k2 even capable of rendering 24-bit samples? And where does it make the jump to infinite attenuation?

@mrbumpy409<https://github.com/mrbumpy409> Sorry to bother you again, but you seem to have a great wealth of knowledge about the EMU hardware. Could you maybe give us your opinion on this subject?

I guess I need to know more about what you would be doing under-the-hood. For example, I can set an instrument's velocity-to-attenuation modulator to a range of 144 dB in the SoundFont, but then this would greatly exaggerate the difference between piano and forte on that instrument. We do not want to alter the dynamic range for things like envelopes and modulators.

One solution would be to add a brief fade-out phase once an envelope hits -96 dB that smoothly pulls the sound from -96 dB down to -144 dB. This way the actual dynamic curves wouldn't be affected.

-~Chris

**Comment by mawe42** [comment]
> I guess I need to know more about what you would be doing under-the-hood.

The aim would be to implement this "96 dB attenuation = zero gain" just for the final gain stage of the voice, as specified in the Sound Font 2.04 document. So only after all modulators, envelopes and initial values that affect the amplification of the sound are taken into account, just before writing the samples to the output buffer. At least that is what I understand is meant by "final gain stage".

> One solution would be to add a brief fade-out phase once an envelope hits -96 dB that smoothly pulls the sound from -96 dB down to -144 dB. This way the actual dynamic curves wouldn't be affected.

Yes, good idea. And something like that is already implemented in another part of the amplification calculation. 

But what is tripping me up is this "In a 16-bit system, this jump is inaudible." comment. Do you know if this  cutoff only applies to the emu8k? Is the emu10k capable of 24 bit output?

**Comment by mrbumpy409** [comment]
On 01/08/2018 04:14 PM, Marcus Weseloh wrote:

But what is tripping me up is this "In a 16-bit system, this jump is inaudible." comment. Do you know if this cutoff only applies to the emu8k? Is the emu10k capable of 24 bit output?

Both the EMU10K and original EMU10K2 (Audigy) were fixed internally at 16-bit 48 KHz, but the later revision of the EMU10K2 used in the Audigy 2 could handle 24-bit audio. More info here<https://en.wikipedia.org/wiki/Sound_Blaster_Audigy>.

Honestly, the "jump" at the bottom of the -96 dB curve is probably inaudible even at 24-bits, unless you have the audio level set really high for some reason. In any type of real-world music scenario, it would never be noticed.

-~Chris

**Comment by derselbst** [comment]
Now that fluidsynth supports 24 bit samples, any 16 bit sample is always promoted to a 24 bit sample making fluidsynth a 24 bit system. But I don't think it matters, the spec is absolutely clear that a "jump to zero gain [happens when 96 dB of attenuation is reached]". There is no 16 / 24 bit dependency here.

Ofc, we could also use 144 dB:

`const fluid_real_t MIN_GAIN = pow(10.0, (double) 1440.0 / -200.0);`

**Comment by mawe42** [comment]
@derselbst While looking through the issue list I found this again. I wonder if we should simply close it. After all, it doesn't seem like a real-world problem anybody (including me) is bothered about. What you think?

**Comment by derselbst** [comment]
Ok for me. The spec is quite vague about it, esp. for 24bit synths and how to deal with panning.
