### ISSUE TITLE
More than 16 midi input channels does not work

### ISSUE THREAD

**Issue by mqnc** [FluidSynth/fluidsynth#326]
Here is what I've tried:

`fluidsynth -i -f fluidsynthcfg.tmp -m jack -a jack -r 44100 -R 0 -C 0 -g 2.0 -s -G 32 -o shell.port=9800 -o midi.jack.id='fluidsynth' -o audio.jack.id='fluidsynth' -o synth.midi-bank-select='mma' -o audio.jack.multi='yes' -o synth.audio-channels=32 -o synth.audio-groups=32 -o synth.midi-channels=32`

and the documentation says:

> synth.midi-channels
> 
> Integer. [min=16, max=256]. This setting defines the number of MIDI channels of the synthesizer. The MIDI standard defines 16 channels, so most hardware keyboards are limited to 16. If you plan to use the synthesizer as a plugin in an application, it might be interesting to set the number of channels to a larger value. In this case you can program a greater number of presets. One MIDI port is created for every 16 channels. Default value: 16.

However, in Qjackctl under connections, MIDI-tab, if I unfold the fluidsynth entry, I only see one port named "midi".
I don't know if it works with alsa midi as I didn't compile with alsa midi support.

**Comment by mawe42** [comment]
From lookit at the source it seems like the `synth.midi-channels` option is currently only implemented in the alsa driver.

**Comment by mqnc** [comment]
Will making this available in jack be a larger project? Should I switch to alsa?

**Comment by mawe42** [comment]
The quickest option would be to switch to alsa for MIDI. You can still use the multi-channel audio for jack.

I think it would be fairly easy to add support for > 16 midi channels to the jack driver. But it's still work that someone has to do... :-) Would you be willing to create a pull-request?

**Comment by mqnc** [comment]
It would take forever for me to get familiar with the code... I'd consider it if I had a complicated feature request that nobody else cares about but I with this here I think it's better if somebody who is already familiar with the code invests 10 minutes.

But I'm also ok using alsa ;)

Or maybe I find the time in the future. I'm using fluidsynth a lot and I really love it and I've tortured you guys enough with my issues :P I guess I should contribute at some point.

**Comment by derselbst** [comment]
Confirmed. Looks indeed more like a not yet implemented feature. Should be pretty trivially fixable, will look into it, but yet cant tell when.

**Comment by derselbst** [comment]
Implemented for branches `master` and `1.1.x`. Not yet tested, feel free to do so.
