### ISSUE TITLE
synth.default-soundfont returns incomplete path

### ISSUE THREAD

**Issue by stsp** [FluidSynth/fluidsynth#332]
`fluid_settings_getstr(settings, "synth.default-soundfont", &sfont);`
returns `share/soundfonts/default.sf2`.

And indeed, `DefaultDirs.cmake` has this:
`set (DEFAULT_SOUNDFONT "share/soundfonts/default.sf2" CACHE STRING`

The installation prefix is forgotten.

**Comment by stsp** [comment]
```$ rpm -q fluidsynth
fluidsynth-1.1.9-1.fc27.x86_64```

1.1.9 from fedora-27 repos.

**Comment by derselbst** [comment]
Yes, after digging in the mailing list this option was indeed intended to be `/usr/share/soundfonts/default.sf2` but none of the DefaultDir variables has it's `CMAKE_INSTALL_PREFIX` set... strange.

**Comment by derselbst** [comment]
Looking at this again, I see no reason not to append `CMAKE_INSTALL_PREFIX` to `DEFAULT_SOUNDFONT`. Applied for master and 1.1.x, feel free to test.

**Comment by stsp** [comment]
Wow! It seems you really reverted make fluid_midi_parser_parse() public!
No more testing or bug reports, thank you very much.
