### ISSUE TITLE
VCPKG package?

### ISSUE THREAD

**Issue by stekyne** [FluidSynth/fluidsynth#333]
I noticed you were using VCPKG to get some dependencies. Any thoughts on adding fluidsynth to VCPKG altogether? It would be handy for all Windows users I'd imagine.

Thanks

**Comment by derselbst** [comment]
> Any thoughts on adding fluidsynth to VCPKG altogether?

I'm open to add a minimalist build of fluidsynth (i.e. no libsndfile, no portaudio, no readline, etc.) to vcpkg. However as Linux user I have no means to test it. Could you draft a `fluidsynth.cmake`?

**Comment by stekyne** [comment]
By fluidsynth.cmake, do you mean the config file for VCPKG or something else?

**Comment by derselbst** [comment]
The vcpkg config file.

**Comment by stekyne** [comment]
Nearly finished this.  Just wondering if it's possible to build Fluidsynth statically (easily) as that's one of the build options in VCPKG?

**Comment by derselbst** [comment]
Great! Do you mean something like

```
cmake -DBUILD_SHARED_LIBS=0 ..
```

**Comment by stekyne** [comment]
That is being set by VCPKG actually. The problem was something else. There is just an issue of the libs being put in a folder named "lib64" instead of "lib". Once that's solved it will be good to go.

**Comment by derselbst** [comment]
There is a `LIB_SUFFIX` var in fluidsynth's CMake file, might this be responsible for it?

https://github.com/FluidSynth/fluidsynth/blob/9cd870ea7a06ae049590b9bb539ef3864e057f34/CMakeLists.txt#L94-L103

This has already been disabled for mingw in #281, if it helps I wouldnt mind disabling this also for MSVC or WIN32 resp.

**Comment by stekyne** [comment]
Closed with #339

**Comment by ollpu** [comment]
The wiki says that the package is available via VCPKG now, but I can't find it (at least using Microsoft's repository). Is someone going to add it upstream?

**Comment by derselbst** [comment]
The wiki refers to 1.1.10, which has not been released yet. Please be patient.

**Comment by ollpu** [comment]
Ah, I see. Thanks!

**Comment by stekyne** [comment]
https://github.com/Microsoft/vcpkg/pull/3016 

I've opened the PR here. Sorry for the delay.

**Comment by stekyne** [comment]
This has now been pulled into VCPKG now so should be available.
