### ISSUE TITLE
Is it possible that 1.1.7 was re-released by accident?

### ISSUE THREAD

**Issue by schnitzeltony** [FluidSynth/fluidsynth#340]
I could bet I've built 1.1.7 long ago...

**Comment by derselbst** [comment]
Wow, you must be watching like a hawk :)

Yes, unfortunately I forgot to mention three changes introduced with 1.1.7
long before I entered as maintainer. When clicking the Save button on the
github release it silently turned it into a draft some days ago. Yesterday
I realized this and republished the release. Dont worry, the git tag v1.1.7
wasnt changed so there is nothing new except the changelog and the
timestamp of the github release.

**Comment by schnitzeltony** [comment]
Thanks for explanation and I use 1.1.9 anyway...
