### ISSUE TITLE
Static build fails on windows

### ISSUE THREAD

**Issue by stekyne** [FluidSynth/fluidsynth#341]
### FluidSynth version 
1.1.9

### Current behaviour
From a client app, linking into the static libfluidsynth.lib fails with missing fluidsynth functions.

### Expected behavior
These methods should not be missing from the library. The client app should build successfully.

### Steps to reproduce
1. Build libfluidsynth.lib
2. Create a simple project to include fluidsynth.h and calls a few of the API functions. Link with libfluidsynth.h
3. Attempt to build the app. If fails with link errors.

Found during #339. Workaround is to define FLUIDSYNTH_API before including fluidsynth.h in the client and also while building fluidsynth.

**Comment by derselbst** [comment]
I committed a fix (I hope), please checkout the [cmake-static](https://github.com/FluidSynth/fluidsynth/tree/cmake-static) branch whether it works for you.

**Comment by stekyne** [comment]
I've built the branch and I can statically link it successfully. Cheers

**Comment by derselbst** [comment]
Great, thx for testing!
