### ISSUE TITLE
Request:  Support OSC input with playback for all frequencies.

### ISSUE THREAD

**Issue by LiamM32** [FluidSynth/fluidsynth#349]
It would be very good to have support for Open Sound Control (OSC) input to achieve functionality beyond the limitations of MIDI.  When using OSC for input, it should be able to playback notes at any frequency, not just 12-tone equal temperament (or a custom tuning with MTS, which is a pain to work with anyway).

If it requires too much of an overhaul to have polyphony without a limited number of keys, then this can be made as a fork.

**Comment by derselbst** [comment]
Please bring this topic to the mailing list for discussion. Make sure you elaborate a little more. (What are the limitations of MIDI you're referring to? Why do you need to play notes at any freq.?)

**Comment by derselbst** [comment]
As fluidsynth being a SF2 synth it is tightly bound to MIDI. Neither do I know how nor which parts to integrate of OSC into fluidsynth. And because you haven't shown any further interest in this topic, I'm closing this.
