### ISSUE TITLE
Error when building on Windows

### ISSUE THREAD

**Issue by weiwei-ww** [FluidSynth/fluidsynth#351]
I am building FluidSynth on Windows using MinGW. However, I encountered this error when building.

> C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lsndfile

Looks like I have to download the sndfile.lib somewhere. However, I am not able to find it on the Internet. Can anyone help?

**Comment by weiwei-ww** [comment]
The only lib file that I can find is 'libsndfile-1.lib' not 'sndfile.lib'. And simply renaming the file did not work.

**Comment by derselbst** [comment]
The `-lsndfile` flag means that the compiler is looking for `libsndfile.lib`. Rename it and try again. If you dont need libsndfile, disable it explicitly when calling cmake: `cmake -Denable-libsndfile=0 ..`

**Comment by jjceresa** [comment]
> Looks like I have to download the sndfile.lib somewhere. However, I am not able to find it on the Internet. Can anyone help?

You will find the necessary file (.h, .lib) on the site of `libsndfile `author (Erik de Castro Lopo):http://www.mega-nerd.com/libsndfile/#Download

> The only lib file that I can find is 'libsndfile-1.lib' not 'sndfile.lib'. And simply renaming the file did not work.

The following is relevant only if you need `libsndfile `library :
- If the original file is named `libsndfile-1.lib` the best is to keep this name.
- However cmake must tell the compiler the `name` of the library. To do that when using 
`cmake -Denable-libsndfile=1` cmake is looking for 
`Freesw/lib/pkgconfig/sndfile.pc` file (note that dir `Freesw` must be different for you).

- here in example of sndfile.pc file
```
prefix=
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: sndfile
Description: A library for reading and writing audio files
Requires: 
Version: 1.0.27
Libs: -L${libdir} -llibsndfile-1
Libs.private: Ext/libflac.la Ext/libvorbis.la Ext/libogg.la
Cflags: -I${includedir}
```
-  Edit the line (if necessary) to reference the correct name library: 
`Libs: -L${libdir} -llibsndfile-1`
- `Freesw/include`  must contain `sndfile.h` file. 
- `Freesw/lib`  must contain `libsndfile-1.lib` file.

Note: Each time `Freesw/lib/pkgconfig/sndfile.pc` is modified, cmake must be re-run before compiling.
Note that `sndfile.h` will use `stdint.h` that must be find by cmake.

**Comment by weiwei-ww** [comment]
@derselbst @jjceresa Thank you both for your help.

I tried renaming the lib file and modifying the .pc file but both approaches gave me back the same error messages as following.

> C:/freesw/lib/libsndfile-1.lib: error adding symbols: File in wrong format

It is my first time to compile and build a project from the source code so I will be grateful if you can offer me some further help.

Thanks!

**Comment by weiwei-ww** [comment]
I also tried to change to 32bit libsndfiles instead and it gave me the following error.

> C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/freesw/lib\libsndfile-1.lib when searching for -llibsndfile-1
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llibsndfile-1

**Comment by jjceresa** [comment]
Usually i use cmake + visual studio. I am not familiar with mingw cross compiler tools chain.

> C:/freesw/lib/libsndfile-1.lib: error adding symbols: File in wrong format

Sorry but this message alone without knowledge of the `tool` who produced it can't help. I suspect that it is the `linker tool` that cannot read this file. This feel like if `libsndfile-1.lib` was corrupted or a great confusion between `library format `and the `tool chain` (compiler + linker) used. 

> C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe:
 skipping incompatible C:/freesw/lib\libsndfile-1.lib when searching for -llibsndfile-1

It seems as mixing `32 bit library` linked by` 64 bit linker tool `?.

I suggest you restart from the beginning.

1. logging `all steps` your are doing.
2. logging `cmake result`.
3. logging mingw `tools chain results`.

With this results, i think that any `mingw `user could help.

**Comment by carlo-bramini** [comment]
If I can tell you my opinion, you should abandon TDM-GCC and migrate to some more recent and free stuff:
1) you can download CYGWIN bash and its included MINGW-W64 cross compiler. Many libraries are available here.
2) you can download MSYS2 and MINGW or MINGW-W64 native compilers. Many libraries are available here too.
3) you can download an old express Visual Studio or the newest Visual Studio 2017 community. It has great CMAKE integration and thanks to the VCPKG tool many thirdy party libraries are made available. See:
https://github.com/Microsoft/vcpkg

PS: why are you trying to make the build with MSVC style libraries (because the ".lib" extension) instead of using proper ".a" libraries for GCC?

**Comment by jjceresa** [comment]
Hello Carlo,

This discussion has been initiated by @weiwei-ww who is using MINGW. As i am not a mingw user
thanks for your advise and useful knowledge.

> PS: why are you trying to make the build with MSVC style libraries (because the ".lib" extension) instead of using proper ".a" libraries for GCC

As `mingw `is a cross compiler tool , i was thinking  it was able to produce a Windows `executable` with "`dynamic link at load time`" capability. In this case `mingw `should be able to understand any `object `file format like (`.obj, .lib` (import, or static) ). But may be i am a dreamer ?.

> CYGWIN , MSYS2 and MINGW or MINGW-W64.Many libraries are available here.

May i suppose your are talking about thirdy party libraries (i.e libsndfile, portaudio,..) ?

>you can download an old express Visual Studio or the newest Visual Studio 2017 community. It has great CMAKE

Did you mean cmake from www.cmake.org or CMAKE microsoft specific ?

> thanks to the VCPKG tool many thirdy party libraries have made available

At a first glance, the tool seems powerful. May i suppose that the tool is able to search thirdy party library (i.e libsndfile, portaudio) somewhere (local or distant) ?
Again many thanks for your experience feedback.

**Comment by derselbst** [comment]
Closed due to inactivity.
