### ISSUE TITLE
crash when seeking

### ISSUE THREAD

**Issue by loki666** [FluidSynth/fluidsynth#356]
when seeking fluidsynth segfault

the issue seems to be in the macro FLUID_API_RETURN_IF_CHAN_DISABLED
when seeking there is a call to `fluid_synth_all_sounds_off(synth, -1)`

at `fluid_synth.c:1878` `fluid_synth_all_sounds_off` call the macro while chan is -1
and `synth->channel[chan]` crashes

**Comment by derselbst** [comment]
Yeah, that's a problem, thanks for the hint.

@jjceresa Do we really need to have the `FLUID_API_RETURN_IF_CHAN_DISABLED` check in `fluid_synth_all_sounds_off` and `fluid_synth_all_notes_off`? No note should be playing on a disabled channel anyway.

**Comment by loki666** [comment]
well it works fine without 😄

**Comment by derselbst** [comment]
Sure, but I'm not sure whether it would be still MIDI PolyMono spec conform. Maybe I'm missing something.

**Comment by loki666** [comment]
isn't PolyMono kind of a live performance setting, while seeking only used with the player ?

**Comment by derselbst** [comment]
PolyMono is part of the Midi standard. It's not limited to live performance, you may also use it in a MIDI file.

**Comment by loki666** [comment]
ok then

**Comment by jjceresa** [comment]
> Do we really need to have the FLUID_API_RETURN_IF_CHAN_DISABLED check in fluid_synth_all_sounds_off and fluid_synth_all_notes_off? No note should be playing on a disabled channel anyway.

>Sure, but I'm not sure whether it would be still MIDI PolyMono spec conform. I think yes, but maybe I'm missing something.

After looking in the MIDI Specs, i see no problem so we can remove the check of `FLUID_API_RETURN_IF_CHAN_DISABLED.` This will be done in a new commit on polymono branch.

@loki666 Thanks for pointing this bug. (I was missing the case of chan = -1 !).

**Comment by derselbst** [comment]
Should be fixed by 124a5b71bc75be956616a8b4ae354271255aa0ef.
