### ISSUE TITLE
Unable to run fast rendering of a file on android platform

### ISSUE THREAD

**Issue by swapnilgt** [FluidSynth/fluidsynth#367]
### FluidSynth version
1.1.10

### Current behavior
I am trying to run file-renderer from within my android app and for this purpose I have built fluidsynth on android using this fork https://github.com/VolcanoMobile/fluidsynth-android. I am using the `CMakeLists.txt` to build the shared library for myself and included as a subdirectory in my top level CMakeLists.txt that looks like this:

```
# Sets the minimum version of CMake required to build your native library.
# This ensures that a certain set of CMake features is available to
# your build.

cmake_minimum_required(VERSION 3.4.1)


######################################################################################
######### Adding fluidsynth library from the external code
######################################################################################
# Sets lib_src_DIR to the path of the target CMake project.
set(fluidsynth-lib-name libfluidsynthsrc)
set( lib_DIR <chackout-path-for-the-source>/fluidsynth-android/android/ )

# Sets lib_build_DIR to the path of the desired output directory.
set( lib_build_DIR ${lib_DIR}/outputs )
file(MAKE_DIRECTORY ${lib_build_DIR})

# Adds the CMakeLists.txt file located in the specified directory
# as a build dependency.
add_subdirectory( # Specifies the directory of the CMakeLists.txt file.
                  ${lib_DIR}

                  # Specifies the directory for the build outputs.
                  ${lib_build_DIR} )

# Adds the output of the additional CMake build as a prebuilt static
# library and names it.
#add_library( ${fluidsynth-lib-name}
#                SHARED
#                IMPORTED )

#set_target_properties( ${fluidsynth-lib-name} PROPERTIES IMPORTED_LOCATION
#                       ${lib_build_DIR}/${ANDROID_ABI}/lib${fluidsynth-lib-name}.so )

######################################################################################
######### Adding fluidsynth library with the JNI function
######################################################################################

# Creating the top level library for accessing by our app
add_library( my-fluidsynth
            SHARED
            src/main/cpp/src/fluidsynth-jni.cpp )

# Specifies a path to native header files
include_directories(src/main/cpp/include/)

# Links the top-level CMake build output against libfluidsynthsrc
target_link_libraries(my-fluidsynth
                        fluidsynth
                        log)
```

I am using JNI to call the fluidsynth library and for fast rendering I am using the following code:

```
#include <fluidsynth-jni.h>
#include <android/log.h>
#include <fluidsynth.h>
/* Header for class com_musicmuni_fluidsynth_FluidSynth */
/*
 * Class:     com_musicmuni_fluidsynth_FluidSynth
 * Method:    getFileFromMIDIAndSoundFont
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_musicmuni_fluidsynth_FluidSynth_getFileFromMIDIAndSoundFont
        (JNIEnv *env, jobject obj, jstring outFile, jstring midiFile, jstring soundfontFile,
         jint sampleRate) {

    const char *outFileChar = env->GetStringUTFChars(outFile, 0);
    const char *midiFileChar = env->GetStringUTFChars(midiFile, 0);
    const char *soundfontFileChar = env->GetStringUTFChars(soundfontFile, 0);

    __android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","outFile path: %s", outFileChar);
    __android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","midiFile path: %s", midiFileChar);
    __android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","soundfontFile path: %s", soundfontFileChar);

    fluid_settings_t* settings;
    fluid_synth_t* synth;
    fluid_player_t* player;
    fluid_file_renderer_t* renderer;
    settings = new_fluid_settings();

    // specify the file to store the audio to
    // make sure you compiled fluidsynth with libsndfile to get a real wave file
    // otherwise this file will only contain raw s16 stereo PCM
    int success = fluid_settings_setstr(settings, "audio.file.name", outFileChar);
    if(FLUID_OK == success) {
        __android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","Successful in setting the out file name");
    } else {
        __android_log_print(ANDROID_LOG_ERROR, "NDK_LOG","Unable in setting the out file name");
        return 0;
    }

    // Setting the sample rate
    success = fluid_settings_setnum(settings, "synth.sample-rate", sampleRate);
    if(FLUID_OK == success) {
        __android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","Successful in setting sample rate");
    } else {
        __android_log_print(ANDROID_LOG_ERROR, "NDK_LOG","Unable in setting the sample rate");
        return 0;
    }

    // use number of samples processed as timing source, rather than the system timer
    success = fluid_settings_setstr(settings, "player.timing-source", "sample");
    if(FLUID_OK == success) {
        __android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","Successful in setting timing source");
    } else {
        __android_log_print(ANDROID_LOG_ERROR, "NDK_LOG","Unable in setting the timing source");
        return 0;
    }

    // since this is a non-realtime szenario, there is no need to pin the sample data
    success = fluid_settings_setint(settings, "synth.lock-memory", 0);
    if(FLUID_OK == success) {
        __android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","Successful in setting lock memory");
    } else {
        __android_log_print(ANDROID_LOG_ERROR, "NDK_LOG","Unable in setting the lock memory");
        return 0;
    }

    synth = new_fluid_synth(settings);

    // Setting the soundfont ..
    success = fluid_synth_sfload(synth, soundfontFileChar, 1);
    if(FLUID_FAILED == success) {
        __android_log_print(ANDROID_LOG_ERROR, "NDK_LOG","Unable in setting the soundfont file");
        return 0;
    } else {
        __android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","Successful in setting the soundfont file");
    }

    player = new_fluid_player(synth);
    success = fluid_player_add(player, midiFileChar);
    if(FLUID_OK == success) {
        __android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","Successful in fluid_player_add");
    } else {
        __android_log_print(ANDROID_LOG_ERROR, "NDK_LOG","Unable in fluid_player_add");
        return 0;
    }


    success = fluid_player_play(player);
    if(FLUID_OK == success) {
        __android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","Successful in fluid_player_play");
    } else {
        __android_log_print(ANDROID_LOG_ERROR, "NDK_LOG","Unable in fluid_player_play");
        return 0;
    }

    renderer = new_fluid_file_renderer (synth);
    while (fluid_player_get_status(player) == FLUID_PLAYER_PLAYING)
    {
        //__android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","FLUID_PLAYER_PLAYING\n");
        if (fluid_file_renderer_process_block(renderer) != FLUID_OK)
        {
            break;
        } else {
            //__android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","fluid_file_renderer_process_block != FLUID_OK\n");
        }
    }

    // just for sure: stop the playback explicitly and wait until finished
    fluid_player_stop(player);
    fluid_player_join(player);
    delete_fluid_file_renderer(renderer);
    delete_fluid_player(player);
    delete_fluid_synth(synth);
    delete_fluid_settings(settings);

    env->ReleaseStringUTFChars(outFile, outFileChar);
    env->ReleaseStringUTFChars(midiFile, midiFileChar);
    env->ReleaseStringUTFChars(soundfontFile, soundfontFileChar);

    __android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","Success in going over the function for generating file");

    return 1;

}
```

I arrived at this implementation using the example mentioned in: http://www.fluidsynth.org/api/index.html#FileRenderer

The problem I am facing is that when I call this function with the midi and soundfont file arguments, it gets stuck infinitely at 
```
while (fluid_player_get_status(player) == FLUID_PLAYER_PLAYING)
    {
        //__android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","FLUID_PLAYER_PLAYING\n");
        if (fluid_file_renderer_process_block(renderer) != FLUID_OK)
        {
            break;
        } else {
            //__android_log_print(ANDROID_LOG_VERBOSE, "NDK_LOG","fluid_file_renderer_process_block != FLUID_OK\n");
        }
    }
```
I have tried the command line on MacOS for running the fast renderer and it works fine. Not sure it the android build has something missing. At first look to the cmake file, it seems to have the code included for the filerender.

### Expected behavior

On calling the above mentioned function with the valid arguments, the function should output a file with raw pcm bits of audio.

### Steps to reproduce
a) Checkout the code for android-fluidsynth from https://github.com/VolcanoMobile/fluidsynth-android
b) Create an android library module and setup NDK for it using a CMakeLists.txt file (as mentioned above) and using instruction on https://developer.android.com/ndk/guides/cmake.html
c) Create a JNI as mentioned above and call it using valid MIDI and soundfont files.
d) The function goes into infinite loops as mentioned above.

### Other information
The MIDI file and the soundfont file that I am using can be found here : http://jmp.sh/b/z76LQfVXgihXcYDKbZBT

**Comment by swapnilgt** [comment]
@loki666 : Can you help with this. I was unable to open an issue on the android repository and hence opened it here. Thanks!

**Comment by loki666** [comment]
no wonder this code is broken...
https://github.com/FluidSynth/fluidsynth/blob/master/src/bindings/fluid_filerenderer.c#L355
`offset += n` but n is never initialized so it's probably 0

**Comment by mawe42** [comment]
> no wonder this code is broken...
https://github.com/FluidSynth/fluidsynth/blob/master/src/bindings/fluid_filerenderer.c#L355
offset += n but n is never initialized so it's probably 0

That looks fine to me. The ```offset += n``` part of the for loop is only called *after* the loop body has run at least once. And in the body, ```n``` is set to the return value of the ```fwrite``` call. So while it's not initialized, it's never used without a defined value.

**Comment by loki666** [comment]
sorry my mistake, but what if fwrite returns 0 then ?

**Comment by loki666** [comment]
mmh it should never returns 0...

**Comment by loki666** [comment]
@swapnilgt could you try to set the `audio.period-size` setting to 1024 or something?

**Comment by mawe42** [comment]
> sorry my mistake, but what if fwrite returns 0 then ?

Hm, good point! I assume on android you are using this implementation:
https://android.googlesource.com/platform/bionic/+/master/libc/stdio/stdio.cpp#1103

And that can return 0 in some cases.

**Comment by loki666** [comment]
yes the libc is bionic

**Comment by derselbst** [comment]
Thanks for the pointer @loki666.

This whole offset-loop is actually wrong. C90 is very clear about `fwrite()`:

> The fwrite function returns the number of elements successfully written, which will be
less than nmemb only if a write error is encountered.

Where `nmemb` means the requested number of elements, i.e. third argument. Committed a fix, pls retest.

**Comment by loki666** [comment]
@swapnilgt I've update my fork, could you give it a shot please ?

**Comment by swapnilgt** [comment]
@loki666 Thank you .. will try and let you know about the status !

**Comment by loki666** [comment]
@swapnilgt if this bug was your issue, that means you have a write error.
are you sure your app has the permission to write the output file?

**Comment by swapnilgt** [comment]
Yeah ... I am sure that the app has this permission `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`. Also, I tried after pulling the latest code and deleting the directory `<repo>/android/outputs` (which my output dir as mentioned in CMakelists.txt) and also. I still have the code running in infinite loop.

**Comment by loki666** [comment]
could you check that the period_size is > 0

before the `while (fluid_player_get_status(player) == FLUID_PLAYER_PLAYING)`

```
int period_size;
fluid_settings_getint (synth->settings, "audio.period-size", &period_size);
__android_log_print(...);
```

**Comment by loki666** [comment]
in last resort, you can do what fluid_file_renderer_process_block does yourself...

basically, you need a buffer to store the output of `fluid_synth_write_s16` and then write in a file

**Comment by swapnilgt** [comment]
It says that the period size is 0

**Comment by loki666** [comment]
yup that's your issue.
set the `audio.period-size` to 1024 in the settings before creating the synth

**Comment by loki666** [comment]
@derselbst maybe an early return `FLUID_FAILED` if `nmemb` equals 0

**Comment by swapnilgt** [comment]
```
success = fluid_settings_setint(settings, "audio.period-size", 1024);
````
Calling this returns with `FLUID_FAILED`

**Comment by derselbst** [comment]
> maybe an early return FLUID_FAILED if nmemb equals 0

No. `audio.period-size` is guaranteed to be `>= 64`. It's your bug, because you removed the setting. And I dont want to add those kinds of paranoia checks, sry.

> question why is fluid_filerenderer using the audio driver period for the buffer? shouldn't it use it's own buffer size and period ?

The file renderer is an audio driver. Technically it can be hidden behind `new_fluid_audio_driver()`. This wasnt done. Anyway, the period size is shared between all audio drivers.

> you are bound to do what fluid_file_renderer_process_block does yourself

I dont support this. The idea of providing functions like `fluid_file_renderer_process_block()` is to make people use them in their programs, not reprogramming them.

**Comment by swapnilgt** [comment]
> No. audio.period-size is guaranteed to be >= 64. It's your bug, because you removed the setting. And I dont want to add those kinds of paranoia checks, sry.

@loki666 : Do we expect a fix for the problem mentioned by @derselbst. 

Have we arrived at a solution or its a roadblock here?

**Comment by loki666** [comment]
@swapnilgt no, @derselbst made it clear that it won't be fixed upstream
as for my fork, I don't see exactly how to fix this.

if you don't want to call fluid_synth_write_s16 yourself, you can register the settings in the beginning of your function

`fluid_settings_register_int(settings, "audio.period-size", 512, 64, 8192, 0);`

that will make the file renderer happy (I hope)

**Comment by derselbst** [comment]
> that will make the file renderer happy (I hope)

`fluid_settings_register*()` are private functions. Calling them from a user application is highly discouraged. There is no API / ABI stability guarantee, they may change at any time.

> I don't see exactly how to fix this.

Why not registering all the audio driver setttings properly in `fluid_audio_driver_settings()`? You are calling it anyway.

**Comment by swapnilgt** [comment]
@loki666 : It works now :). Also, I guess I don't need to set the `period-size` now right. I tried with both and it seem to be working with both.

Thanks you @derselbst for all the inputs :)
