### ISSUE TITLE
Need a way to skip initialisation of CoreAudio, to avoid deadlock

### ISSUE THREAD

**Issue by Birch-san** [FluidSynth/fluidsynth#368]
### FluidSynth version
1.1.10, macOS

### Repro
We begin with `new_fluid_settings()`.
Within that: FluidSynth sets up CoreAudio.

Beware: our application may be hosted inside _another application which uses CoreAudio._ **This causes a deadlock**, as the host _also_ holds a lock on CoreAudio's `HALB_Mutex::Lock()`.

I made an audio plugin (VST/AU), and this is what happens when the host application (FL Studio) initialises my audio plugin:

```
__psynch_mutexwait 0x00007fff55a07d1e
_pthread_mutex_lock_wait 0x00007fff55b43bfe
_pthread_mutex_lock_slow 0x00007fff55b41551
HALB_Mutex::Lock() 0x00007fff2da9c91f
HALC_ProxyIOContext::GetPropertyDataSize(AudioObjectPropertyAddress const&, unsigned int, void const*, unsigned int&) const 0x00007fff2dab9fe1
HALC_ShellObject::GetPropertyDataSize(unsigned int, AudioObjectPropertyAddress const&, unsigned int, void const*, unsigned int&) const 0x00007fff2dacecc8
HAL_HardwarePlugIn_ObjectGetPropertyDataSize(AudioHardwarePlugInInterface**, unsigned int, AudioObjectPropertyAddress const*, unsigned int, void const*, unsigned int*) 0x00007fff2dace4bf
HALPlugIn::ObjectGetPropertyDataSize(HALObject const&, AudioObjectPropertyAddress const&, unsigned int, void const*) const 0x00007fff2dace22c
AudioObjectGetPropertyDataSize 0x00007fff2dac9fb1
get_num_outputs 0x000000012d534584
fluid_core_audio_driver_settings 0x000000012d53474f
fluid_audio_driver_settings 0x000000012d554833
new_fluid_settings 0x000000012d536a4b
```

FL Studio will not release the lock until my plugin finishes initialisation.
My plugin cannot finish initialisation until FL Studio releases the lock.

This deadlock occurs in [LMMS](https://github.com/LMMS/lmms/issues/649) and [FL Studio](https://forum.image-line.com/viewtopic.php?f=1965&t=185063&p=1292991#p1292991), but does not occur in GarageBand or Sibelius.

The punchline:
I _don't even use CoreAudio_. I use FluidSynth solely to render blocks of audio, which I send to the plugin host (which has its own audio driver).

### Proposal
We need an opportunity to avoid some of the mandatory startup steps.

I would like an opportunity to configure my `fluid_settings_t*` _before_ `fluid_settings_init()` runs upon it.

So, imagine this:

```cpp
fluid_settings_t* mySettings = new_fluid_settings_empty();
fluid_settings_setint(mySettings, "disable_audiodriver", 1);
fluid_settings_init(mySettings);
```

This way I could say "don't setup an audio driver when you do the normal startup process".

**Comment by derselbst** [comment]
Thanks for this hint.

At some point fluidsynth needs to initialize the audio drivers for e.g. filling settings like `audio.coreaudio.device`. Conventionally, this is done on object creation.

> This way I could say "don't setup an audio driver when you do the normal startup process".

As of 1.1.9 this is possible using the [fluid_audio_driver_register()](http://www.fluidsynth.org/api/audio_8h.html#ad35f9fb8b124e8e9e8829fa9efefeb34) function.

**Comment by Birch-san** [comment]
Ah, good to know. How would I use `fluid_audio_driver_register()` to register _no_ audio driver? since NULL means all.

I can see use-cases that are currently difficult with this:
- exclude **all** audio drivers (since this is an exhaustive whitelist, and seems not to support empty whitelist)
- exclude **one** driver (since I'd need to know the list of drivers _typically_ registered and splice one out)

**Comment by derselbst** [comment]
> exclude all audio drivers (since this is an exhaustive whitelist, and seems not to support empty whitelist)

https://github.com/derselbst/ANMP/blob/237e373c2756e218322600468ed9e7fc6eea6f3c/src/InputLibraryWrapper/FluidsynthWrapper.cpp#L237-L239

> exclude one driver (since I'd need to know the list of drivers typically registered and splice one out)

Right, this is a little more tricky. This function is called *register() because it assumes that the user knows which driver(s) he wants. If the opposite use-case of knowing "what-drivers-you-dont-want" would be an actively requested feature, one might think about `fluid_audio_driver_deregister()`. Unless you've a better idea?

**Comment by Birch-san** [comment]
> ...it's a NULL terminated array, no one said it cant be "empty".

thanks; I thought the array model in C/C++ was that you point at the first item and seek until the first NULL — and that there'd be no way to tell the difference between "empty set followed by NULL," versus "NULL followed by a NULL". but I guess if it knows the _length_ of the array, that makes sense.

> If the opposite use-case of knowing "what-drivers-you-dont-want" would be an actively requested feature

I suspect there's no need. both me and the LMMS team were in the situation of "can't use CoreAudio" but also "don't need any driver at all", so in both these use-cases it's probably best to just turn off all drivers.

If there is still a need for to _blacklist individual drivers_, (and stop me if something like this already exists…) maybe better to:

- expose a function `const char ** fluid_get_registered_audio_drivers()`
- let the user splice out whatever drivers they want to blacklist
- have user call the existing `fluid_audio_driver_register()` with their filtered list

this means less confusing questions around "how does whitelist interact with blacklist", and arguably is useful detail to expose (for example, I'm personally _curious_ as to what drivers remain after I compiled with CoreAudio disabled).

**Comment by derselbst** [comment]
> I thought the array model in C/C++ was that you point at the first item and seek until the first NULL — and that there'd be no way to tell the difference between "empty set followed by NULL," versus "NULL followed by a NULL". but I guess if it knows the length of the array, that makes sense.

Well you either know the size of an array or you have to NULL terminate it. A terminated array (like C-Strings) must always have at least one element, otherwise the behaviour is undefined, as your array decays to a pointer that just points to some uninitialized memory.
> I'm personally curious as to what drivers remain after I compiled with CoreAudio disabled

In the fluidsynth shell type

```bash
info audio.driver
```

**Comment by Birch-san** [comment]
cool, that confirms that there's no fallback driver. it's typically `coreaudio, file`, but my custom build had just `file`.

Thanks for the workaround:

```cpp
const char *DRV[] = {NULL};
fluid_audio_driver_register(DRV);
```

That successfully enabled me to init FluidSynth without incurring CoreAudio deadlock (and without having to resort to a custom build with CoreAudio removed).
