### ISSUE TITLE
24 bit support enhancement to support fast 24/16 bits interpolation

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#373]
Since 24 bits support, Fluidsynth accepts now 16 or 24 bits soundfonts. 
To be independent of sample format  and for memory consumption reason , the internal interpolator uses numbers on 24 bits  regardless of the initial soundfont sample format (16 or 24b) (in fluid_rvoice_get_sample()). However compared to "`without 24 bits support`"  ` fluid_rvoice_get_sample()` introduces a `cpu load augmentation` of 30% this lead to `lost of number of maximum voices` of 24%. (measured on Windows XP and linux Debian (MinSize release) ). 

It is this simple instruction that introduces mainly this cpu load augmentation (used with FLUID_INTERP_DEFAULT interpolation method):
https://github.com/FluidSynth/fluidsynth/blob/05c2d57e65f3fdc264c53fcaa4947cda2eb508a8/src/rvoice/fluid_rvoice.h#L216

Without the check of `dsp_lsb` pointer, the `cpu load augmentation` is only 2.07% (in others word the `lost of maximun numbers of voices` is only 2.03%) introduced by the necessary following instruction:
https://github.com/FluidSynth/fluidsynth/blob/05c2d57e65f3fdc264c53fcaa4947cda2eb508a8/src/rvoice/fluid_rvoice.h#L218

For no fast embedded cpu with no math co-processor this lost of 22% is not negligible and could be solved "relatively" easily.

@derselbst , @mawe42 Could you please confirm this  ?. This is easy to do as the `dsp_lsb` pointer, check  instruction can be safely temporarily commented when using a 16 bits soundfont.

Next i will continue for a proposal to solve this.
Thanks.

**Comment by mawe42** [comment]
Some more tests on my embedded machine: ~162 voices with current master, ~171 voices with the modified ```fluid_rvoice_get_sample```. So around 5% performance gain. Profiling done on ARM Coretex-A7, 960MHz, without reverb and chorus, 64 byte buffer size, 2 buffers. Fluidsynth compiled with "Release" build, but custom build flags ```-O3 -ffast-math```.

**Comment by jjceresa** [comment]
Many thanks for your useful feedback.

I will investigate further using Release rather MinRelSize, anyway this doesn't not explain why there is a 20% difference between `fluid_rvoice_get_sample() `and `modified fluid_rvoice_get_sample()` using the same type MinRelSize . I will double check this.
Again many thanks for your results.

**Comment by mawe42** [comment]
Slightly off-topic, but still related to performance loss: I used valgrind to profile Fluidsynth while executing the profiling commands. What looked weird were a huge number of calls to ```fluid_iir_filter_apply```, even though I started fluidsynth with ```-R0 -C0```. If I comment out the `fluid_iir_filter_*``` functions in ```fluid_rvoice_write```, I get a 45%(!) performance increase on my embedded machine. I'll investigate further to see if there are easy pickings for people who don't use the build-in reverb (like me).

**Comment by jjceresa** [comment]
>What looked weird were a huge number of calls to fluid_iir_filter_apply, even though I started fluidsynth with -R0 -C0. If I comment out the `fluid_iir_filter_*functions influid_rvoice_write```, I get a 45%(!) 

Yes (Apart reverb and chorus) `Filter `and `interpolator `are the two things that consumes most cpu cycles in fluidsynth.

**Comment by mawe42** [comment]
> Yes (Apart reverb and chorus) Filterand interpolatorare the two things that consumes most cpu cycles in fluidsynth.

Sorry, please ignore that previous comment. Of course the ```fluid_iir_*``` functions have nothing to do with the reverb. Maybe I should go to sleep instead of rambling nonsense here...

**Comment by jjceresa** [comment]
> I will investigate further using Release rather MinRelSize.

Ok, Release build give the rather the same result as yours between `fluid_rvoice_get_sample()` and modified fluid_rvoice_get_sample().
But, i confirm MinSizeRel build still gives 20 % lost between `fluid_rvoice_get_sample()` and `modified fluid_rvoice_get_sample()`.

And the more surprising is that  MinSizeRel build is faster (+14 %) that Release build !.
Well i think i will stop any profiling and should preferably drink something !.

**Comment by jjceresa** [comment]
Using `Release `build  with `modified fluid_rvoice_get_sample()` produce just a gain of 3 % .
However using `MinSizeRel `with modified fluid_rvoice_get_sample() gives the same performance than `Release `build.

That demonstrates that using `MinSizeRel `build is a very bad choice (like RelWithDebInfo ) when profiling and could  introduce pitfalls by masking real performance. Lesson learned.

I still left this issue open to give Tom time to read this.

I dont intend to give a suite and consider this closed. Again thanks to Marcus for experiments results.

**Comment by mawe42** [comment]
Ah, good that you got consistent results as well. No need to keep this open, Tom will have been notified of this issue anyway and can read it even if it's closed.

**Comment by derselbst** [comment]
Ok, I confirm what you guys already said.
