### ISSUE TITLE
Proposal to choose only one method of interpolation at Cmake time only ?

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#377]
I wonder if  `fluid_synth_set_interp_method()` API and even  `commands shell` to set any `interpolation method` distinct for any channels are really useful. The only need i see of choosing a different method is for experiment only.
So i wonder if we could choose only `one` method of interpolation (one between FLUID_INTERP_NONE,
FLUID_INTERP_LINEAR,FLUID_INTERP_4THORDER,FLUID_INTERP_7THORDER) at Cmake time only ?.
- This will allow to reduce the size of the library.
  - suppression of the API and all related shell commands and code in interpolator.
- It will still possible to experiment with distincs methods running on distincts executables libraries.

Any thoughts, opinions, blames ?

**Comment by derselbst** [comment]
I dont think that would be a good idea. fluidsynth allows setting interpolation method per midi channel via `fluid_synth_set_interp_method()`. I'm using this one in my app to set it to sinc interp (and no, I cant hear the difference :P). Still I think it's useful to have the user decide what interpolation method should be used.

**Comment by jjceresa** [comment]
> Still I think it's useful to have the user decide what interpolation method should be used.
Sure i understand this, as with this proposal it is less flexible as the final user should ask to the application developer to do the interpolation method change.
