### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by loki666** [FluidSynth/fluidsynth#378]
https://github.com/FluidSynth/fluidsynth/blob/bad31022513e45e72734779ab5c320c091cbc59c/src/synth/fluid_synth_monopoly.c#L169

clang is complaining here and in other places

```
src/synth/fluid_synth_monopoly.c:169:5: error: comparison of constant -1 with expression of type 'char' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
          if(fluid_channel_is_valid_note(ptc))
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/loki/AndroidStudioProjects/midi-music-player/distribution/fluidsynth-android/android/../src/synth/fluid_chan.h:236:46: note: expanded from macro 'fluid_channel_is_valid_note'
  #define fluid_channel_is_valid_note(n)    (n != INVALID_NOTE)
                                             ~ ^  ~~~~~~~~~~~~
```

**Comment by loki666** [comment]
using -Werror,-Wtautological-constant-out-of-range-compare

**Comment by derselbst** [comment]
Wild guess: `char` means `unsigned char` on your platform?

**Comment by jjceresa** [comment]
For infos i remember that `char `means `unsigned char` on Rasbian (used with Rpi platform). I don't understand why compiler on these platforms aren't C compliant ?.

**Comment by mawe42** [comment]
I think all ARM platform compilers have char as unsigned by default. And as far as I know, that is not against the spec. The C standard doesn't specify the signedness of char.

**Comment by jjceresa** [comment]
> And as far as I know, that is not against the spec. The C standard doesn't specify the signedness of char.

Good to know. In this case it should be preferable to be able to instruct the compiler. Please did you know how to do for example on your platform ?.

**Comment by mawe42** [comment]
For the Linaro toolchain, you can specify ```--signed-char``` to force char to signed. But there are other compilers out there that seem to use ```--signed_chars```.

I think it would be best to be explicit in the code. So use ```unsigned char``` or ```signed char``` where signedness matters.

I also get these warnings on my platform, but didn't notice them because there are so many other warnings about signed/unsigned comparison. Would be great to fix those, so that we don't get accustomed to ignoring warnings again...

**Comment by derselbst** [comment]
The C standard says the signedness of chars is implementation defined... and I keep forgetting about that, so thanks for this hint. Forcing signed chars by default is not my preferred solution either as it changes ABI. Will explicitly fix it in code.

**Comment by derselbst** [comment]
I changed it in f8e4890a637fe2e136e15070b86efcd5172e9e29.

**Comment by jjceresa** [comment]
> I changed it in f8e4890

I think it will be preferable to restore the type `unsigned char` in `mononote `and `INVALID_NOTE` to 255. I can do that if you want ?

**Comment by derselbst** [comment]
Already working on it.

**Comment by derselbst** [comment]
Should be fixed now. @loki666 please retest. @jjceresa please have a look: d47de30f160c222039f7b552ff13edb6c955f484.

**Comment by loki666** [comment]
fixed
