### ISSUE TITLE
how to loop or play another tune.

### ISSUE THREAD

**Issue by tecan** [FluidSynth/fluidsynth#386]
tried doing this in my code to loop or play another midi file without luck.

if (fluid_player_get_status(player) == FLUID_PLAYER_DONE )
{
    printf("done and replaying");
//        fluid_player_stop(player);
//        fluid_player_join(player);
fluid_player_add(player,param);
        fluid_player_play(player);
}

**Comment by derselbst** [comment]
You're supposed to add all files to be played once before initial `fluid_player_play()`: http://www.fluidsynth.org/api/index.html#MIDIPlayer

And have a look at `fluid_player_set_loop()`.
