### ISSUE TITLE
Compilation failure on OS/2

### ISSUE THREAD

**Issue by komh** [FluidSynth/fluidsynth#389]
Hi/2.

I've tried the latest git sources. But it fails with the following messages:

```
[  2%] Building C object src/CMakeFiles/libfluidsynth.dir/drivers/fluid_dart.c.o
In file included from F:/lang/work/fluidsynth/fluidsynth.git/src/drivers/fluid_adriver.h:24:0,
                 from F:/lang/work/fluidsynth/fluidsynth.git/src/drivers/fluid_dart.c:27:
F:/lang/work/fluidsynth/fluidsynth.git/src/utils/fluid_sys.h:371:9: error: unknown type name 'GStatBuf'
 typedef GStatBuf fluid_stat_buf_t;
         ^~~~~~~~
```

Any idea ?

**Comment by mawe42** [comment]
It looks like you are using a very old GLib. Please try again with GLib >= 2.6.

**Comment by komh** [comment]
I'm using GLib v2.12.4.

**Comment by komh** [comment]
I've searched for GStatBuf and found that it has been introduced since v2.26.0. See https://sourceforge.net/p/viking/bugs/104/#5295.

And here is the patch.

```
From a01b0bb3c471ab43c7e6bb28f6d57590c7285e1a Mon Sep 17 00:00:00 2001
From: KO Myung-Hun <komh@chollian.net>
Date: Mon, 28 May 2018 23:19:30 +0900
Subject: [PATCH] fix compilation below GLib v2.26.0

GStatBuf has been introduced since GLib v2.26.0
---
 src/utils/fluid_sys.h | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/src/utils/fluid_sys.h b/src/utils/fluid_sys.h
index 2bda36a..117449b 100644
--- a/src/utils/fluid_sys.h
+++ b/src/utils/fluid_sys.h
@@ -368,6 +368,9 @@ fluid_istream_t fluid_socket_get_istream(fluid_socket_t sock);
 fluid_ostream_t fluid_socket_get_ostream(fluid_socket_t sock);
 
 /* File access */
+#if !GLIB_CHECK_VERSION(2, 26, 0)
+typedef struct stat GStatBuf;
+#endif
 typedef GStatBuf fluid_stat_buf_t;
 #define fluid_stat(_filename, _statbuf)   g_stat((_filename), (_statbuf))
 
-- 
2.13.3
```

**Comment by mawe42** [comment]
Ah... good point, thanks! I looked in the GLib documentation and found the "Since 2.6" in g_stat and assumed that GStatBuf was introduced with the same version.

@derselbst I guess we need to change the minimum GLib version in CMakeLists.txt...

**Comment by derselbst** [comment]
Bumping the minimum required glib version would be a good opportunity for fluidsynth 2.0... basically. If so, I would like to bump it to 2.32 to have the real benefit of getting rid of the `OLD_GLIB_THREAD_API` handling in `fluid_sys.h`.

As I dont see a real gain of bumping to 2.26, I will use @komh's patch. Additionally I'll lower the glib version of the appveyor CI build to catch those kinds of errors in the future.

@komh Thanks for testing + reporting!

**Comment by derselbst** [comment]
Should be fixed on recent git now. I had to use glib 2.16 as lowest version, because older ones were not found by pkg-config on win32 for some reason. That's why those orphaned try and error commits above.

**Comment by mawe42** [comment]
> If so, I would like to bump it to 2.32 to have the real benefit of getting rid of the OLD_GLIB_THREAD_API handling in fluid_sys.h.

Sounds good. And requiring a 6 year old glib shouldn't really be a problem, I guess.

**Comment by mawe42** [comment]
@komh Is there anything preventing you from using a newer glib (>= 2.32) on OS/2?

**Comment by komh** [comment]
There seems to be 2.33.12 for OS/2. But I've not tested with it, yet. After I try, then I'll report the result.

**Comment by derselbst** [comment]
> And requiring a 6 year old glib shouldn't really be a problem, I guess.

[ftp.gnome.org](http://ftp.gnome.org/pub/gnome/binaries/win32/glib/) only provides prebuilt binaries for up to 2.28, and I already hear windows user complaining if we'd bump to 2.32.

**Comment by mawe42** [comment]
> ftp.gnome.org only provides prebuilt binaries for up to 2.28 and I already hear windows users complaining if we'd bump to 2.32.

Ah... and only up to 2.26 for win64. Really a shame that they don't build for Windows anymore.

We could host a build of the most recent glib ourselves. Setup an appveyor that tracks the glib repo for new releases, issues a rebuild and uploads the libs to our release page automatically. But it might be more trouble than it's worth...

**Comment by komh** [comment]
Then any reason to bump to 2.26 ? I think, staying with this patch is not bad, too.

**Comment by derselbst** [comment]
No reason to bump glib for now. If we ever have a serious reason to do so, I'll take Marcus' idea into account.

**Comment by komh** [comment]
Thanks.
