### ISSUE TITLE
High CPU usage on Raspberry Pi Zero? Normal?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [FluidSynth/fluidsynth#390]
I'm running FluidSynth 1.1.6 on a Raspberry Pi Zero.

SoundFont: http://schristiancollins.com/generaluser.php
MIDI:
[The Christmas Song.mid.zip](https://github.com/FluidSynth/fluidsynth/files/2051431/The.Christmas.Song.mid.zip)

Pi specs:
Linux raspberrypi 4.14.34+ #1110 Mon Apr 16 14:51:42 BST 2018 armv6l GNU/Linux

Things are OK at first, but then stuttering begins and gets worse and worse, likely due to CPUs being hosed.

The CPU usage is confusing me. I see 2 processes (why 2?) at 90% each.
<img width="2560" alt="screenshot 2018-05-29 15 08 46" src="https://user-images.githubusercontent.com/382821/40688410-d93d5b52-6352-11e8-81c4-f99a2051db1f.png">

Is 2 processes expected?

Are there any tips to tweak CPU performance?

I may switch to a RPi 3B+, which has 4 cores, instead of the Pi Zero, which has one core, but I'm wondering if I can get more out of the Pi Zero.

**Comment by mawe42** [comment]
The armv6l could indicate that you are running programs that were compiled with "soft float" instead of "hard float". In other words, that you are not using the hardware to do floating point computations, which will slow down FluidSynth considerably.

Try to find a armv6h or armhf compiled distribution, that might already make quite a difference.

**Comment by mawe42** [comment]
Oh, and yes: FluidSynth is expected to start two threads (not processes).

**Comment by GeoffreyPlitt** [comment]
Great feedback, thanks!

**Comment by mawe42** [comment]
One request for the future: please post questions like this on the fluid-dev mailing list instead of opening an issue here. On the list you will also be able to reach more people who might be able to help.

**Comment by GeoffreyPlitt** [comment]
Will do, thanks.
