### ISSUE TITLE
fluid_preset accessor functions should be made public

### ISSUE THREAD

**Issue by mawe42** [FluidSynth/fluidsynth#391]
In current master (and 2.0 beta1), ```fluid_preset``` is an opaque type, meant to be accessed via the ```fluid_preset_get_*``` accessor functions. However, those accessor functions are not exposed via the API but only defined in ```sfloader/fluid_sfont.h```

As we expose iteration functions to retrieve presets from a soundfont, we should also expose accessors to get information about those presets.

fluidsynth-dssi is an example of a downstream user of this API.

**Comment by mawe42** [comment]
> As we expose iteration functions to retrieve presets from a Soundfont, we should also expose accessors to get information about those presets.

Hm, we don't expose the iteration functions, ```fluid_sfont_iteration_start``` and ```fluid_sfont_iteration_next``` are not part of the public API.

I can't remember the intention behind this API change. But as there is at least one downstream user, we should probably expose both iteration and preset accessors. I think fluidsynth-dssi's use case is quite valid: reading the preset names, bank and program numbers to display them in a list.

**Comment by loki666** [comment]
I basically I have the same need, and I also had to go through fluid_sfont.h (not pretty)

**Comment by mawe42** [comment]
QSynth [as well](https://github.com/rncbc/qsynth/blob/aa33a5ff9b8cbd271c5b94634e589bc3b3a270b4/src/qsynthPresetForm.cpp#L163)
