### ISSUE TITLE
Inconsistent symbol export

### ISSUE THREAD

**Issue by fabiangreffrath** [FluidSynth/fluidsynth#392]
Currently, it depends on dbus being available at build time if the `fluid_rtkit_make_realtime()` function is exported as part of the public API or not. This means that applications could never simply call this function without risking an "invalid symbol" kind of crash.

The fix is merely a matter of moving some defines around in `fluid_rtkit.{c,h}`. If dbus is unavailable, the function could be defined to the same dummy that it currently is if dbus is available but the build system is neither Linux nor Apple. 

Please consider making `fluid_rtkit_make_realtime()` part of the stable fluidsynth 2.0 API.

**Comment by derselbst** [comment]
`fluid_rtkit_make_realtime()` is 

1. defined in fluidsynths **private** header `fluid_rtkit.h`,
1. **not exported** with the `FLUIDSYNTH_API` macro, and
1. **not documented** anywhere in the [API docs](http://www.fluidsynth.org/api/).

Therefore it is **not** part of the public API. Any application using it is broken by itself.

Counter-question: Why do you need `fluid_rtkit_make_realtime()` to be public?

**Comment by mawe42** [comment]
> Excuse me, but is cmake really such a crappy build system that it prepares a "release" and a "debug" build profile - which is of course a good thing per se - but then chooses neither of them and runs in some kind of "undefined" mode if none of them is explicitly selected on the command line?

I don't think it uses an "undefined" mode but the "RelWithDebInfo" build type by default. Which is maybe something we should consider changing? My guess is that most people who don't think about the build type also don't need debugging symbols...

What tripped me up a few times though is that cmake accepts *any* string for CMAKE_BUILD_TYPE. So if you have a typo in the build type name, cmake happily compiles with only a few basic cflags.

**Comment by derselbst** [comment]
> Excuse me, but is cmake really such a crappy build system?

No. If the build type is left empty, [it's set to RelWithDebInfo](https://github.com/FluidSynth/fluidsynth/blob/85356d27325f3b45ca2cf5ccdf47130036aabdaf/CMakeLists.txt#L315-L318). But I see a problem here. If you use some unknown build type `-DCMAKE_BUILD_TYPE=bla`, it will build `bla` by only using  `CMAKE_C_FLAGS`, which is currently not set in our CMakeLists.txt. That's a design failure of our CMakeLists.txt. Will fix that.

**Comment by derselbst** [comment]
I meant: It's our design failure [because `CMAKE_C_FLAGS` is used regardless of the build type](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS.html#variable:CMAKE_%3CLANG%3E_FLAGS) but we never set it.

>It seems like debian compiles all cmake packages with CMAKE_BUILD_TYPE=None,

[Seems like openSUSE does the same.](https://build.opensuse.org/public/build/home:derselbst:anmp/openSUSE_Leap_42.3/x86_64/fluidsynth/_log) So this effectively bypasses the visibility control. Will propose a fix.

**Comment by mawe42** [comment]
> I meant: It's our design failure because CMAKE_C_FLAGS is used regardless of the build type but we never set it. [...] Will propose a fix.

Ah, of course. Thanks!
