### ISSUE TITLE
[v2][macOS] No sound is output to audio driver, nor is any output via `fluid_synth_process()`

### ISSUE THREAD

**Issue by Birch-san** [FluidSynth/fluidsynth#399]
Regression. Both these use-cases work fine in v1.

====

I built master like so:

```bash
# get brew dependencies from v1 FluidSynth
brew install fluidsynth --with-libsndfile pkg-config

# now let's build v2
git clone git@github.com:FluidSynth/fluidsynth.git
# very recent commit in master
git checkout 29d194
mkdir -p build
cd build
cmake -Denable-framework=OFF -Denable-portaudio=OFF -Denable-libsndfile=ON ..
make
```

This output a binary to `build/src/fluidsynth`.

I attempted to play a MIDI file through a soundfont:

```bash
build/src/fluidsynth SGM-V2.01.sf2 mario.mid
```

No audio came out of my system. I assume this means nothing is output to CoreAudio.

This is definitely a regression, because next I tried brew fluidsynth v1, from my path:

```bash
fluidsynth SGM-V2.01.sf2 mario.mid
```

It played audio, as expected.

====

I don't think this is a CoreAudio problem. The same thing happens when I invoke `fluid_synth_process(…)` directly to render MIDI into a block of audio samples.

I linked [my VST](https://github.com/Birch-san/juicysfplugin/tree/fluidsynth2) against `build/src/libfluidsynth.2.0.0.dylib`, updated the includes and source, and now no sound is heard when my audio plugin outputs audio to the plugin host via `fluid_synth_process()`.

Is there anything that it would be useful for me to do to debug this for you?

**Comment by derselbst** [comment]
Indeed, seems like I've broken my local setup... should be fixed in a second.

> fluid_settings_setstr(settings, "synth.verbose", "yes");, and no interesting messages are output by fluidsynth.

`synth.verbose` is an int setting, you must use fluid_settings_setint(). And make sure to check the return values of those functions.

**Comment by Birch-san** [comment]
Thanks! Working now.

In case you're interested, these are the code changes I needed to make to upgrade from FluidSynth 1 -> 2:

https://github.com/Birch-san/juicysfplugin/commit/b9eb853e9c3996144968ee75d4ccab44707e29eb

I'll emphasise that 2.0.0.beta1 didn't expose enough public API, so I was reliant on the solution to this issue (now in master): https://github.com/FluidSynth/fluidsynth/issues/391

**Comment by derselbst** [comment]
Ok, thanks for the feedback!
