### ISSUE TITLE
proposal reordering of operations in console application

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#400]
This is a review about reordering some operations in console application:
Mainly this should fixe the bug observed by this mail  http://lists.nongnu.org/archive/html/fluid-dev/2018-06/msg00044.html  

**Actual ordering is:**

- 1)creating the settings.
- 2)reading/setting all options in command line.
- 3)creating the synth.
- 4)loading the soundfonts specified in command line (multiple soundfonts loading is possible).
- 5)create the audio driver (if not fast rendering).
- 6)create the router.
- 7)create the midi driver connected to the router.
- 8)create a player and add it  any midifiles specified in command line (multiple midifiles adding is possible).
- 9)loading a default soundfont if needed before starting the player.
- 10)create a command handler.
- 11)reading the configuration file and submit it to the command handler.
- 12)create a tcp shell if any requested.
- 13)create a synchronous user shell if interactive.
- 14)entering fast rendering loop if requested.

**Proposal reordering:**
a) `Reading the configuration file (10,11)`, should be done:

- before creating the synth (3) . This ensure all settings properly initialized before any synthesis.
- and after (2), if we assume that `configuration file` should have precedence over command line options.
 
b) `Loading a default soundfont if needed before starting the player (9)` should be done also regardless  the player is started or not. So, this step should be done after (4).

**Comment by derselbst** [comment]
We cant read and execute the config file before having created the synth, because all synth related commands, e.g. select and program change as well as noteons, would be discarded. In fact we cant even read the config before having created the midi router to ensure all router related commands are executed properly.

Currently I only see three solutions:

1. Remove the `set` command, forcing everyone to initialize the settings via command line parameters.
1. Convert (all?) settings to realtime settings.
1. Read and execute the config file twice, i.e. one additional time as you suggested between 2) and 3)

**Comment by jjceresa** [comment]
Solution 1, losts the benefice of multiple configuration file.
Solution 2: Elegant. However assuming that some settings must not be realtime (or being very difficult to implement the realtime capabilities) this  solution can be inefficient in some case.
Solution 3: It is a workaround of solution 2. But works in all case. It is easy to implement via a function. I would vote for this solution. Any opinion ?

**Comment by jjceresa** [comment]
Yes my ordering was not good. May be could we put this execution of config file (10,11) just after router creation between 6) and 7) (before 8) ?.

**Comment by jjceresa** [comment]
Yes, i am aware , step (10) is the handler creation, than (11) is the execution of command file . Both steps could be moved between 6) and 7). (i.e after router and synth creation and before player creation) ?

**Comment by derselbst** [comment]
It would only conceal this issue for the midi player, but wouldnt
solve the underlying problem. Also I just realized that for my third
proposal we need an early command handler, but this command handler in
turn needs the synth at least.

We could make our life very easy by simply documenting the `set`
command as being not supported when put in a config file. Or we go
with realtime settings.

**Comment by jjceresa** [comment]
> It  would only conceal this issue for the midi player, but wouldnt solve the underlying problem.

Solution 2 (realtime): Is the most elegant , but not obvious for all settings. We need time to review
all settings realtime capabilities/dependencies. As an example a setting like `audio.period-size` probably should never be realtime capable (because of the disability of most audio driver to resize their inner buffer size in real time).

> We could make our life very easy by simply documenting the `set` command as being not supported when put in a config file. 

Yes, it worth we should document this limitation for config file.

**Comment by derselbst** [comment]
Closing this, as I dont think reordering will fix the issue described on the mailing list. It's a limitation of the `set` command, which only applies for realtime settings. This is now properly documented, users will be warned when `set`ing a non-realtime setting.

**Comment by jjceresa** [comment]
Normally making "reset" setting real time as you have done would be sufficient to fix the issue described on the mailing list. Also this make the reordering proposal now useless. Also the new interactive warning of set command is really a good thing. Thanks.
