### ISSUE TITLE
Prefer CMAKE_INSTALL_LIBDIR over LIB_SUFFIX

### ISSUE THREAD

**Issue by t-chaik** [FluidSynth/fluidsynth#411]
### FluidSynth version 
1.1.11

### Current behavior
Fluidsynth CMake scripts uses a custom `LIB_SUFFIX` variable for managing `libdir`. 

### Expected behavior
CMake's GNUInstallDirs module defines `CMAKE_INSTALL_LIBDIR` for the same thing [1]. Would probably make sense for FluidSynth to use that, would be less confusing from a user point of view.

### Other information
[1] https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

**Comment by derselbst** [comment]
Why? `LIB_SUFFIX` is pretty common and it will only be applied if the user doesnt override `LIB_INSTALL_DIR`. I dont see a benefit moving to GNUInstallDirs in this case.
