### ISSUE TITLE
Error when building on Windows with MSYS2

### ISSUE THREAD

**Issue by areeves87** [FluidSynth/fluidsynth#412]
### FluidSynth version 
1.1.11

### Current behavior

When trying to build using cmake within shell MINGW64.
I'm on Windows 7 64-bit.

$ cmake -G "MSYS Makefiles" ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:363 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "fluidsynth".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.11)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Reeves/fluidsynth-1.1.11/src/build/CMakeFiles/CMakeOutput.log".

### Other information

```
insert code snippets, soundfonts or anything relevant here, or attach it as extra file(s) if it's too much
```

**Comment by derselbst** [comment]
Which version of cmake are you using exactly? (3.11.?)

**Comment by derselbst** [comment]
And please attach `CMakeCache.txt`.

**Comment by areeves87** [comment]
Thank you so much for your reply! I was at my wit's end yesterday when I reached out for help.

Cmake is version 3.11.4.

The `CmakeCache.txt` is attached.

[CMakeCache.txt](https://github.com/FluidSynth/fluidsynth/files/2170901/CMakeCache.txt)

**Comment by derselbst** [comment]
I see. You misunderstood the build instructions. You are not supposed / allowed to navigate to navigate to `fluidsynth-1.1.11/src`. I've updated the instructions, please let me know whether it's clear now: https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake#building

**Comment by areeves87** [comment]
Thanks, yes I confused source files with the `src` folder. Using your updated instructions I successfuly built and made the fluidsynth.pc file. If I can provide any more info for your records, let me know.

**Comment by derselbst** [comment]
Great, thx!
