### ISSUE TITLE
Error running fluidsynth.exe after building on Windows 7 64 bit

### ISSUE THREAD

**Issue by areeves87** [FluidSynth/fluidsynth#413]
### FluidSynth version 
1.1.11

### Current behavior

After using cmake to successfully build and make the fluidsynth.exe with the [MSYS2 procedure](https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake#building-with-msys2-on-windows), I opened the cmd terminal as an administrator and navigated to the newly-made `src` folder within the `../fluidsynth-1.1.11/build` folder. With this folder as my working directory, and with fluidsynth.exe inside it, I enter `fluidsynth --help` in the terminal and get the following error:

"fluidsynth.exe - Application Error
The application was uable to start correctly (0xc000007b). Click OK to close the application."

### Expected behavior

Normally, `fluidsynth --help` should return some information about available commands, [etc.](https://github.com/FluidSynth/fluidsynth/wiki/GettingStarted)

### Other information

```
insert code snippets, soundfonts or anything relevant here, or attach it as extra file(s) if it's too much
```

**Comment by derselbst** [comment]
Looks like windows doesnt find some shared libraries. Try building again with

 `cmake -DBUILD_SHARED_LIBS=0 -G "MSYS Makefiles" ..`

If that doesnt work either, I'm out of ideas and you should ask the mailing list again.

**Comment by areeves87** [comment]
Okay thanks for the idea and for your continued patience. `fluidsynth --help` threw an error again after building and making with your suggested command. I will reach out to the mailing list.

**Comment by jjceresa** [comment]
>Looks like windows doesnt find some shared libraries.

@areeves87 

>"fluidsynth.exe - Application Error
The application was uable to start correctly (0xc000007b). Click OK to close the application."

Normally when a windows application start correctly (and when  any dll is referenced and not present) it will able to display the name of the shared libraries it try to  link dynamically.
In your case the issue isn't understandable. You should verify that the OS target build is making a true 64 bits executable. Particularly you should verify that the dependency libraries (glib, and other selected during cmake) used during build are valid 64 bits libraries.
just an idea relatively easy to verify.
When building a 32 bits executable fluidsynth using shared libraries with visual studio (targeted for Win 32 bit), the executable that run on a XP 32 bits **is able** to run on a 64 bits Window 7 and 10 (apart the fact that the 32 bits dll should located on a special OS folder). That means that if you try to build the same application (i.e 32 bits) using MSYS2 you should get the same result running this on a Window 7 - 64 bits. Of course MSYS2 need to be instructed to build for a win 32 bits (assuming it will be possible !).

**Comment by areeves87** [comment]
Okay so if I understand correctly you suggest a couple actions:

1. **Verify the OS target build is a 64-bit exe.** In the mingw64 terminal I verified fluidsynth.exe was built as a 64-bit executeable by typing `file fluidsynth.exe` with the terminal returning `fluidsynth.exe: PE32+ executable (console) x86-64, for MS Windows`.
2. **Verify dependency libraries are valid 64 bits libaries.** I checked what the dependency libraries are in my `CMakeCache.txt` file and found this line: 
`//Dependencies for the target
libfluidsynth_LIB_DEPENDS:STATIC=general;gthread-2.0;general;glib-2.0;general;intl;general;sndfile;general;C:/msys64/mingw64/lib/libreadline.dll.a;general;dsound;general;winmm;general;ws2_32;` But I don't know how to check whether, for example, my glib is a valid 64 bit library.
3. **Try building a 32 bit version of fluidsynth using the MSYS2 procedure**. After following the MSYS2 procedure for building a 32-bit version, I used the cmd shell to navigate to the `..fluidsynth-1.1.11/build/src` directory containing the fluidsynth executable. I entered `fluidsynth --help` into the terminal and this time got a _different_ error message:
`fluidsynth.exe - Entry Point Not Found
The procedure entry point g_cond_broadcast could not be located in the dynamic link library libglib-2.0-0.dll` This error suggests that, in contrast to the 64bit version, the 32bit version of fluidsynth starts correctly! But perhaps a dll is missing?

Thoughts on how to proceed?

Also, I am attaching some log files for reference. The files with _32 are from the 32 bit MSYS build procedure.
[build_log.txt](https://github.com/FluidSynth/fluidsynth/files/2174256/build_log.txt)
[build_log_32.txt](https://github.com/FluidSynth/fluidsynth/files/2174257/build_log_32.txt)
[CMakeLists.txt](https://github.com/FluidSynth/fluidsynth/files/2174258/CMakeLists.txt)
[make_log.txt](https://github.com/FluidSynth/fluidsynth/files/2174259/make_log.txt)
[make_log_32.txt](https://github.com/FluidSynth/fluidsynth/files/2174260/make_log_32.txt)






`

**Comment by jjceresa** [comment]
>But I don't know how to check whether, for example, my glib is a valid 64 bit library.

I am  not familiar with MSYS2 but may be you could use the command:  `file xxxxx.dll` ?

>This error suggests that, in contrast to the 64bit version, the 32bit version of fluidsynth starts correctly! But perhaps a dll is missing?

For a build using 32 bits shared library (i.e .dll) the following glib dll are needed at execution time:

- **libgthread-2.0.dll**  <- may be this one is missing in your setup ?
- libglib-2.0.dll
- intl.dll (not called by fluidsynth but called by others glib library).

**Comment by areeves87** [comment]
I got the following advice from the message boards which solved my problem:

> You cannot (naively) use the cmd.exe to run the fluidsynth binary that
> you've built in the MSYS MINGW64 shell. The MSYS shell probably sets
> up all kinds of environment variables, that make sure all .dll files
> are found during compile- and runtime. Most importantly the $PATH
> variable. That's why you should stick to the MSYS shell when
> attempting to run fluidsynth.

So I repeated the MSYS2 installation procedure for 64-bit. After the step where you run the `make` command in the MSYS shell, I navigated to the `../build/src` directory containing the `fluidsynth.exe`, still using the MSYS shell. Typing `./fluidsynth` into the MSYS shell successfully started the fluidsynth program.

**Comment by jjceresa** [comment]
>Basically, staying within the MSYS shell throughout the procedure solved my problem.

Great. Thanks for the feedback.

>Based on my experiences, it would help if it were more explicit in the directions that all commands should be entered into the MSYS shell.

Yes, i agree i have read the MSYS documentation and a lot of things are missing.

I am not a MSYS user but potentially interested by this cross-compiler tools. At the occasion , if you intend to write a paper  on how to install and use this let me know !

Also be aware that the fluidsynth Wiki https://github.com/FluidSynth/fluidsynth/wiki can be completed by anyone.

**Comment by derselbst** [comment]
> it would help if it were more explicit in the directions that all commands should be entered into the MSYS shell.

Done. Thanks for testing.
