### ISSUE TITLE
Sharing sound font among various synths.

### ISSUE THREAD

**Issue by rpvelloso** [FluidSynth/fluidsynth#420]
In my application I have several musics playing simultaneously, by now I'm opening a sound font for each 'synth' object and, hence, for each music that is playing. Is there a way to share the same sound font between various songs? Or can I share the same 'synth' object between several players?

**Comment by derselbst** [comment]
Please follow the advice of the issue template and ask questions on the mailing list. You will reach many more users.

Soundfonts are already being shared under the hood. This has been improved in version 2.0. Each player needs its own synth.
