### ISSUE TITLE
Midi channel grouping for left / right audio channel in stereo

### ISSUE THREAD

**Issue by iv41879** [FluidSynth/fluidsynth#422]
I would like to group some midi channels (instruments) to render only on left audio channel and some other midi channels (instruments) to be rendered only on right audio channel. I see there is audio grouping and rendering to more then one stereo channel supported but what about above case when we want to split within single stereo on left/right channels?

I can't find if that is possible at all right now?

Thanks

**Comment by derselbst** [comment]
Please follow the advice of the issue template and ask questions on the mailing list. You will reach many more users. And make sure to describe your environment more detailed.
