### ISSUE TITLE
Avoid usage of g_stat()

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#452]
Any effort from our side to reliably mock GStatBuf is in vain. E.g. glib-2.16 is broken as it uses `struct stat` rather than `struct _stat32` on Win x86:

https://ci.appveyor.com/project/derselbst/fluidsynth/build/job/gi5pgn6q9m5wec22#L272

Try GIO API instead.

**Comment by derselbst** [comment]
Glib upstream doesn't provide up to date prebuilt windows binaries newer >2.28. This means trouble for our windows users. Consider to setup a CI repository for building glib.

**Comment by x42** [comment]
for inspiration: https://github.com/Ardour/ardour/blob/master/libs/pbd/pbd/gstdio_compat.h

**Comment by derselbst** [comment]
Thanks.
