### ISSUE TITLE
What's the official download link for sound fonts (FluidR3_GM.sf2, FluidR3_GS.sf2)?

### ISSUE THREAD

**Issue by mojca** [FluidSynth/fluidsynth#479]
What is the official way to download `FluidR3_GM.sf2` and `FluidR3_GS.sf2`?

We are packaging fluidsynth in MacPorts and noticed the switch to GitHub after a looooong time (we were stuck with the ancient version before that), but I started wondering where the official sound files are. We have a link with homepage pointing to now defunct https://sourceforge.net/p/fluidsynth/wiki/SoundFont/

Your wiki [GettingStarted](../wiki/GettingStarted) page lists the name, but not the location from where the fonts could be fetched. While I'm able to find random fonts with that name at random places around the web, I feel somewhat uncomfortable about this. We may "steal" fonts from another linux distribution, but I would still prefer to see an official upstream location. (I would like to apologise in case the fonts are not related to your project and only use the same name.)

**Comment by derselbst** [comment]
AFAIK this soundfont is not related to fluidsynth. It was however
created for the use with fluidsynth (more or less). Debian or Ubuntu
should be a good source for the original version. The mailing list
might know more.

Our github wiki now includes the SoundFont page you are looking for.

2018-11-29 7:53 GMT+01:00, Mojca Miklavec <notifications@github.com>:

**Comment by felixniemeyer** [comment]
I was wondering the same. I'm on arch linux and not debian.  

Arch wiki links to [http://www.hammersound.net/](http://www.hammersound.net/) as the origin of FluidR3 but that website is down. 
Someone extracted the soundfont from the debian package and [provides it on GitHub](https://github.com/pinkflames/fluid-soundfont) but he compresses it as FLAC which feels weird to me. 

As an alternative, you may look here: 
MuseScore which appears to be an active user of soundfonts, has a curated list of soundfonts here: [soundfonts-and-sfz-files](https://musescore.org/en/handbook/3/soundfonts-and-sfz-files#list)
They also maintain their own soundfont "MS Basic", which can be found in [their repo](https://github.com/musescore/MuseScore/tree/master/share/sound). They also have a "FluidR3Mono_GM.sf3" in that repo.
