### ISSUE TITLE
Enviorment Setting problem

### ISSUE THREAD

**Issue by maxichu** [FluidSynth/fluidsynth#481]
Hi, I followed the instruction, and built with MSYS.
Now I got this,  may I ask what should I do next?

Thanks a lot.

![image](https://user-images.githubusercontent.com/12728844/49433860-e53ba000-f7ed-11e8-9334-c6b58b984bf9.png)

**Comment by maxichu** [comment]
Can someone tell me how to make the fluidsynth command runnable in cmd.exe on win10...
Kind of spent a whole afternoon but failed to make the environment correct...
Thanks a lot!

**Comment by jjceresa** [comment]
Here an example of the command line you can invoke.
In this example, executable 'fluidsynth.exe' , dll 'libfluidsynth-2.dll' and the soundfont files 'GUGSv1_47.sf2' are in 'D:\WinProjet\Git\GitHub\fluidsynth-VS10\src\Debug\' folder.
No need of particular 'environment'.

D:\WinProjet\Git\GitHub\fluidsynth-VS10\src\Debug\fluidsynth.exe  -g 1.0   -o audio.period-size=256 -o audio.periods=8  GUGSv1_47.sf2
