### ISSUE TITLE
-i option just quits

### ISSUE THREAD

**Issue by stanelie** [FluidSynth/fluidsynth#494]
On fluidsynth 2.0.3, if I add -i to the command line, fluidsynth just quits after initialization and doesn't keep running in the background, as expected.

If I don't use the -i option, it works and displays its command shell.

**Comment by derselbst** [comment]
This is exactly what it's supposed to do.

> doesn't keep running in the background, as expected

I don't know what makes you think so. If you want to keep it running, pass the `-s` flag additionally.

**Comment by stanelie** [comment]
Hum...
I'm confused then. Could you clarify when the -i switch should be used?
Thanks!

**Comment by derselbst** [comment]
As the documentation says: In case you don't want commands to be read from stdin. Think of a fluidsynth daemon that you start on boot-up. You would pass `-is`.

**Comment by stanelie** [comment]
The -is option works. I still have no idea why one would use the -i option alone, or why the -s option doesn't automatically include the -i option.
Thanks for the help!
