### ISSUE TITLE
-o audio.alsa.device=dmix:0 : Failed to find a workable audio format

### ISSUE THREAD

**Issue by stanelie** [FluidSynth/fluidsynth#496]
As the title says : 
When I try to use the dmix alsa device in an attempt to have the alsa sytem used by more then one application and not have it blocked by Fluidsynth, I get this error message from Fluidsynth : 
Failed to find a workable audio format

Thoughts?

**Comment by derselbst** [comment]
It means that your dmix device neither supports int16 interleaved PCM, nor float32 noninterleaved PCM. You might try using a different alsa device or even a different audio driver (e.g. jack or pulseaudio). If you have to use alsa though, I suggest you ask at the mailing list.

**Comment by stanelie** [comment]
I fiddled with /etc/asound.conf and I managed to make it work by creating a default "dmixed" device, reference here : https://stackoverflow.com/questions/14398573/alsa-api-how-to-play-two-wave-files-simultaneously . Thanks!
