### ISSUE TITLE
fluidsynth: error: Device </dev/dsp> does not exists

### ISSUE THREAD

**Issue by si-dongli** [FluidSynth/fluidsynth#499]
run fluidsynth :
$ fluidsynth 
FluidSynth runtime version 2.0.3
Copyright (C) 2000-2019 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

fluidsynth: error: Device </dev/dsp> does not exists
Failed to create the audio driver
$ 
How to solve?
my os : fedora 29

**Comment by jjceresa** [comment]
Please read the wiki https://github.com/FluidSynth/fluidsynth/wiki/FluidSettings.
