### ISSUE TITLE
Problem in installing fluidsynth for windows using MSYS

### ISSUE THREAD

**Issue by DavidPrimor** [FluidSynth/fluidsynth#502]
I'm trying to install fluidsynth  on windows using MSYS (I want to use pyfluidsynth package with my pycharm editor).

I'm following the explanation in the CMake page, but I got this error when I try to run CMake:

 MSYS /c/Users/david/fluidsynth/Build
$ cmake -G "MSYS Makefiles"
CMake Error: Could not create named generator MSYS Makefiles

What should I do? Thanks!

**Comment by derselbst** [comment]
The wiki also points out that you should contact the mailing list in case you need support.
