### ISSUE TITLE
Allow specifying compiler for gentables

### ISSUE THREAD

**Issue by mojca** [FluidSynth/fluidsynth#509]
### FluidSynth version 
2.0.3

### Current behavior

When we pass the desired C/C++ compiler to CMake, gentables compilation completely ignores that choice.

### Expected behavior

We (the package manager team) would like to be able to specify the compiler used for everything that gets built. Now, I admit that it is hard to argue why this is needed for `gentables` in particular since pretty much any compiler out there should build it fine, and there are no such issues as `libc++` vs. `libstdc++` incompatibilities as with C++ software, but please note that we go to extremes of supporting C++17 on operating systems released in 2005, and we support compiling PPC binaries on intel etc., so it's super important that all build systems behave as expected, use the correct compiler and the correct compiler flags, else we end up in problems stacking up.

### Steps to reproduce

Set `CC` and `CXX` to some compilers with a weird name before running CMake, like for example
```
export CC=/opt/local/bin/gcc-mp-9.0
export CXX=/opt/local/bin/g++-mp-9.0
cmake [parameters]
```

### Other information

Now, I've seen that this has apparently been a deliberate choice to circumvent issues with cross-compiler. I searched and didn't find any reasonable support for specifying a more finegrained control over host-guest-target fiddling in CMake. The latest CMake did improve some cross-compiling stuff, but I'm not sure if that's of any help (probably not). One strange workaround that comes to my mind would be checking whether the compiled binaries run / make a check whether we are cross-compiling or not, and keep the same compiler in case it's not cross-compiling. But honestly I'm somewhat out of good ideas.

See: https://github.com/macports/macports-ports/pull/3583

@MarcusCalhoun-Lopez @kencu

PS and off-topic: in case you have ideas how we could avoid downstream patches, please let us know:
https://github.com/macports/macports-ports/commit/13194e9f2e8894cf8bc3af1433efb5c19636ee48
I won't submit a PR as this is not a suitable patch per-se, but it would take me too much time to figure out what would be the correct code for all the cases.

**Comment by derselbst** [comment]
Sry, I don't understand your problem.

`make_tables.exe` is a stupid "python" script that generates two header files containing a bunch of lookup tables. Except that it is no python script, just a binary that can be executed on the host system during the build and then be discarded. No matter whether you are cross compiling or not, the tables always look the same on any architecture. And by "the same" I mean with a precision of 10e-7 or so. We could also autogenerate those headers and version control them, but that's lame.

> but please note that we go to extremes of supporting C++17 on operating systems released in 2005,

gentables as well as fluidsynth are written in C. It's invalid to argue with C++ here.

> so it's super important that all build systems behave as expected, use the correct compiler and the correct compiler flags

You don't need any special flag for this "python" script to "behave as expected".

> Now, I've seen that this has apparently been a deliberate choice to circumvent issues with cross-compiler.

Yes.

> One strange workaround that comes to my mind would be checking whether the compiled binaries run / make a check whether we are cross-compiling or not, and keep the same compiler in case it's not cross-compiling.

Again, that's irrelevant. `gentables` must be compiled by the host compiler so it can be executed on the host. And CMake's job is exactly that to look for a working host compiler, in case no further flags are given and environment variables are set.

> PS and off-topic: in case you have ideas how we could avoid downstream patches, please let us know:

I was not aware of this. You should still submit the patch, we can think about later whether it's suitable.

**Comment by mojca** [comment]
I will ask other project members to help clarify. As I already mentioned, it is hard for me to explain why we want to do this based on super simple C source that can be compiled with just about any compiler, and doesn't even break in your case (C code may still be written in incompatible ways, or using newer standards like C99, C11, C18, ...), but based on long years of experience compiling tens of thousands of packages, it turns out that only by having full control of which compiler and compiler flags are used we can provide a reliable way to compile software for so many different systems. This means that we often have to delete multiple flags or hardcoded compilers from upstream projects.

**Comment by derselbst** [comment]
I am a packager myself and understand the need of controlling compile flags.
But this only applies for binaries that are actually packaged. make_tables is
built, generates some text files and is thrown away right after that. For
the moment, I'm not intending to make gentables any more complicated than it
already is. Unless there's a build breakage or another good reason.

> C code may still be written in incompatible ways, or using newer standards like C99, C11, C18, ...

gentables is written in C89. New standards are backwards compatible. I don't
see how a new standard can break anything here.

> This means that we often have to delete multiple flags or hardcoded compilers from upstream projects.

An upcoming bug fix will unset any C and Linker Flags passed to it:
72cb4504bc4dfe69b58734f101774ab563ce1366


Think of gentables as fluidsynth's private python script: You don't
want to control it, because you don't need to.

**Comment by kencu** [comment]
Although @mojca indeed expresses the MacPorts default position -- being super TypeA about things helps us keep control of a big herd of cats -- you're right that there are exceptions. You make a good point about the fact that it's not installed.

@mojca -- I think we see what happens going forward. I think if there are any build troubles identified we may have a stronger case in the future, but for now the "keep it simple" approach is working for this project.

**Comment by RJVB** [comment]
If this is "just a stupid python script", why not actually (re)write it in python? Would probably simplify things at the cmake level

**Comment by derselbst** [comment]
> If this is "just a stupid python script", why not actually (re)write it in python?

[Because it would require python as dependency... ](http://lists.nongnu.org/archive/html/fluid-dev/2018-09/msg00008.html)

We already had those discussions, I don't want to go through it again. Pls. refer to:

#417 
#423
#433
http://lists.nongnu.org/archive/html/fluid-dev/2018-09/msg00004.html
#438

If there are still open questions, feel free to ask.

**Comment by RJVB** [comment]
With all due respect, in it's not a "stupid python script", it's rather stupid to call it like that O:-)

**Comment by RJVB** [comment]
(inconstructive mode off)

How about these alternatives:

- introduce options for the compiler and arguments used to build make_tables, with appropriate defaults? Probably there's only a need for the compiler if you pass on the current CMAKE_BUILD_TYPE to the external build system. It's a bit of a public secret that setting the build type to something custom gives you full control over the compiler flags via CFLAGS (and family).

- make the thing an actual python script and use that if python is installed. CMake excels at that sort of thing, and who doesn't have python installed anyways nowadays?
Sorry if that was already discussed and dismissed; I too don't want to spit through a list of exchanges to find the answer to a question that IMHO should never have been asked.

**Comment by derselbst** [comment]
> introduce options for the compiler and arguments used to build make_tables, with appropriate defaults?

Why?? Currently, there is neither a need for any compile flags nor arguments and __any__ available host compiler will do.

> who doesn't have python installed anyways nowadays?

All those Windows users who constantly express how painfully those glib and pkg-config dependencies are. I don't want to be the one explaining to them why they have to install python just to build a tiny C library like fluidsynth, do you? And don't forget the users we have on OS/2 and Solaris.

**Comment by mojca** [comment]
@derselbst: Thanks a lot for clarification.

I'm closing this issue and if needed, we'll apply a simple patch on the MacPorts side instead. (What I didn't know is that some MacPorts developers in fact have "deliberately broken" default compiler, so that they can easily catch cases with compiler choice not being respected, which is also how this was discovered in the first place. But those same developers also know how to circumvent the "problem".)

To me it also doesn't make that much sense to pull in additional dependencies like python or make stuff overcomplicated. Let's start thinking about more productive challenges than this one :)

**Comment by RJVB** [comment]
> Currently, there is neither a need for any compile flags nor arguments and __any__ available host compiler will do.

You can't guarantee that, can you now? 

- there may not be a compiler in the path for cmake to find, for whatever local reasons you are unaware of
- the compiler found by cmake may actually be a cross-compiler that produces code that won't run locally.

Both situations may seem contrived, but not impossible, and can be dealt with trivially using existing cmake hooks.

> All those Windows users who constantly express how painfully those glib and pkg-config dependencies are.

That argument can easily apply to using the host compiler too, if you assume that has to be installed from source. My MSWin computers have always had some python version installed that I never built myself; there are at least 2 sources for python installers. I don't know about OS/2 but Solaris is Unix and indeed has python:
https://blogs.oracle.com/solaris/python-on-solaris
http://unixpackages.com/packages/package-matrix/?frm_search=python

Anyway that argument is a bit moot in a context where python is already installed, as stipulated in my 2nd alternative above...

More to the point: has anyone ever written an actual python implementation? Or an implementation in another more-or-less standard interpreted language?

**Comment by RJVB** [comment]
> to pull in additional dependencies like python or make stuff overcomplicated.

A priori you don't need to if the host python is good enough.

**Comment by derselbst** [comment]
@mojca To clarify: If gentables really causes builds to break downstream, anybody is welcome to file a bug and upstream will see how to fix it. If you ask me: macports should not patch that.

---

> Kind of stupid that they don't want to use an interpreted language to generate the necessary tables because that would add a dependency. I didn't go over the list of tickets and/or other kinds of exchanges they referenced as justification for not reopening that discussion. Could be worth it to have a look if there is no pointer to a working python implementation in there, which we might be able to use.

@RJVB Thank you very much for admitting to not even have clicked on the links above, outstanding commitment.

**Comment by RJVB** [comment]
Why would I have any more motivation to dig through those than you have to discuss the topic again? My commitment is to the port, the project is yours.

Long story short: if what I asked for exists, confirming that could well get us out of your hair.

**Comment by derselbst** [comment]
> Why would I have any more motivation to dig through those than you have to discuss the topic again?

Everything you've mentioned here and in macports has already been discussed.

> Long story short: if what I asked for exists, confirming that could well get us out of your hair.

Click the links and find out yourself to learn what is most suitable as a custom solution.

**Comment by realnc** [comment]
Typical. As soon I post this, I find the mistake...

Disregard by previous comment. User error. Don't `export CMAKE_TOOLCHAIN_FILE` in the build environment. You need to pass it to the cmake invocation instead.
