### ISSUE TITLE
Registers in JACK as two elements: Audio and Midi, instead of just one

### ISSUE THREAD

**Issue by yurivict** [FluidSynth/fluidsynth#510]
See the screenshot below.
Please observe how Carla registers as one element, but Fluidsynth registers as two elements.
It is more natural to register one program to be one element.

![fluidsynth-bug-jack-split](https://user-images.githubusercontent.com/271906/52539422-c2b88c80-2d32-11e9-817f-684a08442b12.png)

**Comment by derselbst** [comment]
I think that this was fixed by #434.
