### ISSUE TITLE
problem with pyFluidSynth

### ISSUE THREAD

**Issue by RZz96** [FluidSynth/fluidsynth#511]
i have installed pyFluidSynth using pip but import pyFluidSynth give an error :ModuleNotFoundError: No module named 'pyFluidSynth'

**Comment by derselbst** [comment]
pyfluidsynth is here: https://github.com/nwhitehead/pyfluidsynth

**Comment by RZz96** [comment]
i installed from there also but the import dosnt work

**Comment by derselbst** [comment]
This is the wrong project for python question. Ask at pyfluidsynth pls.

**Comment by RZz96** [comment]
why i have error : Couldn't find the FluidSynth library?
