### ISSUE TITLE
Troubles when building for Windows

### ISSUE THREAD

**Issue by carlo-bramini** [FluidSynth/fluidsynth#514]
I'm having some troubles at compiling FluidSynth after latest commits:

1) compilation fails because some GLIB macros like `G_FILE_TEST_IS_REGULAR` are undefined. In my opinion, perhaps it would be worth to have an "fopen" function that does the job of `default_fopen()`, rather than having a `fluid_file_test` function called multiple times.

2) I'm getting these messages:

> C4273: 'fluid_get_stdin' : inconsistent dll linkage.  dllexport assumed.
> C4273: 'fluid_get_stdout' : inconsistent dll linkage.  dllexport assumed.

Because `fluid_get_stdin` and `fluid_get_stdout` are defined in both `include/fluidsynth/shell.h` and `src/utils/fluid_sys.h`, but in a different manner. I could fix it myself, but it is not clear to me where these declarations should stay and how.

**Comment by derselbst** [comment]
> compilation fails because some GLIB macros like G_FILE_TEST_IS_REGULAR are undefined.

It works fine for our appveyor builds. Did you build an unmodified version?

> perhaps it would be worth to have an "fopen" function that does the job of default_fopen(), rather than having a fluid_file_test function called multiple times.

`default_fopen()` verbosely reports errors, which I didn't want to have elsewhere. Also, care must be taken to not break any existing behaviour that may be achieved by using pipes with e.g. the file renderer or the midi player. I may take care of this later.

> Because fluid_get_stdin and fluid_get_stdout are defined in both include/fluidsynth/shell.h and src/utils/fluid_sys.h

Fixed in bfc03136bb836fbc0dfee44d8845da8a6c181e1f, thx.

**Comment by derselbst** [comment]
> compilation fails because some GLIB macros like G_FILE_TEST_IS_REGULAR are undefined.

@carlo-bramini Is this still an issue? If so, could you please provide further information?

**Comment by carlo-bramini** [comment]
> @carlo-bramini Is this still an issue? If so, could you please provide further information?

Well, when compiling with GLIB, there are no problems.
The problem happens when I tried to rebuild with my native port for Windows.
It is true that GLIB is an unavoidable dependency in the official builds, at least at the time of writing, but actually FluidSynth has virtualized everything, including very standard functions like strcpy(), so avoiding the direct usage of `G_FILE_TEST_IS_REGULAR` macro and similar would be helpful.

**Comment by derselbst** [comment]
> avoiding the direct usage of G_FILE_TEST_IS_REGULAR macro and similar would be helpful.

Ok, I will take care of that when implementing that `default_fopen()` mentioned earlier. But for now, I'd like to release 2.0.4.
