### ISSUE TITLE
fluid_event_system_reset & sound cracks

### ISSUE THREAD

**Issue by desunit** [FluidSynth/fluidsynth#517]
Hi,

I was trying to use `fluid_event_system_reset` when the MIDI file is interrupted to be sure that all voices are turned off but I've noticed that when I try to play another MIDI file immediately after that then there I hear static cracks in the speaker. The reset method:
```
        fluid_event_t *evt = new_fluid_event();
	fluid_event_set_source(evt, -1);
	fluid_event_set_dest(evt, synthSeqID);
	fluid_event_system_reset(evt);
	int time = fluid_sequencer_get_tick (_fluidSequencer);
	if (fluid_sequencer_send_at(_fluidSequencer, evt, (unsigned int)time, 1) != FLUID_OK)
		LOGE("can't send system reset");
	delete_fluid_event(evt);
```
What I've noticed that when I call `fluid_synth_write_s16` I could eliminate them (mostly) but the problem with that approach that it causes deadlocks. Is there a better way how to eliminate cracks or interrupt playing?

Any thoughts on how to fix that issue would be great!

**Comment by derselbst** [comment]
1. Which version of fluidsynth are you using?
2. Which platform and OS are you using?
3. Are you using an audio driver of fluidsynth? If yes, which one? If not, how are you playing audio and how many samples are you requesting from `fluid_synth_write_*()` during each call?
4. Does it happen with any MIDI file?
5. Does it happen with any soundfont?
6. What do you mean by "when the MIDI file is interrupted"?
6. Have you tried `fluid_event_all_sounds_off()` and does it reproduce the same behaviour?
6. Which "deadlocks" are you referring to, where do they occur?

**Comment by desunit** [comment]
Thanks! It looks I've found what was going on. I was using it with OpenSL callbacks which continue working even when I try to stop them (looks like race conditions since not so easy to reproduce). That explains why `fluid_synth_write_s16` could cause deadlocks. I've added mutex and the problem disappeared.
