### ISSUE TITLE
Still timing issues - now with the command line program

### ISSUE THREAD

**Issue by prof-spock** [FluidSynth/fluidsynth#519]
This is a repetition of #192 (that has already been closed for 1.1.7).
But there still seems to be some problem with the timing; I have tried version 1.1.10, 1.1.11 and 2.0.1 with
[drums-test.zip](https://github.com/FluidSynth/fluidsynth/files/2968621/drums-test.zip)
The midi file and the flac file generated by fluidsynth on a Windows command line are not in sync (but they should).
Any ideas?

**Comment by derselbst** [comment]
I see, the flac plays slightly faster than it's supposed to be. Did you use the file renderer? I also wonder why the AllNotesOff event triggers a noteon.

**Comment by prof-spock** [comment]
I used the commandline fluidsynth with the "-F" flag as follows:
    fluidsynth.exe -n -i -g 1 -R 0 -F drums-test.wav FluidR3_GM.SF2 drums-test.mid

**Comment by derselbst** [comment]
I looked into this. The midi file you provided does not specify the tempo. The MIDI spec says that in this case a default of 120 BPM should be assumed. The midi player of fluidsynth however uses 125 BPM as default. I've fixed that in the commit above.

**Comment by prof-spock** [comment]
Thanks a lot, derselbst! Precise analysis, quick fix...
