### ISSUE TITLE
fluid_synth_write_s16 outputting random noise

### ISSUE THREAD

**Issue by TheDiscoMole** [FluidSynth/fluidsynth#522]
I want to use use Fluidsynth to iteratively build short audio samples from MIDI notes in Python and initially found the [pyFluidsynth](https://github.com/nwhitehead/pyfluidsynth) library for this. Unfortunately this library is out of date and fails due to deprecated API calls so I decided to take what i needed from the code and just write my own:

```

from ctypes import *
from ctypes.util import find_library

import numpy as np

lib = find_library('fluidsynth') or find_library('libfluidsynth')

if lib is None:
    raise ImportError("Couldn't find the FluidSynth library.")

def cfunc(name, result, *args):
    """Build and apply a ctypes prototype complete with parameter flags"""
    atypes = []
    aflags = []
    for arg in args:
        atypes.append(arg[1])
        aflags.append((arg[2], arg[0]) + arg[3:])
        return CFUNCTYPE(result, *atypes)((name, _fl), tuple(aflags))

new_fluid_settings = cfunc('new_fluid_settings', c_void_p)
fluid_settings_setstr = cfunc('fluid_settings_setstr', c_int,
    ('settings', c_void_p, 1),
    ('name', c_char_p, 1),
    ('str', c_char_p, 1))

new_fluid_synth = cfunc('new_fluid_synth', c_void_p,
    ('settings', c_void_p, 1))

fluid_synth_noteon = cfunc('fluid_synth_noteon', c_int,
    ('synth', c_void_p, 1),
    ('chan', c_int, 1),
    ('key', c_int, 1),
    ('vel', c_int, 1))
fluid_synth_noteoff = cfunc('fluid_synth_noteoff', c_int,
    ('synth', c_void_p, 1),
    ('chan', c_int, 1),
    ('key', c_int, 1))

fluid_synth_write_s16 = cfunc('fluid_synth_write_s16', c_int,
    ('synth', c_void_p, 1),
    ('len', c_int, 1),
    ('lbuf', c_void_p, 1),
    ('loff', c_int, 1),
    ('lincr', c_int, 1),
    ('rbuf', c_void_p, 1),
    ('roff', c_int, 1),
    ('rincr', c_int, 1))

class Synth:
    
    def __init__ (self):
        self.settings = new_fluid_settings()
        fluid_settings_setstr(self.settings,b'audio.driver','pulseaudio'.encode())
        self.synth = new_fluid_synth(self.settings)
    
    def wave (self,len=1024):
        buf = create_string_buffer(len * 4)
        err = fluid_synth_write_s16(self.synth,len,buf,0,2,buf,1,2)
        
        if err == -1:
            print ('WARNING: midi to wave generation error')
        
        return np.frombuffer(buf[:],dtype=np.int16)

    def noteon (self,chan,key,vel):
        fluid_synth_noteon(self.synth,chan,key,vel)

    def noteoff (self,chan,key):
        fluid_synth_noteoff(self.synth,chan,key)
    
if __name__ == '__main__':
    
    synth = Synth()
    
    synth.noteon(0, 60, 30)
    synth.noteon(0, 67, 30)
    synth.noteon(0, 76, 30)
    
    wave = synth.wave(100)
    
    print (wave)
    
    synth.noteoff(0, 60)
    synth.noteoff(0, 60)
    synth.noteoff(0, 60)
    
    wave = synth.wave(100)
    
    print (wave)
```

the test is just taken straight from `pyFluidsynth` and is supposed to be a certain cord, but all i get back is numpy arrays of 0s -1s and 1s, like:

`[ 0 0 0 0 -1 0 0 0 1 -1 ... 0 0 -1 0 1 1 1 0 -1]`

everyhing else seems to work fine, for example using my Fluidsynth in command line with:

`fluidsynth -a pulseaudio -m alsa_seq file.midi`

This plays just fine.

No errors occur during the `Synth` initialisation and `noteon/off` stuff. Additionally the `synth.wave` function does error checking which is never triggered.

Any ideas? does my script work on your end? Are there any issues with `fluid_synth_write_s16`?

**EDIT:** So when adding the error check to the `noteon` and `noteoff` it appears that adding the notes fails silently, but since i have understanding of how to do this callback logging with ctypes in python i am stumped on how to proceed to investigate the issue. Also this doesn't explain why and uninitialized note spectrum doesn't give out an all 0 array.

**Comment by derselbst** [comment]
> [ 0 0 0 0 -1 0 0 0 1 -1 ... 0 0 -1 0 1 1 1 0 -1]

This randomization is intendedly caused by fluidsynth's [dithering](https://en.wikipedia.org/wiki/Dither#Digital_audio) algorithm.

>     wave = synth.wave(100)

Given a default sample rate of 44100 Hz, requesting only 100 frames to render means requesting 2ms of audio. Very likely being too short to give any audible sound. But even if you requested more frames: Where should the audio come from? You haven't loaded any soundfont.

**Comment by TheDiscoMole** [comment]
Thanks for the response,

I don't care about audible audio length, the goal is actually to render exactly 5ms of sound and use the numpy array outputs for further processing.

In regards to the soundfont, I am running `Arch Linux` and followed the [Arch Wiki Fluidsynth](https://wiki.archlinux.org/index.php/FluidSynth) entry and created a symbolic link for the default soundfont with:

 `ln -s /usr/share/soundfonts/FluidR3_GM.sf2 /usr/share/soundfonts/default.sf2`

This is why I can use Fluidsynth from the command line without specifying a sounfont when simply trying to play a MIDI. Does this automatic soundfont not work for the way I am trying execute Fluidsynth through Python C-types?

**Comment by derselbst** [comment]
> Does this automatic soundfont not work for the way I am trying execute Fluidsynth functions through Python C-types?

As pointed out by [the documentation](http://www.fluidsynth.org/api/fluidsettings.xml#synth.default-soundfont), `synth.default-soundfont` is specific to the fluidsynth executable only.

**Comment by TheDiscoMole** [comment]
Hey, thanks finally had time to try it.

Adding the manual soundfont worked, but I am still confused by the output. What I want is to be able use `fluid_synth_write_s16` to iteratively generate each sound "frame" per MIDI tick to train a neural network to play piano by ear, but the output at the few ms frame range is just silence. Is there a way to achieve what i need? Like is there a consistency in the wave generation that allows me to synth like 44100 samples and just take some `x` offset like `samples[x:x+250]` ?

It must be possible to take correctly synthesized small samples, otherwise whats the use of the `fluid_synth_write_s16` function?

**Comment by TheDiscoMole** [comment]
Never mind, after finding [this](https://fluid-dev.nongnu.narkive.com/rTIVOQJ8/fluid-synth-write-and-sequencer-queries) discussion on something similar I realized is was making an obvious mistake. I was turning the notes on over and over each synthesization iteration, making them start from 0.

thanks for your help though would have never guessed the soundfont thing.
