### ISSUE TITLE
Detecting number of cores

### ISSUE THREAD

**Issue by carlo-bramini** [FluidSynth/fluidsynth#531]
Hello,
this line:

https://github.com/FluidSynth/fluidsynth/blob/c9a670d26c71cff2fc74c882a15222f1a2a2ebaa/src/synth/fluid_synth.c#L226

configure multi-core processing when ENABLE_MIXER_THREADS is defined.
The default value sets the maximum number of mixing threads to 256 and a single thread as current value.
What do you think about adding a feature for detecting the number of logical cores available in the system? On Windows, it would be something like this:

```
int fluid_get_num_cores(void)
{
#ifdef _WIN32
    SYSTEM_INFO si;

    GetSystemInfo(&si);
    return si.dwNumberOfProcessors;
#else
    return 256;
#endif
}
```
which is something I'm using in my branch.
So, that line in fluid_synth.c will be:

`fluid_settings_register_int(settings, "synth.cpu-cores", 1, 1, fluid_get_num_cores(), 0);`

or, if you would like to optimize also the initial number of threads:

```
n = fluid_get_num_cores();
fluid_settings_register_int(settings, "synth.cpu-cores", (n == 256) ? 1 : n, 1, n, 0);
```

what do you think?
Sincerely.

**Comment by mawe42** [comment]
What immediately comes to mind is hyperthreading. Does dwNumberOfProcessors give the number of hardware cores, or does it also take hyperthreading into account?

I must admit I don't understand why would you want to force an upper limit on the number of threads. After all, there is no actual harm in using four threads on a single core system. It could be just for experimentation, or the person running Fluidsynth knows something you don't... like a special process scheduler that is incredibly efficient in terms of processing time, energy, etc.

So in my opinion, settings an upper limit sounds like a bad idea.

As to the default number of cores... on the plus side it would probably mean that most non-technical users would see an increase in performance, because they probably don't know about this setting and never adjust it to their platform. More technically-minded people either have that setting at their preferred value already or rely on the default being 1. So I have no string opinion on this change. But is there a reliable way to detect the number of (physical/logical?) cores on all/most platforms we support?

**Comment by carlo-bramini** [comment]
> What immediately comes to mind is hyperthreading. Does dwNumberOfProcessors give the number of hardware cores, or does it also take hyperthreading into account?

It returns the number of logical processors. So, if for example you have a dual-core CPU with hyperthreading, it returns 4.

> I must admit I don't understand why would you want to force an upper limit on the number of threads.

I arrived to this conclusion after pratical usage. I started my software and I wanted that it could take advantage of efficent parallel processing. So, I setup the "synth.cpu-cores", but later I was thinking if FluidSynth could be smart enought for doing it transparently.

> But is there a reliable way to detect the number of (physical/logical?) cores on all/most platforms we support?

Well, the function can simply return 256 and in this case it will work as it worked until now, no?

However, I admit that we are talking about a thing that an user can do without troubles in his software, at least for me it is not a problem to call `GetSystemInfo()` and then `fluid_settings_setint()` for setting "synth.cpu-cores" after `new_fluid_settings()`. In this way, the library is free from this platform-dependent stuff. It depends if you like it or not, or if you think it could be helpful.

**Comment by carlo-bramini** [comment]
> I must admit I don't understand why would you want to force an upper limit on the number of threads.

Sorry, I also forgot to write that I was thinking to do that:

```
fluid_settings_getint_range(settings, "synth.cpu-cores", &imin, &imax);
fluid_settings_setint(settings, "synth.cpu-cores", imax);
```

if the final user wanted to set the multi-processing to its maximum efficiency, without worry too much.
But this would be redundant if the library sets also the start value and not only the upper limit.

Sincerely.

**Comment by mawe42** [comment]
> if the final user wanted to set the multi-processing to its maximum efficiency, without worry too much.

And that's the thing... "maximum efficiency". I agree that setting the number of render threads to the number of logical cores is probably going to be most efficient. But my guess is that it might depend on the target platform. By preventing anyone from setting it to a higher value (which you effectively do if you determine the max cores from system info), you take that control away from the user.

So I see why we might want to set a default or maybe even a recommended range for the number of render threads based on system info, but I'm strongly against changing the maximum allowed threads.

**Comment by derselbst** [comment]
For the record: I share Marcus' concerns about the upper limit. Regarding the default value: Yes, fluidsynth might be smart enough to adjust it, however it would be a too severe change in current behaviour at this point I'm afraid. Thus I'd also vote to leave it up to the user app.

**Comment by mawe42** [comment]
@carlo-bramini The way you closed this issue without further comment makes me wonder if I came across too strong. If I did, then please accept my apology. And please bear in mind that I'm just voicing my opinion, and a single one at that.

I'm only strongly against limiting the maximum number of threads. Having a way to configure Fluidsynth with the "likely optimum" number of render threads still sounds like a viable idea. What about extending the ```synth.cpu-cores``` setting with a value to indicate "automatic"? Maybe with a value of -1. And then a little down the road, then it proved useful, we could make it the new default.

**Comment by carlo-bramini** [comment]
Sorry, excuse me if I did not reply, I have seen this only now. There are not problems, actually it is not a big effort to detect the number of useful core inside the application instead of the library, at least it is not on Windows, so if you prefer to keep the library "generic", it is good anyway. I was thinking that it was clear that both choices were good to me, so that's why I closed the thread without more comments. But this seems that it has caused a misunderstand, I'm sorry...

Sincerely.

**Comment by ThreeDeeJay** [comment]
On a side note, how would we make FluidSynth use all available cores?
It doesn't matter if I set `synth.cpu-cores` to 1, 8, 64, 256, etc., it doesn't really go over 30% CPU usage (and I see the extra threads in task manager, but high values actually slow it down) so converting several files in batch seems slower than it should be. Is there a way to make it use more resources to speed up processing or is there a bottleneck/limit set somewhere? 🤔

**Comment by derselbst** [comment]
You need to have many voices playing for increased CPU consumption. And effects should be enabled, ideally by using multiple effect groups.

**Comment by ThreeDeeJay** [comment]
> You need to have many voices playing for increased CPU consumption. And effects should be enabled, ideally by using multiple effect groups.

@derselbst Hmm, shouldn't that just apply to realtime playback though? what I'm trying to do is render several (thousands) of [MIDIs into files using different soundfonts](https://airtable.com/shrisbbTdiSawCkuK), hopefully as efficiently and quickly as possible so I'm assuming it should be using all resources available, but increasing cores as suggested by the official documentation doesn't seem to make any difference. 

> Sets the number of synthesis CPU cores. If set to a value greater than 1, additional synthesis threads will be created to do the actual rendering work that is then returned synchronously by the render function. **This has the affect of utilizing more of the total CPU for voices or decreasing render times when synthesizing audio**. So for example, if you set cpu-cores to 4, fluidsynth will attempt to split the synthesis work it needs to do between the client's calling thread and three additional (internal) worker threads. As soon as all threads have done their work, their results are collected and the resulting buffer is returned to the caller. 
https://www.fluidsynth.org/api/settings_synth.html

I read somewhere that the other relevant command (`synth.threadsafe-api`) only applies on Linux and I'm on windows so I wonder if that's why multi-threading doesn't work 🤔

**Comment by derselbst** [comment]
Wavetable synthesis is low on CPU usage by nature. When there is not enough work to do, increasing CPU cores won't change anything. That's what my comment above meant. 

Your use case and usage are vaguely described. If you need serious advice, provide a precise description of _what_ and _how_ you do it, as well as enough example data to reproduce your issue. This is not the right place for discussing this.
