### ISSUE TITLE
Question about fluid_synth_set_gen() - instrument release

### ISSUE THREAD

**Issue by MaKiPL** [FluidSynth/fluidsynth#544]
### FluidSynth version 
2.0.5 + DLS support

Hello,
After the artifact appeared for windows with libinstpatch I began to implement audio in my project, however it turns out that the DLS loaded has wrong release, attack and others values. More or less they are default which is wrong. Now after browsing the API I found the `fluid_synth_set_gen()` that lets you edit the generator for channels- does that mean I'm able to edit the _Modulation envelope release_ and _Volume envelope release_ from the API? I tried to alter the values corresponding to available values from SoundFont 2 documentation but there seems to be no change at all. I also tried to load casual GS.sf2 and iterated over every possible `synth_gen_type` to see what are the values for soundfont that has good release and all I'm getting is 0 in every single value- that's because 0 means default, right?

Therefore how should I use this `fluid_synth_set_gen()` method to alter the instrument release amount? Does fluidsynth makes it possible to alter some parsed values of the soundfont?

**Comment by mawe42** [comment]
The `fluid_synth_set_gen()` and `fluid_synth_get_gen()` functions set the NRPN part of the generator value. Basically the final value of the generator is the sum of the initial value set in the Soundfont, the current value from all modulators with this generator as target and the NRPN offset value (which defaults to 0). So when you use `fluid_synth_set_gen()` to alter a generator, it's important to know that it is only part of a sum and can therefore be used as an offset. And that `fluid_synth_get_gen()` does not retrieve the generator value set in the Soundfont, but only the NRPN offset.

Also bear in mind that the NRPN values are not real-time, they are only taken into account when the voice is created (i.e when a new note-on message arrives).

Not sure about the DLS code, but it looks like it should read and set the generators properly...

**Comment by mawe42** [comment]
And as the name suggests, you don't need to use the API to set NRPN generator values. You can also use CC MIDI messages. See the Soundfont Spec 2.04 section 9.6 on page 59. For example, to increase the volume envelope release time to maximum, you would send the following:
```
CC 0 99 120  # NRPN select on channel 0
CC 0 90 38    # Chooses generator 38 for channel 0 (volEnvRelease)
CC 0 38 127  # LSB of generator 38 offset for channel 0
CC 0 6 127    # MSG of generator 38 offset for channel 0
```
Then a when you start a new note and send note-off straight after, it will have a maximum release time.

**Comment by MaKiPL** [comment]
Thank you, it worked!
