### ISSUE TITLE
No way to pass -r to jackd

### ISSUE THREAD

**Issue by glixx** [FluidSynth/fluidsynth#546]
Please implement option to pass parameters to jackd.

**Comment by derselbst** [comment]
AFAIK, jackd does not provide an API call to set the sample rate on the fly.

**Comment by glixx** [comment]
Flag -r disables real time.

**Comment by glixx** [comment]
I'm about situation when fluidsynth runs jackd if jackd is not running yet.
On FreeBSD no way to disable realtime for jack, but user does not have permissions to run jack realtime, but by default it starts with -R.

**Comment by derselbst** [comment]
Ok, so you are talking about jack's command line options, not fluidsynth's.

The jack server is started implicitly when a first client connects to it. We neither have any control nor knowledge if/how the server will be started or if it is already run. Also, when looking through jack's API, there seems to be no way to pass any parameters to jack that influence the start of the jack server.
