### ISSUE TITLE
Building errors, it seems that some packages are missing, how to get them?

### ISSUE THREAD

**Issue by gpblg** [FluidSynth/fluidsynth#552]
``The C compiler identification is GNU 5.1.0
Check for working C compiler: C:/TDM-GCC-64/bin/gcc.exe
Check for working C compiler: C:/TDM-GCC-64/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Checking whether system has ANSI C header files
Looking for 8 include files dlfcn.h, ..., float.h
Looking for 8 include files dlfcn.h, ..., float.h - not found
ANSI C header files - not found
Looking for include file unistd.h
Looking for include file unistd.h - found
Looking for DIR in sys/stat.h;sys/types.h;dirent.h
Looking for DIR in sys/stat.h;sys/types.h;dirent.h - found
Looking for string.h
Looking for string.h - found
Looking for stdlib.h
Looking for stdlib.h - found
Looking for stdio.h
Looking for stdio.h - found
Looking for math.h
Looking for math.h - found
Looking for errno.h
Looking for errno.h - found
Looking for stdarg.h
Looking for stdarg.h - found
Looking for memory.h
Looking for memory.h - found
Looking for sys/mman.h
Looking for sys/mman.h - not found
Looking for sys/time.h
Looking for sys/time.h - found
Looking for sys/ioctl.h
Looking for sys/ioctl.h - not found
Looking for fcntl.h
Looking for fcntl.h - found
Looking for sys/socket.h
Looking for sys/socket.h - not found
Looking for netinet/in.h
Looking for netinet/in.h - not found
Looking for netinet/tcp.h
Looking for netinet/tcp.h - not found
Looking for arpa/inet.h
Looking for arpa/inet.h - not found
Looking for limits.h
Looking for limits.h - found
Looking for pthread.h
Looking for pthread.h - found
Looking for signal.h
Looking for signal.h - found
Looking for getopt.h
Looking for getopt.h - found
Looking for stdint.h
Looking for stdint.h - found
Performing Test _have_inline
Performing Test _have_inline - Success
Performing Test _have_vla
Performing Test _have_vla - Success
Check if the system is big endian
Searching 16 bit integer
Looking for stddef.h
Looking for stddef.h - found
Check size of unsigned short
Check size of unsigned short - done
Using unsigned short
Check if the system is big endian - little endian
Looking for windows.h
Looking for windows.h - found
Looking for io.h
Looking for io.h - found
Looking for dsound.h
Looking for dsound.h - found
Looking for include files windows.h, mmsystem.h
Looking for include files windows.h, mmsystem.h - found
Looking for inet_ntop
Looking for inet_ntop - not found
Found PkgConfig: D:/Linux-File/tool/bin/pkg-config.exe (found version "0.23") 
Checking for modules 'glib-2.0>=2.6.5;gthread-2.0>=2.6.5'
  Found glib-2.0, version 2.26.1
  Found gthread-2.0, version 2.26.1
Checking for module 'sndfile>=1.0.0'
  No package 'sndfile' found
Checking for module 'libpulse-simple>=0.9.8'
  No package 'libpulse-simple' found
Checking for module 'jack'
  No package 'jack' found
Checking for module 'dbus-1>=1.0.0'
  No package 'dbus-1' found
Looking for ladspa.h
Looking for ladspa.h - not found
Checking for module 'libinstpatch-1.0'
  No package 'libinstpatch-1.0' found
Checking for module 'sdl2'
  No package 'sdl2' found
Could NOT find READLINE (missing: READLINE_INCLUDE_DIR READLINE_LIBRARIES) 
Looking for sinf
Looking for sinf - found
Looking for cosf
Looking for cosf - found
Looking for fabsf
Looking for fabsf - found
Looking for powf
Looking for powf - found
Looking for sqrtf
Looking for sqrtf - found
Looking for logf
Looking for logf - found
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 

**************************************************************
Build Summary:
Build type:            RelWithDebInfo
Install Prefix:        C:/Program Files (x86)/FluidSynth

Audio / MIDI driver support:
  ALSA:                  no
  CoreAudio:             no
  CoreMIDI:              no
  DSound:                yes
  JACK:                  no
  MidiShare:             no
  Oboe:                  no
  OpenSLES:              no
  OS/2 DART:             no
  OSS:                   no
  PortAudio:             no
  PulseAudio:            no
  SDL2:                  no
  WaveOut:               yes
  WinMidi:               yes

Support for SF3 files:   no (libsndfile not found)
Support for DLS files:   no (libinstpatch not found)

Audio to file rendering: yes
  libsndfile:            no (RAW PCM rendering only)

Miscellaneous support:
  D-Bus:                 no
  LADSPA support:        no
  LASH support:          no
  NETWORK Support:       yes
    IPV6 Support:        no
  Readline:              no
  systemd:               no

Developer nerds info:
  Samples type:          double
  Multithread rendering: yes
  OpenMP 4.0:            no
  Profiling:             no
  Debug Build:           no
  Trap on FPE (debug):   no
  Check FPE (debug):     no
  UBSan (debug):         no

**************************************************************

Configuring done

**Comment by derselbst** [comment]
What is your problem? It says "Configuring done", now you have to compile it. Check out the wiki for information on how to do that:

https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake
