### ISSUE TITLE
Allow audio render to STDOUT

### ISSUE THREAD

**Issue by FalcoGer** [FluidSynth/fluidsynth#553]
### Is your feature request related to a problem?
I wish to pipe the output of fluidynth audio data to another program. Writing to /dev/stdout however gives me this error:

```
fluidsynth -a pulseaudio -d -F /dev/stdout /usr/share/sounds/sf2/FluidR3_GM.sf2 sample.mid
FluidSynth version 1.1.9
Copyright (C) 2000-2018 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

Rendering audio to file '/dev/stdout'..
RIFWAVEfmt D��dataRIFWAVEfmt D��data����fluidsynth: error: Failed to open audio file '/dev/stdout' for writing
```

### Describe the solution you'd like
Allow `-F -` or `-F STDOUT` or similar to put the stream as a byte stream to standard output.

**Comment by mawe42** [comment]
Please see this libsndfile FAQ entry: http://www.mega-nerd.com/libsndfile/FAQ.html#Q017

As explained there, rendering WAV to a pipe is difficult, as the header needs to be filled in with information that is not known until the complete audio data has been rendered. But you can use other file formats to render, for example `raw`, `au`, or `flac`. Just specify the output format on your command line, for example with `-o audio.file.format=au`.

One thing to note is that currently the fluidsynth command line program **always** prints a welcome message to stdout. So your resulting file will have non-audio text garbage at the beginning. But it's of a predicable length, so you can either filter it out before using the output somewhere else... or you could send your output to a different pipe. A quick'n dirty test with stderr worked well for me:
`fluidsynth -a none -F /dev/stderr  /path/to/song.mid /path/to/font.sf2 -o audio.file.type=au 2> test.au`

Or... you can write your own program that uses the the Fluidsynth API to fast render to stdout.

**Comment by mawe42** [comment]
@FalcoGer As #554 has just been merged, you could also try out the new `-q / --quiet` option. :-)

Oh, and bear in mind that rendering the audio to stdout and having it spew binary data to your terminal will probably break. But redirecting it to a file or other program works fine.

So this breaks:
```
$ fluidsynth -a none -F- test.mid test.sf2 -o audio.file.type=au -q
.snd�����Dfluidsynth: error: Failed to open audio file '-' for writing
```

But this works fine:
```
$ fluidsynth -a none -F- test.mid test.sf2 -o audio.file.type=au -q | aplay
Playing Sparc Audio 'stdin' : Signed 16 bit Big Endian, Rate 44100 Hz, Stereo
```

**Comment by derselbst** [comment]
Documentation added to wiki and man page. Will be available in 2.1 .

**Comment by hyansuper** [comment]
Is it possible to perform live(like interactive shell) and also redirect output to a pip or a file?
what I am trying to do is to have a interactive gui on one computer and send sound data to a remote sound peripheral

**Comment by mawe42** [comment]
Please don't post usage questions in issues, and especially not closed issues. Use our [discussion forum](https://github.com/FluidSynth/fluidsynth/discussions) or the [fluid-dev mailing list](http://lists.nongnu.org/mailman/listinfo/fluid-dev) instead.
