### ISSUE TITLE
Sound font version is 3.1 but fluidsynth was compiled without（I use android version）

### ISSUE THREAD

**Issue by zhouzhihao07** [FluidSynth/fluidsynth#556]
![TIM图片20190817225108](https://user-images.githubusercontent.com/8677018/63213665-9a767400-c141-11e9-9b39-b709e7fedaec.png)
   Sound font version is 3.1 but fluidsynth was compiled without（FluidR3Mono_GM.sf3）
why？

**Comment by mawe42** [comment]
You compiled fluidsynth without libsndfile support, so you can't load SF3 files. Either use SF2 files or conpile in libsndfile.

**Comment by zhouzhihao07** [comment]
> You compiled fluidsynth without libsndfile support, so you can't load SF3 files. Either use SF2 files or compile in libsndfile.

I had installed libsndfile,but  I should how to compile in libsndfile.

**Comment by zhouzhihao07** [comment]
![QQ图片20190820111731](https://user-images.githubusercontent.com/8677018/63315038-4388be80-c33c-11e9-9214-39760be0ca87.png)
File contains data in an unimplemented format

**Comment by mawe42** [comment]
Looks like your libsndfile was compiled without support for the ogg vorbis format.

**Comment by zhouzhihao07** [comment]
> Looks like your libsndfile was compiled without support for the ogg vorbis format.

I find that there is a lot of work to do if I want to use sf3. Does the code you provided support the use of sf3 on android phones? Besides, I use sf2 without sound, why?Is it related to the libsndfile library?

**Comment by zhouzhihao07** [comment]
> Looks like your libsndfile was compiled without support for the ogg vorbis format.

![QQ图片20190828160719](https://user-images.githubusercontent.com/8677018/63837430-0c568500-c9ae-11e9-81a1-3d2a132d2c78.png)
To support ogg vorbis format., I used cmake -DENABLE_EXTERNAL_LIBS=ON and needed to install flac, which depends ON nasm, so I added nasm, but there was an error in the figure below. It feels so hard, is it beyond my ability to solve. Please reply to me, if it is difficult to achieve, I am going to give up.
![QQ图片20190828161433](https://user-images.githubusercontent.com/8677018/63838181-74f23180-c9af-11e9-8d2b-f83c825cb753.png)

**Comment by mawe42** [comment]
Sorry, but this is not a support forum for building nasm for Android or any other platform. Please ask the nasm developers for help.

And for support requests about fluidsynth, please use our mailing-list:
https://lists.nongnu.org/mailman/listinfo/fluid-dev

This bug tracker is for fluidsynth *bugs* and *feature requests* only. If you post to the mailing-list, you will reach more people anyway, including people who have already built fluidsynth on Android.
