### ISSUE TITLE
MIDI files may fail to play

### ISSUE THREAD

**Issue by ThunkMonkey** [FluidSynth/fluidsynth#557]
I am using the FluidSynth API to play MIDI files on Windows as shown [here](http://www.fluidsynth.org/api/index.html#MIDIPlayer):
```
    settings = new_fluid_settings();
    synth = new_fluid_synth(settings);
    player = new_fluid_player(synth);
    adriver = new_fluid_audio_driver(settings, synth);
    /* process command line arguments */
    for (i = 1; i < argc; i++) {
        if (fluid_is_soundfont(argv[i])) {
           fluid_synth_sfload(synth, argv[1], 1);
        }
        if (fluid_is_midifile(argv[i])) {
            fluid_player_add(player, argv[i]);
        }
    }
    /* play the midi files, if any */
    fluid_player_play(player);
```
Sometimes the MIDI files fail to play.

I dug into this issue, and I suspect there is a race condition between the audio driver initialization and the player configuration. I think [this code](https://github.com/FluidSynth/fluidsynth/blob/master/src/midi/fluid_midi.c#L2065-L2074) in `fluid_player_callback` is to blame:
```
        if(loadnextfile)
        {
            loadnextfile = 0;
            fluid_player_playlist_load(player, msec);

            if(player->currentfile == NULL)
            {
                return 0;
            }
        }
```
When the audio driver is created, it looks like it starts an asynchronous operation that ends up calling `fluid_player_callback` at some point. If the playlist has not been initialized by then, `fluid_player_callback` will `return 0` and never get called again.

Indeed, if I ensure `new_fluid_audio_driver` is called after calling `fluid_player_add`, the problem goes away, but that doesn't seem like the best option to fix this. Ideally, I should be able to create one synthesizer and audio driver combination and then use that with multiple players. I am trying to use FluidSynth for a game and will need to start and stop multiple MIDI files during gameplay.

**Comment by derselbst** [comment]
> I am using the FluidSynth API to play MIDI files on Windows as shown here:

Oh, our example code seems to be wrong. I'll fix that, thanks for the hint.

> Indeed, if I ensure new_fluid_audio_driver is called after calling fluid_player_add, the problem goes away,

This is the correct way to use the player.

> When the audio driver is created, it looks like it starts an asynchronous operation that ends up calling fluid_player_callback at some point.

Once you start an audio driver, a synthesization thread is created, see the [note here](http://www.fluidsynth.org/api/audio_8h.html#a4ad51317b10b89bfe94ade5db345864b).

> Ideally, I should be able to create one synthesizer and audio driver combination and then use that with multiple players.

I don't think that this will work. The MIDI player was designed to use only one unique synth. Ofc, feel free to try using multiple player with one synth, but without any manual mixing the MIDI events this will end up in a huge cacophony.

> I am trying to use FluidSynth for a game and will need to start and stop multiple MIDI files during gameplay.

You may consider to use the sequencer instead. In this case, your game would be responsible for collecting the MIDI events from the files and send them to fluidsynth. A bit more work, but you'll gain greater flexibility.
