### ISSUE TITLE
Android: only 'file' driver is available

### ISSUE THREAD

**Issue by lastant** [FluidSynth/fluidsynth#558]
After compiling Fluidsynth 2.0.6 for Android ARM64 with `-Denable-opensles=1 -Denable-oboe=1`, integrating it as a shared library and reading the `audio.driver` setting, there is only `file` in the list...

**Comment by derselbst** [comment]
...because neither opensles nor oboe is implemented in 2.0.6 . These are features for 2.1, which hasn't been released yet. If you want to use it right now, you'll have to build the master branch. You are welcome to provide feedback how it works at our mailing list. But this is clearly not a bug.

**Comment by lastant** [comment]
Ok. But when I'm trying to build the master, the linker is missing the following libraries:
libOpenSLES.so
libandroid.so
liblog.so
libc++_shared.so

Which packages do I need to build extra?

**Comment by lastant** [comment]
@derselbst I managed to link it manually with adding the arguments `-Wl,-rpath=...`, it works now!
But I need to copy multiple .so libraries to the device for it to work, which is over 10MB altogether. Is it somehow possible to compile it into one smaller library?
