### ISSUE TITLE
Multiple Jack Outputs

### ISSUE THREAD

**Issue by holborn2019** [FluidSynth/fluidsynth#570]
### FluidSynth version
_Execute `fluidsynth --version` and provide the output._

### Describe the bug
_Provide a clear and concise description of the current situation, e.g. how the bug manifests._

### Expected behavior
_Provide a clear and concise description of what you expected to happen._

### Steps to reproduce
_Please explain the steps required to duplicate the issue, esp. if you are able to provide a sample application. E.g. how to start fluidsynth, what shell commands to enter, what midi events to send, etc._

### Additional context
_If you are able to illustrate the bug with an example, please provide simple
source code below or as attached file. List any other information that is relevant to your issue, e.g. stack traces, related issues, build logs, suggestions on how to fix, links to related discussions at fluid-dev, etc._

```
insert code snippets, soundfonts or anything relevant here, or attach it as extra file(s) if it's too much
```

**Comment by holborn2019** [comment]
FluidSynth runtime version 2.0.7
Copyright (C) 2000-2019 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.
FluidSynth executable version 2.0.7
Sample type=double
Using the git version :-)

Linux p4 5.3.4 #1 SMP PREEMPT Mon Oct 7 09:49:08 WEST 2019 i686 GNU/Linux
bullseye/sid
Compiled with gcc (Debian 9.2.1-9) 9.2.1 20191008



Hi
Thanks for this peace of wonder ....fluidsynth is a wonder :-)

When multiple jack outputs enabled .... fx 1 doesent have signal ...  I was read the code and I reach to have changing line 3713 of fluid_synth.c ...  

3713 for(i = 0; i < nfxchan+1; i++)

I know that the better way maybe is change the nfxchan value ...  but due the long and complex the code is.. I prefer dont touch so much.

And the most important that affect to both effect output ...im not a engineer ..im just musician but I really think that the signal level LR on both effects need to be relative not just with the control change 91 and 93  .... need to be panned as well ...  with control change 10 maybe not at all in case of the reverb due the reverb is what is ... but need to be ... and sure on the chorus .... because sounds really ugly when u have some channel panned to left or right that have lot of effect and u hear just the effect on the other channel ....well I think would sound more realistic :-)

Thanks

**Comment by derselbst** [comment]
> When multiple jack outputs enabled .... fx 1 doesent have signal

fx1 carries the chrous signal only. If you don't have chorus enabled in fluidsynth or the MIDI doesn't make use of CC93 you won't hear any chorus.

> And the most important that affect to both effect output ...im not a engineer ..im just musician but I really think that the signal level LR on both effects need to be relative not just with the control change 91 and 93 .... need to be panned as well ... with control change 10 maybe not at all in case of the reverb due the reverb is what is ... but need to be ... and sure on the chorus .... because sounds really ugly when u have some channel panned to left or right that have lot of effect and u hear just the effect on the other channel ....well I think would sound more realistic

Perhaps you ... should ... try to ... in case ... you want me ... to understand ... anything ... speak in ... proper sentences ... using proper word order ... so I can ... without asking my ... magic crystal ball ... comprehend your ... twisted thoughts ......... easily.

**Comment by jjceresa** [comment]
:)

**Comment by holborn2019** [comment]
Yes after some more checks you have the truth ... my mistake ...sorry  close this bug.

I was try to use external effects with fluidsynth  using the effects output channels that provide jack when you active the jack multi channel output.
I was just using the level parameters provided on fluidsynth effects to have signal level of each channel but not the internal fluidsynth effect. Works fine on fluidsynth internal reverb but  on the fluidsynth internal chorus that also needed the voice parameter "N" up to 2 at least.

I was up just the levels and that was my mistake.

Im really sorry and sorry also for my bad english.

Then close the bug ... but still have the request .... I will try to explain better ....

If you have a channel using Reverb and Chorus ... and you pan this channel to left or to the right   ... the main signal is panned on the main stereo outputs "lr" .All perfect. 
But is not panned on the stereo effects outputs "fx_l_0x" " fx_r0x" ...  and I think would be really better if its also panned on the stereo effect outputs.

Hope u can understand :-)

Thanks 
Josep

**Comment by holborn2019** [comment]
Hi ... 
Hi again.

Thinking about my request ....  if you want the true sound ... a channel that is using Chorus and Reverb ... wondering is already panned this chorus and reverb effects :-) ..... to have the true sound you also need to put on the reverb the output of the chorus effect  ... in case that the channel has the reverb activated. 

Im asking so much .. i know :-)
Thanks for the patience.

Josep

**Comment by derselbst** [comment]
> If you have a channel using Reverb and Chorus ... and you pan this channel to left or to the right ... the main signal is panned on the main stereo outputs "lr" .All perfect.
But is not panned on the stereo effects outputs "fx_l_0x" " fx_r0x" ... and I think would be really better if its also panned on the stereo effect outputs.

What you are suggesting would sound very strange, at least for reverb. Think of it: You are sitting in a big empty hall. Somebody to the left plays some instrument. Only your left ear will receive the direct, "dry" sound. But the "wet" reverberating sound will spread all over the hall, so also your right ear will hear some "wet" sound. The amount of this  *stereo spreading* can be controlled with the  [reverb's width setting](https://github.com/FluidSynth/fluidsynth/wiki/UserManual#reverb).

Chorus is currently monophonic. This will be changed by #548. But don't expect such a rich stereo spread like the reverb has.

> to have the true sound you also need to put on the reverb the output of the chorus effect

That would be an overkill. fluidsynth is not claiming to be a highly detailed, rich sound, realistic effect audio simulation software. It is rather a CPU **inexpensive** real-time synth.
