### ISSUE TITLE
Patch to automatically open/close OSS MIDI device(s) and FIFOs

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#58]
Hi,  

Extended fluidsynth usage on FreeBSD 8.0  

mkfifo /midi  

fluidsynth -o midi.oss.device0=/midi -o midi.oss.device1=/dev/umidi0.0  

Allows multiple MIDI streams to co-exist, in addition to more seamless integration with pluggable devices.  

\--HPS  

Reported by: hselasky

Original Ticket: [fluidsynth/tickets/58](https://sourceforge.net/p/fluidsynth/tickets/58)

**Comment by derselbst** [comment]
Sry, the patch seems to be lost and I dont consider OSS midi to be dying. If you're still following this issue or need the functionality anyway, please speak up. Closing for now.

**Comment by hselasky** [comment]
FYI: We now have ALSA sequencer support in FreeBSD. And can possibly use that.
