### ISSUE TITLE
Low frequency clipping at 96kHz

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#580]
### FluidSynth version
2.0.x ~(and 1.1.x, IIRC)~

### Describe the bug
Low frequencies tend to clip when rendering at 96 kHz. Weirdly, it seems to matter which audio driver is used for playing. For me, clipping occurs with jack and sdl2, and when rendering via `fluid_synth_process()`, but not when using alsa. Investigation needed.

However: issue is not related to reverb. Reverb just makes the clipping more obvious, but it also occurs in dry sound.

**I would like to know:** Is there anybody able to reproduce the clippings for any audio driver?

### Expected behavior
Not clipping should occur.

### Steps to reproduce
Demo MIDI is attached below. A sample rendering of the clipping is included (clipping is quite evidently audible at the beginning of the file).

Using the following command:

```bash
fluidsynth -C0 -a sdl2 -jnil  -o synth.sample-rate=96000 -o synth.reverb.room-size=0.8 -o synth.reverb.damp=0.1 -o synth.reverb.width=0 -o synth.reverb.level=0.8 DP.sf2 DP_0xF.mid
```

### Additional context

[DP_0x1E.zip](https://github.com/FluidSynth/fluidsynth/files/3770858/DP_0x1E.zip)
[DP_0xF.zip](https://github.com/FluidSynth/fluidsynth/files/3768838/DP_0xF.zip)
[Soundfont to use](https://github.com/derselbst/ANMP-data/raw/dk64-defmod/soundfonts/N64/DP.sf2)

**Comment by jjceresa** [comment]
1)I heard clipping on the `tom percussion instrument` at the beginning of  DP_0xF_96khz.mid.ogg sample rendering.

2)Here using fluidsynth 2.0.7, `sr:96000Hz`,  `dsound` driver  doesn' clip but  with `waveout` it clip.
3)Using sr:48000Hz , `waveout` doesn't clip. 



should

**Comment by jjceresa** [comment]
1)I heard clipping on `tom-tom percussion instrument` at the beginning of `DP_0xF_96khz.mid.ogg` sample rendering.

2)Here using fluidsynth 2.0.7, playing the MIDI file using the same command as in previous comment: 
2.1)`sr:96000Hz`, `dsound` driver doesn' clip but with `waveout `driver it clip.
2.2) Using `sr:48000Hz` , `waveout` doesn't clip.

3)If we hear clipping  when playing through `audio driver` or through `file driver (i.e rendering)` does it means that clipping is probably produced by fluidsynth rather the driver  ?

3.1) Assuming than (3) is true, what could be the response of the fluidsynth filter on percussive instrument  at sr:96000Hz ?

**Comment by derselbst** [comment]
> If we hear clipping when playing through audio driver or through file driver

I had the same though. So far, I haven't been able to reproduce the clipping via the file renderer. HOWEVER, when rendering via `fluid_synth_process()` (in my custom player app) and writing that output to a file, it clips again... so strange.

Also, keep in mind that those clips are actually processed by the reverb engine. The clips are not dry, they are wet... thus, it must be an issue in fluidsynth. 

I think I will just test all the four rendering functions one after another. But still, I think I'll release a 2.1 prerelease in the next days. This bug is not a showstopper.

> what could be the response of the fluidsynth filter on percussive instrument at sr:96000Hz ?

Ah, you mean the IIR filter? That's a good idea, I'll keep this in mind.

**Comment by derselbst** [comment]
Just added another example [DP_0x1E.zip](https://github.com/FluidSynth/fluidsynth/files/3770858/DP_0x1E.zip). Below the corrupt waveform.

![Screenshot_20191025_092320](https://user-images.githubusercontent.com/8152480/67551703-ceee4980-f709-11e9-813f-0eebd5e82992.png)

**Comment by jjceresa** [comment]
>So far, I haven't been able to reproduce the clipping via the file renderer. HOWEVER, when rendering via fluid_synth_process() ...., it clips again... so strange.

>I think I will just test all the four rendering functions one after another. 

Yes, it is necessary to determine if clipping occurs before calling rendering function or not.
Note that  fluid_synth_write_s16()  call `round_clip_to_i16()` that does a true clipping [-32768..32767]. This is an interesting feature, because the resulting waveform observed should be flat (i.e constant) in the clipping region (note that in your picture example below , corrupted waweform isn't flat !). Also for debugging purpose it is easy to insert a `printf("clip\n")` when clipping occurs. May be, such a  `round_clip_to_float()` could be added (for debugging only) for other rendering functions.

****
>1)However: issue is not related to reverb. Reverb just makes the clipping more obvious, but it also occurs in dry sound.

>2)Also, keep in mind that those clips are actually processed by the reverb engine. The clips are not dry, they are wet... thus, it must be an issue in fluidsynth.

Sorry, now I am a bit in trouble. I think you suspect that clipping occurs before reverb with the risk that those clipping will be "sustained" by the reverb ?.

In all cases it will be better to try with reverb and chorus both off.

A bit out of subject: Now i think that adding a developer option  `peak meter` would be useful. But this is another story.

**Comment by derselbst** [comment]
> I think you suspect that clipping occurs before reverb with the risk that those clipping will be "sustained" by the reverb ?.

Yes. To me it sounds like the clipping gets it's own "reverb".

So far I tested the following scenarios (Chorus always off, reverb on/off doesn't make a significant change):

| Driver                             | rendering func.   |  |
|----------------------------------|-------------------------|------------------|
| SDL2                             | fluid_synth_write_s16   | clipping audible |
| Jack                             | fluid_synth_process     | clipping audible |
| Jack                             | fluid_synth_write_float | clipping audible |
| Alsa                             | fluid_synth_write_s16   | not audible      |
| fast file renderer with libsndfile    | fluid_synth_write_float | not audible      |
| fast file renderer without libsndfile | fluid_synth_write_s16   | not audible      |

...not really enlightening. Will continue investigating.

**Comment by jjceresa** [comment]
> 2.1)sr:96000Hz, dsound driver doesn't clip..

Sorry I must correct me. I was wrong, even dsound driver clip (only at sr:96KHz). 

I did tests using my MIDI keyboard using `GUGSv1_47.sf2 (Christian Collins)`, playing `one note` at a time, reverb and chorus off, sr:96kHz.
-1) Mainly all percussive `preset` clip only at the `beginning` of the note (during attack). 
If we pay attention to play note at `low velocity`, we hear a very `short clip` not very loud but obviously audible on each note. Then once a note has been started, the rest of the note (hold, decay,sustain, release) is clean.
-2) Preset (1 to 40) clip all except 7:Harpsichord , 20:church organ , 25: nylon guitar, 26:Steel guitar that seem clean.
-3) Following preset 41:violin, 42, 43,.. doesn't clip (they aren't percussive).

**Comment by derselbst** [comment]
Found it! It's a regression introduced in 907ec27a9ee3cb22217d61e045ec36ae164e3ee0. Will make a fix.
