### ISSUE TITLE
Output of reverb depends on sample rate used

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#581]
### FluidSynth version 
\>=2.0.0

### Current behavior
_This is not really a bug, just a question to understand what's going on..._

I observed that the reverb output has a (somewhat strong) dependency on the sample rate being used for rendering.

Trying sample rates 22050, 48000 and 96000 Hz, to me personally 22050 Hz sounds best. 48000Hz has many more high frequencies, of course, which is still ok though. At 96000Hz, however, reverb "decays" much slower than at 48kHz. Also, the "wobble" is more evident for 96kHz. (In case you don't hear what I mean, try exaggerating the effect by hacking fluidsynth to render at 196kHz).

### Expected behavior
The difference between 48kHz and 96kHz should me "smaller" (?). Opinions?

Again, this is no request for change. Ofc. there must be a dependency to the sample rate. Just trying to understand things.

### Steps to reproduce
Using the MIDI and soundfont below with this command:

```bash
fluidsynth -C0 -a WhateverYouLike -jnil -o synth.sample-rate=96000 -o synth.reverb.room-size=0.8 -o synth.reverb.damp=0.1 -o synth.reverb.width=0 -o synth.reverb.level=0.8 DK64.sf2
```

### Other information

[DK64-JJ-Underground.zip](https://github.com/FluidSynth/fluidsynth/files/2080291/DK64-JJ-Underground.zip)
[Soundfont to use](https://github.com/derselbst/ANMP-data/raw/dk64-defmod/soundfonts/N64/DK64.sf2)

For testing purposes, you may also check out the example MIDI provided in #580, and hear how it correlates with sample rate.

@jjceresa I'm assigning you, as you are the expert for reverb related issues. Would be great if you could look into this.

**Comment by jjceresa** [comment]
>Would be great if you could look into this.

I will do. First we must review and document how `hard` is reverb `dependency in regard to `sample rate`. I need time to review how was the behaviour of the previous reverb (`freeverb`) compared to the new one (`fdn-reverb`).

>At 96000Hz, however, reverb "decays" much slower than at 48kHz. Also, the "wobble" is more evident for 96kHz.

I always had difficulties for reproducing this "wobble". I need time to investigate using the supplied files (.mid and .sf2).

**Comment by jjceresa** [comment]
>Trying sample rates 22050, 48000 and 96000 Hz, to me personally 22050 Hz sounds best. 48000Hz has many more high frequencies, of course, which is still ok though. At 96000Hz, however, reverb "decays" much slower than at 48kHz. Also, the "wobble" is more evident for 96kHz. 
1)Test
Confirmed. For sample rate > 44100Hz, the reverb tail quality is degraded (this more obvious for sr > 48000Hz).

> Also, the "wobble" is more evident for 96kHz.
I think you refer to "ringing" (resonant frequencies) or "low beating of resonant frequencies" (beating is at very low frequency).

Testing this is far more  obvious in the following conditions: Using percussive note, One note at a time, maximum room size (1.0), minimum damping(0.0), minimum width (0.0), hearing with a head phone.

2)Explanations:
Actually, delays length are constant and give a sound result that is convenient for sr:44100Hz.
The reason of this degradation (for sample rate > 44100Hz) is that the delay line length should dependent of sample rate .  I forgot completely this and, I consider this as a bug.

3)Solutions:
3.1)In theory we should have a set of delay length for each sample rate value (implemented as a bank of sample rate range), which is difficult to implement. 
3.2)Instead, I propose a simple compensation of the delay length for sample rate > 44100Hz. 
This should give "smaller" acceptable difference for sample rate > 44100Hz.
I will propose a PR implementing this.

**Comment by jjceresa** [comment]
>Trying sample rates 22050, 48000 and 96000 Hz, to me personally 22050 Hz sounds best. 48000Hz has many more high frequencies, of course, which is still ok though. At 96000Hz, however, reverb "decays" much slower than at 48kHz. Also, the "wobble" is more evident for 96kHz.

1)Testing:
Confirmed. For sample rate > 44100Hz, the reverb tail quality is degraded (this more obvious for sr above 48000Hz).

>Also, the "wobble" is more evident for 96kHz.

I think you refer to "ringing" (resonant frequencies) or "low beating of resonant frequencies" (beating is at very low frequency).

Testing this is far more obvious in the following conditions: Using percussive note, One note at a time, maximum room size (1.0), minimum damping(0.0), minimum width (0.0), hearing with a head phone.

2)Explanations:
Actually, delays length are constant and give a sound result that is convenient for sr:44100Hz.
The reason of this degradation (for sample rate > 44100Hz) is that the delay line length should dependent of sample rate . I forgot completely this and, I consider this as a bug.

3)Solutions:
3.1)In theory we should have a set of delay length for each sample rate value (implemented as a bank of sample rate range), which would difficult to implement.
3.2)Instead, I propose a simple compensation of the delay length for sample rate > 44100Hz.
This should give "smaller" acceptable difference for sample rate > 44100Hz.
I will propose a PR implementing this.

**Comment by jjceresa** [comment]
>Trying sample rates 22050, 48000 and 96000 Hz, to me personally 22050 Hz sounds best. 48000Hz has many more high frequencies, of course, which is still ok though. At 96000Hz, however, reverb "decays" much slower than at 48kHz. Also, the "wobble" is more evident for 96kHz.

1)Testing:
Confirmed. For sample rate > 44100Hz, the reverb tail quality is degraded (this more obvious for sr above 48000Hz).

>Also, the "wobble" is more evident for 96kHz.

I think you refer to "ringing" (resonant frequencies) or "low beating of resonant frequencies" (beating is at very low frequency).

Testing this is far more obvious in the following conditions: Using percussive note, One note at a time, maximum room size (1.0), minimum damping(0.0), minimum width (0.0), hearing with a head phone.

2)Explanations:
Actually, delays length are constant and give a sound result that is convenient for sr:44100Hz.
The reason of this degradation (for sample rate > 44100Hz) is that the delay line length should be dependent of sample rate . I forgot completely this and, I consider this as a bug.

3)Solutions:
3.1)In theory we should have a set of delay length for each sample rate value (implemented as a bank of sample rate range), which would difficult to implement.
3.2)Instead, I propose a simple compensation of the delay length for sample rate > 44100Hz.
This should give "smaller" acceptable difference for sample rate > 44100Hz.
I will propose a PR implementing this.

**Comment by jjceresa** [comment]
>Trying sample rates 22050, 48000 and 96000 Hz, to me personally 22050 Hz sounds best. 48000Hz has many more high frequencies, of course, which is still ok though. At 96000Hz, however, reverb "decays" much slower than at 48kHz. Also, the "wobble" is more evident for 96kHz.

1)Testing:
Confirmed. For sample rate > 44100Hz, the reverb tail quality is degraded (this more obvious for sr above 48000Hz).

>Also, the "wobble" is more evident for 96kHz.

I think you refer to "ringing" (resonant frequencies) or "low beating of resonant frequencies" (beating is at very low frequency).

Testing this is far more obvious in the following conditions: Using percussive note, One note at a time, maximum room size (1.0), minimum damping(0.0), minimum width (0.0), hearing with a head phone.

2)Explanations:
Actually, delays lengths are constant and give a sound result that is convenient for sr:44100Hz.
The reason of this degradation (for sample rate > 44100Hz) is that each delay line `length` should be dependent of `sample rate` . I forgot completely this, I consider this as a bug.

3)Solutions:
3.1)In theory we should have a set of `delays lengths` for each `sample rate` value (implemented as a set for each bank of sample rate range), which would be difficult to implement.
3.2)Instead, I propose a simple compensation of the `delay length` for `sample rate > 44100Hz`.
This should give "smaller" acceptable difference for sample rate > 44100Hz.
I will propose a PR implementing this.

**Comment by derselbst** [comment]
> > Also, the "wobble" is more evident for 96kHz.
> 
> I think you refer to "ringing" (resonant frequencies)

I referred to the higher resonant frequencies, yes.

> each delay line length should be dependent of sample rate .

Sounds plausible, thanks. Yeah, I think 3.2) seems to be a good approach then.
