### ISSUE TITLE
Potential issues on sample rate changes

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#585]
Note this potential issue has been noted in PR https://github.com/FluidSynth/fluidsynth/pull/584

1)Note there is still a potential issue calling `fluid_revmodel_samplerate_change()`. If the function fail, the caller have no possibility to know that the function fail because the function return void.
But the function could be changed to return a status (FLUID_FAILED, FLUID_OK).

2)Note that this potential issue already exists in the previous reverb (freeverb) in which the same function makes memory allocation but silently doesn't return an error if malloc fail.

3)Actually the caller is DECLARE_FLUID_RVOICE_FUNCTION(fluid_rvoice_mixer_set_samplerate)

This caller silently doesn't check result when calling new_fluid_chorus(samplerate);
Also, this caller silently doesn' tcheck result when calling fluid_revmodel_samplerate_change();
This potential issue exists when calling fluid_revmodel_samplerate_change(samplerate) and the `sample rate` is augmented so that malloc could fail.

4) If this caller is running in the audio task context, I don't know how he could check the status and take appropriate action  ?.

5) I don't remember when sample rate changes occurs ? when any API function is called ?.

**Comment by derselbst** [comment]
Having thought about it... `fluid_synth_set_sample_rate` is broken by design. 

`fluid_synth_set_sample_rate` only dispatches an event. The actual sample rate change is executed during rendering. You're right, if memeory allocation fails there is no way for the caller to know. And we would end up with a corrupted effect unit.

I see two options:

1. deprecate `fluid_synth_set_sample_rate` and discourage its usage
1. when creating the reverb initially, allocate all the maximum memory we might potentially (ever) need, i.e. allocate for 96kHz.


> I don't remember when sample rate changes occurs ? when any API function is called ?.

I think this function was added, because the jack driver could spontaneously say: "Dear fluidsynth, my sample rate has changed. Pls. do something." ...And this something IMO would be to delete the synth and recreate it. On the other hand, I've never observed jack doing sample rate changes on-the-fly.

**Comment by jjceresa** [comment]
Having a capability of sample rate change on-the-fly while the synth is rendering will always produce some artifact ("clic", "pop") on the dry sound and also for chorus and the reverb because LFOs (chorus and reverb) need to be reinitialized due to new sample rate change. So I don't find these sample rate changes useful.

I would vote  for
1) Deprecate `fluid_synth_set_sample_rate` and discourage its usage  and
2) Encourage application for deleting the synth and recreate it with the new sample rate when needed.

**Comment by jjceresa** [comment]
>Having a capability of sample rate change on-the-fly while the synth is rendering 

I forgot to say that having a new `sample rate change on-the-fly` applied to the synth, require also  this `new sample rate` be applied to the `audio driver` in use (if any exist in the current application). It means that the application have to delete the audio driver and than recreate it.
In fact different components of the fluidsynth library are really dependent of the sample rate, and the application is the only one that knows which components to use. Consequently it seems that the application is the only one that can deal properly in case of sample rate change need.
As said above `fluid_synth_set_sample_rate()` appears to be broken by design.

**Comment by jjceresa** [comment]
>Having a capability of sample rate change on-the-fly while the synth is rendering

I forgot to say that having a new `sample rate change` on-the-fly applied to the synth, requires also this new sample rate be applied to the `audio driver` in use (if any exist in the current application). It means that the application have to delete the audio driver and than recreate it.
In fact different components of the fluidsynth library are really dependent of the sample rate, and the application is the only one that knows which component to use. Consequently it seems that the application is the only one that can deal properly in case of sample rate change need.
As said above `fluid_synth_set_sample_rate()` appears to be broken by design.
