### ISSUE TITLE
Wrong filename version when building v2.1.0

### ISSUE THREAD

**Issue by lhondareyte** [FluidSynth/fluidsynth#601]
Hi,
When building fluidsynth lib, the version is wrong:
```
git clone https://github.com/FluidSynth/fluidsynth.git
cd fluidsynth
git checkout v2.1.0
mkdir build && cd build && cmake .. && cd src && ls *.so.*
...
lrwxrwxrwx 1 luc users      18 Dec 17 19:44 libfluidsynth.so -> libfluidsynth.so.2
lrwxrwxrwx 1 luc users      22 Dec 17 19:44 libfluidsynth.so.2 -> libfluidsynth.so.2.3.0
-rwxr-xr-x 1 luc  users 1630304 Dec 17 19:44 libfluidsynth.so.2.3.0
```
The filename should be` libfluidsynth.so.2.1.0`. Checked on FreeBSD 12 and Debian 9
Regards

**Comment by lhondareyte** [comment]
After some digging, there is perhaps with a problem with `$LIB_VERSION`:
```
luc@unxbox:~/fluidsynth# grep -r  LIB_VERSION CMakeLists.txt 
set ( LIB_VERSION_CURRENT 2 )
set ( LIB_VERSION_AGE 3 )
set ( LIB_VERSION_REVISION 0 )
...
```
But I am not familliar with `cmake `

**Comment by derselbst** [comment]
You are confusing `SOVERSION` and `project version`. The `SOVERSION` (i.e. library version) indicates API/ABI compatibility. The `project version` indicates bugfix releases, new feature releases and breaking-change releases.

For more information about this versioning scheme, see: 
https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html

Specifically:

> Never try to set the interface numbers so that they correspond to the release number of your package. This is an abuse that only fosters misunderstanding of the purpose of library versions.
