### ISSUE TITLE
out of memory while loading sfont in c#

### ISSUE THREAD

**Issue by veritas501** [FluidSynth/fluidsynth#602]
### FluidSynth version
2.1.0

### Describe the bug
I write a dll function to use fluidsynth to convert midi to wav.
When I call this function from C++ program, every thing was fine, but when I call this function from C# program, it shows :
```
fluidsynth: error: Out of memory
fluidsynth: error: Attempted to read 621046190 words of sample data, but got -1 instead
```
This size equals to 592MB, which is my soundfont2 file's size.

First i think it may be C#'s fault and i write a sample test demo.
DLL side:
```
int DoTest(){
    if(malloc(621046190)){
        return 1;
    }
    return 0;
}
```
I call this function in C#, it return 1. Then i test the maximum size in C#, and get 3.9G.
So it may not C#'s fault.

I have no idea how to fix this problem 😢

**Comment by derselbst** [comment]
Well, according to the error message, fluidsynth is unable to allocate memory. Looking at the code, the error handling could be improved in this case, I'll see what can be done.

> When I call this function

Which function? Is that the only soundfont you are loading? Is there something in the C# world already occupying a lot of memory?

Note that it says `621046190` _words_, i.e. `621046190 * 2` bytes. So update your test dll and try again. If it still fails, your memory might be too fragmented. In this case: did you try to reboot your PC?

Btw, your test dll should free() the memory.

**Comment by veritas501** [comment]
After serveral tests, I finally find the nuget package called fody.PropertyChanged which I use it to write mvvm INotifyPropertyChanged cause it. 🤣 
Althrough I still don't know how this package cause this bug, but it's absolutely not fluidsynth's fault.
Any way, thanks for your reply.  🙏
