### ISSUE TITLE
Example of hosting fluidsynth in another application

### ISSUE THREAD

**Issue by reduz** [FluidSynth/fluidsynth#603]
Looking at the source code, I am not seeing a way from my application to create Fluidsynth instances (from C/C++ using the library), where I pass the MIDI events and get audio back. Is this possible? If not, is it too difficult to add?

**Comment by derselbst** [comment]
This is no support forum. Consult the mailing list, pls.

**Comment by reduz** [comment]
But you can ask for features and doc, right? This is what it says in the issue template.
Well, thanks for the warm answer, but not planning to use the mailing list anyway.
