### ISSUE TITLE
Add Processing Time Offset Parameter

### ISSUE THREAD

**Issue by prof-spock** [FluidSynth/fluidsynth#618]
Hello derselbst,

I have a somewhat esoteric request: how complicated is it to add an API (and possibly command line) parameter for shifting the processing time of fluidsynth?
The use case is as follows:
* I have some midi file _M1_ that is processed via fluidsynth giving wave file _W1_.
* Then I cut that midi file at time _t_ and process its remainder _M2_ via fluidsynth giving wave file _W2_.
* Now I split _W1_ at time _t_ giving _W3_.
* My hope is that (apart from some transients) _W2_ and _W3_ are identical.

But, of course, they are not. I assume that some free-running oscillators for modulators are not in sync, because they start at time _0_ in _W1_ and _W2_, but at time _t_ in _W3_.
If there were some magical parameter `offsetTime`, one could process _M2_ with `offsetTime=t` and have the oscillators run for time _t_ before processing _M2_.

Okay, everybody in his right mind says: why don't you just _W3_ for a split audio? But this does not work for me, because I use fluidsynth in two ways:
* I process _M1_ via a command-line giving _W1_.
* Additionally I have midi file _M1_ as a track _T1_ in a DAW with fluidsynthVST as the plugin.
* On another track _T2_ I have wave file _W1_.
* I try to compare output of _T2_ with the realtime output of  _T1_ (by subtracting them).

This works quite well when starting the rendering at 0:00 (apart from some fixed VST processing offset that can be compensated), but fails for above reason when rendering starts somewhere in the middle. But this could work in principle, when the VST can tell the libfluidsynth library to "start" at the current DAW time.
I assume that syncing oscillators to some given time might be complicated, but then the remaining processing should be straightforward.
Is this reasoning plausible? Or do I miss something important?

Best regards,
Prof. Spock

**Comment by derselbst** [comment]
Well, adding a time offset as you suggest is complicated enough (due to several LFOs as you correctly noted). But even with such an offset I'm afraid that it wouldn't fix your problem. There are a couple more time depending on parameters that influence the rendered waveform. The

* state of the IIR filter,
* state of the ADSR envelopes,
* the pitch and volume of each voice (which we linearly interpolate between 64 frames of rendered audio), and
* the delay lines in reverb and chorus

are coming to my mind ATM. So, I'm think it's practically impossible to get all of them in sync.

Instead of "cutting" _M1_, have you considered to simply kill all noteon events in _M1_ up until time _t_ giving you silence before _t_ and _W2_ (with somewhat the same oscillator states etc.) after _t_?

Have you considered to use cross-correlation rather than subtraction?

Have you switched off reverb and chorus?

**Comment by prof-spock** [comment]
Hello derselbst,

first of all thanks for your quick and very competent response!

I want to make clear that _I do not strive for a complete cancellation of the signals_!  I just want to be able to emulate the results of an external rendering line with fluidsynth (and sox) within a DAW with appropriate plugins (one of them being fluidsynthVST).  So I would be absolutely fine with a residue of say -40dB between the signals, because I do not hear differences in the signals that are below that threshold and typically are masked (by the interesting audio!).

Let me discuss a few points in your comment:

> [Besides LFO phases the parameters affected by time are]
> • state of the IIR filter,

Granted, but I think that the differences between an IIR filter "in action" and some filter just starting should be below the mentioned threshold after some time.  Of course, this will depend on the feedback coefficients.

> • state of the ADSR envelopes,

You're right for an arbitrary split point, but when assuming that the cut is done where no note is active (e.g. when previewing some region within a song), only the release parts of the envelopes could spill over.  Again after some setup time this should be below the threshold.

My naive assumption is that the envelopes are triggered by NOTEON and NOTEOFF events or do I miss something here?

> • the pitch and volume of each voice (which we linearly interpolate between 64 frames of rendered audio), and

I do not get that assuming that no portamento or CC07 is used for some note crossing the cut line.  Even then there might be small differences, but they should be below the threshold.

> • the delay lines in reverb and chorus
> Have you switched off reverb and chorus?

The MIDI files are automatically transformed for the DAW not to use reverb at all (by setting CC91 to 0 in the beginning of the file and deleting them elsewhere).  The command line fluidsynth has a `-R 0` parameter.  But I missed chorus so far, good advice, the same probably applies to delay.

I just was assuming that my preferred instruments from Fluid_R3 don't use that, but I have to check.

> Instead of "cutting" M1, have you considered to simply kill all noteon events in M1 up until time t giving you silence before t and W2 (with somewhat the same oscillator states etc.)  after t?

A good idea in principle, but it does not apply to the DAW situation, where you just start playing at _t_ and comparing _M2_ rendered by fluidsynthVST/libfluidsynth to _W1_ cut at _t_.

Here is my test setup using S.C.Collins midi test file and the associated diagnostic soundfont.
![Test Setup](https://i.imgur.com/T9NG9Uc.png)
I have also written a small plugin compensating the amplitude and offset difference of fluidsynthVST:
![Amplitude and Latency Compensation](https://i.imgur.com/3lVOPvU.png)

> Have you considered to use cross-correlation rather than subtraction?

No, I didn't, thanks for the hint: I was looking for such a VST, but didn't know the technical term.  I will be playing around with it and also try to ascertain the latency of fluidsynthVST (which seems to be 64 samples).

Okay, let me play around with your ideas; I'll keep you informed.

Best regards,
Prof. Spock

**Comment by mawe42** [comment]
Just a quick thought, maybe too basic, but I thought I'd write anyway: does your midi file maybe contain not just note on/off messages, but also cc commands that affect the channel setup? For example things like channel expression, pitch bend range, maybe even sysex commands to alter envelopes? In that case you would obviously get very different results if you omit those messages and start somewhere further down in the midi stream.

**Comment by prof-spock** [comment]
Hello mawe42,

for the diagnostic test shown above the [midi file from S.C.Collins](https://drive.google.com/open?id=1srPwp1TiAtTQLJFCuXfRQ-ENoxKN_sCa) does not contain anything except note data (and initial volume and pan setup). But to be honest the [soundfont](https://drive.google.com/open?id=1gb-V3cl7jkhkZBKbNC0ZY3bP8YK3BqQp) is a bit pathological, because Christian used it for testing the soundfont spec conformity of several plugins.
When using the above setup (with external fluidsynth and fluidsynthVST), everything cancels out fine when starting with t=0, but, of course, for arbitrary t, there is no cancellation of the tracks.

Best regards,
Prof. Spock

**Comment by prof-spock** [comment]
Dear all,

first of all sorry for still keeping this issue alive!
I concede that introducing such a time offset parameter might be hopeless in the general case, because of the free-running oscillators and possibly other circumstances.
Now if we cannot handle a soundfont with a complex oscillator logic in such a way, why not use/create a soundfont with just simple sample playback and envelopes?
In my opinion its playback should be completely time-independent: the sample playback and the envelope start at the time of the noteon, the release at the noteoff, so there is no surprising magic here.
I tried this with a [naive midi file](https://drive.google.com/open?id=1fVXHU50LfU-9Mc-COrd0Ybw4uCDgrWtA) and a stripped down [piano soundfont](https://drive.google.com/open?id=1UObIQ2c3HD0rHQhD3FqDsAlgH1vtTWS9) with fluidsynth on the command line and fluidsynthVST (using libfluidsynth) in Reaper.
As always the fluidsynth wave file and the live rendered audio from fluidsynthVST completely cancel out when starting at t=0 (with a processing(?) offset of -64 samples for the VSTi).
Unfortunately when starting at an arbitrary position this cancellation does not work. So libfluidsynth is in a different state although it is just rendering samples plus envelopes.
And to be honest I do not understand where my above reasoning fails...

Best regards,
Prof. Spock

**Comment by mawe42** [comment]
Can you try if the cancellation works if you use a starting point that is a multiple of 64 frames from the start of your reference?

**Comment by prof-spock** [comment]
Hello mawe42,
great analysis! The cancellation works if the starting point is at k·64s/44100 (k∈ℕ).
This seems to be the VST block size?
Best regards,
Prof. Spock

**Comment by mawe42** [comment]
Great! I got the idea from something that @derselbst wrote in his first reply:
> the pitch and volume of each voice (which we linearly interpolate between 64 frames of rendered audio)

So my guess is: without significant changes to the way we handle those aspects of the sound, you're out of luck.

**Comment by prof-spock** [comment]
Hello mawe42,

you wrote:
>  without significant changes to the way we handle those aspects of the sound, you're out of luck (for arbitrary offsets)

I am fine with that, you do not have to add complexity to your software for esoteric use cases.

What I can do instead in the DAW is introduce a macro to rasterize loop positions and the play cursor start onto the 64 sample raster. This is easy to do.
And I doubt I will be able to hear that the chorus starts 32 samples early or late ... 😉

Best regards,
Prof. Spock

**Comment by prof-spock** [comment]
Dear all,

I have written the macro and it works perfectly! So I just have to make sure that no free-running modulation occurs in the soundfont and I'm fine.
Thanks to you both for restoring my faith in digital audio processing! 👍

I assume we can close this issue: such a parameter would be desirable from a scientific standpoint, but an okay workaround exists for the issue...

Best regards,
Prof. Spock

**Comment by derselbst** [comment]
> I have written the macro and it works perfectly!

Glad to hear that!

And to my surprise, it seems that your "😉" was the expression of an emotion... fascinating.
