### ISSUE TITLE
add sfz format support

### ISSUE THREAD

**Issue by Reaper10** [FluidSynth/fluidsynth#620]
add sfz format support
https://sfzformat.com/

**Comment by derselbst** [comment]
Nope, won't happen. Fluidsynth was designed for SF2. SFZ is way too powerful and doesn't fit into our architecture. There was an effort from a contributor to [build up an sfz synth based on fluidsynth](https://github.com/swesterfeld/liquidsfz). The author ended up dropping fluidsynth. I don't know the details why he dropped it. If you want to know, you'll have to ask the author.
