### ISSUE TITLE
Possible Pan Problem in Comparison to Version 2.0.1?

### ISSUE THREAD

**Issue by prof-spock** [FluidSynth/fluidsynth#621]
Dear all,

you might know I sometimes hear the grass grow, so this again might be a non-problem.

But it seems that there is an issue with pan handling in version 2.1.0.
I rendered an innocent (almost) [single track midi file](https://github.com/FluidSynth/fluidsynth/files/4269492/panTestFile.zip) with soundfont FluidR3_GM.sf2 and my standard command line
`fluidsynth -n -i -g 1 -R 0 -F test.wav FluidR3_GM.SF2 panTestFile.mid`
Note that the single guitar has a dead center pan position.

When checking the audio file from FS 2.0.1 with a correlation meter it shows "0.0" for mono (as expected), when checking the result of FS 2.1.0 the correlation value is oscillating.

Do I miss something?

Best regards,
Prof. Spock

**Comment by derselbst** [comment]
That's because the "Clean Guitar" instrument has an initial chorus generator set. You did not disable chorus in your commandline. That's why you are getting such a rich sound from the guitar. And since version 2.1.0 we now use a new stereophonic chorus engine, which is exactly the stereo spread that you hear.

**Comment by derselbst** [comment]
Nice tune btw.

**Comment by prof-spock** [comment]
Hello derselbst,

thanks a lot for the explanation!  Precise and convincing as always 👍
Great enhancement even when it had derailed me somewhat...

I used azslow3's fluidsynthVST in Reaper in comparison with the current command line version and he is using FS 2.0.5. So in my hunt for bit-exact reproduction this effect (!) came up.

> Nice tune btw.

It is an intermediate file - sorry to bother you with that - in my automated command line processing chain for notation videos called [lilypondToBandVideoConverter](https://github.com/prof-spock/LilypondToBandVideoConverter).
The verse and chorus part of the guitar are a bit simplistic (because the guitarist also sings), but hypnotic and the guitar solo is great. The song is "Ladylike" by "Big Wreck", an unfortunately completely underrated band from Canada.

Best regards,
Prof. Spock

P.S.: Of course, you can close this issue...

**Comment by derselbst** [comment]
Interesting, thanks!
