### ISSUE TITLE
Sample rate capped at 96kHz; causes bad output when JACK running at 192kHz

### ISSUE THREAD

**Issue by fabiangreffrath** [FluidSynth/fluidsynth#623]
This has been reported by Mark Wooding <mdw@distorted.org.uk> against the fluidsynth Debian package [1]:

> Package: libfluidsynth1
> Version: 1.1.6-4
> Severity: normal
> Tags: patch
> 
> When recording, I run JACK with a 192kHz sample rate, to match my audio
> interface, so as to minimize the cumulative errors through the audio
> processing chain.  Fluidsynth-based instruments appear to work, but
> produce bad-sounding audio pitched an octave higher than intended.
> Also, a log message is printed
> 
> | fluidsynth: Jack sample rate mismatch, adjusting. (synth.sample-rate=96000, jackd=192000)
> 
> The underlying cause is that, for some reason, Fluidsynth's
> `synth.sample-rate' parameter must be between 8kHz and 96kHz, and values
> beyond these bounds are /silently/ clamped to these bounds.
> 
> If I start Fluidsynth with `-r192000', then it pretends to accept that,
> but internally clamps the sample rate to 96kHz.  The JACK client code
> then notices that JACK is really running at 192kHz, prints the message
> above, and tries to reconfigure the synthesizer's sample rate to 192kHz.
> Again, this is silently clamped back to 96kHz.
> 
> In this state, Fluidsynth is essentially writing samples twice as
> quickly as they should be, resulting in the octave pitch shift I
> reported.  But this also adversely affects the instrument timbre (e.g.,
> violin vibrato is unpleasantly rapid; piano attack sounds like a cheap
> imitation).
> 
> My patch just raises the upper sample-rate bound to 192kHz, which is
> enough for my purposes.  With this change, Fluidsynth sounds pretty good
> agin.  I don't know whether the library actually needs an upper bound
> here at all; if not, it should probably be removed.  I've also not done
> anything about the silent clamping; at least Fluidsynth should print
> some log message here.
> 
> This patch applies to current sid (which is also affected).  Indeed, I
> originally fumbled dgit and mistakenly patched sid; so I had to rebase
> the change, which was trivial.

The original bug report even contained a patch, but this was against fluidsynth 1.1.6 and unfortunately does not apply anymore:

```
diff --git a/doc/fluidsynth-v10-devdoc.xml b/doc/fluidsynth-v10-devdoc.xml
index d20ba1a..47c6d1d 100644
--- a/doc/fluidsynth-v10-devdoc.xml
+++ b/doc/fluidsynth-v10-devdoc.xml
@@ -235,7 +235,7 @@ saturation of the output when random MIDI files are played.<
 <row>
   <entry></entry>
   <entry>Min-Max</entry>
-  <entry>22050-96000</entry>
+  <entry>22050-192000</entry>
 </row>
 <row>
   <entry></entry>
diff --git a/doc/fluidsynth-v11-devdoc.txt b/doc/fluidsynth-v11-devdoc.txt
index 381ef80..56ebe1a 100644
--- a/doc/fluidsynth-v11-devdoc.txt
+++ b/doc/fluidsynth-v11-devdoc.txt
@@ -589,7 +589,7 @@ in rendering-to-file scenarios where underruns is not an iss
   <tr>
     <td></td>
     <td>Min-Max</td>
-    <td>22050-96000</td>
+    <td>22050-192000</td>
   </tr>
   <tr>
     <td></td>
diff --git a/doc/fluidsynth.1 b/doc/fluidsynth.1
index 389532f..e788a82 100644
--- a/doc/fluidsynth.1
+++ b/doc/fluidsynth.1
@@ -212,7 +212,7 @@ Voice polyphony count (number of simultaneous voices allowed
 .B synth.reverb.active      BOOL  [def=True]
 Reverb effect enable toggle.
 .TP
-.B synth.sample\-rate       FLOAT [min=22050.000, max=96000.000, def=44100.000]
+.B synth.sample\-rate       FLOAT [min=22050.000, max=192000.000, def=44100.000
 Synthesizer sample rate.
 .TP
 .B synth.threadsafe-api     BOOL  [def=True]
diff --git a/src/synth/fluid_synth.c b/src/synth/fluid_synth.c
index 1e782f1..10f579d 100644
--- a/src/synth/fluid_synth.c
+++ b/src/synth/fluid_synth.c
@@ -202,7 +202,7 @@ void fluid_synth_settings(fluid_settings_t* settings)
   fluid_settings_register_int(settings, "synth.effects-channels",
                              2, 2, 2, 0, NULL, NULL);
   fluid_settings_register_num(settings, "synth.sample-rate",
-                             44100.0f, 8000.0f, 96000.0f,
+                             44100.0f, 8000.0f, 192000.0f,
                              0, NULL, NULL);
   fluid_settings_register_int(settings, "synth.device-id",
                              0, 0, 126, 0, NULL, NULL);
@@ -590,7 +590,7 @@ new_fluid_synth(fluid_settings_t *settings)

   /* register the callbacks */
   fluid_settings_register_num(settings, "synth.sample-rate",
-                             44100.0f, 8000.0f, 96000.0f, 0,
+                             44100.0f, 8000.0f, 192000.0f, 0,
                              (fluid_num_update_t) fluid_synth_update_sample_rat
   fluid_settings_register_num(settings, "synth.gain",
                              0.2f, 0.0f, 10.0f, 0,
@@ -2139,7 +2139,7 @@ fluid_synth_set_sample_rate(fluid_synth_t* synth, float sa
   int i;
   fluid_return_if_fail (synth != NULL);
   fluid_synth_api_enter(synth);
-  fluid_clip (sample_rate, 8000.0f, 96000.0f);
+  fluid_clip (sample_rate, 8000.0f, 192000.0f);
   synth->sample_rate = sample_rate;

  fluid_settings_getint(synth->settings, "synth.min-note-length", &i);
```  

Cheers,

 - Fabian

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929960

**Comment by derselbst** [comment]
At least for human beings, sample rates >48kHz don't really make any sense, the difference is inaudible. Our effect units (reverb and chorus) have been designed for 44.1kHz. They work well for 48kHz. And at least our new reverb engine as of 2.1.0 compensates sample rates quite well for sample rates from 22kHz up to 96kHz. I have no clue what was the motivation of fluidsynth to support 96kHz. However, I'm not willing to extend that limit up to 196kHz. Likewise to keep backward compatibility, I'm neither willing to truncate the supported range to 48kHz.

I'm open to exit with an error though, if unsupported values are passed to fluidsynth via `-r`.

**Comment by fabiangreffrath** [comment]
> At least for human beings, sample rates >48kHz don't really make any sense, the difference is inaudible. 

I agree with you here.

> I'm open to exit with an error though, if unsupported values are passed to fluidsynth via `-r`.

My issue is the library silently capping the sample rate at 96 kHz and reporting success. I'd recommend the library initialization to fail (not only the frontend) if an unsupported sample rate is requested.

**Comment by derselbst** [comment]
> My issue is the library silently capping the sample rate at 96 kHz and reporting success.

The library call is `fluid_settings_setnum()`. And as of version 2.0.0 it returns `FLUID_FAILED` in this case. It's just that our binary "frontend" is not checking for it. I'll fix both issues within the next day(s). It'll take some time until there is a reason to release a 2.1.2. In the meantime, if you need the fixes for packaging, I'd suggest that you apply the upstream commits as patches.
