### ISSUE TITLE
It is impossible to locate or change the default configuration by the manuals

### ISSUE THREAD

**Issue by TCH68k** [FluidSynth/fluidsynth#632]
### FluidSynth version
Irrelevant, it's not a software bug.

### Describe the bug
I would like to change the default settings of FluidSynth, but i could not find the default config file anywhere. It's neither in my home dir, nor in /etc or /usr. I've checked the manuals, but they gave zero info about, how i can change the default settings.
There is this page https://github.com/FluidSynth/fluidsynth/wiki/FluidSettings which describes how can i change the settings at start, but that is not what i would like to do.
The manual also describes `set name value` as an option to change settings during running, but that is not persistent, after i quit, they revert to the default. `info name` just prints out the default value for a setting, but gives no further information about how can i change it permanently.
It also says, that i can load a configuration file with `-f, --load-config`, but first, that is also must be specified at start and second, how does a FluidSynth configuration file look like anyway? I've tried to find example config files, but to no avail at all.

### Expected behavior
The manual should contain the location of the default config file, or should describe how else i can change the default settings.

### Additional context
For example, I would like to change the `audio.driver` to `alsa`, because the default `jack` is not on my machine.

**Comment by derselbst** [comment]
There is no "default config file" and you cannot change the default settings. What makes you think you could?

The closest what you can get is by using a configuration file. [As the manual says](https://github.com/FluidSynth/fluidsynth/wiki/UserManual#options), "command configuration file (shell commands)" is exactly that: a plain text file where each line contains a shell command. Nothing special here.

**Comment by TCH68k** [comment]
Because it would make sense to be able to do that.

Just putting 'shell commands' into a parenthesis are really not explains anything; it should be at least 'which contains shell commands' but still, what kind of shell commands? FluidSynth related ones or anything which you could type into the terminal, so the command files are practically shellscripts? If yes, then what use the config files have anyway? Why use them instead of a shellscript?

And also, as i said in the OP, loading a config file when running FluidSynth from a terminal is not what i would like to do. I cannot do that when an external program (like WINE, or DuneDynasty) uses FluidSynth as a plugin and there is no way to change how they call it. That is why it would be useful if i could change the default settings.

So, it seems, i have to modify the sources and compile it myself, if i want to set the default audio driver to ALSA, instead of JACK.

**Comment by derselbst** [comment]
> what kind of shell commands? FluidSynth related ones or anything which you could type into the terminal, so the config files are practically shellscripts? If yes, then what use the config files have anyway? Why use them instead of a shellscript?

You've already concluded by yourself, that it must be fluidsynth related commands, otherwise it would be pointless, right? Anyway, I'll update the manual.

> I cannot do that when an external program (like WINE, or DuneDynasty) uses FluidSynth as a plugin

A "default config file" would be useless in this case. Because serious programs manage audio by themselves. I.e. **they do not use fluidsynth's audio driver**. DuneDynasty is one of them. Look at their source code in `allegro_midi.cpp`:

```c++
void *buf = al_get_audio_stream_fragment(pl->stream);
if (buf) {
    fluid_synth_write_float(pl->synth, FRAG_SAMPLES,
        buf, 0, 2,  /* left channel */
        buf, 1, 2   /* right channel */
    );
    al_set_audio_stream_fragment(pl->stream, buf);
}
```

They use their own audio stream. They only ask fluidsynth to render some samples, which are then played back in their own stream. It is impossible that fluidsynth related settings like `audio.driver` can change anything here.

And if an application really uses fluidsynth's audio driver, while not providing a way to change fluidsynth's related settings `audio.driver`, it's a limitiation of that application, not fluidsynth.

You are basically suggesting to make the behaviour of a shared library (=fluidsynth) depending on a configuration file, which may or may not be available in the user's domain. This effectively hijacks fluidsynth's behaviour assumed by  other applications. And this really poor practice.

**Comment by TCH68k** [comment]
> You've already concluded by yourself, that it must be fluidsynth related commands, otherwise it would be pointless, right? Anyway, I'll update the manual.

While you're right in theory, in practice any manual should be straight and obvious, to prevent the user relying on his own "conclusions".

> A "default config file" would be useless in this case. Because serious programs manage audio by themselves. I.e. **they do not use fluidsynth's audio driver**. DuneDynasty is one of them. Look at their source code in `allegro_midi.cpp`:

>They use their own audio stream. They only ask fluidsynth to render some samples, which are then played back in their own stream. It is impossible that fluidsynth related settings like `audio.driver` can change anything here.

I wasn't aware of that, DuneDynasty did not elaborated how they use FluidSynth, they just said it can play MIDIs _via_ FluidSynth (which literally means they do this _through_ FluidSynth), so i just assumed, they do the entire MIDI playback through the library. Thanks for enlightening me.

> And if an application really uses fluidsynth's audio driver, while not providing a way to change fluidsynth's related settings `audio.driver`, it's a limitiation of that application, not fluidsynth.

While this is true, the two do not excluses each other.

> You are basically suggesting to make the behaviour of a shared library (=fluidsynth) depending on a configuration file, which may or may not be available in the user's domain. This effectively hijacks fluidsynth's behaviour assumed by other applications. And this really poor practice.

First, _optionally_ depending, i've never said, it should be mandatory.

Second, FluidSynth being a shared library is irrelevant. It is providing a service to apps and services can manifest in various forms. A library can use configuration files too.

Third, i don't see, how this could not be available in the user's reach. First it can check for `/home/username/.whatever/path/it/uses.conf` to provide per-user default settings, and if it does not exists, it can check - for instance - for `/etc/fluidsynth.conf` to provide system-wide default settings, and if that does not exists either, then it still can revert to the wired-in default settings.

Fourth, i disagree with the poor practice part: the user should be always in power, so if the user wants to supersede how his applications use his libraries, it's his choice and his responsibility. Yeah, he may do something stupid. So? It's his problem. Maybe it's the application which does something stupid, by using the library erroneously. Yes, that is the user's problem too, but if you provide an option to override this in the middle layer, he may be able to solve his own problem. 

(Yes, i understood, that i cannot change how DuneDynasty uses FluidSynth by changing default FluidSynth settings; i meant this four paragraph en generique.)

**Comment by derselbst** [comment]
> > You are basically suggesting to make the behaviour of a shared library (=fluidsynth) depending on a configuration file, which may or may not be available in the user's domain. This effectively hijacks fluidsynth's behaviour assumed by other applications. And this really poor practice.
> 
> First, _optionally_ depending, i've never said, it should be mandatory.

Ofc, optionally. This makes it even harder for the application to derive fluidsynth's "default" behaviour.

> Second, FluidSynth being a shared library is irrelevant.

It's not irrelevant. Just like you said, that you cannot change the application's possibly inappropriate usage of fluidsynth, the application would have zero control over whether or not user-provided defaults are in use. This configuration file stuff is exposed via our API. If an application wants to give that freedom to a user, it should use our API appropriately.

> Third, i don't see, how this could not be available in the user's reach. First it can check for /home/username/.whatever/path/it/uses.conf to provide per-user default settings, and if it does not exists, it can check - for instance - for /etc/fluidsynth.conf to provide system-wide default settings

And something like this does exist (granted, undocumented, I'll see where it fits). If `-f, --load-config` is not given when starting the fluidsynth binary, it looks for a user-local config, then for a system-wide config file. However, they do not contain the permanent default values for all the FluidSettings (which from my understanding you were asking for in the beginning). These files contain shell commands, provided for convenience usage when not specifying  `-f, --load-config`. I understand this is not what you are looking for, as this behaviour only applies to the fluidsynth binary, not to the library itself.

> Fourth, i disagree with the poor practice part: the user should be always in power, so if the user wants to supersede how his applications use his libraries, it's his choice and his responsibility.

Again, it's up to the application whether or not to give that freedom to a user. I'm not willing to introduce this "invisible" change in behaviour for the whole library as you suggested, sorry.

**Comment by derselbst** [comment]
> > Third, i don't see, how this could not be available in the user's reach. First it can check for /home/username/.whatever/path/it/uses.conf to provide per-user default settings, and if it does not exists, it can check - for instance - for /etc/fluidsynth.conf to provide system-wide default settings
> 
> And something like this does exist (granted, undocumented, I'll see where it fits)

UserManual has been [updated](https://github.com/FluidSynth/fluidsynth/wiki/UserManual#description). Therefore, I'm closing this.

**Comment by TCH68k** [comment]
Well, i tried. I still say, an optional superseding of the application's settings would be good in case the application does it's job miserably, but if not, then not.

At least the manual is improved and obvious now, so it was not futile to open this discussion.
