### ISSUE TITLE
Android: Fluidsynth does not support MIDI input

### ISSUE THREAD

**Issue by carlo-bramini** [FluidSynth/fluidsynth#633]
It seems to me that Fluidsynth allows to play audio samples natively when compiled for Android, but it does not support MIDI input yet. It would be nice if this feature could be introduced.

**Comment by atsushieno** [comment]
I once tried to implement AMidi support, but I didn't have motivation enough to finish it because I thought it also covers the output but it doesn't. The input driver part might be still useful. You (anyone) can feel free to take it from my incomplete fork: https://github.com/FluidSynth/fluidsynth/compare/master...atsushieno:amidi

**Comment by probonopd** [comment]
What is FluidSynth useful for on Android without MIDI input?

**Comment by probonopd** [comment]
https://play.google.com/store/apps/details?id=net.volcanomobile.fluidsynthmidi claims

> Plug your device to your computer, or hook a MIDI USB master keyboard via an OTG cable to play with this low-latency FluidSynth 1.1.9 based Synthesizer.

But it did not work for me either.

**Comment by pestophagous** [comment]
> What is FluidSynth useful for on Android without MIDI input?

I cannot speak to that.  However, I can provide another minor data point about volcanomobile.fluidsynthmidi in specific, and more generally about the feasibility of a fluidsynth library running on Android with MIDI input.

@probonopd I am using volcanomobile.fluidsynthmidi on my Android phone with a Casio Privia (and previously with an Alessis midi piano keyboard) and it has always "just worked" for me with both keyboards (photo attached).

I also used the volcanomobile codebase (https://github.com/VolcanoMobile/fluidsynth-android) as a "cheatsheet" to hack my own (friendly, toy) [fork of fluidsynth](https://github.com/pestophagous/fluidsynth) for a (toy, personal) mobile app, and that is also cooperating quite nicely on the single phone that I have as a point of reference.

Maybe the Android version matters?

I have Android 8.1.0, LineageOS 15.1 Cheeseburger.

I have FluidSynth Android app version 1.2.4, December 23, 2020.

![pxl_20210725_185145140](https://user-images.githubusercontent.com/14035898/126910185-4825d5b1-f52c-43c8-8ed5-02618455bbc7.jpg)

**Comment by probonopd** [comment]
Thanks @pestophagous. I will do more experimentation. 2 other apps on the same Android device are working fine with MIDI input, so I am a bit puzzled.

**Comment by atsushieno** [comment]
> What is FluidSynth useful for on Android without MIDI input?

Fluidsynth is already useful without its own MIDI input support.
I have been using MIDI keyboard apps to connect to my [MidiDeviceService implementation](https://github.com/atsushieno/fluidsynth-midi-service-j) (it's not on Google Play after I received weird rejection from Google saying that there is concern on "trademark", which looked super weird as there is already "Fluidsynth MIDI" app). The keyboard apps can be anything (there are quite a few apps on Google Play. It is how MIDI works.

It's not my primary use of Fluidsynth on Android though; I'm making use of it as a GM device for my MIDI player (in the mentioned repo) and an instrument for my own audio plugin framework.
