### ISSUE TITLE
Inconsistent seek behavior due to race conditions

### ISSUE THREAD

**Issue by ThunkMonkey** [FluidSynth/fluidsynth#634]
`fluid_player_seek()` can be called any time and writes directly to `player->seek_ticks` as seen [here](https://github.com/FluidSynth/fluidsynth/blob/master/src/midi/fluid_midi.c#L2184):
```
int fluid_player_seek(fluid_player_t *player, int ticks)
{
    if(ticks < 0 || ticks > fluid_player_get_total_ticks(player))
    {
        return FLUID_FAILED;
    }

    player->seek_ticks = ticks;
    return FLUID_OK;
}
```
`fluid_player_callback()` reads from `player->seek_ticks` [here](https://github.com/FluidSynth/fluidsynth/blob/master/src/midi/fluid_midi.c#L2080) (1) and [here](https://github.com/FluidSynth/fluidsynth/blob/master/src/midi/fluid_midi.c#L2094), on a separate thread:
```
        if(player->seek_ticks >= 0)
        {
            fluid_synth_all_sounds_off(synth, -1); /* avoid hanging notes */
        }

        for(i = 0; i < player->ntracks; i++)
        {
            if(!fluid_track_eot(player->track[i]))
            {
                status = FLUID_PLAYER_PLAYING;
                    (player->track[i], synth, player, player->cur_ticks);
            }
        }

        if(player->seek_ticks >= 0)
        {
            player->start_ticks = player->seek_ticks;   /* tick position of last tempo value (which is now) */
            player->cur_ticks = player->seek_ticks;
            player->begin_msec = msec;      /* only used to calculate the duration of playing */
            player->start_msec = msec;      /* should be the (synth)-time of the last tempo change */
            player->seek_ticks = -1;        /* clear seek_ticks */
        }
```
Because of this, it looks like there are race conditions that can result in inconsistent behavior. For example, calling `fluid_player_seek()` after (1) but before `fluid_track_send_events()` is called means the track will still seek, but `fluid_synth_all_sounds_off()` will not be called to avoid hanging notes.

Every read of `player->seek_ticks` has the potential to be different than the last, so, for example, in the block that clears seek_ticks, `player->start_ticks` and `player->cur_ticks` could end up being different values, when they are not meant to be.

I'm not sure how to solve this without invoking thread synchronization primitives. One mitigation could be to reduce the window for the race condition. For example, just read `player->seek_ticks` once at the beginning of `fluid_player_callback()`, and use that value for the rest of the reads.
```
int seek_ticks = player->seek_ticks;
player->seek_ticks = -1;

...

if(seek_ticks >= 0)
{
    ...
```
I don't have a reliable repro, and as this is a race condition, I don't expect to get one.. I just created this issue after reviewing the code.

**Comment by derselbst** [comment]
You are right. Thanks for pointing this out.

Your approach of reducing the number of reads to `seek_ticks` looks good to me. Additionally one might consider to make `seek_ticks` an atomic int, to avoid a potentially dirty read in the beginning and dirty write when setting it to -1 at the end. You're welcome to draft a PR for that.

**Comment by ThunkMonkey** [comment]
Thanks for looking at this, but 69cfa78 does not fix the issue. You are still accessing `player->seek_ticks` in multiple locations. I suspect `fluid_atomic_int_set()` doesn't really help much, since int reads and writes will be atomic on most platforms anyway.

I suggest using a mutex. When setting in `fluid_player_seek()`
```
fluid_mutex_lock(mutex)
player->seek_ticks = ticks;
fluid_mutex_unlock(mutex)
```
When reading in `fluid_player_callback()`
```
fluid_mutex_lock(mutex)
int seek_ticks = player->seek_ticks;
player->seek_ticks = -1;
fluid_mutex_unlock(mutex)
```
Then never read `player->seek_ticks` anywhere else. This will likely mean passing an additional parameter to `fluid_track_send_events()`.

**Comment by derselbst** [comment]
I don't want to add a mutex into `fluid_player_callback()`, because it's called from synth context, where we need performance. Guarding it with a mutex here would open a DOS vulnerability, because  threads making massive calls to `fluid_player_seek()` would be able to block the synthesizer to do its job.

Esp. it's not a use-case to call `fluid_player_seek()` like crazy to set one seek position after another. You seek to a position, listen to the music at this position, maybe recognize, oops, wrong position and seek again.

However, you are correct, that `seek_ticks` should be passed to `fluid_track_send_events()` directly, rather than reading it over and over again. Thanks.

**Comment by ThunkMonkey** [comment]
Since it's not a use-case to call `fluid_player_seek()` like crazy, I would not worry about a "DOS vulnerability". Regarding performance, I don't think it would have a huge effect, but if you're that worried about it, maybe you should condition inclusion of the seek feature and related code on a preproceesor flag (`#ifdef`) that could be specified at compile time. Otherwise, without a mutex, you will not be able to implement the seek feature reliably. With the implementation as it stands today, there is a chance I could call `fluid_player_seek()` even just once, and it will fail to work properly.

**Comment by derselbst** [comment]
> With the implementation as it stands today, there is a chance I could call fluid_player_seek() even just once, and it will fail to work properly.

That you need to explain pls. How could it fail?

**Comment by ThunkMonkey** [comment]
Apologies. I reviewed the code, and I think a single call will work fine. I actually think what you've done is a good compromise between performance and correctness. However, since `fluid_player_seek()` is a public API, I would suggest adding a comment in the documentation that states it may not work if multiple calls are made in quick succession.

Thanks for quickly addressing this issue.

**Comment by derselbst** [comment]
Ok, thanks for your feedback. I'll elaborate the API doc as suggested.

**Comment by derselbst** [comment]
It's actually possible to guard against multiple calls properly. This is what I've done.

**Comment by ThunkMonkey** [comment]
I had a thought: could you add a `fluid_atomic_int_or()` and use it read `player->seek_ticks` and make it negative in one atomic operation?
```
seek_ticks = fluid_atomic_int_or(&player->seek_ticks, -1);
```

**Comment by ThunkMonkey** [comment]
Also, here's a note about atomic operations from the [glib docs](https://developer.gnome.org/glib/stable/glib-Atomic-Operations.html):

> It is also worth noting that since all of these operations require global synchronisation of the entire machine, they can be quite slow. In the case of performing multiple atomic operations it can often be faster to simply acquire a mutex lock around the critical area, perform the operations normally and then release the lock.

**Comment by derselbst** [comment]
> could you add a fluid_atomic_int_or() and use it read player->seek_ticks and make it negative in one atomic operation?

`g_atomic_int_or()` was introduced in glib 2.30, but fluidsynth can be built with glib >= 2.6.5 . And we cannot simply bump the minimum required version either, because glib 2.28 is the latest version that provides prebuilt binaries on windows:

http://ftp.gnome.org/pub/gnome/binaries/win32/glib/ 

> Also, here's a note about atomic operations from the glib

In this context, I am not concerned about the performance of a few single atomic operations. I am concerned about mutexes locking and blocking the synthesis context.

**Comment by ThunkMonkey** [comment]
Sounds good. Curious if it makes sense to reset `player->seek_ticks` as soon as possible, such as [here](https://github.com/FluidSynth/fluidsynth/blob/master/src/midi/fluid_midi.c#L2078-L2082):
```
        seek_ticks = fluid_atomic_int_get(&player->seek_ticks);
        if(seek_ticks >= 0)
        {
            fluid_atomic_int_set(&player->seek_ticks, -1);
            fluid_synth_all_sounds_off(synth, -1); /* avoid hanging notes */
        }
```
You can reduce the window in which a call to `fluid_player_seek()` will fail.
