### ISSUE TITLE
Memory violation access if new_fluid_revmodel() return NULL

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#640]
Just discover this bug, using the console application.
If `new_fluid_revmodel()` return NULL, the message `fluidsynth: error: Out of memory` is displayed followed by a `memory violation access`. I haven't yet investigated, I don't know if the `violation` occurs in the library or in the console application.

**Comment by jjceresa** [comment]
The bug is deep in delete_rvoice_mixer_threads(), called from new_fluid_rvoice_mixer().

Example, in new_fluid_rvoice_mixer(), if creation of reverb or chorus fail, new_fluid_rvoice_mixer() call the following chain ::delete_fluid_rvoice_mixer()->delete_rvoice_mixer_threads()->fluid_cond_mutex_lock(mixer->wakeup_threads_m).

**Comment by derselbst** [comment]
Nice spot!

Yes, the cleanup logic in `delete_rvoice_mixer_threads` is not bullet proof in case of partly initialized rvoice_mixer. I'll fix that (later).
