### ISSUE TITLE
Call ipatch_close()

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#643]
Fluidsynth should call `ipatch_close()` to avoid memory leaks. This could be done by keeping track of created `settings` xor `synth` instances: When all instances of either type have been destoryed, call `ipatch_close()`. When the first instance is created again, call `ipatch_init()`. Need to figure whether `settings` or `synth` is more appropriate.

**Comment by derselbst** [comment]
... or make use of swami/libinstpatch#47 and always call `ipatch_init()` in `new_fluid_synth()` and `ipatch_close()` in `delete_fluid_synth()`

**Comment by jjceresa** [comment]
>always call ipatch_init() in new_fluid_synth() and ipatch_close() in delete_fluid_synth()

This is the good solution and will work safely only if swami/libinstpatch#47 is applied. Otherwise Swami will fail during its deinitialization step  because libinstpatch was already deinitialized by fluidsynth.
