### ISSUE TITLE
Seek does not work properly when notes start at the seek time

### ISSUE THREAD

**Issue by ThunkMonkey** [FluidSynth/fluidsynth#646]
If you call `fluid_player_seek(player, ticks)`, and the midi file has notes that start at exactly the value of `ticks`, they will not be played.

As far as I can tell, this happens because when seeking, all note on/off events are ignored as seen [here](https://github.com/FluidSynth/fluidsynth/blob/master/src/midi/fluid_midi.c#L1596):
```
        else if(seeking && (event->type == NOTE_ON || event->type == NOTE_OFF))
        {
            /* skip on/off messages */
        }
```
When we reach the seek ticks value, any note on events at that time will be ignored as well.

Not sure what the best solution is here. Perhaps one way to fix it is to modify the seeking flag [here](https://github.com/FluidSynth/fluidsynth/blob/master/src/midi/fluid_midi.c#L1586-L1589):
```
        if(track->ticks + event->dtime > ticks)
        {
            return;
        }

        if(track->ticks + event->dtime == ticks)
        {
            seeking = 0;
        }           
```

**Comment by derselbst** [comment]
Sorry for the delay. I've adapted your suggestion and committed a potential fix. Please test this branch:

https://github.com/FluidSynth/fluidsynth/tree/issue646

**Comment by ThunkMonkey** [comment]
Works great. Thanks!
