### ISSUE TITLE
No audio in Unity3D  

### ISSUE THREAD

**Issue by Yorgg** [FluidSynth/fluidsynth#656]
### FluidSynth version
2.1.3

### Describe the bug
There is no audio when playing noteon events within the Unity Editor (on play mode). 

### Steps to reproduce
1. [Build on windows 10, 64 bit  using Msys2 instructions](https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake#building-with-msys2-on-windows)
2. On `/build/src/`, copy `libfluidsynth-2.dll` to plugins folder in Unity and rename file to `fluidsynth.dll`.
3. Add the following fluidsynth dependencies to plugins folder in Unity:

libFLAC-8.dll
libglib-2.0-0.dll
libiconv-2.dll
libintl-8.dll
libogg-0.dll
libpcr-1.dll
libreadline8.dll
libsndfile-1.dll
libspeex-1.dll
libtermcap-0.dll
libvorbis-0.dll
libvorbiisenc-2.dll
libwinpthread-1.dll

4. Add [nfluidsynth](https://github.com/atsushieno/nfluidsynth) library to your plugins (for c# bindings)

### Additional context

There is no audio issue when I run `fluidsynth.exe` on `MSYS2` (noteon events produce sound!).
Below is my nfluidsynth code.  It produces no errors, so I'm not sure what to do.  

```
 using (var settings = new NFluidsynth.Settings())
            {
              
                settings[ConfigurationKeys.SynthAudioChannels].IntValue = 2;
                using (var syn = new Synth(settings))
                {
                    syn.LoadSoundFont("/usr/share/sounds/pathtoyoursoundfont.sf2", true);
                    for (int i = 0; i < 16; i++)
                        syn.SoundFontSelect(i, 1);
                   
                        using (var adriver = new AudioDriver(syn.Settings, syn))
                        {
                            syn.ProgramChange(0, 0);
                            syn.NoteOn(0, 60, 120);
                        }
                    }
                }
```

**Comment by derselbst** [comment]
> syn.LoadSoundFont("/usr/share/sounds/pathtoyoursoundfont.sf2", true);

You are  on windows, so why are you trying to load a soundfont from a unix directory?


>                   for (int i = 0; i < 16; i++)
>                        syn.SoundFontSelect(i, 1);

This is redundant. 


> using (var adriver = new AudioDriver(syn.Settings, syn))
>                        {
>                            syn.ProgramChange(0, 0);
>                            syn.NoteOn(0, 60, 120);
>                        }

Immediately after triggering a noteOn, you are destroying the audio driver. Not surprising that there is no audio.

**Comment by Yorgg** [comment]
Yes you are right - I just realized it was being immediately disposed and was going to close this issue.  My apologies. 

Thanks for pointing out the for-loop redundancy.
