### ISSUE TITLE
start fluidsynth as a global service in daemon mode

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#66]
There is in Debian and other distros, an init script that starts timidity as a global service. This script is installed at /etc/init.d/timidity, and the package name is "timidity-daemon".  

The same can be done with fluidsynth, adding two files to the source tarball, and installing them at the right places:  
* /etc/fluidsynth.conf containing the fluidsynth daemon initial parameters  
* /etc/init.d/fluidsynth executable script controlling the global service (start, stop, restart, and status standard actions).  

Reported by: pedrolcl

Original Ticket: [fluidsynth/tickets/66](https://sourceforge.net/p/fluidsynth/tickets/66)

**Comment by derselbst** [comment]
Though this seem to be a nice idea, there doesnt seem to be any activity even 7 years later. I dont see this to happen, I neither have the knowledge nor the interest to implement this functionality.
Sry, but closing for now.

**Comment by mckaygerhard** [comment]
> ¿ Someone had a Script for OpenRC ? to start Fluidsynth without that filth of systemd. i am Devuan user, this use OpenRC or SysVInit or Both xD.

i never imaginate that this was an idea.. i am interestted.. of course this is a older post but valid cos i used devuan and alpine too..  that crap of shistemd.. i am making a package with sysvinit .. maybe alpine users have something for openrc..
