### ISSUE TITLE
About audio driver "multi channels"

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#665]
Fluidsynth `mixer` allows to produce audio on multiple `stereo outputs` (using **synth.audio-groups** > 1).
This allows to map MIDI channel on separate output.
Fluidsynth can have more than one `Fx unit `(using **synth.effects-groups** > 1)
This allows to map MIDI channel on separate fx unit input.

Actually there is only jack driver that use multiple output capabilities.

Today many low cost audio device could have: 2,4,6 or 8 audio channels. So it is interesting to bring
the mixer capabilities to these audio devices.

Here, I added  multi channel capabilities on `dsound`and `waveout`driver that work well tested on 2 audio devices.
In short, this multi channel support is based on new functions (`fluid_synth_write_s16_channels()` and 
`fluid_synth_write_s16_channels()`) that use a large part of the code of actual **fluid_synth_write_s16()** and 
`fluid_synth_write_float()` functions. So simply, these new drivers call `fluid_synth_write_s16_channels()` instead of fluid_synth_write_s16() and `fluid_synth_write_float_channels()` instead of fluid_synth_write_float().
I will do a PR to propose this enhancement.

I think that `alsa`driver could be adapted similarly to call these new functions. Unfortunately I have no linux machine equipped with the required audio devices (4,6 or 8 channels).

If you are interested and if you have the required audio devices on linux, I can help to place the changes in **fluid_alsa.c**.

**Comment by derselbst** [comment]
Sounds good, go ahead :+1:
