### ISSUE TITLE
Define FLUIDSYNTH_API on OS/2

### ISSUE THREAD

**Issue by komh** [FluidSynth/fluidsynth#678]
Hi/2.

On OS/2, CMake exported all the symbols so far. Now it changed. So it's necessary to export necessary symbols only. 

Here is the patch. 

Review, please...

[0001-Define-FLUIDSYNTH_API-on-OS-2.patch.txt](https://github.com/FluidSynth/fluidsynth/files/5261561/0001-Define-FLUIDSYNTH_API-on-OS-2.patch.txt)

```
From b822750fa3b2c3749d3e4e61816ec7e353cb0081 Mon Sep 17 00:00:00 2001
From: KO Myung-Hun <komh@chollian.net>
Date: Tue, 22 Sep 2020 21:40:29 +0900
Subject: [PATCH] Define FLUIDSYNTH_API on OS/2

Previously, CMake on OS/2 exported all the symbols unconditionally. Now
it exports necessary symbols only. As a result, it's necessary to
define FLUIDSYNTH_API correctly.
---
 include/fluidsynth.cmake | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/include/fluidsynth.cmake b/include/fluidsynth.cmake
index 021b1cda..654a4fd1 100644
--- a/include/fluidsynth.cmake
+++ b/include/fluidsynth.cmake
@@ -43,6 +43,9 @@ extern "C" {
 #elif defined(MACOS9)
 #define FLUIDSYNTH_API __declspec(export)
 
+#elif defined(__OS2__)
+#define FLUIDSYNTH_API __declspec(dllexport)
+
 #elif defined(__GNUC__)
 #define FLUIDSYNTH_API __attribute__ ((visibility ("default")))
 
-- 
2.22.0
```

**Comment by derselbst** [comment]
Ok, thanks. Question: Do you need to use `__declspec(dllimport)` on OS2 as well when consuming the library? So, just as it's done on Windows? Because if this is the case I'd propose to simply re-use the logic under the win32 condition.

**Comment by komh** [comment]
__declspec(dllimport) is not needed on OS/2.

**Comment by derselbst** [comment]
Ok, applied it to master. Thank you!
