### ISSUE TITLE
DLS Soundfont not loading in Android

### ISSUE THREAD

**Issue by TimeLimitExceeded** [FluidSynth/fluidsynth#686]
### FluidSynth version
2.1.5

### Describe the bug
On Android, when trying to load a DLS soundfont with `fluid_synth_sfload(synth, "my_dls_soundfont.dls", 1)`, it returns `FLUID_FAILED`.
In the past, I have succesfully loaded DLS Soundfonts in Fluidsynth from the command line and from desktop C++ applications, but I haven't had any success in Android.

### Expected behavior
 `fluid_synth_sfload(synth, "my_dls_soundfont.dls", 1)` should return the ID of the succesfully loaded DLS soundfont.

### Steps to reproduce

Simple steps:

1. Clone the minimal reproducible example from this repo: [https://github.com/TimeLimitExceeded/fluidsynth-dls-bug](https://github.com/TimeLimitExceeded/fluidsynth-dls-bug).
2. Open the project in Android Studio.
3. Run the project and hear 3 notes being played from the Android device.
4. Now, on `MainActivity.java` line 25, change this line so it becomes: ` String soundfontFileName = "dls_example.dls";`
5. Run the project again and you won't hear the 3 notes being played anymore.

Explanation:

This project is simply a Fluidsynth Hello World app in Android. It integrates the Android `.so` files downloaded from the releases section. To play sound, it loads a soundfont file from the assets folder. Because it's not possible to get the soundfont as a file directly from the assets, I need to copy the soundfont file to a temporary file, and then pass the path of this temporary path to fluidsynth (this is exactly what method `writeFileToPrivateStorage` in MainActivity.java). 

This procedure works perfectly for several `.sf2` soundfont files. However, I have tried it for various `.dls` soundfonts and all of them have failed. If you go to `app/src/main/cpp/native-lib.cpp`, on line 13:

```c++
int sfont_id = fluid_synth_sfload(synth, soundfontPath, 1);
bool result;
if (sfont_id == FLUID_FAILED) {
    result = false;
}
``` 
Variable `sfont_id` always is `FLUID_FAILED`

### Additional context
Not sure if this helps, but I tested this with my phone, Huawei p30 Lite (Huawei MAR-LX3A), Instruction set `arm64-v8a`

**Comment by derselbst** [comment]
I must excuse myself as I haven't had a close look at your provided example
(yet). Busy schedule. Yet I'm pretty sure I know the problem: Fluidsynth
requires libinstpatch to read DLS files. Thus it needs to be built with
libinstpatch. You've taken the precompiled Android libs. Those do not
include support for libinstpatch. If you want it, you'll need to
cross-compile it yourself as our CI Android build is currently broken and
my attempts on fixing it haven't been successful, unfortunately.

Also, I'd recommend to check soundfonts with fluid_is_soundfont() before
actually loading them.

The example project you've built looks really good and is highly
appreciated. In the past, I had no opportunity and no reason for diving
into the Java/Android world. Maybe this would be a good starting point,
perhaps even something that we should include in our documentation
somewhere. So, please do not delete it yet, I'll try to find some time
looking into it the upcoming weekend.

**Comment by TimeLimitExceeded** [comment]
@derselbst Thanks for your quick response. One quick question... was it intentional that the binaries released were compiled without libinstpatch? Maybe because you wanted to keep the binaries small? Or is it something that was missed?

Regarding the example I provided, recognition should go to my friend [@HectorRicardo](https://github.com/HectorRicardo). These links are a really good starting point, they were very helpful to me, and that's where I got the example from.

[https://medium.com/@hectorricardomendez/creating-a-fluidsynth-hello-world-app-for-android-5e112454a8eb](https://medium.com/@hectorricardomendez/creating-a-fluidsynth-hello-world-app-for-android-5e112454a8eb)
[https://github.com/HectorRicardo/fluidsynth-android-hello-world](https://github.com/HectorRicardo/fluidsynth-android-hello-world)

**Comment by derselbst** [comment]
I wouldn't call it intentional. It's just that nobody has taken the effort
to do it. The same applies to libsndfile, which the Android build doesn't
include as well. Which means you won't be able to open SF3 files.

Thanks for the pointers, I'll look into them.

**Comment by derselbst** [comment]
Closing this ticket in favor of #689.
