### ISSUE TITLE
Update test soundfonts and reactivate SF3 loading tests

### ISSUE THREAD

**Issue by mawe42** [FluidSynth/fluidsynth#701]
I noticed that the SF3 loading tests are currently disabled because of a lack of a test soundfont in SF3 format. As the license of the VintageDreams soundfont doesn't allow us to convert it to SF3, maybe we should think about replacing that soundfont with something with a more permissive license.

We could build our own test soundfont. Advantage would be that we could (only) add features we actually want to test. But we also loose some of the "real-world" dirt that comes with the VintageDreams font.

Or we could use something ready-made to get us started, like Christian Collins [Test Soundfont](https://www.dropbox.com/s/qmf0ej91h2ka5xw/SoundFont_2.01_Implementation_Test_v2.01.zip) or his [Virtue Soundfont](http://schristiancollins.com/virtue.php). Of course we would have to ask him for permission and possibly a re-licensed file.

Or try to find an alternative to the VintageDreams font. Something real-world, small and public domain. But that seems to be difficult...

I think my preferred option would be to build our own and maybe keep VintageDreams for the real-world SF2 test. What do you think?

**Comment by jjceresa** [comment]
>Advantage would be that we could (only) add features we actually want to test.
>I think my preferred option would be to build our own.

What could be the tools actually ready to use that could help to build SF3 from scratch ?.

**Comment by mawe42** [comment]
Polyphone can export SF3 files.

**Comment by mawe42** [comment]
There could be another option, but I'm not sure if that as already been tried: we could try to contact Ian Wilson and ask for permission and/or re-licence of the file so we can convert it to MP3...

@derselbst have you tried reaching out to Ian already?

**Comment by mawe42** [comment]
Ian Wilsons company Analoguesque Sound Designs has shut down, but he has created a new site with what seems to be an up-to-date contact email: http://analoguesque.x10host.com/

**Comment by derselbst** [comment]
> @derselbst have you tried reaching out to Ian already?

No, but good idea. I'll try to contact him via the site you've found.

**Comment by derselbst** [comment]
Permission granted b28c0ed044e303eb4844ce8abd0426e34619225a

**Comment by mawe42** [comment]
Very cool, thanks!
