### ISSUE TITLE
Wiki API documentation: misplaced topics.

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#712]
Using recent XML API documentation. I suggest following change.

On menu API reference.
1) `Effect-Reverb, Effect-Chorus`  sub group seem misplaced. They should be placed in sub group of `Synthesizer`, at the same level that `Effect - LADSPA`.

2) `MIDI Player` sub group should be moved at the same level that `MIDI sequencer` and should be named `MIDI file player`.

Again, many thanks to Marcus for this new efficient documentation.

**Comment by jjceresa** [comment]
Consulting Player API, we got this display:

Lifecycle Functions for MIDI Player_linebr@{

**Comment by mawe42** [comment]
Hm, the API docs are messed up. The sub grouping is completely wrong.

**Comment by mawe42** [comment]
@derselbst Has something changed in the way we build the API docs?

**Comment by derselbst** [comment]
> Has something changed in the way we build the API docs?

Not that I knew of. But it's obviously completely broken :(

I think now it's time to figure out how to get that GitHub Actions artifact downloaded with a shell script, so that we can provide it to Josh.

**Comment by mawe42** [comment]
The output from the latest API doc build action looks fine:
https://github.com/FluidSynth/fluidsynth/actions/runs/389192187

So maybe the doxygen version has changed on Joshs server?

**Comment by mawe42** [comment]
> I think now it's time to figure out how to get that GitHub Actions artifact downloaded with a shell script, so that we can provide it to Josh.

Good idea. I've written a small Python tool to help with the download: https://github.com/mawe42/github-artifact-download

Better than shell and some extra dependencies, I think. Only Python 3 is required, nothing else.

**Comment by jjceresa** [comment]
>The sub grouping is completely wrong

No, a lot of sub groups are well placed. 
The `API reference` tree is really efficient. It help me to find the player API quickly.

**Comment by derselbst** [comment]
> I've written a small Python tool to help with the download

Oh, you are already done. Very nice! I'll contact Josh.
