### ISSUE TITLE
Associate multiple sf2 to different channels

### ISSUE THREAD

**Issue by hagay321** [FluidSynth/fluidsynth#715]
Hi everyone, I encounter some issue trying to loud multiple sf2 files and associate each one with a different channels.

I used,
fluid_synth_sfload(synth, "path to sf.sf2", 1);

for loading the soundfonts and with,
fluid_synth_program_select_by_sfont_name(synth, ch, "path to sf.sf2", bank_num, preset_num);

to associate the sf files with the relevant bank-program to a specific channel.

I know that each sf2 piled into a stack and that each sf2 receiving an ID in ascending order, so in the code below,
"sf1.sf2" has ID = 1;
"sf2.sf2" has ID = 2;
"sf3.sf2" has ID = 3;
"sf4.sf2" has ID = 4;

sf1,2,3 and 4 are madded with an sf2-fils editing software and contain exactly one bank and one soundfont as follow,
sf1 contain one bank=0 and one program=1
sf2 contain one bank=0 and one program=2
sf3 contain one bank=0 and one program=3
sf4 contain one bank=0 and one program=4

the bank and program numbers that are sets for each cahnnel is correct and verified by the function,
fluid_synth_get_program(synth, 0, &sf_id, &bank_num, &preset_num);

I also set "player.reset-synth" to '0' as mentioned in some forums.
fluid_settings_setint(settings, "player.reset-synth", 0);

For what I'm understand from fluidsynth wiki, while rendering fluidsynth start to look for a bank-program match for each channel from TOS to bottom. If not found then it uses TOS sf.

I thought that "fluid_synth_program_select_by_sfont_name" suppose to associate the midi channel to the sf-bank-program set in this function regardless to the original bank-program of the midi channel. Am I wrong?

In the code below it seems that "fluid_synth_program_select_by_sfont_name" doesn't do a thing. The output is empty unless I use midi file that contain a channel with program 1,2,3 or 4 - as the loaded sf files.

There is few info on net about loading multiple sf2 files.
Really appreciate if somebody could light me up or give me some lead, thank.

I do the follow,

{
	int err;
	int ch;
	int sf_id
	int bank_num;
	int preset_num;

	// ***
	fluid_settings_t* settings;
	fluid_synth_t* synth;
	fluid_player_t* player;
	fluid_file_renderer_t* renderer;
	settings = new_fluid_settings();
	// specify the file to store the audio to
	// make sure you compiled fluidsynth with libsndfile to get a real wave file
	// otherwise this file will only contain raw s16 stereo PCM
	fluid_settings_setstr(settings, "audio.file.name", wav_filename.c_str());
	// use number of samples processed as timing source, rather than the system timer
	fluid_settings_setstr(settings, "player.timing-source", "sample");
	// since this is a non-realtime scenario, there is no need to pin the sample data
	fluid_settings_setint(settings, "synth.lock-memory", 0);
	// set player.reset-synth
	fluid_settings_setint(settings, "player.reset-synth", 0); // H:
	synth = new_fluid_synth(settings);

	// *** loading of a soundfont omitted ***
	fluid_synth_sfload(synth, "sf1.sf2", 1);  // contain one bank=1 with one program=0 
	fluid_synth_sfload(synth, "sf2.sf2", 1);  // contain one bank=2 with one program=0 
	fluid_synth_sfload(synth, "sf3.sf2", 1);  // contain one bank=3 with one program=0 
	fluid_synth_sfload(synth, "sf4.sf2", 1);  // contain one bank=4 with one program=0 

	// associate channel with a sf-bank-program
	ch = 1;
	bank_num = 0;
	preset_num = 1;
	err = fluid_synth_program_select_by_sfont_name(synth, ch, "sf1.sf2", bank_num, preset_num);
	
	ch = 2;
	bank_num = 0;
	preset_num = 2;
	err = fluid_synth_program_select_by_sfont_name(synth, ch, "sf2.sf2", bank_num, preset_num);

	ch = 3;
	bank_num = 0;
	preset_num = 3;
	err = fluid_synth_program_select_by_sfont_name(synth, ch, "sf2.sf2", bank_num, preset_num);

	ch = 4;
	bank_num = 0;
	preset_num = 4;
	err = fluid_synth_program_select_by_sfont_name(synth, ch, "sf2.sf2", bank_num, preset_num);

	//
	player = new_fluid_player(synth);
	fluid_player_add(player, clSrcMidiFile.c_str());
	fluid_player_play(player);
	renderer = new_fluid_file_renderer(synth);
	while (fluid_player_get_status(player) == FLUID_PLAYER_PLAYING)
	{
		if (fluid_file_renderer_process_block(renderer) != FLUID_OK)
		{
			break;
		}
	}

	// just for sure: stop the playback explicitly and wait until finished
	fluid_player_stop(player);
	fluid_player_join(player);
	delete_fluid_file_renderer(renderer);
	delete_fluid_player(player);
	delete_fluid_synth(synth);
	delete_fluid_settings(settings);
	// ***

}

**Comment by derselbst** [comment]
Perhaps it's due to the contradiction of your statement in comment vs. code:

> sf1 contain one bank=0 and one program=1
sf2 contain one bank=0 and one program=2
sf3 contain one bank=0 and one program=3
sf4 contain one bank=0 and one program=4

> // contain one bank=1 with one program=0 
// contain one bank=2 with one program=0 
// contain one bank=3 with one program=0 
// contain one bank=4 with one program=0 

Or perhaps it's because of the copy paste errors:

>err = fluid_synth_program_select_by_sfont_name(synth, ch, "sf2.sf2", bank_num, preset_num);
err = fluid_synth_program_select_by_sfont_name(synth, ch, "sf2.sf2", bank_num, preset_num);
err = fluid_synth_program_select_by_sfont_name(synth, ch, "sf2.sf2", bank_num, preset_num);

Or perhaps the MIDI file only plays on channels 0 or 5-15, which you have not assigned.

Or perhaps it's your assumption that you can "pin" certain soundfonts to certain MIDI channels. Not really, because as soon as the next bank or prog change event arrives, a different soundfont may be picked.

**Comment by jjceresa** [comment]
>sf1,2,3 and 4 are madded with an sf2-fils editing software and contain exactly one bank and one soundfont as follow,
sf1 contain one bank=0 and one program=1
sf2 contain one bank=0 and one program=2
sf3 contain one bank=0 and one program=3
sf4 contain one bank=0 and one program=4

Ok. Now you should verify this, before attempting to write any code. The fast, best and simple way to do that is using the fluidsynth console application.
You only need 3 commands (load,select, noteon):
1) `load` only one `soundfont` file at a time
2) `select` a bank and preset in a channel `x`
3) play a note with the `noteon` command on this channel `x`. You should hear the expected instrument.
