### ISSUE TITLE
Minor fluidsynt error when invoking fluidsynth with a MIDI file.

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#730]
On Branch `master`.

1)When invoking fluidsynth console application with a midifile like this:
>fluidsynth   midifile.mid soudfont.sf2     or
>fluidsynth   soudfont.sf2  midifile.mid

We got the following fluidsynth error message: 
`fluidsynth: error: fluid_is_soundfont(): expected RIFF chunk id 0x46464952' but got '0x6468544D.`

But the midifile is played correctly. So this error message shouldn't be displayed.

2)there is no error message when invoking fluidsynth console application with `only` the soundfont file, like this:
>fluidsynth   soudfont.sf2

**Comment by derselbst** [comment]
Oh, this was most recently introduced when I tried to debug #720 and I thought it would be useful if that function reports the reason for the failure. Could we just lower it to `FLUID_DBG` level?

**Comment by jjceresa** [comment]
>...and I thought it would be useful if that function reports the reason for the failure.

Ah, yes. Sure this is useful.

>Could we just lower it to FLUID_DBG level?

No, the error level is fine. However in fluidsynth.c it would be preferable to change the order of file check file to avoid fluid_is_soundfont() checking a MIDI. Something like that:
if(!fluid_is_midifile(argv[i]))
{
       if(fluid_is_soundfont(argv[i]))
       {
               if(fluid_synth_sfload(synth, argv[i], 1) == -1)
                {
                    fprintf(stderr, "Failed to load the SoundFont %s\n", argv[i]);
                }
        }
        else
        {
                fprintf(stderr, "Parameter '%s' not a SoundFont or MIDI file or error occurred identifying it.\n", argv[i]);
        }
}

I will do a PR in one minute.
