### ISSUE TITLE
add a "skip n bars" feature

### ISSUE THREAD

**Issue by juanlucasrey** [FluidSynth/fluidsynth#757]
useful when doing rapid cycle of writing/listening using the command line only.

so for example 

>fluidsynth -ni file.sz2 generated_midi.mid --skip 8

to avoid listening to the first 8 bars again and again.

I can of course write and generate a second midi file skipping whatever bars I need, but I assume an option like that would not be too hard to add (I might be wrong)

**Comment by derselbst** [comment]
What do you mean by "bar"?

**Comment by jjceresa** [comment]
>I can of course write and generate a second midi file skipping whatever bars I need, but I assume an option like that would not be too hard to add (I might be wrong)

You probably expect that the player is able to handle bar:beat:unit pointer time isn't ?

**Comment by juanlucasrey** [comment]
right midi probably does not have that information, but I am not sure. regardless any kind of measure that would be recognisable by the player, (like seconds for example) would be as useful.

I'm just trying to replicate the functionality of a full fledged GUI (like Sibelius or others) where I am able to play what I write starting form a certain point, and not the beginning every time.

**Comment by jjceresa** [comment]
>right midi probably does not have that information, but I am not sure. regardless any kind of measure that would be recognisable by the player, (like seconds for example) would be as useful.

MIDI file specs provide time signature events, that allows any application to express time in bar:beat:unit which is the relative musical time any musician are familiar with. This kind of time is always relative to a quarter note regardless the absolute duration (i.e in second) of a quarter note.  Actually the simple fluidsynth player ignore time signature events. And this isn't easy to implement. However, the player know the tick time which is a fraction of a quarter note.
Using recent master you have a player command `player_step num` that allows to move the current position forward/backward. You should try it using fluidsynth application console.

**Comment by juanlucasrey** [comment]
I might test once it is released. when would that be more or less?

**Comment by juanlucasrey** [comment]
oh I see it is only available on the console. ok will test there. I guess then it would be a matter of adding an option on the terminal call driving that.

**Comment by jjceresa** [comment]
>I'm just trying to replicate the functionality of a full fledged GUI.

Did you read the Wiki about the player API ?

**Comment by juanlucasrey** [comment]
yes not fully but I am aware of it. I try to avoid though because my "iteration" involves another application. here is what I do after some writing, hopefully it's self explanatory:

abc2midi ./some_song.abc -o some_song.mid && fluidsynth -ni some_soung.sf2 ./some_song.mid

**Comment by juanlucasrey** [comment]
now of course you don't have to adapt to my or any's way of doing things, but I just think it would be a useful option, like tempo is too, for example.

**Comment by jjceresa** [comment]
>now of course you don't have to adapt to my or any's way of doing things, but I just think it would be a useful option, like tempo is too, for example.

Try to put the necessary player commands in a config file (i. config.txt) and invoque fluidsynth with the option -f config.tx.

**Comment by jjceresa** [comment]
>Try to put the necessary player commands in a config file (i.e `config.txt`) and invoke fluidsynth with the option -f `config.txt`.

Does this, fluidsynth will read `config.txt` and execute automatically each commands.

**Comment by derselbst** [comment]
The `player_seek` shell command can now be placed in a user-command file. Which I believe satisfies the needs of this issue.
