### ISSUE TITLE
Windows waveout driver crash

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#758]
This is issue has been introduced by commit 772f62fc91c06f070791fea9cd81e9629d7ff71f.

This commit has introduced the use of `audio.periods` and `audio.period-size` settings
The segmentation fault occurs for low value of audio.periods, audio.periods-size, for example
- audio.periods=4, audio.periods-size=64 or 128.
This produces a segmentation when the driver is started, or when quitting the application.
Will fix that in a PR.

**Comment by derselbst** [comment]
Fixed by #759
