### ISSUE TITLE
Windows drivers now exclude 16bits audio cards

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#760]
Recent changes on Windows drivers make those drivers now failling when used with 16bits only audio card.

**Comment by derselbst** [comment]
Are you sure that this could cause trouble? Does it cause trouble for you?

Because [according to Chris](https://github.com/FluidSynth/fluidsynth/pull/754#issuecomment-767400421) the sample format only matters if you have exclusive access to the sound card. And the new WASAPI driver is the only one that has.

His statement is backed by the fact that my Win10 laptop's sound card only supports 48kHz int16 natively:

```
	Speakers/Headphones (Realtek(R) Audio)
	  8000Hz, 16bits ................................ FAILED
	  8000Hz, float ................................. FAILED
	  11025Hz, 16bits ............................... FAILED
	  11025Hz, float ................................ FAILED
	  16000Hz, 16bits ............................... FAILED
	  16000Hz, float ................................ FAILED
	  22050Hz, 16bits ............................... FAILED
	  22050Hz, float ................................ FAILED
	  24000Hz, 16bits ............................... FAILED
	  24000Hz, float ................................ FAILED
	  32000Hz, 16bits ............................... FAILED
	  32000Hz, float ................................ FAILED
	  44100Hz, 16bits ............................... FAILED
	  44100Hz, float ................................ FAILED
	  48000Hz, 16bits ............................... OK
	  48000Hz, float ................................ FAILED
	  88200Hz, 16bits ............................... FAILED
	  88200Hz, float ................................ FAILED
	  96000Hz, 16bits ............................... FAILED
	  96000Hz, float ................................ FAILED
```

However, when running waveout or dsound I can pretty much choose any sample rate and any sample format and it just works. Whereas we observed that the WASAPI driver would fail for those configurations.

**Comment by jjceresa** [comment]
>Are you sure that this could cause trouble? Does it cause trouble for you?

This cause trouble, because I am using a palette of cards on different machines that are not all usb card (they cannot easily interchangeable).
Also, I use dsound with 16bits card that fails now.

>Because according to Chris the sample format only matters if you have exclusive access to the sound card.

The audio path is:   FS-audio-drivers-->[dsound]-->[`device-driver/ks`]->audio-card. 

No, the sample format can be imposed by the `device driver` which is between `dsound` and the i/o `audio card`. The device-driver has the knowledge about the capabilities of the hardware.  This as nothing to do with the fact we want to use the audio card in exclusive mode or not.

>Whereas we observed that the WASAPI driver would fail for those configurations.
Yes , WASAPI being intended to be a very low latency driver should ovoid to work in shared mode to obtain this result. Shared mode require: mixing + buffer adaptation + [sample rate conversion]. Ofc, all this is against very low latency goal.

Here, to give an example of a 16bits audio card used with dsound (shared mode) the best latency is: 46ms.
The same 16bits audio card used through `portaudio-wdm/ks` , the best possible latency is : 12 ms.

I am really sorry to say that having any FS-drivers that reject 16 bits card isn't a good new.

**Comment by derselbst** [comment]
Ok, no problem. I'll restore it later.

**Comment by derselbst** [comment]
Should work again, pls. test.

**Comment by jjceresa** [comment]
The restore 16bits for dsound, waveout works fine. Thanks.
