### ISSUE TITLE
The MIDI file player starts playing immediately at soon it is created

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#763]
On `master`, the player starts playing immediately at soon it is created (`new_fluid_player()`) and a MIDI file is added `fluid_player_add()`.

expected behaviour: The player should stay in "stop" state after its creation.

Steps to reproduce:
1) comment line 994 in fluidsynth.c: `//        fluid_player_play(player);`
2) fluidsynth anysf2.sf2 anymidifile.mid

**Comment by derselbst** [comment]
Should be fixed by #765

**Comment by jjceresa** [comment]
>Should be fixed by #765

Yes, it is fixed by #765.
