### ISSUE TITLE
Rapidly changing/extreme panning values result in audible clicks/pops

### ISSUE THREAD

**Issue by dwhinham** [FluidSynth/fluidsynth#768]
### FluidSynth version
2.1.7

### Describe the bug
Some MIDI soundtracks change the panning values to extreme values (i.e hard-left to hard-right) rapidly while notes are playing for effect. A good example is the bassline from the Descent Level 1 music (about 30 seconds into the song - examples attached).

With FluidSynth, this can result in audible clicks/pops. Tested mainly with GeneralUser GS, but other SoundFonts exhibit this behaviour too.

### Expected behavior
The audio should be panned without audible artifacts.

### Steps to reproduce
1. Start FluidSynth with any GM/GS  SoundFont (GeneralUser GS was used for testing).
2. Play the attached MIDI (`descent_pan_bass_only.mid`) and notice clicks/pop.

### Additional context

I'm guessing that the distortion is because the panning is instantaneous, maybe similar to the "click" you get when you truncate a sample. Maybe the behaviour could be mitigated by applying a very fast envelope to smoothly fade out the transition?

The archive attached below archive contains the following files:

- `D1-Level 1.mid` - Complete Level 1 MIDI song from Descent 1. Panned bassline that triggers the behaviour starts at ~30 seconds into the song.
- `descent_pan_bass_only.mid` - Just the panned bassline on its own.
- `descent_pan_gugs.wav` - Recording of the above from FluidSynth using GeneralUser GS.
- `descent_pan_mu2000.wav` - Recording of the above from a Yamaha MU2000, just for comparison.

[descent.zip](https://github.com/FluidSynth/fluidsynth/files/5928868/descent.zip)

**Comment by derselbst** [comment]
I can confirm this. Looking at only one channel, we can see the clicks in a spectrogram:

![left](https://user-images.githubusercontent.com/8152480/107117689-5a96d580-687c-11eb-96f6-849569839dfb.png)

When mixing both channels, the clicks average each other out:

![mixed](https://user-images.githubusercontent.com/8152480/107117710-80bc7580-687c-11eb-9d27-b6a3803fbfd3.png)

Disabling panning also makes the clicks go away.

Looking at one of those clicks in more detail, we can see that the waveform makes a jump:

![jump](https://user-images.githubusercontent.com/8152480/107117746-a9dd0600-687c-11eb-841e-b075980f6ab4.png)

This can be reproduced with fluidsynth 1.1.6 as well. We already interpolate the sample's amplitude (`_fluid_rvoice_dsp_t::amp`) between `FLUID_BUFSIZE` samples in a linear way:

https://github.com/FluidSynth/fluidsynth/blob/e2d67ea77237046b703d537aec90620c22f7f629/src/rvoice/fluid_rvoice.c#L98-L99

This is then considered, when the sample is actually rendered, see here (nearest neighbor interpolation for simplicity, 4th order cubic is default which you can find more to the bottom):
https://github.com/FluidSynth/fluidsynth/blob/e2d67ea77237046b703d537aec90620c22f7f629/src/rvoice/fluid_rvoice_dsp.c#L90

However, here is a different amplitude, namely `_fluid_rvoice_buffers_t::amp`. This one tells us the amplitude by which we want to mix that mono sample from above into the final left- and right-buffers. This `amp` is set here

https://github.com/FluidSynth/fluidsynth/blob/e2d67ea77237046b703d537aec90620c22f7f629/src/rvoice/fluid_rvoice.c#L515

and later used here during mixing:

https://github.com/FluidSynth/fluidsynth/blob/e2d67ea77237046b703d537aec90620c22f7f629/src/rvoice/fluid_rvoice_mixer.c#L395


As we can see it is used without interpolation. Adding a simple linear interpolation between `FLUID_BUFSIZE` samples should solve this problem. However, we must pay attention: The loop in which it it used is currently vectorized by the compiler and I would like to keep it that way. So a simple `amp+=incr;` won't do it.

I will probably come back to this in a few days.

**Comment by dwhinham** [comment]
Thanks for the detailed investigation and confirming the issue, I appreciate the need to maintain vectorization - my project uses FluidSynth in a baremetal ARM environment and performance is important.

I look forward to a possible solution when you have some free time. 🙂

**Comment by derselbst** [comment]
I just found some time, so here we go. Feel free to test: [issue768](https://github.com/FluidSynth/fluidsynth/tree/issue768)

**Comment by dwhinham** [comment]
Thanks for this!

I gave it a shot - the clicks are definitely gone, which is great, although I _**think**_ I'm hearing something new that wasn't there before - it's as if there's a chorus/phase shift effect being applied.

I've attached a recording, with the test phrase played through 2.1.7 and then through [issue768](https://github.com/FluidSynth/fluidsynth/tree/issue768).

[pan_fix1.zip](https://github.com/FluidSynth/fluidsynth/files/5937489/pan_fix1.zip)

Do you hear it? What do you think?

**Comment by derselbst** [comment]
Thanks, glad to hear that it works fine!

FYI: This fix will be part of fluidsynth 2.1.8, not sure when it will be released though.

**Comment by dwhinham** [comment]
Thankyou so much for the quick fix!
