### ISSUE TITLE
Clicks/pops in audio output

### ISSUE THREAD

**Issue by vladkosi** [FluidSynth/fluidsynth#786]
### FluidSynth version
2.2 beta1 or latest master
Windows 10 64-bit

### Describe the bug
Audible clicks/pops in rendered file or audio output. These defects can also be heard in GZDoom.

### Expected behavior
Audio without clicks/pops.

### Steps to reproduce
Render WAV file:
```
fluidsynth -R 0 -C 0 -r 44100 -F output.wav gzdoom.sf2 e1m1.mid
```

Or just play:
```
fluidsynth -R 0 -C 0 -r 44100 gzdoom.sf2 e1m1.mid
```

Most obvious at 6.6 seconds and 24.5 seconds.

### Additional context
Bug was introduced in commit aebc4837ddfe0c9329211d9806a9c77bc83a4e1c, commit 25b0503ba764769808318f5deabdb125500d0a84 sounds fine.
Attached Doom 1 MIDI and GZDoom default soundfont.

[doom.zip](https://github.com/FluidSynth/fluidsynth/files/6079106/doom.zip)

**Comment by derselbst** [comment]
Thanks for the report! And already bisected, perfect!

I can confirm that aebc4837ddfe0c9329211d9806a9c77bc83a4e1c is to blame. I'll investigate.

**Comment by derselbst** [comment]
Should be fixed in recent master. Feel free to test.

**Comment by vladkosi** [comment]
Audio sounds perfect now and the rendered files are identical between commits https://github.com/FluidSynth/fluidsynth/commit/25b0503ba764769808318f5deabdb125500d0a84 and https://github.com/FluidSynth/fluidsynth/commit/8adaaa7079e7d4f37e00615b4024957daaca71c1 on branch 2.1.x.

Thanks!
