### ISSUE TITLE
Bad License

### ISSUE THREAD

**Issue by MaxBr5** [FluidSynth/fluidsynth#797]
### Related discussion on the mailing list
_Features should be discussed by the community. Historically, our community lives at the mailing list. Bring up your ideas there, before opening tickets. In case you already did that, provide a link to the thread._

### Is your feature request related to a problem?
_A clear and concise description of what the problem is._
Bad license, Gnu LGPL is bad.
### Describe the solution you'd like
_A clear and concise description of what you want to happen._
<pre>Please change the license to </pre>[Gnu GPL1](https://www.gnu.org/licenses/gpl-1.0.txt)
### Describe alternatives you've considered
_A clear and concise description of any alternative solutions or features you've considered._
<pre>Change license to the MIT license or the <A HREF="https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_(original_%22BSD_License%22)">4-clause BSD license</a></pre>
### Additional context
_Add any other context or screenshots about the feature request here._

**Comment by derselbst** [comment]
> Bad license, Gnu LGPL is bad.

You must be kidding.

**Comment by MaxBr5** [comment]
<pre>Actually no. I was not kidding, there is actually and older, less boring <a href="https://web.archive.org/web/20010630060627/http://www.apache.org/licenses/LICENSE-1.0">apache 1.0 license </a></pre>

**Comment by MaxBr5** [comment]
<pre>Opps, I meant an , not and sorry to confuse you</pre>
