### ISSUE TITLE
Failed to create the audio driver

### ISSUE THREAD

**Issue by jedker999** [FluidSynth/fluidsynth#803]
Im using macOS big sur and have installed fluidsynth v 2.1.7. When I want to start it I get an error:

fluidsynth: error: Error setting the audio callback. Status=-66748
Failed to create the audio driver

any ideas how to fix it?

**Comment by derselbst** [comment]
Same issue as https://lists.nongnu.org/archive/html/fluid-dev/2021-02/msg00003.html

No idea how to fix it. Pls. verify that when using the portaudio driver `fluidsynth -a portaudio` it fails as well. If it does fail, it's not a fluidsynth issue.

**Comment by jedker999** [comment]
> Same issue as https://lists.nongnu.org/archive/html/fluid-dev/2021-02/msg00003.html
> 
> No idea how to fix it. Pls. verify that when using the portaudio driver `fluidsynth -a portaudio` it fails as well. If it does fail, it's not a fluidsynth issue.

unfortunately throws error as well:
||PaMacCore (AUHAL)|| Error on line 1316: err='-66748', msg=Unknown Error
fluidsynth: error: Error opening PortAudio stream: Internal PortAudio error
Failed to create the audio driver

**Comment by derselbst** [comment]
This error is printed when the call to `AudioUnitSetProperty` fails. According to www.osstatus.com the returned error is `kAudioComponentErr_NotPermitted`. You'll probably be more lucky trying to reach out in a Mac Forum.

**Comment by jedker999** [comment]
> This error is printed when the call to `AudioUnitSetProperty` fails. According to [www.osstatus.com](http://www.osstatus.com) the returned error is `kAudioComponentErr_NotPermitted`. You'll probably be more lucky trying to reach out in a Mac Forum.

Thanks for response.

**Comment by giona69** [comment]
@jedker999 any luck on solving this problem? I have it too ...

**Comment by mawe42** [comment]
Just an idea (coming from somebody who doesn't use Macs): According to [this](https://github.com/bruce0505/ios7frameworks/blob/master/AudioUnit/AUComponent.h#L790), the `kAudioComponentErr_NotPermitted` error might point to insufficient privileges: 
> @constant   kAudioComponentErr_NotPermitted
>      app needs "inter-app-audio" entitlement or host app needs "audio" in its UIBackgroundModes. Or app is trying to register a component not declared in its Info.plist.

Could you try giving fluidsynth more permissions under System Preferences / Security & Privacy / Privacy? The following might be interesting:
 - Microphone
 - Media & Apple Music
 
 But maybe there are even more audio related permissions?

**Comment by ringoz** [comment]
@jedker999  can you reopen this issue?

fluidsynth just doesn't work on macOS currently.

**Comment by ringoz** [comment]
quote from debug output:
> This application, or a library it uses, is using the deprecated Component Manager for hosting Audio Components. This is not supported when rebuilding against the 11.00 or later SDK. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

**Comment by derselbst** [comment]
Wow, I would have never guessed that `kAudioComponentErr_NotPermitted` is due to a deprecated API. @ringoz Thank you very much! Does the debug output you've posted show up automatically, or do you have to set some environment variables or something?

**Comment by ringoz** [comment]
Fortunately, this debug output was shown by OS automatically.
It is not stdout or stderr, but NSLog & os_log kind of output.

**Comment by derselbst** [comment]
Ok, thanks.

@giona69 @jedker999 I've just applied the fix to master. Pls. let me know if it works for you, so I can backport this to 2.1.x .

**Comment by mawe42** [comment]
Great that this was fixed! And funny that PortAudio had the exact same problem: https://github.com/PortAudio/portaudio/pull/338

**Comment by justinpage** [comment]
For those on macOS Big Sur who download `fluidsynth` via homebrew: you have version `2.1.8` installed.

I was seeing the same issue described in this thread and the following command did the trick:

```sh
fluidsynth -g 2 -p fluidsynth -o midi.driver=coremidi -o audio.driver=portaudio \
	-o audio.coreaudio.device=default -o audio.period-size=256 \
	soundfont.sf2
```

In other words, running `audio.driver=portaudio` instead of `audio.driver=coreaudio` worked for me.

Keep in mind that Homebrew has an open pull request to make the latest version number available:
https://github.com/Homebrew/homebrew-core/pull/74428

Hope this helps!
