### ISSUE TITLE
fluidsynth hangs on quit command after playing a MIDI file

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#817]
### FluidSynth version
current master 2.1.8

### Describe the bug
Execute: fluidsynth yoursf.sf2 yoursong.mid
The MIDI  file is played and when finished if the user type the `quit` command, fluidsynth displays `cheers!` then hangs.

If no MIDI file is played, Fluidsynth doesn't hang on `quit` command.

**Comment by derselbst** [comment]
Seems like `fluid_player_stop` should only set the stopping state, if the player's state is ready or playing, but not when the player is already done. Care must be taken to perform this atomically, for which I'm currently lacking a solution.

**Comment by jjceresa** [comment]
The bug was introduced by commit 676923757c4f96c5c34931da5566d5b5be3e15eb.
