### ISSUE TITLE
SoundFont loader does not properly validate preset generators

### ISSUE THREAD

**Issue by mawe42** [FluidSynth/fluidsynth#821]
The default SoundFont loader attempts to validate the generators in preset zones against a list of invalid generators in [valid_preset_genid()](https://github.com/FluidSynth/fluidsynth/blob/661a06b5045b7004c3f6f8d7c5c5aea6e94e6440/src/sfloader/fluid_sffile.c#L2393). The list of invalid preset generators has a sentinel value of 0 which marks the end of the list. The problem is that the first entry in this list is the generator `Gen_StartAddrOfs`, which has the id 0. This effectively prevents genid checks against any other entries in this list.

Affects at least current and recent versions of FluidSynth, but probably much older versions as well.

I'm currently preparing a code cleanup branch for fluid_sffile, so I would address this issue in there if you don't mind.

**Comment by jjceresa** [comment]
>The list of invalid preset generators has a sentinel value of 0

Please note that the list of invalid inst generator `invalid_inst_gen[]` has also 0 which marks the end of the list. I am aware that this is not an issue for `valid_inst_genid()`. If you have in mind to change the end of list marker value for `invalid_preset_gen[]`, then for consistency  perhaps it worth to change this for  `invalid_inst_gen[]` as well ?.

**Comment by mawe42** [comment]
Yes, good point. And I've already made both list behaviours consistent and without sentinal. Will push a refactor-branch tonight or tomorrow, then you can review those proposed changes.
