### ISSUE TITLE
FluidSynth 2.2.0 Android using NDK runtime exception

### ISSUE THREAD

**Issue by nahumbudin** [FluidSynth/fluidsynth#827]
Hello.

FluidSynth 2.2.0  for Android.

Following Hector Ricardo paper Creating a Fluidsynth Hello World App for Android that works fine for ver 2.1.15
[https://medium.com/swlh/creating-a-fluidsynth-hello-world-app-for-android-5e112454a8eb](url)

When upgrading to V 2.2.0, build works OK, however, a runtime exception is reported for the Java line code loading the native-lib

System.loadLibrary("native-lib");:

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/app/com.projects.tiltune.fluidsynthtest2-WaZQFCqdWYwLahoagbcT0g==/base.apk!/lib/arm64-v8a/libfluidsynth.so"... 

Thanks,

Nahum.

[FluidSynth220TestAndroidNDK.zip](https://github.com/FluidSynth/fluidsynth/files/6263991/FluidSynth220TestAndroidNDK.zip)

**Comment by derselbst** [comment]
Which version of Android are you using?

**Comment by nahumbudin** [comment]
Android 10 device.

build.gradle (app):

minSdkVersion 27
targetSdkVersion 30

**Comment by derselbst** [comment]
Have you read the release notes of fluidsynth 2.2.0?

**Comment by nahumbudin** [comment]
Android API Level >=30  

Sorry, missed that.... :-(
