### ISSUE TITLE
Support reverb with the WASAPI audio driver

### ISSUE THREAD

**Issue by jimhen3ry** [FluidSynth/fluidsynth#836]
### Related discussion on the mailing list
WASAPI and reverb #831

### Is your feature request related to a problem?
FluidSynth reverb setting apparently become ineffective when the Windows WASAPI audio driver is used.

### Describe the solution you'd like
Support reverb with the WASAPI audio driver. If exclusive versus non-exclusive WASAPI is an issue, allow a choice between exclusive and non-exclusive modes.

### Describe alternatives you've considered
Using the PortAudio WASAPI driver.

### Additional context
Reverb is absolutely necessary for virtual organs and WASAPI nearly so. It would be a big help for the Miditzer to be able to allow users to use the WASAPI audio driver without giving up reverb.

**Comment by jimhen3ry** [comment]
Related discussion on the mailing list:
WASAPI and reverb #831

Is your feature request related to a problem?
FluidSynth reverb setting apparently become ineffective when the Windows WASAPI audio driver is used.

Describe the solution you'd like:
Support reverb with the WASAPI audio driver. If exclusive versus non-exclusive WASAPI is an issue, allow a choice between exclusive and non-exclusive modes.

Describe alternatives you've considered:
Using the PortAudio WASAPI driver.

Additional context:
Reverb is absolutely necessary for virtual organs and WASAPI nearly so. It would be a big help for the Miditzer to be able to allow users to use the WASAPI audio driver without giving up reverb.

**Comment by jjceresa** [comment]
>Using the PortAudio WASAPI driver.

Have you considered using PortAudio WDM/KS as alternative ?

**Comment by jimhen3ry** [comment]
> Have you considered using PortAudio WDM/KS as alternative ?

Yes. 

A design goal for the Miditzer is to be very easy for a complete novice to get up and running. We believe that if someone isn't up and running within minutes of downloading, without support or reading documentation, then it is likely they will delete the program and be lost to us. To date, we make dsound the default audio driver because we know it works 99.99% of the time.

When users add a MIDI keyboard the latency of dsound becomes an issue and a lot of support time is spent trying to coach users through tuning their system for reduced latency. We have debated WASAPI versus WDM/KS for many years. The big stumbling block is the lack of understanding of how many users would be negatively affected by using WASAPI or WDM/KS. 

We are only now adding support for selecting a FluidSynth audio driver. (The use of FluidSynth is optional in the Miditzer but the vast majority of users do use it.) The addition of WASAPI support in FluidSynth 2.2.0 was serendipitous timing because it coincides with the first major revision of the Miditzer in many years. The Miditzer is strongly driven by the KISS principle. If we can support FluidSynth WASAPI without having to qualify that it kills reverb, that would be our preference. If we can avoid having to talk about adding PortAudio to the mix, we'd like that too. 

At this point, nothing is off the table. We are just trying to put together the best "it just works" solution we can.

**Comment by jjceresa** [comment]
@jimhen3ry Thanks for the explanations.

>If we can avoid having to talk about adding PortAudio to the mix, we'd like that too.

I understand your point. I noticed that portaudio WDM/KS is bugged (using certain audio hardware). So it is best to keep the KISS principle.

**Comment by chirs241097** [comment]
Should be a fairly easy fix. Will work on it tomorrow.

**Comment by derselbst** [comment]
@jimhen3ry I've just merged Chris' PR to master. It will be available in version 2.2.1.
