### ISSUE TITLE
FluidSynth Error "Audio Driver not found" message on Mac OS Big Sur

### ISSUE THREAD

**Issue by cunningar0807** [FluidSynth/fluidsynth#870]
My name is Arianna.

I was trying to setup FluidSynth with a midi player, using a custom SoundFont.

I tried typing a command in Terminal such as: `fluidsynth -a jack -j -m jack ~/Documents/MuseScore3/SoundFonts/Orpheus_1.042_31.01.2021.sf2`

I get a message saying:
`fluidsynth: error: Unknown integer parameter 'audio.jack.autoconnect'`

Does this actually mean that coreaudio, portaudio, or FluidSynth is no longer supported for Mac OS Big Sur?

**Comment by derselbst** [comment]
It means that fluidsynth was compiled without jack support. And it surely is no bug.

**Comment by cunningar0807** [comment]
> It means that fluidsynth was compiled without jack support. And it surely is no bug.

Then how do I fix the Jack Support issue?
