### ISSUE TITLE
Header files are missing from Android release zip

### ISSUE THREAD

**Issue by atsushieno** [FluidSynth/fluidsynth#894]
Currently Android build artifacts on the Releases page are created from the new Azure pipelines. I noticed that it is missing headers and when we build apps that references fluidsynth API in our code we will have to get those headers from somewhere separately.

Windows release binary zip seems to contain the headers. I think it is the right way for Android too.

### Is your feature request related to a problem?

- when we build apps that references fluidsynth API in our code we will have to get those headers from somewhere separately, otherwise.

### Describe the solution you'd like

- Add `fluidsynth.h` in the archive too, probably within `include/fluidsynth` directory (assuming it is platform independent).

### Describe alternatives you've considered

- I could download headers manually.

### Additional context

Not sure if it is worth mentioning, but I make use of fluidsynth for Android in this app (which I think has build setup in closer mindset to the latest Android builds here rather than my original Cerbero builds), https://github.com/atsushieno/aap-lv2-fluidsynth (It is still not an intuitive use case and not for testing header inclusion at all.)

Checked release v2.2.1. It might be different from the latest azure pipeline settings.

**Comment by derselbst** [comment]
Oh, right. I only cared about getting binaries compiled and completely for about the headers. I'll look into it.

**Comment by atsushieno** [comment]
If I can add small minor thing here, Android shared libraries had better be renamed to .so, without symbolic links to so.x.y. Android does not support those symbolic links at loading. Those dependencies have valid filenames. Only iconv and the deps have this issue.
