### ISSUE TITLE
Sequencer event ordering is broken for NoteOn vel=0 events

### ISSUE THREAD

**Issue by jet2jet** [FluidSynth/fluidsynth#907]
### FluidSynth version
(commit hash: 17fb48def5b6bd17cd5d0e5acfefd0ab009e4bad )

```
$ ./fluidsynth --version
FluidSynth runtime version 2.2.1
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.2.1
Sample type=double
```

### Describe the bug
With using sequencer (`fluid_sequencer_t`), when sending 'Note on' event immediately after (i.e. same tick of) 'Note on with velocity = 0' event, the first 'Note on' event may sound nothing.

### Expected behavior
'Note on' should always sound in that case

### Steps to reproduce
I attached reproduce source code: [main.cpp.zip](https://github.com/FluidSynth/fluidsynth/files/6616294/main.cpp.zip)
(I used VintageDreamsWaves-v2.sf2 Soundfont on reproduce.)

Extract `main.cpp`, build with `gcc -o main main.cpp libfluidsynth.a -lglib-2.0 -lstdc++ -lm -fopenmp`, and execute `./main`.  
The WAVE file `out.wav` is generated and it may play something weird sound.

### Additional context
- If 'Note off' event is used instead of 'Note on with velocity = 0', it seems OK.
- I wonder that this problem occurs from 0d98c47545aa2424741c0cc2b244e4f73249302c (not tested well, but v2.1.x had no problem)

**Comment by derselbst** [comment]
Since 2.2.0 events that share the same tick are ordered in a special way, see docs of [fluid_sequencer_send_at()](https://www.fluidsynth.org/api/group__sequencer.html#ga83314f4ad773979841afe50cc2efd83f). This ordering currently considers NoteOn Vel=0 events as real NoteOns by mistake. NoteOns with velocity=0 are always treated as noteoff by the synth.

There is more than one way to fix this, I'll need to think about it.

**Comment by derselbst** [comment]
I think the best way would be to make `fluid_event_noteon()` return a NOTEOFF event when `vel==0`. I'll add a regression test for this as well.

**Comment by derselbst** [comment]
Implemented in #908, feel free to test.

**Comment by jet2jet** [comment]
Thanks for the fix.
I tested and confirmed that the issue was fixed.

> Since 2.2.0 events that share the same tick are ordered in a special way, see docs of fluid_sequencer_send_at(). 

I understood that the order of events that have the same timestamp is undefined, but how do you think about 'on-off' effects such as Hold? I wonder that, there may be the case that Hold-off event is followed by Hold-on event with the same timestamp, which assumes it resets sounded notes and turn hold on again at the same time. (If it is a rare or not so good case, the current behavior would be fine.)

**Comment by derselbst** [comment]
By "hold-event" you mean regular Sustain and Sostenuto events? If yes: Just like other CC events, if you want them to be applied in a special order to achieve a special effect, you would need to use different ticks.

**Comment by jet2jet** [comment]
> By "hold-event" you mean regular Sustain and Sostenuto events?

Yes.

> Just like other CC events, if you want them to be applied in a special order to achieve a special effect, you would need to use different ticks.

I understood. Thanks for the reply.
