### ISSUE TITLE
fails to link external OpenMP library

### ISSUE THREAD

**Issue by hmoffatt** [FluidSynth/fluidsynth#917]
On macOS, the clang/LLVM compiler does not include OpenMP support but it is available as an external library via brew:
```
brew install libomp
```

When this library is installed, it is correctly detected by the cmake scripts, but then the compile fails because src/CMakeLists.txt fails to include the include directory and fails to link the library.

I was able to get this to work by adding

```
if ( HAVE_OPENMP )
  include_directories ( ${OpenMP_C_INCLUDE_DIR} )
endif ( HAVE_OPENMP )
```

and to target_link_libraries

```
    ${OpenMP_libomp_LIBRARY}
```

This last one doesn't look 100% correct although it does work; the cmake script has not calculated a nice linker flag (-lomp).

**Comment by derselbst** [comment]
> This last one doesn't look 100% correct although it does work; the cmake script has not calculated a nice linker flag (-lomp).

Could you please uncomment those two lines and try again?
https://github.com/FluidSynth/fluidsynth/blob/15bd824af0362ac443e869521f8bc260bfc89d6b/CMakeLists.txt#L709-L710

**Comment by derselbst** [comment]
Also, which version of clang are you using? Because I tried to reproduce this in [our Mac CI Build](https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=5556&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=5852bf5a-5a02-52f3-bee8-4fdc90cda9d0&l=104), but it keeps reporting that only openMP 201107 is supported, which in insufficient. No matter if libomp is installed or not.

**Comment by hmoffatt** [comment]
Uncommenting those lines fixes the linking, but it doesn't find the include file (/usr/local/include/omp.h) without also adding ${OpenMP_C_INCLUDE_DIR} to the include directories.

My clang is 12.0.5 as provided by Xcode 12.5 (currently the latest):

```
$ clang --version
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

The parallel sound font loading does work nicely on macOS with these changes.

**Comment by hmoffatt** [comment]
By the way, the latest MSVC does support OpenMP 4.0 for 64-bit Windows applications. I haven't tested it yet as 32-bit support (which I need) is coming later.

**Comment by derselbst** [comment]
A PR is ready for this, feel free to test. Unfortunately, Mac11  is still not publicly available for Github Actions and AzureDevOps (actions/virtual-environments#2486), so I cannot see whether it actually works.

**Comment by hmoffatt** [comment]
That's working perfectly for me. Thanks.
