### ISSUE TITLE
audio.jack.autoconnect=1 only connects the first output and first effects channel

### ISSUE THREAD

**Issue by albedozero** [FluidSynth/fluidsynth#920]
### FluidSynth version
2.2.1

### Describe the bug
When using `audio.jack.autoconnect=1` with `audio.jack.multi=1`, only the first effects channel (Reverb) is connected. Additionally, if a value >1 is used for `synth.audio-channels` and `synth.audio-groups`, only the first output channel is connected.

### Expected behavior
Would expect for all Fluidsynth outputs to be connected to the JACK system playback inputs.

### Steps to reproduce
Can be reproduced via the command line
```
fluidsynth -a jack -j -o audio.jack.multi=1 -o synth.audio-channels=2 -o synth.audio-groups=2
```
### Additional context
```
pi@raspberrypi:~ $ jack_lsp -c
system:playback_1
   fluidsynth:l_00
   fluidsynth:fx_l_00
system:playback_2
   fluidsynth:r_00
   fluidsynth:fx_r_00
fluidsynth:l_00
   system:playback_1
fluidsynth:r_00
   system:playback_2
fluidsynth:l_01
fluidsynth:r_01
fluidsynth:fx_l_00
   system:playback_1
fluidsynth:fx_r_00
   system:playback_2
fluidsynth:fx_l_01
fluidsynth:fx_r_01
```

**Comment by derselbst** [comment]
A PR is ready for this, feel free to test. The question remains though how meaningful an autoconnection in case of jack.multi=1 is. It will now just connect all input ports to all output ports and then wraps around in case there are too few input ports.

**Comment by albedozero** [comment]
Perfect - works as expected! I think it makes sense that jack.autoconnect=1 does the same thing whether jack.multi=1 or 0 - i.e. it connects all the available system inputs to FS outputs. In the case where a user has a sound card with multiple stereo outputs, it should be up to the user to determine output routing and not use autoconnect. It's also useful in the case where I want to use JACK to create subgroups of channels for routing LADSPA effects, and don't want to have to use (much slower) shell commands to connect the jack inputs.
