### ISSUE TITLE
src/synth/fluid_synth_monopoly.c license clarification

### ISSUE THREAD

**Issue by cghawthorne** [FluidSynth/fluidsynth#936]
The license header at the top of `src/synth/fluid_synth_monopoly.c` says it's under "GNU Library General Public License" version 2, but the rest of the project is "GNU Lesser General Public License" version 2.1.

I'm guessing this was just a file that happened to be missed when the license was changed. Can you clarify if this was intentional or not? I'm happy to submit a PR to fix it if the intention was to also update it to LGPL-2.1.

Thanks!

**Comment by derselbst** [comment]
Well spotted! It's only a leftover, LGPL-2.1 is correct.

> I'm happy to submit a PR to fix

You're welcome!
