### ISSUE TITLE
[BUG] apt-get build-dep fluidsynth --no-install-recommends removes my existing JACK2 audio system

### ISSUE THREAD

**Issue by EdChdX** [FluidSynth/fluidsynth#941]
### FluidSynth version
2.2.2

### Describe the bug
Tried to build FluidSynth 2.2.2. When running `apt-get build-dep fluidsynth --no-install-recommends` it removes my already-configured JACK2 audio system, rendering my DAWs and other plugins unusable.

### Expected behavior
Just... Don't remove JACK2...

### Steps to reproduce
1. Fetch the source
1. Try to fetch build dependencies
2. JACK2 is removed

**Comment by derselbst** [comment]
This is definitely no fluidsynth issue. Report it to ubuntu packaging.

My best guess is that fluidsynth's .deb package recommends jack. But since you've given `--no-install-recommends` apt-get removes it.

**Comment by EdChdX** [comment]
> This is definitely no fluidsynth issue. Report it to ubuntu packaging.
> 
> My best guess is that fluidsynth's .deb package recommends jack. But since you've given `--no-install-recommends` apt-get removes it.

Actually it's Debian Bullseye
