### ISSUE TITLE
Fluidsynth does not build on macOS 10.5 and earlier

### ISSUE THREAD

**Issue by evanmiller** [FluidSynth/fluidsynth#946]
With #828, Fluidsynth no longer builds on MacOS 10.5 Leopard and earlier. The AudioComponent symbols added in that PR were introduced in 10.6, and so targeting earlier OSes will produce a compile-time error.

There has been discussion over at MacPorts on how to work around this issue (see https://trac.macports.org/ticket/63230 and https://github.com/macports/macports-ports/pull/11706). The consensus has been to check to see if fluidsynth is interested in supporting these OS versions, or if the project would prefer to leave the problem to downstream package maintainers.

In practical terms, the issue can likely be worked around with a few #ifdefs, e.g.

```
#if __MAC_OS_X_VERSION_MIN_REQUIRED < 1060
    ComponentDescription desc;
#else
    AudioComponentDescription desc;
#endif
```

etc.

Is this a feasible change from the project's perspective?

**Comment by derselbst** [comment]
I'd probably accept a PR with those `#ifdefs` as you suggested. Esp. if you have users who still use macOS <=10.5. However, I don't know of any CI service which still provides an old macOS image, so in the future it could break again.
