### ISSUE TITLE
fluidsynth for windows failed to load soundfont path containing non-ASCII chars

### ISSUE THREAD

**Issue by tsingakbar** [FluidSynth/fluidsynth#983]
### FluidSynth 2.2.3
os: win10
locale(ANSI encoding): CP936(default for widows for china since windows xp?)

### Describe the bug
```cmd
d:\opt\fluidsynth-2.2.3\bin>fluidsynfluidsynth.exe d:\冷备\音乐制作\软件\soundfont2\GeneralUser-GS-Live-Audigy-v1.43.sf2
FluidSynth runtime version 2.2.3
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

fluidsynth: error: fluid_is_soundfont(): fopen() failed: 'File does not exist.'
Parameter 'd:\冷备\音乐制作\软件\soundfont2\GeneralUser-GS-Live-Audigy-v1.43.sf2' not a SoundFont or MIDI file or error occurred identifying it.
```
But that file indeed exists.

### Expected behavior
Soundfont file should be loaded.

### Additional context
seems related to https://github.com/FluidSynth/fluidsynth/issues/880

**Comment by tsingakbar** [comment]
## another encoding problem: wasapi enumeration can not display properly

### FluidSynth 2.2.3
os: win10
locale(ANSI encoding): CP936(default for widows for china since windows xp?)

### Describe the bug
```cmd
d:\opt\fluidsynth-2.2.3\bin>fluidsynth.exe -Q
FluidSynth runtime version 2.2.3
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

Available audio devices:
 default
 杩滅▼闊抽

Shared mode:
        default
          8000Hz, 16bits ................................ OK(I)
(omit....)
        杩滅▼闊抽
          8000Hz, 16bits ................................ OK(I)
(omit....)
```

```
> info audio.waveout.device
audio.waveout.device:
Type:          string
Value:         default
Default value: default
Options:       default, 远程音频
Real-time:     no
> info audio.dsound.device
audio.dsound.device:
Type:          string
Value:         default
Default value: default
Options:       default, 远程音频, 主声音驱动程序
Real-time:     no
> info audio.wasapi.device
audio.wasapi.device:
Type:          string
Value:         default
Default value: default
Options:       default, 杩滅▼闊抽
Real-time:     no
```
obviously chinese charactors not displayed properly.

### Expected behavior
Than device is actually "远程音频" instead of non-sense "杩滅▼闊抽"

### Additional context
fluidsynth support waveout, directsound and wasapi for windows platform. after checking the codes, it seems implementations for waveout and dsound will use the ANSI version win32 api to get the device names, so the ANSI encoded names can be displayed in windows cmd.exe properly; but implementation for wasapi fetched the widechar names then converted to utf8, and utf8 encoded names will display properly only when ANSI==UTF8.

IMHO this is awkward, all implementations should use the same encoding.

**Comment by tsingakbar** [comment]
> 
> ### FluidSynth 2.2.3
> 
> os: win10
> locale(ANSI encoding): CP936(default for widows for china since windows xp?)
> ### Describe the bug
> 
> ```batchfile
> d:\opt\fluidsynth-2.2.3\bin>fluidsynfluidsynth.exe d:\冷备\音乐制作\软件\soundfont2\GeneralUser-GS-Live-Audigy-v1.43.sf2
> FluidSynth runtime version 2.2.3
> Copyright (C) 2000-2021 Peter Hanappe and others.
> Distributed under the LGPL license.
> SoundFont(R) is a registered trademark of Creative Technology Ltd.
> 
> fluidsynth: error: fluid_is_soundfont(): fopen() failed: 'File does not exist.'
> Parameter 'd:\冷备\音乐制作\软件\soundfont2\GeneralUser-GS-Live-Audigy-v1.43.sf2' not a SoundFont or MIDI file or error occurred identifying it.
> ```
> 
> But that file indeed exists.
> ### Expected behavior
> 
> Soundfont file should be loaded.
> ### Additional context
> 
> seems related to #880

after applying #984 :
```
d:\opt\fluidsynth-tsingakbar>fluidsynth.exe d:\冷备\音乐制作\软件\soundfont2\GeneralUser-GS-Live-Audigy-v1.43.sf2
FluidSynth runtime version 2.2.3
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

fluidsynth: error: not enough MIDI in devices found. Expected:1 found:0
fluidsynth: error: Device "default" does not exists
Failed to create the MIDI thread; no MIDI input
will be available. You can access the synthesizer
through the console.
Type 'help' for help topics.
````
no more file not found error reports

**Comment by tsingakbar** [comment]
> 
> ## another encoding problem: wasapi enumeration can not display properly
> ### FluidSynth 2.2.3
> 
> os: win10
> locale(ANSI encoding): CP936(default for widows for china since windows xp?)
> ### Describe the bug
> 
> ```batchfile
> d:\opt\fluidsynth-2.2.3\bin>fluidsynth.exe -Q
> FluidSynth runtime version 2.2.3
> Copyright (C) 2000-2021 Peter Hanappe and others.
> Distributed under the LGPL license.
> SoundFont(R) is a registered trademark of Creative Technology Ltd.
> 
> Available audio devices:
>  default
>  杩滅▼闊抽
> 
> Shared mode:
>         default
>           8000Hz, 16bits ................................ OK(I)
> (omit....)
>         杩滅▼闊抽
>           8000Hz, 16bits ................................ OK(I)
> (omit....)
> ```
> 
> ```
> > info audio.waveout.device
> audio.waveout.device:
> Type:          string
> Value:         default
> Default value: default
> Options:       default, 远程音频
> Real-time:     no
> > info audio.dsound.device
> audio.dsound.device:
> Type:          string
> Value:         default
> Default value: default
> Options:       default, 远程音频, 主声音驱动程序
> Real-time:     no
> > info audio.wasapi.device
> audio.wasapi.device:
> Type:          string
> Value:         default
> Default value: default
> Options:       default, 杩滅▼闊抽
> Real-time:     no
> ```
> 
> obviously chinese charactors related to wasapi not displayed properly.
> ### Expected behavior
> 
> That device is actually "远程音频" instead of non-sense "杩滅▼闊抽"
> ### Additional context
> 
> fluidsynth support waveout, directsound and wasapi for windows platform. after checking the codes, it seems implementations for waveout and dsound will use the ANSI version win32 api to get the device names, so the ANSI encoded names can be displayed in windows cmd.exe properly; but implementation for wasapi fetched the widechar names then converted to utf8, and utf8 encoded names will display properly only when ANSI==UTF8.
> 
> IMHO this is awkward, all implementations should use the same encoding.

after applying #984 
```
d:\opt\fluidsynth-tsingakbar>fluidsynth.exe -Q
FluidSynth runtime version 2.2.3
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

Available audio devices:
 default
 远程音频

Shared mode:
        default
          8000Hz, 16bits ................................ OK(I)
(omit...)

        远程音频
          8000Hz, 16bits ................................ OK(I)
(omit...)
```

```
> info audio.wasapi.device
audio.wasapi.device:
Type:          string
Value:         default
Default value: default
Options:       default, 远程音频
Real-time:     no
```

all wasapi device displaying problem fixed.

**But this requires a better fix**
use utf8 for device names across waveout, dsound and wasapi should be considered a better solution.
but this requires more modifications.
including replacing ANSI win32 api to Unicode version(`xxxxW()` ) for waveout and dsound implementation. and also requires all device name related `printf()` `puts()` replaced with something like:
```c
int utf8_printf(fmt, ...) {
    auto u8_str = sprintf(fmt, ...);
    auto u16_str = MultiByteToWideChar(CP_UTF8);
    WriteConsoleW(u16_str);
}
```

**Comment by derselbst** [comment]
Thank you for taking care of this! Your PR looks good, there're only some tiny issues I'll comment on later. I have no preference of whether to use the ANSI or unicode API. I would also be happy with your current proposal.

@chirs241097 What do you think about @tsingakbar 's `utf8_printf` proposal?
