### ISSUE TITLE
The daemon could work with multiple users

### ISSUE THREAD

**Issue by es20490446e** [FluidSynth/fluidsynth#999]
### Version
2.2.3

### How to reproduce
1. Log in as user1
2. systemctl --user start fluidsynth
3. Switch user to user2
4. systemctl --user start fluidsynth
5. systemctl --user status fluidsynth

### Output
fluidsynth.service: Failed with result 'protocol'

### Result
Only the first logged in user is able to play midi

**Comment by es20490446e** [comment]
@derselbst It seems a bug, since I have tested that the fluidsynth daemon cannot also work by itself with multiple users running it.

It doesn't even need to be simultaneously. Only the first user that will daemonize fluidsynth will be able to play midi, even if the daemon of the second terminates.

**Comment by es20490446e** [comment]
And changing audio o midi driver doesn't seem to affect this fact.

**Comment by derselbst** [comment]
I consider this to be a systemd related issue, not a bug in fluidsynth. To reproduce, it would probably helpful if you share the fluidsynth.service file and the distribution you're on.
I have little knowledge about systemd, and no idea, how to investigate or solve this. Contributions are welcome.

**Comment by es20490446e** [comment]
Observe that the behavior is reproducible without systemd. It's just reporting that Fluid is trying to claim the same resource for both users, and that's not possible.

Without systemd:
1. Log in user1, run fluidsynth on the terminal (it doesn't matter the arguments).
2. aplaymidi -p 128:0 song.mid (get sound)
3. Change to user2, without log off user1, and start fluidsynth on the terminal.
4. Log off user1.
5. On user1 session: aplaymidi -p 128:0 song.mid (no sound).

The systemd service I have on my Manjaro system is the official one in this repository:
```
[Unit]
Description=FluidSynth Daemon
Documentation=man:fluidsynth(1)
After=sound.target

[Service]
Type=notify
NotifyAccess=main
EnvironmentFile=/etc/conf.d/fluidsynth
EnvironmentFile=-%h/.config/fluidsynth
ExecStart=/usr/bin/fluidsynth -is $OTHER_OPTS $SOUND_FONT

[Install]
WantedBy=default.target
```

Any idea what that conflict may be?

**Comment by derselbst** [comment]
The first fluidsynth instance will most likely have client ID 128. The second instance will have a different client ID. It doesn't matter in which user you start it. Even if you start it in the same user, the ID will be different. By executing
 `aplaymidi -p 128:0 song.mid` in user2 you're again sending events to the first instance, which won't exist anymore when logging off user1.

Your statement "it doesn't matter the arguments" is quite telling. I suggest you start thinking about arguments. They do matter. Read the docs.

To solve this systemd multiple users issue, I suggest you figure out the arguments fluidsynth will really be started with. I.e. we neither know about `$OTHER_OPTS` nor do we know about `$SOUND_FONT`. Once you know the arguments, start the two fluidsynth instances in different users without systemd and see whether it works. Then start it again in systemd and try to get a meaningful error message from systemd.

With that meaningful error message, someone at the mailing might be able to help.

**Comment by es20490446e** [comment]
I have already tried all you mention.
